Remove `RewardsManager.sol`
ajna-finance/ajna-core pull request #1041
Opened 2023-12-17 19:59 UTC by MikeHathaway

## Description

* Removed `RewardsManager.sol` and all respective tests
* Unwound RewardsManager invariants with PositionManager invariants

## Purpose

During our Sherlock and Kiril audits there was a bug discovered in `RewardsManager.sol`. Although we had previously agreed not to deploy the contract prior to the audit, having a implementation example with a bug is a bad idea. We opted to remove `RewardsManager.sol` all together in the event someone used it.

## Impact

## Tasks

- [x] Changes to protocol contracts are covered by unit tests executed by CI.
- [x] Protocol contract size limits have not been exceeded.
- [x] Gas consumption for impacted transactions have been compared with the target branch, and nontrivial changes cited in the _Impact_ section above.
- [x] Scope labels have been assigned as appropriate.
- [x] Invariant tests have been manually executed as appropriate for the nature of the change.

2023-12-17 20:08 UTC, MikeHathaway commented on tests/forge/invariants/PositionsAndRewards/handlers/ERC20PoolPositionHandler.sol
> +    function lenderKickAuction(
Do we still need access to `lenderKick` and `takeOrSettle` in position if we're no longer handling rewards?

2023-12-17 21:03 UTC, EdNoepel commented on tests/forge/invariants/PositionsAndRewards/handlers/ERC20PoolPositionHandler.sol
> +    function lenderKickAuction(
Unsure.  We have regression tests which were using these with no staked liquidity.  Want to ensure we don't eliminate any `PositionManager` invariant coverage.

2023-12-19 17:14 UTC, ith-harvey commented on tests/forge/invariants/PositionsAndRewards/handlers/ERC20PoolPositionHandler.sol
> +    function lenderKickAuction(
I don't think `lenderKick()` and `takeOrSettle()` are necessary. They were originally added to check invariants against rewards manager. See the original PR here -> https://github.com/ajna-finance/contracts/commit/ac303b81ffd76bf4a3b0a17e43d92a1cd8be8e39

2023-12-19 19:44 UTC, ith-harvey approved these changes
LGTM

2023-12-19 19:50 UTC, EdNoepel requested changes
Commit 9fd555c48a6f51fce46f2ae8281f8f6cdf39486b removes `ERC20PoolPositionHandler` and regression tests, which I spent substantial effort making operational.

2023-12-19 19:53 UTC, grandizzy reviewed
I prefer to be consistent in naming, that is rename `Positions` directories in tests to `PositionManager` (to match `ERC20Pool` and `ERC721Pool` namings)

2023-12-19 21:00 UTC, ith-harvey commented
> Commit [9fd555c](https://github.com/ajna-finance/contracts/commit/9fd555c48a6f51fce46f2ae8281f8f6cdf39486b) removes `ERC20PoolPositionHandler` and regression tests, which I spent substantial effort making operational.

Apologies @EdNoepel , didn't take the time to review "why" you made the changes. Your changes successfully resolved `test_regression_index_out_of_bounds()` and `test_regression_max_less_than_min()`. I added them again in this commit -> https://github.com/ajna-finance/contracts/pull/1041/commits/3a63048a77a381449fabc84c1175b6c8a677aeed

2023-12-19 21:00 UTC, ith-harvey commented
> I prefer to be consistent in naming, that is rename `Positions` directories in tests to `PositionManager` (to match `ERC20Pool` and `ERC721Pool` namings)

Resolved -> https://github.com/ajna-finance/contracts/pull/1041/commits/3a63048a77a381449fabc84c1175b6c8a677aeed

2023-12-19 22:43 UTC, EdNoepel approved these changes
LGTM; much thanks.

2023-12-20 07:25 UTC, grandizzy approved these changes

2023-12-20 08:54 UTC, prat-gpt approved these changes
LGTM

2023-12-20 13:44 UTC, merged

2023-12-21 00:21 UTC, dmitriia reviewed
Ok