ERC721 pool initial implementation
ajna-finance/ajna-core pull request #114
Opened 2022-05-12 00:25 UTC by MikeHathaway

ERC721Pool:

- Initial implementation of ERC721 specific collateral handling methods: `addCollateral`, `removeCollateral`, `claimCollateral`, `purchaseBid`.
- Usage of `OpenZeppeling.ennumerableSet` data structs to handle tracking the individual tokenIds in the pool, and owned by borrowers so that we can make changes at the tokenId level, and not rely on `push` and `pop`.
- Reuse existing `addQuoteToken` `moveQuoteToken` and `removeQuoteToken` methods from ERC20Pool as they don't involve any NFT specific actions.
- Reuse existing `Buckets.sol` logic for most of the underlying methods to maximize maintainability
- Add `initializeSubset` method, and `onlySubset` function check to allow the same pool contract to support both the entire NFT collection, as well as any arbitrary subset of that collection.
- Calculates and stores the total collateral in the pool in WAD terms so as to allow reuse of existing collateralization and utilization functions.
- None of these additions increase gas costs for ERC20Pool state transitions. They do make deploying all pool types more expensive, however.

OTHER CHANGES
==========================

Adds:
1. `PoolDeployer.sol` abstract contract that provides a single source of truth for tracking all deployed pools, and centralizes the check for a pool being valid into a single modifier.
2. `SUBSET_HASH` to the `deployedPools` mapping. This allows us to ensure that multiple overlapping NFT subsets can be deployed for the same NFT collection, along with a broader NFT collection that would accept any tokenId in that contract. Hashing the tokenIds appeared to be the most gas efficient approach.
3. `ERC721PoolFactory.sol` new factory contract with two seperate methods for deploying the different types of NFT pools, given the differing requirements around tracking acceptable tokenIds for the subset.
4. `claimNFTCollateralFromBucket` method to `Buckets.sol` to allow claiming collateral without increasing gas costs for other pool types. 
5. `divRoundingUp<>` methods to `Maths.sol`, to support rounding up to the nearest whole NFT when attempting to determine how many NFTs are required.
6. NFT collateral specific user contracts to `_test/utils`.
7. Tests covering the currently implemented ERC721 collateral functionality: `addCollateral`, `removeCollateral`, `claimCollateral`, `purchaseBid`.

Updates:
1. Move `generateAddress` used by the `PositionManager` tests to `DSTestPlus` for increased reusability
2. Move ERC20Pool tests into their own folder within _test to ease navigation.

TODO:
1. Implement liquidations. This is currently on hold pending 8.1 features.
3. Implement repay(). This shouldn't take too long, but was pushed off due to the already large size of the PR
4. Implement `<>CollateralMultiple()` methods in `ERC721Pool.sol` that support dealing with multiple tokenIds at a time.

2022-05-12 18:37 UTC, MikeHathaway commented on src/base/Interest.sol
> +    uint256 public totalDebt;          // WAD
Given the semantic relationship with interest, I figured it was ok to migrate the `totalDebt` variable over, which allowed two additional methods to be moved over at no additional gas cost.

2022-05-23 17:57 UTC, MikeHathaway commented on src/base/Interest.sol
> +    uint256 public totalDebt;          // WAD
Address in other PRs, latest here: https://github.com/ajna-finance/contracts/pull/130

2022-06-07 18:06 UTC, grandizzy reviewed
hey @MikeHathaway I left some comments, I have to get a second read of the entire PR as there are some other things NFT related I am not very familiar with

2022-06-07 18:06 UTC, grandizzy commented on src/ERC20Pool.sol
> +import { console }     from "@std/console.sol";
style related - extra spaces before `from` can be removed

2022-06-07 18:06 UTC, grandizzy commented on sdk/ajna_protocol.py
> +    ERC20_POOL_HASH = "ab835e09eb0e6c29f0c283ee3c270414bb498606c3d68718b89dbbe96435a088"
can you pls explain to me what's this for?

2022-06-07 18:06 UTC, grandizzy commented on src/ERC721PoolFactory.sol
> +    function deployNFTCollectionPool(address collateral_, address quote_) external canDeploy(NON_SUBSET_HASH, collateral_, quote_) returns (address) {
minor comment - for ERC20 was used `returns (address pool_)` and then used `pool_ = address(pool)` instead having several `address(pool)` inline, I think would be nice to have them the same

2022-06-07 18:06 UTC, grandizzy commented on src/ERC721PoolFactory.sol
> +    function deployNFTSubsetPool(address collateral_, address quote_, uint256[] memory tokenIds_) external canDeploy(getNFTSubsetHash(tokenIds_), collateral_, quote_) returns (address) {
same as above

2022-06-07 18:06 UTC, grandizzy commented on src/ERC721Pool.sol
> +import { console }     from "@std/console.sol";
there are extra spaces before from

2022-06-07 18:06 UTC, grandizzy commented on src/ERC721Pool.sol
> +    // TODO: convert to modifier and add check at start of each method
is this something we want in the PR or to be done later?

2022-06-07 18:06 UTC, grandizzy commented on src/ERC721Pool.sol
> +                revert("P:ONLY_SUBSET");
is there any reason not using require but revert? In this way we could even give up the convert to modifier to do and put require in functions?

2022-06-07 18:06 UTC, grandizzy commented on src/ERC721Pool.sol
> +        // add tokenIds to the pool
this part should be removed?

2022-06-07 18:06 UTC, grandizzy commented on src/ERC721Pool.sol
> +    // TODO: finish implementing
is this something we want in the PR or should be done later?

2022-06-07 18:06 UTC, grandizzy commented on src/ERC721Pool.sol
> +    // TODO: create seperate NFT specific events
is this something we want in the PR or should be done later?

2022-06-07 18:06 UTC, grandizzy commented on src/ERC721Pool.sol
> +    function liquidate(address borrower_) external {}
is this a TODO to implement or there won't be liquidations for this pool?

2022-06-07 18:06 UTC, grandizzy commented on src/ERC721Pool.sol
> +            if (collateral().ownerOf(tokenIds_[i]) != msg.sender) {
same as above, is it better here to revert instead require?

2022-06-07 18:06 UTC, grandizzy commented on src/base/Buckets.sol
> +    mapping(uint256 => Buckets.NFTBucket) internal _nftBuckets;
would having both ERC20 and NFT related mappings in same contract impact gas for one or the other pool?

2022-06-07 18:06 UTC, grandizzy commented on src/base/BorrowerManager.sol
> +    mapping(address => NFTBorrowerInfo) internal NFTborrowers;
would this mapping somehow impact gas on ERC20 pool? and viceversa, the ` mapping(address => BorrowerInfo) public override borrowers;` ERC20 one would have any impact on NFT pool gas?

2022-06-07 20:55 UTC, MikeHathaway commented on src/base/Buckets.sol
> +    mapping(uint256 => Buckets.NFTBucket) internal _nftBuckets;
The additional mapping doesn't impact gas on the existing ERC20Pool methods. It will increase gas costs for the deployment of any additional pool, but this should be negligible given our usage of clones.

Alternative approaches, such as tracking `collateralDeposited` as an enumerableSet in the existing `Buckets` would have increased gas costs.

2022-06-07 21:00 UTC, MikeHathaway commented on src/base/BorrowerManager.sol
> +    mapping(address => NFTBorrowerInfo) internal NFTborrowers;
Similar to the additional mapping in `Buckets.sol` the additional mapping will increase pool deployment costs for both types of pools, but will have no impact on subsequent method calls for the different types. Usage of the mappings is isolated by pool type.

2022-06-07 21:20 UTC, MikeHathaway commented on src/ERC721PoolFactory.sol
> +    function deployNFTCollectionPool(address collateral_, address quote_) external canDeploy(NON_SUBSET_HASH, collateral_, quote_) returns (address) {
Will remove to keep it in sync

2022-06-07 21:20 UTC, MikeHathaway commented on src/ERC721PoolFactory.sol
> +    function deployNFTSubsetPool(address collateral_, address quote_, uint256[] memory tokenIds_) external canDeploy(getNFTSubsetHash(tokenIds_), collateral_, quote_) returns (address) {
Will remove to keep it in sync

2022-06-07 21:20 UTC, MikeHathaway commented on src/ERC20Pool.sol
> +import { console }     from "@std/console.sol";
Removed

2022-06-07 21:21 UTC, MikeHathaway commented on src/ERC721Pool.sol
> +import { console }     from "@std/console.sol";
Removed

2022-06-07 21:25 UTC, MikeHathaway commented on sdk/ajna_protocol.py
> +    ERC20_POOL_HASH = "ab835e09eb0e6c29f0c283ee3c270414bb498606c3d68718b89dbbe96435a088"
This hash is used to enable the creation and tracking of multiple NFT subset pools that share a common `collateral` address. As currently written in `deployedPools`, a single NFT subset pool would preclude the deployment of any other subsets, or a broader collection. To allow usage of a single mapping, I added a constant hash that can be used to signify the non subset pools for minimal gas. This is that constant hash hardcoded as a string.

2022-06-07 21:35 UTC, MikeHathaway commented on src/ERC721Pool.sol
> +                revert("P:ONLY_SUBSET");
The gas cost would be the same, but `require` is cleaner, so I will update accordingly. Revert was a byproduct of a previous implementation of that function.

2022-06-07 22:58 UTC, MikeHathaway commented on src/ERC721Pool.sol
> +    // TODO: create seperate NFT specific events
Had a question about that I was going to bring up at standup - basically is it worth adding the extra events just to rename that field (which will still be a uint256) from `amount` to `tokenId`?

2022-06-07 22:59 UTC, MikeHathaway commented on src/ERC721Pool.sol
> +            if (collateral().ownerOf(tokenIds_[i]) != msg.sender) {
Changed this from revert to require

2022-06-07 23:32 UTC, MikeHathaway commented on src/ERC721Pool.sol
> +    function liquidate(address borrower_) external {}
I left that as a TODO since liquidations 8.1 are still in flight and NFT liquidations have their own complications.

2022-06-08 00:28 UTC, MikeHathaway commented on src/ERC721Pool.sol
> +    // TODO: finish implementing
I just added an implementation, tests are in progress.

2022-06-08 00:28 UTC, MikeHathaway commented on src/ERC721Pool.sol
> +        // add tokenIds to the pool
Added implementation

2022-06-08 04:50 UTC, grandizzy commented on sdk/ajna_protocol.py
> +    ERC20_POOL_HASH = "ab835e09eb0e6c29f0c283ee3c270414bb498606c3d68718b89dbbe96435a088"
thanks!

2022-06-08 04:52 UTC, grandizzy commented on src/ERC721Pool.sol
> +    // TODO: create seperate NFT specific events
I think the naming matters, but let's discuss at standup

2022-06-08 04:58 UTC, grandizzy requested changes
some comments related to gas consumption

2022-06-08 04:58 UTC, grandizzy commented on src/base/BorrowerManager.sol
> +        NFTBorrowerInfo storage borrower = NFTborrowers[borrower_];
this can be changed to `memory`

2022-06-08 04:58 UTC, grandizzy commented on src/ERC721Pool.sol
> +        NFTBorrowerInfo storage borrower = NFTborrowers[msg.sender];
In gas optimization PR that I just merged in `develop` the `BorowerInfo` is loaded in memory and then passed to `accumulateBorrowerInterest` which accepts memory args as well. Then after all operations are done it is saved to storage. This reduce gas costs as we avoid writing debt twice to storage, once in `accumulateBorrowerInterest` and then in function's body when we do borrower accounting. Let's apply same here.

2022-06-08 04:58 UTC, grandizzy commented on src/ERC721Pool.sol
> +        NFTBorrowerInfo storage borrower = NFTborrowers[msg.sender];
same as above

2022-06-08 15:49 UTC, MikeHathaway commented on src/base/BorrowerManager.sol
> +        NFTBorrowerInfo storage borrower = NFTborrowers[borrower_];
Unfortunately it has to be storage since the NFTBorrowerInfo struct has a nested mapping within it, and compilation disallows nested mappings in memory. Release note about this issue here: https://docs.soliditylang.org/en/v0.7.2/070-breaking-changes.html#mappings-outside-storage

2022-06-08 15:52 UTC, MikeHathaway commented on src/ERC721Pool.sol
> +        NFTBorrowerInfo storage borrower = NFTborrowers[msg.sender];
Addressed above

2022-06-08 15:56 UTC, grandizzy commented on src/base/BorrowerManager.sol
> +        NFTBorrowerInfo storage borrower = NFTborrowers[borrower_];
ah, OK, that's fine. I guess that's the same for ERC721Pool too but there we can save gas bby not passing `storage` param but rather local variables (stored in stack) to `accumulateNFTBorrowerInterest` and write to storage only once. I am OK with keeping as it is rn and then improving it, I can have a look at

2022-06-08 16:21 UTC, MikeHathaway commented on src/ERC721Pool.sol
> +    // TODO: create seperate NFT specific events
Resolving this as consensus was to leave NFT specific events in ERC721Pool while we figure out a better pattern for refactoring. Goals were to index tokenId, and account for differing interface requirements for methods like `purchaseBid` between the different pool types which IPool currently does not.

2022-06-08 16:22 UTC, MikeHathaway commented on src/base/BorrowerManager.sol
> +        NFTBorrowerInfo storage borrower = NFTborrowers[borrower_];
Yep, we'll have the same issue with this struct in ERC721Pool as well. I agree it would be good to optimize gas usage here

2022-06-14 01:31 UTC, EdNoepel reviewed
Quite happy with this.  Once any other concerns are resolved, I'd favor merging this despite its TODOs, mainly to reduce the cost of managing the branch.  I would also be happy to help fill in the unit tests if that's helpful.

2022-06-14 01:31 UTC, EdNoepel commented on src/ERC721Pool.sol
> +        onlySubsetMultiple(tokenIds_);
Why not use the `tokensInPool` modifier?  Or, since we need to iterate through the tokens anyway, should we check in this method's own `for` loop?

2022-06-14 01:31 UTC, EdNoepel commented on src/base/BorrowerManager.sol
> +            collateralEncumbered  = getEncumberedCollateral(borrowerPendingDebt);
Note to self: This calls the same `getEncumberedCollateral` in `PoolState.sol`, which returns debt, denominated in the number of NFTs, as a RAY.

2022-06-14 01:31 UTC, EdNoepel commented on src/ERC721Pool.sol
> +   /*****************************/
nit: comment alignment

2022-06-14 01:31 UTC, EdNoepel commented on src/_test/ERC721Pool/ERC721PoolBorrow.t.sol
> +        // TODO: RAISES THE QUESTION -> How to deal with a pool where the universe of possible collateral has been exhausted
Borrower would just have to repay, which is done in quote token.  Similar scenario: a fungible shitcoin is created, and everything minted was deposited into a pool.

2022-06-14 01:31 UTC, EdNoepel commented on src/base/Buckets.sol
> +import { console }     from "@std/console.sol";
nit: alignment of `from` statements

2022-06-14 01:31 UTC, EdNoepel commented on src/base/Buckets.sol
> +    function claimNFTCollateralFromBucket(uint256 price_, uint256 tokenId_, uint256 lpBalance_) internal returns (uint256 lpRedemption_) {
Will there be a method to claim multiple collateral tokens?  Or should that be an SDK-layer multicall facility?

2022-06-14 01:31 UTC, EdNoepel commented on src/base/Interest.sol
> +    function accumulateNFTBorrowerInterest(IBorrowerManager.NFTBorrowerInfo storage borrower_) internal {
Is this just needed because of the `NFTBorrowerInfo` struct?  If I understand correctly, structs cannot leverage polymorphism, and it'd be crazy expensive to make `BorrowerInfo` a contract.

2022-06-14 01:51 UTC, MikeHathaway commented on src/base/Buckets.sol
> +    function claimNFTCollateralFromBucket(uint256 price_, uint256 tokenId_, uint256 lpBalance_) internal returns (uint256 lpRedemption_) {
Yes I've added a separate method to `Buckets` that supports an array of `tokenIds` to a separate branch that I was planning on raising in another PR

2022-06-14 01:57 UTC, MikeHathaway commented on src/base/Interest.sol
> +    function accumulateNFTBorrowerInterest(IBorrowerManager.NFTBorrowerInfo storage borrower_) internal {
Yes exactly, if we pass through the entire struct as opposed to the individual args it needs a separate method to support the different struct location.

2022-06-14 02:32 UTC, MikeHathaway commented on src/ERC721Pool.sol
> +        onlySubsetMultiple(tokenIds_);
`tokenInPool` is designed to check that the collateral to be removed or claimed is actually extant in the pool (which would indeed preclude using `onlySubset`. But any collateral added here would need to not be in the pool. I can convert `onlySubset` to a modifier though. I had avoided this previously in order to simplify the require checks in `purchaseBid`

2022-06-14 13:29 UTC, EdNoepel approved these changes

2022-06-14 15:39 UTC, merged