convert Buckets from library to abstract contract
ajna-finance/ajna-core pull request #123
Opened 2022-05-16 20:06 UTC by MikeHathaway

Functionality is unchanged, but there are substantial gas savings compared to the previous implementation. There is also less code in the pool contract, with functionality more easily reused across pool types.

2022-05-17 05:21 UTC, grandizzy requested changes

2022-05-17 05:21 UTC, grandizzy commented on src/ERC20Pool.sol
> +        Buckets.Bucket memory bucket = _buckets[price_];
With the new implementation there's a slightly increase in gas costs, previously the bucket was loaded from storage only once and then passed to library. Taking example of `removeQuoteToken` when bucket becomes eligible to be deactivated following operations are now executed:
- load bucket from storage in `Buckets.removeQuoteTokenFromBucket` function
- load bucket in memory to check if eligible for deactivation in `ERC20Pool.removeQuoteToken` function
- load bucket again from storage in `Buckets.deactivateBucket` function

With code in `develop` branch current operation takes `Gas used: 91253` while with the new code is `Gas used: 91638`.

I did a test in `internalize-buckets` branch by loading bucket in memory within `ERC20Pool.removeQuoteToken` and passing that reference to  `Buckets.removeQuoteTokenFromBucket` and then to `Buckets.deactivateBucket` - the gas used in same scenario considerably decreased to `Gas used: 86071`, I will create a PR against your branch with the changes and see if we should go that way

2022-05-17 05:21 UTC, grandizzy commented on src/base/Buckets.sol
> +    function addQuoteTokenToBucket(
we should preserve style here

2022-05-17 05:21 UTC, grandizzy commented on src/base/Buckets.sol
> -    function removeQuoteToken(
we should preserve style here

2022-05-17 05:21 UTC, grandizzy commented on src/base/Buckets.sol
> +    function claimCollateralFromBucket(
we should preserve style here

2022-05-17 05:21 UTC, grandizzy commented on src/base/Buckets.sol
> +    function borrowFromBucket(
we should preserve style here

2022-05-17 05:21 UTC, grandizzy commented on src/base/Buckets.sol
> -    function deactivateBucket(mapping(uint256 => Bucket) storage buckets_, Bucket storage bucket_) public {
same as above re style

2022-05-17 05:21 UTC, grandizzy commented on src/base/Buckets.sol
> +    function initializeBucket(
same as above re style

2022-05-17 05:21 UTC, grandizzy commented on src/base/Buckets.sol
> +    function bucketAt(uint256 price_)
same as above re style

2022-05-17 05:21 UTC, grandizzy commented on src/base/Buckets.sol
> +    function estimatePrice(
same as above re style

2022-05-17 05:21 UTC, grandizzy commented on src/base/Buckets.sol
> +        Bucket storage bucket_,
same as above re style

2022-05-17 05:21 UTC, grandizzy commented on src/base/Buckets.sol
> +        Bucket storage bucket_,
same as above re style

2022-05-17 05:21 UTC, grandizzy commented on src/base/Buckets.sol
> +    function liquidateAtBucket(
same as above re style

2022-05-17 05:21 UTC, grandizzy commented on src/base/Buckets.sol
> +    function purchaseBidFromBucket(
same as above re style

2022-05-17 05:21 UTC, grandizzy commented on src/base/Buckets.sol
> +    function repayBucket(
same as above re style

2022-05-17 07:26 UTC, grandizzy commented on src/ERC20Pool.sol
> +        Buckets.Bucket memory bucket = _buckets[price_];
@MikeHathaway Please see PR https://github.com/ajna-finance/contracts/pull/124 to address comments above
here are the gas costs for develop branch and for interalize buckets one with this PR:
```
>>> pool.addQuoteToken(lenders[0], 5_000 * 1e18, protocol.bucket_math.indexToPrice(1600), {'from': lenders[0]})
develop: Gas used: 330578 (2.75%)
new:      Gas used: 327574 (2.73%)

>>> pool.addQuoteToken(lenders[0], 5_000 * 1e18, protocol.bucket_math.indexToPrice(1500), {'from': lenders[0]})
develop: Gas used: 282874 (2.36%)
new:      Gas used: 281218 (2.34%)

>>> pool.addQuoteToken(lenders[0], 5_000 * 1e18, protocol.bucket_math.indexToPrice(1400), {'from': lenders[0]})
develop: Gas used: 283954 (2.37%)
new:      Gas used: 282816 (2.36%)

>>> pool.removeQuoteToken(lenders[0], 5_000 * 1e18, protocol.bucket_math.indexToPrice(1500), {'from': lenders[0]})
develop: Gas used: 91245 (0.76%)
new:      Gas used: 86750 (0.72%)

>>> pool.removeQuoteToken(lenders[0], 5_000 * 1e18, protocol.bucket_math.indexToPrice(1600), {'from': lenders[0]})
develop: Gas used: 99189 (0.83%)
new:      Gas used: 93654 (0.78%)

>>> pool.removeQuoteToken(lenders[0], 5_000 * 1e18, protocol.bucket_math.indexToPrice(1400), {'from': lenders[0]})
develop: Gas used: 89284 (0.74%)
new:      Gas used: 85003 (0.71%)
```

2022-05-17 12:08 UTC, grandizzy commented on src/ERC20Pool.sol
> +        Buckets.Bucket memory bucket = _buckets[price_];
@MikeHathaway Please see also PR https://github.com/ajna-finance/contracts/pull/125 with a different approach, that is to move all buckets related operations to `Buckets` contract (including initialization and deactivation). Gas cost is not so efficient as the first approach but still a good gain compared with `develop`

```
>>> pool.addQuoteToken(lenders[0], 5_000 * 1e18, protocol.bucket_math.indexToPrice(1600), {'from': lenders[0]})
Gas used: 328789 (2.74%)

<Transaction '0xa5fb03ab168e1549e9ab4b7c4dc8798b3b3227df15920f9f54167781d4c759e5'>
>>> pool.addQuoteToken(lenders[0], 5_000 * 1e18, protocol.bucket_math.indexToPrice(1500), {'from': lenders[0]})
Gas used: 281295 (2.34%)

>>> pool.addQuoteToken(lenders[0], 5_000 * 1e18, protocol.bucket_math.indexToPrice(1400), {'from': lenders[0]})
Gas used: 282548 (2.35%)

<Transaction '0x9dc7149bf6f4431ad6827aa0c705c7f960376d8eb53e9b50078ac68e2eec9aab'>
>>> pool.removeQuoteToken(lenders[0], 5_000 * 1e18, protocol.bucket_math.indexToPrice(1500), {'from': lenders[0]})
Gas used: 90002 (0.75%)

>>> pool.removeQuoteToken(lenders[0], 5_000 * 1e18, protocol.bucket_math.indexToPrice(1600), {'from': lenders[0]})
 Gas used: 97601 (0.81%)

>>> pool.removeQuoteToken(lenders[0], 5_000 * 1e18, protocol.bucket_math.indexToPrice(1400), {'from': lenders[0]})
Gas used: 89390 (0.74%)
```

2022-05-17 12:12 UTC, grandizzy commented
> Functionality is unchanged, but there are substantial gas savings compared to the previous implementation. There is also less code in the pool contract, with functionality more easily reused across pool types.

Is there any way this could be a vector of attack like for example someone directly calling functions of `Buckets` contract, bypassing `Pool` logic (which updated pool debt, total quote, lup, etc.) and messing up entire pool logic?

2022-05-17 13:03 UTC, grandizzy commented
> > Functionality is unchanged, but there are substantial gas savings compared to the previous implementation. There is also less code in the pool contract, with functionality more easily reused across pool types.
> 
> Is there any way this could be a vector of attack like for example someone directly calling functions of `Buckets` contract, bypassing `Pool` logic (which updated pool debt, total quote, lup, etc.) and messing up entire pool logic?

That's actually possible so `Buckets` function visibility should be changed to `internal`. I added this in the 2 PRs I made on top of the `internalize-buckets` branch

2022-05-18 18:26 UTC, EdNoepel approved these changes
This changes the relationship to the pool "being a buckets" rather than "having buckets".  Multiple pool implementations could still reuse the buckets library in the old implementation, but this change moves some logic (such as price pointer management) from the pool into the buckets.  My hope is that we won't need to break apart `Buckets.sol` into fungible and nonfungible implementations, even if they share a common baseclass.  Since quote token is always fungible, I suspect methods not involving collateral, such as `addQuoteToken` and `removeQuoteToken`, would move to a `base/Pool.sol` in the future.

Approved with comments.

2022-05-18 18:26 UTC, EdNoepel commented on src/ERC20Pool.sol
> +     */
LOCs as measured by auditors don't include comments, right?

2022-05-18 18:26 UTC, EdNoepel commented on src/ERC20Pool.sol
> -        //  TODO: emit _amount / quoteTokenScale
Do we want to emit scaled amounts or not?  What would make more sense for those consuming the event logs?

2022-05-18 18:26 UTC, EdNoepel commented on src/base/Buckets.sol
> +        uint256 exchangeRate = getExchangeRate(bucket);                 // RAY
nit: comment alignment

2022-05-18 18:26 UTC, EdNoepel commented on src/base/Buckets.sol
> +        bool noClaim = bucket.lpOutstanding == 0 && bucket.collateral == 0;
Much easier to read than the old implementation.

2022-05-18 18:26 UTC, EdNoepel commented on scripts/erc20setup.py
> -        10_000 * 1e45,
Sorry for missing these when I changed the numeric types.

2022-05-18 18:26 UTC, EdNoepel commented on src/interfaces/IPool.sol
> -    function getHup() external view returns (uint256 hup_);
Consumer should still be able to call public views for price pointers, which would be serviced by the buckets baseclass.  Why remove?

2022-05-18 18:33 UTC, grandizzy commented
> This changes the relationship to the pool "being a buckets" rather than "having buckets".

Yes, was also thinking about this meaning. Would it make sense to rename from `Buckets.sol` to `BucketsManager.sol` or something similar?

2022-05-18 18:34 UTC, grandizzy commented on src/ERC20Pool.sol
> +     */
That's my understanding that LOCs does not include comments, @lucas-manuel do you know if that's the case?

2022-05-18 18:43 UTC, grandizzy commented on src/interfaces/IPool.sol
> -    function getHup() external view returns (uint256 hup_);
They are still able to call them (and served by `Buckets.sol` as you mentioned). If we leave `getHup()` and `getHpb()` in `IPool` interface then the derived contract `ERC20Pool.sol` must override them and I didn't find a nice way to maintain that

2022-05-18 18:55 UTC, grandizzy commented on src/ERC20Pool.sol
> -        //  TODO: emit _amount / quoteTokenScale
I created card https://www.notion.so/worlds-best-crypto-lending-platform/Discuss-and-implement-emit-scaled-amounts-3d0dd70d031344b396aaba8a507c272e to continue discussion and track implementation of events with scaled amounts

2022-05-18 18:58 UTC, EdNoepel commented on src/interfaces/IPool.sol
> -    function getHup() external view returns (uint256 hup_);
Agreed; less code is better.

2022-05-18 18:59 UTC, EdNoepel commented
> > This changes the relationship to the pool "being a buckets" rather than "having buckets".
> 
> Yes, was also thinking about this meaning. Would it make sense to rename from `Buckets.sol` to `BucketsManager.sol` or something similar?

I'm happy to leave as-is for now.  In the future, perhaps this will all move into `base/Pool.sol`.

2022-05-18 19:05 UTC, grandizzy commented on src/base/Buckets.sol
> +        uint256 exchangeRate = getExchangeRate(bucket);                 // RAY
updated with https://github.com/ajna-finance/contracts/pull/123/commits/4d48d22c489ecf2b7de0f968fca1f4ef0da4b577

2022-05-19 06:43 UTC, merged