Abstract pool state
ajna-finance/ajna-core pull request #130
Opened 2022-05-21 22:03 UTC by MikeHathaway

2022-05-23 19:06 UTC, MikeHathaway commented
Opened this for discussion purposes. I'm still working in the background on a cleaner inheritance approach, but I think it is directionally correct and wanted feedback.

The goal is to separate concerns into discrete modules, defined by their relevant business logic. `ERC20Pool` would then inherit at a top level from `LenderManager`, and `BorrowerManager`. `PoolState` and `Interest` are successively chained through `BorrowerManager` and thereby made available to the Pool. My concern is that `ERC20Pool`'s usage of methods in `PoolState` is obfuscated for external observors, who would have to trace the chain of inheritance back. `PoolState`, `Interest`, and `Bucket` cannot be inherited directly by `ERC20Pool` as it would result in a cyclical inheritance graph. The Compiler will ultimately flatten all inheritance, so this is primarily an issue when viewing the source code in git.

Overall, this change results in a modest decrease in gas usage, and a significant decrease in code as these methods could be reused across different pool types.

2022-05-23 19:07 UTC, MikeHathaway commented on src/base/Interest.sol
> +abstract contract Interest is IInterest, PoolState {
Considering renaming this to `InterestManager` to conform to other base contracts.

2022-05-24 10:09 UTC, grandizzy requested changes
LGTM, couple of minor style and obsolete comments to be removed

2022-05-24 10:09 UTC, grandizzy commented on src/base/PoolState.sol
> +import { IPoolState }          from "../interfaces/IPoolState.sol";
style comment, `from` should be aligned

2022-05-24 10:09 UTC, grandizzy commented on src/base/BorrowerManager.sol
> +        // convert amount from WAD to collateral pool precision - RAD
this comment can be removed, collateral pool precision is now WAD

2022-05-24 10:09 UTC, grandizzy commented on src/base/Interest.sol
> +import { Maths }     from "../libraries/Maths.sol";
style comment. `from` should be aligned

2022-05-24 10:09 UTC, grandizzy commented on src/base/PoolState.sol
> +        // Calculate encumbrance as RAY to maintain precision
this comment can be removed, encumbrance is now WAD

2022-05-24 14:21 UTC, MikeHathaway commented on src/base/PoolState.sol
> +        // Calculate encumbrance as RAY to maintain precision
Good catch - there may actually be a related bug here: https://github.com/ajna-finance/contracts/blob/develop/src/ERC20Pool.sol#L159

2022-05-24 14:57 UTC, EdNoepel commented on src/base/PoolState.sol
> +        // Calculate encumbrance as RAY to maintain precision
I'm not convinced encumbrance should be WAD.  I'd like to investigate outside this PR.

2022-05-24 16:31 UTC, EdNoepel commented on src/base/PoolState.sol
> +        // Calculate encumbrance as RAY to maintain precision
Please see PR #132.

2022-05-24 18:57 UTC, MikeHathaway commented on src/base/Interest.sol
> +import { Maths }     from "../libraries/Maths.sol";
Updated

2022-05-24 18:57 UTC, MikeHathaway commented on src/base/BorrowerManager.sol
> +        // convert amount from WAD to collateral pool precision - RAD
Removed comment

2022-05-24 18:57 UTC, MikeHathaway commented on src/base/PoolState.sol
> +import { IPoolState }          from "../interfaces/IPoolState.sol";
Aligned from

2022-05-25 18:37 UTC, grandizzy approved these changes

2022-05-25 18:37 UTC, grandizzy commented on src/base/PoolState.sol
> +        // Calculate encumbrance as RAY to maintain precision
hm, yeah, didn't notice that one, I think we can remove all `Maths.rayToWad` calls when calculating the encumbered collateral, could be the case it doesn't affect tests...

2022-05-25 18:37 UTC, grandizzy commented on src/base/PoolState.sol
> +        // Calculate encumbrance as RAY to maintain precision
just checked, removing `Maths.rayToWad` from https://github.com/ajna-finance/contracts/blob/develop/src/ERC20Pool.sol#L159 and from https://github.com/ajna-finance/contracts/blob/develop/src/ERC20Pool.sol#L201 doesn't break tests. and I guess that's expected since they were going from a higher to a lower precision

2022-05-25 19:13 UTC, merged