Pool optimizations
ajna-finance/ajna-core pull request #143
Opened 2022-06-10 11:01 UTC by grandizzy

ERC20 pool improvements
- read pool state variables only once per function call (e.g. debt, inflator)
- add internal functions for pool related accounting (also more efficient in terms of gas costs). All external functions are calling the internal functions and passing variables read from storage 
- rename all internal function (prefixed with `_`) to make interaction clear

Gas comparison: 
`develop`:
    5 buckets:  borrow: 0.260838 ETH, repay: 0.204805 ETH
    10 buckets: borrow: 0.356331 ETH, repay: 0.308353 ETH
    20 buckets: borrow: 0.546983 ETH, repay: 0.514930 ETH
    30 buckets: borrow: 0.737968 ETH, repay: 0.721680 ETH
    40 buckets: borrow: 0.928624 ETH, repay: 0.928430 ETH
    50 buckets: borrow: 1.120127 ETH, repay: 1.135698 ETH

`pool-optimizations`:
    5 buckets:  borrow: 0.253633 ETH, repay: 0.195550 ETH
    10 buckets: borrow: 0.349142 ETH, repay: 0.298925 ETH
    20 buckets: borrow: 0.539794 ETH, repay: 0.506525 ETH
    30 buckets: borrow: 0.730418 ETH, repay: 0.713275 ETH  
    40 buckets: borrow: 0.921074 ETH, repay: 0.920009 ETH
    50 buckets: borrow: 1.112059 ETH, repay: 1.127120 ETH

TODOs:
- read `lup` and `hpb` only once from storage and use it in pool calculation / events
- compare results

2022-06-13 11:24 UTC, ith-harvey reviewed
Looks good, made some comments. Make sure that we are on the same page when it comes to right aligning formatting... looks like some places you removed the right aligning and other places in the contracts didn't have it at all yet. We should make sure we have consistency.

One of the overarching quesitons I have for gas savings is... is it cheaper to just always perform the computation and not store the interest? Or is storing intermittently cheaper?

2022-06-13 11:24 UTC, ith-harvey commented on src/ERC20Pool.sol
> +        totalCollateral += amount_;
Shouldn't the formatting be cleaned up so `+=amount_;` is right aligned as before?

2022-06-13 11:24 UTC, ith-harvey commented on src/base/Interest.sol
> +            inflatorSnapshot           = curInflator_;
add `// RAY` comment

2022-06-13 11:24 UTC, ith-harvey commented on src/base/PoolState.sol
> +        return _encumberedCollateral(debt_);
Why don't you pass `lup` as an arg?

2022-06-13 11:24 UTC, ith-harvey commented on src/ERC20Pool.sol
> +        (totalDebt, ) = _accumulatePoolInterest(totalDebt, inflatorSnapshot);
In addition to the `totalDebt` assignment I think you should assign `inflatorSnapshot` too (take a a look at my comment under `_accumulatePoolInterest`).

2022-06-13 11:24 UTC, ith-harvey commented on src/base/Interest.sol
> +            inflatorSnapshot           = curInflator_;
Something I have noticed is that the global variable `inflatorSnapshot` is always maintained but `totalDebt` is not always updated (see add collateral for instance). This could create a scenario where the `totalDebt` is not increased for a window in time but the inflator is. Thus the window of outstanding interest is "missed", not tacked on to total debt.

I think the solution for this is to either ensure that `totalDebt` is always being reassigned every time `inflatorSnapshot` is reassigned. Since you are attempting to reduce storage writes I would suggest you do not assign global `inflatorSnapshot` here but rather on return just like you do with `totalDebt`

2022-06-13 11:24 UTC, ith-harvey commented on src/ERC20Pool.sol
> +        (uint256 curDebt, uint256 curInflator) = _accumulatePoolInterest(totalDebt, inflatorSnapshot);
Fine if you make changes to `_accumulatePoolInterest` function

2022-06-13 11:24 UTC, ith-harvey commented on src/ERC20Pool.sol
> +        (uint256 curDebt, uint256 curInflator) = _accumulatePoolInterest(totalDebt, inflatorSnapshot);
fine if you make changes to `_accumulatePoolInterest` function

2022-06-13 11:24 UTC, ith-harvey commented on src/ERC20Pool.sol
> +        curDebt += amount_ + fee;
Shouldn't this formatting match what Lucas did? -> right aligning?

2022-06-13 11:39 UTC, ith-harvey commented on src/ERC20Pool.sol
> +        totalDebt       = curDebt - Maths.min(curDebt, amount);
This looks incorrect...

2022-06-13 12:02 UTC, grandizzy commented on src/base/PoolState.sol
> +        return _encumberedCollateral(debt_);
internal function `_encumberedCollateral` is reading `lup` from storage already, so no need to pass it as a variable

2022-06-13 12:03 UTC, grandizzy commented on src/ERC20Pool.sol
> +        (totalDebt, ) = _accumulatePoolInterest(totalDebt, inflatorSnapshot);
`inflatorSnapshot` is updated in `_accumulatePoolInterest` function while the debt is accumulated and passed back to the pool to make additional calculations and then to be stored. this way `totalDebt` is read and stored only once

> One of the overarching quesitons I have for gas savings is... is it cheaper to just always perform the computation and not store the interest? Or is storing intermittently cheaper?

Each time we read from storage an `SLOAD` opcode is used https://github.com/wolflo/evm-opcodes/blob/main/gas.md#a6-sload that consume 100 to 2100 gas. With current approach the data is stored in stack which

```
The third one is the stack, which is used to hold small local variables. It is almost free to use, but can only hold a limited amount of values.
```

see https://medium.com/coinmonks/ethereum-solidity-memory-vs-storage-which-to-use-in-local-functions-72b593c3703a
So for `totalDebt` for example, the new approach reads the value from storage once (consuming gas `SLOAD`) then store it in a data variable in stack (`curDebt`) which is used for calculations inside the functions, then it is written back to the storage in pool contract only once by `totalDebt = curDebt` using `SSTORE` opcode and consuming gas https://github.com/wolflo/evm-opcodes/blob/main/gas.md#a7-sstore

2022-06-13 12:04 UTC, grandizzy commented on src/ERC20Pool.sol
> +        totalDebt       = curDebt - Maths.min(curDebt, amount);
hm, why do you think so? it was `totalDebt       -= Maths.min(totalDebt, amount);` and now `totalDebt       = curDebt - Maths.min(curDebt, amount);` where `curDebt` is `totalDebt` + interest (https://github.com/ajna-finance/contracts/pull/143/files#diff-2f9fd539920b1df6741f9c67f34a441cc5649f94d49e2a6ddf12c3339a1a9901R79)

2022-06-13 12:08 UTC, grandizzy commented on src/base/Interest.sol
> +            inflatorSnapshot           = curInflator_;
this shouldn't be the case, `inflatorSnapshot` is updated in `_accumulatePoolInterest` function while the debt is accumulated and passed back to the pool to make additional calculations and then to be stored at the end of each call (that is in every transaction). I don't see where such a scenario where the `totalDebt `is not increased for a window in time but the inflator is could happen...

2022-06-13 12:21 UTC, grandizzy commented on src/ERC20Pool.sol
> +        curDebt += amount_ + fee;
can you pls be more specific? I don't see where to align this line

2022-06-13 12:22 UTC, grandizzy commented on src/ERC20Pool.sol
> +        totalCollateral += amount_;
yep, changed with https://github.com/ajna-finance/contracts/pull/143/commits/e6bf5933d251027a0ef1838fa35f8e109f42bf60

2022-06-13 12:23 UTC, grandizzy commented on src/base/Interest.sol
> +            inflatorSnapshot           = curInflator_;
added with https://github.com/ajna-finance/contracts/pull/143/commits/e6bf5933d251027a0ef1838fa35f8e109f42bf60

2022-06-13 12:28 UTC, grandizzy commented on src/ERC20Pool.sol
> +        (uint256 curDebt, uint256 curInflator) = _accumulatePoolInterest(totalDebt, inflatorSnapshot);
see my comments above

2022-06-13 12:28 UTC, grandizzy commented on src/ERC20Pool.sol
> +        (uint256 curDebt, uint256 curInflator) = _accumulatePoolInterest(totalDebt, inflatorSnapshot);
see my comments above

2022-06-13 16:08 UTC, ith-harvey commented on src/base/Interest.sol
> +            inflatorSnapshot           = curInflator_;
I see, yes you are correct : )

2022-06-13 16:20 UTC, EdNoepel commented on src/ERC20Pool.sol
> +        totalDebt       = curDebt;
`_addQuoteTokenToBucket` doesn't appear to change `curDebt`.  Seems the only reason we'd update `totalDebt` here is for interest accumulation, which should be handled within `_accumulatePoolInterest`.  The consumer would not expect an increase in debt as a result of a lender adding liquidity.

2022-06-13 16:20 UTC, EdNoepel commented on src/base/Interest.sol
> -            totalDebt                  += getPendingInterest(totalDebt, pendingInflator, inflatorSnapshot); // WAD
Why don't we want this method to update `totalDebt` any more?

2022-06-13 16:20 UTC, EdNoepel commented on src/ERC20Pool.sol
> +        totalDebt       = curDebt;
Again, it feels unnatural to adjust total debt from this method.  Purchasing a bid should not result in a non-interest-related change in pool debt.

2022-06-13 16:20 UTC, EdNoepel commented on src/base/Interest.sol
> +            totalDebt   = curDebt;
Even here, it makes sense to accumulate interest before updating the rate, but it doesn't make sense to explicitly change `totalDebt`.

2022-06-13 16:20 UTC, EdNoepel commented on src/base/Interest.sol
> +        return _pendingInflator(previousRate, inflatorSnapshot, block.timestamp - lastInflatorSnapshotUpdate);
I like the way this has been refactored into a public view and internal function which doesn't need to read from storage.

2022-06-13 16:20 UTC, EdNoepel commented on src/ERC20Pool.sol
> +        (totalDebt, ) = _accumulatePoolInterest(totalDebt, inflatorSnapshot);
There are a several actions (lenders adding liquidity, updating interest rate, actor purchasing bid) which aren't expected to result in a change in `totalDebt` other than interest accumulation.  In these cases, the calling function has no need to change debt other than for interest accumulation.  The question becomes whether it makes sense to pollute these function with a `totalDebt` mutation, such that we could realize a gas savings on other functions which are expected to mutate `totalDebt`.

2022-06-13 16:20 UTC, EdNoepel reviewed
Left some comments regarding where `totalDebt` should be mutated and whether the gas optimization is worth the maintainability tradeoff.

2022-06-13 16:37 UTC, grandizzy commented on src/ERC20Pool.sol
> +        totalDebt       = curDebt;
Yep, you are right, only reason is for interest accumulation but also for loading debt only once from storage. How the change works is that `_accumulatePoolInterest` calculate and store in stack the debt accumulated plus interest, passing it then for further calculations inside functions (in this case pool's `addQuoteToken` function. Then at the end of debt calculations it is saved to storage. This is done in order to prevent multiple reads / writes to storage and be more efficient in terms of gas usage (as every load / write will imply such)

2022-06-13 16:40 UTC, grandizzy commented on src/base/Interest.sol
> -            totalDebt                  += getPendingInterest(totalDebt, pendingInflator, inflatorSnapshot); // WAD
The reason is that there could be subsequent actions in debt (like in case of borrow) that would increase debt. That means another `SSTORE` opcode requiring gas https://github.com/wolflo/evm-opcodes/blob/main/gas.md#a7-sstore
Therefore IMO is desired to write it only once at the end of pool function execution.

2022-06-13 16:42 UTC, grandizzy commented on src/ERC20Pool.sol
> +        totalDebt       = curDebt;
Correct, please see my comment above. Since there are other checks (pool collateralization for example) that needs totalDebt is cheaper to pass it as a var from stack instead reading it again from storage.

2022-06-13 16:43 UTC, grandizzy commented on src/base/Interest.sol
> +            totalDebt   = curDebt;
See my previous comment.

2022-06-13 16:45 UTC, grandizzy commented
> 

Makes sense, I'd favour gas cost, happy to discuss as a team in our standup and make the final decision.

2022-06-13 17:12 UTC, ith-harvey commented on src/base/PoolState.sol
> +        return _encumberedCollateral(debt_);
Still a little confused on how the gas savings of this works sadly, lets chat tomorrow when you're back : )

2022-06-13 18:02 UTC, grandizzy commented on src/base/PoolState.sol
> +        return _encumberedCollateral(debt_);
Well this is a public view, it doesn't consume / save gas. The gas savings happens in internal function `_encumberedCollateral` when called by pool functions by not rereading debt from storage and by being an internal call. The public view function `getEncumberedCollateral` calls `_encumberedCollateral` to reuse code. I find it really intuitive to have internal functions prefixed with _ so we know which one is involved in a transaction and hence gas care needed.

2022-06-15 12:05 UTC, EdNoepel approved these changes
LGTM

2022-06-15 15:35 UTC, MikeHathaway commented on src/ERC721Pool.sol
> +    function _tokensInPool(uint256[] memory tokenIds_) internal view {
Was there a reason for changing this from a modifier to a function? Was going to go the opposite way in my Pr and change onlySubset to a modifier as well

2022-06-15 15:41 UTC, MikeHathaway commented on src/ERC721Pool.sol
> +            Maths.ray(tokenIds_.length) <= unencumberedCollateral || unencumberedCollateral >= Maths.ray(tokenIds_.length) + Maths.ONE_RAY,
This require statement isn't equivalent to the previous check, and could fail improperly. The previous encumbrance check looked to see that there was at least 1 whole unencumbered collateral following withdrawal.

2022-06-15 15:41 UTC, MikeHathaway commented on src/ERC721Pool.sol
> +        require(collateral().ownerOf(tokenId_) == address(this), "P:T_NOT_IN_P");
Why was this broken out of a common modifier / function?

2022-06-15 15:46 UTC, MikeHathaway requested changes
Generally looks good, but had some questions about changes to `ERC721Pool`, and I believe the change to `removeCollateralMultiple` encumberance check isn't correct.

2022-06-15 15:47 UTC, grandizzy commented on src/ERC721Pool.sol
> +    function _tokensInPool(uint256[] memory tokenIds_) internal view {
yeah, that's the low hanging fruit in reducing contract size, see https://www.youtube.com/watch?v=XDqD3X8DCiw

2022-06-15 15:48 UTC, grandizzy commented on src/ERC721Pool.sol
> +        require(collateral().ownerOf(tokenId_) == address(this), "P:T_NOT_IN_P");
see above, change was to reduce the contract size

2022-06-15 15:49 UTC, MikeHathaway commented on src/ERC721Pool.sol
> +    function _tokensInPool(uint256[] memory tokenIds_) internal view {
Interesting, thanks

2022-06-15 15:50 UTC, MikeHathaway commented on src/ERC721Pool.sol
> +        require(collateral().ownerOf(tokenId_) == address(this), "P:T_NOT_IN_P");
Wouldn't having a single common reused function for this require check (especially if not a modifier, given above comment) still be less?

2022-06-15 15:51 UTC, grandizzy commented on src/ERC721Pool.sol
> +            Maths.ray(tokenIds_.length) <= unencumberedCollateral || unencumberedCollateral >= Maths.ray(tokenIds_.length) + Maths.ONE_RAY,
hm, why do you think so?

original code reverts if `(Maths.ray(tokenIds_.length) > unencumberedCollateral) ` or `(unencumberedCollateral - Maths.ray(tokenIds_.length) < Maths.ONE_RAY)` which can be written as ``(unencumberedCollateral < Maths.ray(tokenIds_.length) + Maths.ONE_RAY)``

require statement requires `Maths.ray(tokenIds_.length) <= unencumberedCollateral` or `unencumberedCollateral >= Maths.ray(tokenIds_.length) + Maths.ONE_RAY` otherwise reverts

2022-06-15 15:56 UTC, grandizzy commented on src/ERC721Pool.sol
> +        require(collateral().ownerOf(tokenId_) == address(this), "P:T_NOT_IN_P");
let me check, so you basically suggest to have the `modifier tokenInPool` converted to an internal function, is that right?

2022-06-15 15:57 UTC, MikeHathaway commented on src/ERC721Pool.sol
> +        require(collateral().ownerOf(tokenId_) == address(this), "P:T_NOT_IN_P");
Yeah exactly, similar to what was done here for `tokensInPool`

2022-06-15 16:01 UTC, MikeHathaway commented on src/ERC721Pool.sol
> +            Maths.ray(tokenIds_.length) <= unencumberedCollateral || unencumberedCollateral >= Maths.ray(tokenIds_.length) + Maths.ONE_RAY,
Yes, you are right - my mistake.

2022-06-15 16:01 UTC, MikeHathaway approved these changes
LGTM

2022-06-15 16:09 UTC, grandizzy commented on src/ERC721Pool.sol
> +        require(collateral().ownerOf(tokenId_) == address(this), "P:T_NOT_IN_P");
yep, that was a good call, https://github.com/ajna-finance/contracts/pull/143/commits/bbb24492e635c5cb1c033d4411ad21eec824f770 reduced size from 26311 to 25824

2022-06-15 16:41 UTC, ith-harvey approved these changes

2022-06-15 16:48 UTC, merged