Claim collateral multiple
ajna-finance/ajna-core pull request #146
Opened 2022-06-14 17:47 UTC by MikeHathaway

- Changes to the pool deployment process to preclude a potential griefing attack whereby an ERC20 token was incorrectly deployed via the `ERC721PoolFactory` and blocking any future correct deployment by `ERC20PoolFactory` (and vice versa).
- Implements `claimCollateralMultiple()`
- Adds a separate method to `Buckets.sol` for tracking the specific collateral deposited into a bucket.
- Adds additional testing around claimingCollateral and purchaseBid in `ERC721Pool`
- Removes gas optimization around collateral counting that would have opened the door to a minor reentrancy attack.
- Create an `IFungibilePool` interface to host `ERC20Pool` specific code.
- Convert nftBucket to a mapping to an EnnumerableSet

2022-06-14 18:17 UTC, EdNoepel commented on src/ERC721Pool.sol
> +        // Relys on nonRentrant modifier to guard against reentrancy attacks on lpBalance
spelling: "Relies on nonReentrant"

2022-06-15 17:25 UTC, MikeHathaway commented on src/ERC721Pool.sol
> +        // Relys on nonRentrant modifier to guard against reentrancy attacks on lpBalance
I ended up removing the local count gas optimization trick entirely so as to avoid the possible reentrancy and need for that modifier

2022-06-15 18:31 UTC, grandizzy requested changes
LGTM but the comment re doubled require.
Also I think we can get totally rid of NFTBucket struct and use a `uint256 price ->  EnumerableSet.UintSet collateralDeposited` mapping but I am happy to give this a try in a subsequent PR

2022-06-15 18:31 UTC, grandizzy commented on src/ERC721Pool.sol
> +        require(amount_ > getPoolMinDebtAmount(), "P:AQT:AMT_LT_AVG_DEBT");
isn't this one already handled at line 235, by calling the internal function and without reading again from storage

2022-06-15 18:33 UTC, MikeHathaway commented on src/ERC721Pool.sol
> +        require(amount_ > getPoolMinDebtAmount(), "P:AQT:AMT_LT_AVG_DEBT");
Good catch, I will remove that. That was an artifact of resolving the merge conflicts

2022-06-15 18:54 UTC, MikeHathaway commented
> LGTM but the comment re doubled require. Also I think we can get totally rid of NFTBucket struct and use a `uint256 price -> EnumerableSet.UintSet collateralDeposited` mapping but I am happy to give this a try in a subsequent PR

Updated accordingly, seeing major gas savings from doing so.

2022-06-15 19:01 UTC, grandizzy requested changes
LGTM, only one minor change

2022-06-15 19:01 UTC, grandizzy commented on src/base/Buckets.sol
> +        EnumerableSet.UintSet storage collateralDeposited = _collateralDeposited[price_];
this can go below the require statement at line 199, that is to save gas by not loading `collateralDeposited` from storage in case require reverts. I suggest putting it at line 210 ` // update collateralDeposited`

2022-06-15 19:08 UTC, MikeHathaway commented on src/base/Buckets.sol
> +        EnumerableSet.UintSet storage collateralDeposited = _collateralDeposited[price_];
Good idea, updated accordingly

2022-06-15 19:11 UTC, grandizzy approved these changes
LGTM

2022-06-16 02:07 UTC, merged