Split removeQuoteToken and removeCollateral into two methods; one to remove some, another to remove all
ajna-finance/ajna-core pull request #202
Opened 2022-08-21 01:15 UTC by EdNoepel

Before, removal methods were passed a `maxAmount` and calculated how much a user can actually remove given their LP.  We take a max instead of actual amount to allow users to perform a full withdrawal, because they cannot accurately predict how much interest will accumulate in the block where their transaction is mined.

The new solution is to break withdrawals into two methods:
- a full withdrawal, which takes no amount
- a partial withdrawal, which takes the actual amount

Removed the no-longer-necessary `lpsToCollateral` facility created for `PositionManager`.  Extended tests to cover all the potential reverts.  Per feedback on last PR, now also checking return values of removal functions.

Also brought real-world test up-to-date.

2022-08-21 03:08 UTC, EdNoepel commented on src/_test/ERC20Pool/ERC20ScaledPoolCollateral.t.sol
> -        assertEq(_pool.lpBalance(testIndex, address(_bidder)), 12_043.568088791526231380000000000 * 1e27);
this block was duplicated

2022-08-21 18:13 UTC, grandizzy requested changes
Looks good and removes duped operations! Couple of changes requested re minimizing gas cost in case of failures

2022-08-21 18:13 UTC, grandizzy commented on src/base/PositionManager.sol
> +        require(params_.lpTokens != 0 && params_.lpTokens <= curPos, "PM:DL:INSUF_LP_BAL");
I don't think we should check for `params_.lpTokens != 0` and leave it as an user / dapp responsibility? Any special reason you included here?

2022-08-21 18:13 UTC, grandizzy commented on src/base/ScaledPool.sol
> +        require(availableQuoteToken != 0, "S:RAQT:NO_QT");
to minimize gas cost in case of failure, I suggest to 
```
uint256 availableQuoteToken = _rangeSum(index_, index_);
require(availableQuoteToken != 0, "S:RAQT:NO_QT");
```
first and then fetch bucket, calculate `rate` and `amount_` and check for `require(amount_ != 0,             "S:RAQT:NO_CLAIM");`

2022-08-21 18:13 UTC, grandizzy commented on src/base/ScaledPool.sol
> +            amount_ = availableQuoteToken;
nitty style alignment

2022-08-21 18:13 UTC, grandizzy commented on src/base/ScaledPool.sol
> +        buckets[index_] = bucket;
to minimize gas in case of failure we can delay writing bucket to storage until after checking htp against lup `require(_htp() <= newLup, "S:RQT:BAD_LUP");`

2022-08-21 18:13 UTC, grandizzy commented on src/base/ScaledPool.sol
> +        lpBalance[index_][msg.sender] -= lpAmount_;
same as above, to minimize gas in case of failure we can delay writing LP balance to storage until after checking htp against lup `require(_htp() <= newLup, "S:RQT:BAD_LUP");`

2022-08-21 18:13 UTC, grandizzy commented on src/erc20/ERC20Pool.sol
> +        require(bucket.availableCollateral != 0, "S:RAC:NO_COL");
to minimize gas in case of failure this can be checked right after fetching bucket in memory (line 220. possible also before `_accruePoolInterest`?)

2022-08-21 18:13 UTC, grandizzy commented on src/erc20/ERC20Pool.sol
> +        require(amount_ <= bucket.availableCollateral, "S:RC:INSUF_COL");
same as above, let's check this right after fetching bucket from memory (possible also before `_accruePoolInterest` ?)

2022-08-21 18:29 UTC, EdNoepel commented on src/base/PositionManager.sol
> +        require(params_.lpTokens != 0 && params_.lpTokens <= curPos, "PM:DL:INSUF_LP_BAL");
With the old implementation, user could call with 0 LP.  `removeCollateral` and `removeQuoteToken` would silently do nothing, so user would pay the gas without withdrawing anything.

I'll remove this check.  Calling with 0 LP should cause `removeQuoteToken` to revert.

2022-08-21 18:40 UTC, EdNoepel commented on src/erc20/ERC20Pool.sol
> +        require(bucket.availableCollateral != 0, "S:RAC:NO_COL");
Yes; as long as we accrue interest before calculating the tree's `rangeSum`, that should be fine.

2022-08-21 18:56 UTC, EdNoepel commented
@grandizzy  Believe I've hit all items in e86a92287cd4e379facbf21cb9e475d31e3a5179; please have a look.

2022-08-21 19:32 UTC, grandizzy commented
> @grandizzy Believe I've hit all items in [e86a922](https://github.com/ajna-finance/contracts/commit/e86a92287cd4e379facbf21cb9e475d31e3a5179); please have a look.

Yep, all good here

2022-08-21 19:32 UTC, grandizzy approved these changes

2022-08-21 21:20 UTC, MikeHathaway commented on src/base/PositionManager.sol
> +            (collateralToRemove, lpTokensUsed) = pool.removeAllCollateral(params_.index);
Should we be using `removeCollateral` as opposed to `removeAllCollateral` here? There might be situations in which a LP only wants to make a partial claim

2022-08-22 13:01 UTC, EdNoepel commented on src/base/PositionManager.sol
> +            (collateralToRemove, lpTokensUsed) = pool.removeAllCollateral(params_.index);
We've never given the user a choice in how to redeem their LP token, but it would certainly be desirable.

2022-08-22 14:24 UTC, EdNoepel commented on src/base/PositionManager.sol
> +            (collateralToRemove, lpTokensUsed) = pool.removeAllCollateral(params_.index);
Added a comment to the v10 Master Spec to discuss this inconsistency.

2022-08-22 17:10 UTC, merged