Working through liquidation
ajna-finance/ajna-core pull request #258
Opened 2022-09-10 04:23 UTC by ith-harvey

Filled out `kick` & `take` "happy path".
- Implemented accounting for happy path
- Added `Queue` class to track loans in auction

2022-09-21 13:02 UTC, EdNoepel requested changes
Some comments inline.  Curious why there were no updates to NFT pool.  The important bit here is the liquidation queue.

2022-09-21 13:02 UTC, EdNoepel commented on src/base/ScaledPool.sol
> +import "@std/console.sol";
remove before flight

2022-09-21 13:02 UTC, EdNoepel commented on src/erc20/ERC20Pool.sol
> +        //collateral().safeTransfer(msg.sender, collateralToPurchase);
Why is this commented out?  Previous implementation transferred the collateral and then made the external call, as expected.

2022-09-21 13:02 UTC, EdNoepel commented on src/erc20/ERC20Pool.sol
> +    // TODO: remove this method, it is for testing only.
It'd be nice if `foundry` provided a way for us to test internal functions.  I see this is used by `_assertAuction`, so let's determine a long-term solution before merging.

2022-09-21 13:02 UTC, EdNoepel commented on src/erc20/ERC20Pool.sol
> +            liquidations[borrower_].bondSize // used to calculate pending interest (WAD)
nit: comment alignment

2022-09-21 13:02 UTC, EdNoepel commented on src/erc20/interfaces/IERC20Pool.sol
> +    error AuctionIsActive();
These errors should be in `IScaledPool`; we can reuse for fungible and NFT pools.

2022-09-21 13:02 UTC, EdNoepel commented on src/erc20/interfaces/IERC20Pool.sol
> +     *  @return bondSize       Bond
nit: doco alignment

2022-09-21 13:02 UTC, EdNoepel commented on src/erc20/interfaces/IERC20Pool.sol
> +     *  @param  bondSize       Bond
doco should explain `bondFactor` and `bondSize`

2022-09-21 13:02 UTC, EdNoepel commented on src/libraries/Maths.sol
> +    }
We already have `max` and `min` functions which work just fine with unscaled integers.

2022-09-21 13:02 UTC, EdNoepel commented on src/_test/ERC20Pool/ERC20PoolGasLoadTest.t.sol
> +            _mintQuoteAndApproveTokens(lender, 300_000_000_000 * 1e18);
Why did we suddenly need more tokens for the gas load test?

2022-09-21 13:02 UTC, EdNoepel commented on src/_test/ERC20Pool/ERC20ScaledPoolLiquidations.t.sol
> +        //TODO: assert lender state
Several TODOs in this test...will they be handled with a future PR?

2022-10-04 17:46 UTC, EdNoepel reviewed
Quite happy with this, especially relocating `kick` to `Pool.sol`.  Most of my notes involve documentation.  Note the most recent commit indicates `ERC721Pool is 28787 bytes (over size limit of 24576 bytes).`, which needs to be addressed before merging to develop.

2022-10-04 17:46 UTC, EdNoepel commented on src/_test/ERC20Pool/ERC20PoolGasLoadTest.t.sol
> -
nit: likely unintentional removal of blank line between functions

2022-10-04 17:46 UTC, EdNoepel commented on src/base/PoolInfoUtils.sol
> +     *  @notice Returns info related to Auction.
Although it's obvious what to pass, for completeness, natspec should include the two input arguments.

2022-10-04 17:46 UTC, EdNoepel commented on src/base/Pool.sol
> +                if (loansCount != 0
Note: I'm working on changing this to `> 10`.  Happy to leave it `!= 0` for this PR.

2022-10-04 17:46 UTC, EdNoepel commented on src/base/Pool.sol
> +            // If loan has debt or collateralized auction has debt
I cannot reconcile this comment against the code.  The comment should seemingly read `If loan has debt and either no auction is active or the borrower is well-collateralized`.  Have I misunderstood lines 745-748?

2022-10-04 17:46 UTC, EdNoepel commented on src/base/Pool.sol
> +     *  @notice Calculates the MOMP, most optomistic matching price.
sp: `optimistic`

2022-10-04 17:46 UTC, EdNoepel commented on src/base/Pool.sol
> +     *  @param borrowerPledgedCollateral_ Total borrower pledged collateral.
`lup_` param is missing from natspec

2022-10-04 17:46 UTC, EdNoepel commented on src/libraries/PoolUtils.sol
> +    function _sign(int256 val_) private pure returns (int256) {
Does this belong in `Maths` library?

2022-10-04 19:52 UTC, mattcushman commented on src/libraries/PoolUtils.sol
> +        if (thresholdPrice <= neutralPrice) {
should be < not <=- to avoid division by zero

2022-10-05 00:21 UTC, ith-harvey commented
> Quite happy with this, especially relocating `kick` to `Pool.sol`. Most of my notes involve documentation. Note the most recent commit indicates `ERC721Pool is 28787 bytes (over size limit of 24576 bytes).`, which needs to be addressed before merging to develop.

Working with @grandizzy on a refactor fix that will hopefully solve our problem :crossed_fingers:

2022-10-13 19:40 UTC, ith-harvey commented
@grandizzy used this as a guide on his large refactor PRs... this code was included in those PRs, closing.

2022-10-13 19:40 UTC, closed without merging