Claimable Reserve Auction
ajna-finance/ajna-core pull request #262
Opened 2022-09-13 18:13 UTC by EdNoepel

Implemented Claimable Reserve Auctions (CRAs), aka _Ajna Token Burn and Buy_.

Did the unit tests in an NFT collection pool merely to offer some coverage of that deployment use case.

Since the Ajna token address is hardcoded, testing requires testing against a fork with the Ajna token deployed.  CI has already been updated with a `ETH_RPC_URL` secret for this purpose.

2022-09-13 21:23 UTC, EdNoepel commented on src/erc20/ERC20Pool.sol
> +        ajnaTokenAddress           = 0x9a96ec9B57Fb64FbC60B423d1f4da7691Bd35079;
For the record, I don't believe we should hardcode the token address.  It was already hardcoded in `ScaledPool`, but needs to be initialized here to persist when pool is cloned.  I would like to address this in another PR.

2022-09-13 21:24 UTC, EdNoepel commented on src/base/ScaledPool.sol
> +    uint256 public constant MINUTE_HALF_LIFE    = 0.988514020352896135_356867505 * 1e27;  // 0.5^(1/60)
The underscore here separates WAD from RAY precision.  Happy to omit it if confusing.

2022-09-14 02:31 UTC, grandizzy requested changes
looks good, I left couple of comments re optimizing code. NFT pool contract size also started to get over the limit again but I think I'll have soon a proposal to solve this for good

2022-09-14 02:31 UTC, grandizzy commented on src/base/ScaledPool.sol
> +        if (reserveAuctionKicked == 0) {
since `_price` default value is 0 this can be rewritten as
```
if (reserveAuctionKicked != 0) {
    uint256 secondsElapsed = block.timestamp - reserveAuctionKicked;
    uint256 hoursComponent = 1e27 >> secondsElapsed / 3600;
    uint256 minutesComponent = Maths.rpow(MINUTE_HALF_LIFE, secondsElapsed % 3600 / 60);
    _price = Maths.rayToWad(1_000_000_000 * Maths.rmul(hoursComponent, minutesComponent));
}
```

2022-09-14 02:31 UTC, grandizzy commented on src/base/ScaledPool.sol
> +    function _claimableReserves() internal view returns (uint256) {
I think this can be optimized as
```
    function _claimableReserves() internal view returns (uint256 claimable_) {
        claimable_ = Maths.wmul(0.995 * 1e18, borrowerDebt) + quoteToken().balanceOf(address(this));
        claimable -= Maths.min(claimable, this.poolSize() + liquidationBondEscrowed + reserveAuctionUnclaimed);
    }
```

2022-09-14 02:31 UTC, grandizzy commented on src/base/ScaledPool.sol
> +        if (reserveAuctionKicked == 0 || block.timestamp - reserveAuctionKicked > 72 hours) revert NoAuction();
for optimizing gas we can load  `reserveAuctionKicked` from storage only once and then use it to check and revert `NoAuction` if case.

2022-09-14 02:38 UTC, MikeHathaway commented on src/erc20/ERC20Pool.sol
> +        ajnaTokenAddress           = 0x9a96ec9B57Fb64FbC60B423d1f4da7691Bd35079;
It seems like passing it via the factory and setting in `initialize()` might be a good spot?

2022-09-14 03:03 UTC, MikeHathaway commented on src/base/ScaledPool.sol
> +        quoteToken().safeTransfer(msg.sender, amount_ / quoteTokenScale);
Should the `quoteToken().safeTransfer()` happen after the `burn()` as an extra reentrancy guard (don't think it's possible here, but wouldn't hurt).

2022-09-14 03:14 UTC, MikeHathaway approved these changes
LGTM - had a few minor comments but otherwise looks great

2022-09-14 05:40 UTC, EdNoepel commented on src/base/ScaledPool.sol
> +        if (reserveAuctionKicked == 0) {
Done in bd21b9b92bef1c18bbc23b5fd0c71364683ea61a.

2022-09-14 05:40 UTC, EdNoepel commented on src/base/ScaledPool.sol
> +    function _claimableReserves() internal view returns (uint256) {
Agreed; done in bd21b9b92bef1c18bbc23b5fd0c71364683ea61a.

2022-09-14 05:42 UTC, EdNoepel commented on src/base/ScaledPool.sol
> +        if (reserveAuctionKicked == 0 || block.timestamp - reserveAuctionKicked > 72 hours) revert NoAuction();
I was skeptical that the compiler would load an unmutated member variable from storage twice.  Sure enough, average gas dropped from 36274 to 36203 when I read it into a local variable.  Done in bd21b9b92bef1c18bbc23b5fd0c71364683ea61a.

2022-09-14 05:46 UTC, EdNoepel commented on src/base/ScaledPool.sol
> +        quoteToken().safeTransfer(msg.sender, amount_ / quoteTokenScale);
Sure; done in 2d05edae683d3dc052a1c9b57a5c537adf53b9fe.

2022-09-14 05:56 UTC, EdNoepel commented on src/erc20/ERC20Pool.sol
> +        ajnaTokenAddress           = 0x9a96ec9B57Fb64FbC60B423d1f4da7691Bd35079;
Should it be hardcoded in `PoolDeployer`, or should it be an argument to `deployPool`?  We don't want users controlling it, but we also need the ability to pass the correct address for the chain we're deploying to.

2022-09-14 10:12 UTC, grandizzy approved these changes
LGTM

2022-09-14 14:13 UTC, merged