Add pool utils unit tests
ajna-finance/ajna-core pull request #290
Opened 2022-10-19 11:08 UTC by prat-gpt

- poolUtils library unit tests added.
- bucketMath library pending unit tests updated

2022-10-19 17:24 UTC, grandizzy requested changes
Looks good!
Just couple of comments re code style we're using,
- numbers like`1000274010136660929` should be `1.000274010136660929 * 1e18`, it's easier to read / make sense of the precision
- there should always be a space between current and expected, e.g .instead
`assertEq(current,18_942 * 1e18);` should be `assertEq(current, 18_942 * 1e18);`
or instead multiple spaces `assertEq(PoolUtils.encumberance(debt, price),      10.98202093218880245 * 1e18);` should be `assertEq(PoolUtils.encumberance(debt, price), 10.98202093218880245 * 1e18);`
- current and expected should be aligned in the same block, e.g. instead
```
        assertEq(PoolUtils.encumberance(debt, price),   10.98202093218880245 * 1e18);
        assertEq(PoolUtils.encumberance(0, price),  0);
        assertEq(PoolUtils.encumberance(debt, 0),  0);
        assertEq(PoolUtils.encumberance(0, 0),  0);
```
is better / readable to have
```
        assertEq(PoolUtils.encumberance(debt, price), 10.98202093218880245 * 1e18);
        assertEq(PoolUtils.encumberance(0, price),    0);
        assertEq(PoolUtils.encumberance(debt, 0),     0);
        assertEq(PoolUtils.encumberance(0, 0),        0);
```

2022-10-20 16:56 UTC, grandizzy approved these changes

2022-10-28 12:05 UTC, EdNoepel commented on src/_test/BucketMathTest.t.sol
> +    function testLenderInterestMargin() external {
This duplicates a test in `PoolUtils`: https://github.com/ajna-finance/contracts/blob/develop/src/_test/ERC721Pool/ERC721PoolInterest.t.sol#L393

Should discuss value of covering the same functions proxied through different libraries with respect to maintenance cost.

2022-10-28 13:17 UTC, prat-gpt commented on src/_test/BucketMathTest.t.sol
> +    function testLenderInterestMargin() external {
I missed to remove this test. I think we should remove it from the ERC721PoolInterest.t.sol file and move it to the BucketMath test file as this test does not interact with the ERC721 pool at all.

For readabillity and non-duplication perspective, when same function is proxied through different libraries we should keep the test in the most base contract.

If you agree let me know and I will update the PR accordingly.

2022-10-28 13:35 UTC, EdNoepel commented on src/_test/BucketMathTest.t.sol
> +    function testLenderInterestMargin() external {
Agree completely.  👍

2022-10-31 14:15 UTC, merged