Take cleanup
ajna-finance/ajna-core pull request #296
Opened 2022-10-26 16:06 UTC by ith-harvey

* Adjusted when `liquidationBondCleanup` is updated
* Reassigned `collateralTaken_` after possible `RepayAmount_` conditional

2022-10-26 19:18 UTC, EdNoepel commented on src/_test/ERC20Pool/ERC20PoolLiquidations.t.sol
> +                collateralTaken: 0.127160642539504961 * 1e18,
An auction was kicked, and 2 collateral tokens are under liquidation.  Lender runs a full `take` for all the collateral, but only gets 0.127 of it?  Why?

2022-10-26 19:59 UTC, ith-harvey commented on src/_test/ERC20Pool/ERC20PoolLiquidations.t.sol
> +                collateralTaken: 0.127160642539504961 * 1e18,
I asked Matt the same question. This is to protect the borrower... The amount of collateral that we allow the taker to take is restricted by the amount of debt that needs to be covered at the current `auctionPrice` . In this case the borrower only had sub `20.0` of debt, therefore we only allow the taker to take `0.127` collateral because the `aucitonPrice` is so high.

2022-10-26 20:01 UTC, ith-harvey commented on src/libraries/Auctions.sol
> +            collateralTaken_  = Maths.wdiv(quoteTokenAmount_, auctionPrice);
Instead of calculating `collateralTaken_` once on LN 210 we calculate it here and on LN 201 to increase the accuracy of the `collateralTaken_` value. (division twice is BAD)

2022-10-26 20:08 UTC, EdNoepel commented on src/_test/ERC20Pool/ERC20PoolLiquidations.t.sol
> +                collateralTaken: 0.127160642539504961 * 1e18,
Indeed.  I bumped it to 4 hours and got a quarter of the collateral requested.
How can we query the neutral price of the liquidation?

2022-10-26 20:23 UTC, ith-harvey commented on src/_test/ERC20Pool/ERC20PoolLiquidations.t.sol
> +                collateralTaken: 0.127160642539504961 * 1e18,
Hmm correct me if I'm wrong but the same UX would happen if the user were to pass in `maxQuotetoken`... so I think it's safe to say that `maxCollateral` isn't an issue.

Well since NP is calculated by -> `int256 neutralPrice = int256(Maths.wmul(mompFactor_, inflatorSnapshot_));`
, we could have the UI / SDK get the mompFactor of the borrower in liquidation and multiply that by the PoolState.inflator (both of these values would be out of date so to speak as the pool level inflator is only congruent with the last time the pool was touched... ). That could at least provide the taker with a worst expected take (worst expected swap of QT for CT base d on old `neutralPrice` value). Admittedly I don't like that UX....

2022-10-26 20:50 UTC, EdNoepel commented on src/_test/ERC20Pool/ERC20PoolLiquidations.t.sol
> +                collateralTaken: 0.127160642539504961 * 1e18,
Agreed; I was confusing the MOMP (attached to the liquidation) with the MOMP factor (attached to the borrower).  If I understand correctly, the former is the neutral price and requires no inflator adjustment.

2022-10-27 09:28 UTC, grandizzy requested changes

2022-10-27 09:28 UTC, grandizzy commented on src/libraries/Auctions.sol
> +import '@std/console.sol';
This can be removed

2022-10-27 09:28 UTC, grandizzy commented on src/libraries/Auctions.sol
> +            self.liquidationBondEscrowed            += bondChange_;
we have to assert / cover `liquidationBondEscrowed` accumulator changes in our forge tests (maybe as part of `_assertAuction`)

2022-10-27 12:55 UTC, EdNoepel commented on src/libraries/Auctions.sol
> +            self.liquidationBondEscrowed            += bondChange_;
If we make changes to `_assertAuction`, I recommend we assert on the auction price as well.

2022-10-27 17:02 UTC, ith-harvey commented on src/_test/ERC20Pool/ERC20PoolLiquidations.t.sol
> +                collateralTaken: 0.127160642539504961 * 1e18,
No the latter, as per the V10 docs: `The actual neutral price for the loan is this factor multiplied by the current borrowerInflator.`

2022-10-27 20:19 UTC, ith-harvey commented on src/libraries/Auctions.sol
> +            self.liquidationBondEscrowed            += bondChange_;
resolved -> https://github.com/ajna-finance/contracts/pull/296/commits/8cc44ade159bcc35c8f3ba68dfadd7d0e0c3aa4a

2022-10-27 20:20 UTC, ith-harvey commented on src/libraries/Auctions.sol
> +import '@std/console.sol';
resolved -> https://github.com/ajna-finance/contracts/pull/296/commits/8cc44ade159bcc35c8f3ba68dfadd7d0e0c3aa4a

2022-10-27 21:06 UTC, EdNoepel requested changes

2022-10-27 21:06 UTC, EdNoepel commented on src/base/Pool.sol
> +            auctions.totalBondEscrowed
`auctionInfo` should only return data which pertains to an auction identified by the specified borrower.  It should not return the pool-level `totalBondEscrowed`.  `DSTestPlus._assertAuction` should query that separately.

2022-10-28 15:27 UTC, ith-harvey commented on src/base/Pool.sol
> +            auctions.totalBondEscrowed
resolved -> https://github.com/ajna-finance/contracts/pull/296/commits/bb4faa208ab8e3c7e4b8e677af5f7a72ae06554d

2022-10-28 15:29 UTC, EdNoepel commented on src/base/Pool.sol
> +            auctions.totalBondEscrowed
👌

2022-10-28 15:32 UTC, EdNoepel approved these changes
Looks good.  👍

2022-10-28 15:39 UTC, ith-harvey commented
I'll wait to merge until after @grandizzy PR

2022-10-28 17:20 UTC, grandizzy commented
> I'll wait to merge until after @grandizzy PR

It is merged now, there are merging conflicts in this PR though :(

2022-10-28 17:21 UTC, grandizzy approved these changes
good to go after resolving merge PR

2022-10-28 19:14 UTC, EdNoepel approved these changes
Still looks good.

2022-10-28 19:19 UTC, merged