ERC20 Arb take
ajna-finance/ajna-core pull request #312
Opened 2022-11-03 13:51 UTC by grandizzy

- changed pool's `arbTake` signature and removed `amount` parameter (arb is bounded by amount of borrower debt / collateral and bucket deposit) 
- added `AuctionPriceGteQArbPrice` error to revert when price of arbed bucket is lower than auction price
- included `isReward` flag in `ArbTake` event
- added `Auctions._validateTake` that is called by both `*take` methods (and will probably be called by `depositTake` too): check if auction is valid to be taken and calculates values for take action
- added `Buckets.addLPs` to add LP amount in bucket and lender's accumulators

Tests:
- moved all `*take` assertion from `ERC20DSTestPlus` to `DSTestPlus`
- `testArbTakeLTNeutralPrice` and `testArbTakeGTNeutralPrice` + revert tests `testArbTakeReverts`. Other tests pending. TODO: in a different PR we should split auction related tests in different contracts as `ERC20PoolLiquidationsTest` counts now 2160 LOCs and it becomes hard to follow / maintain
- added gas load test for `arbTake` with different way of deposits setup

gas results (`arbTake` test skips hours to account interest rate accumulation while regular `take` doesn't hence the difference in gas)
```
│ addQuoteToken                              ┆ 91205           ┆ 153360 ┆ 132790 ┆ 638279  ┆ 47999   │
│ arbTake                                    ┆ 400167          ┆ 400191 ┆ 400191 ┆ 400215  ┆ 2       │
│ borrow                                     ┆ 167250          ┆ 226820 ┆ 192581 ┆ 768700  ┆ 104002  │
│ kick                                       ┆ 173453          ┆ 252313 ┆ 246817 ┆ 1078412 ┆ 32000   │
│ moveQuoteToken                             ┆ 269533          ┆ 269533 ┆ 269533 ┆ 269533  ┆ 1       │
│ pledgeCollateral                           ┆ 62635           ┆ 65226  ┆ 64870  ┆ 508922  ┆ 96001   │
│ removeAllQuoteToken                        ┆ 149391          ┆ 151566 ┆ 151274 ┆ 165987  ┆ 2000    │
│ removeQuoteToken                           ┆ 184168          ┆ 189999 ┆ 189793 ┆ 207041  ┆ 2000    │
│ repay                                      ┆ 483292          ┆ 558028 ┆ 569947 ┆ 809526  ┆ 16001   │
│ take                                       ┆ 51484           ┆ 55208  ┆ 54672  ┆ 274626  ┆ 15998   │
```
compared with `develop`
```
│ addQuoteToken                              ┆ 91148           ┆ 156506 ┆ 133879 ┆ 638222  ┆ 43999   │
│ borrow                                     ┆ 167250          ┆ 231927 ┆ 191892 ┆ 768700  ┆ 88002   │
│ kick                                       ┆ 173475          ┆ 249007 ┆ 244636 ┆ 1078434 ┆ 16000   │
│ moveQuoteToken                             ┆ 288482          ┆ 288482 ┆ 288482 ┆ 288482  ┆ 1       │
│ pledgeCollateral                           ┆ 62657           ┆ 64767  ┆ 64836  ┆ 508944  ┆ 80001   │
│ removeAllQuoteToken                        ┆ 149413          ┆ 151586 ┆ 151292 ┆ 168363  ┆ 2000    │
│ removeQuoteToken                           ┆ 184190          ┆ 190022 ┆ 189815 ┆ 209403  ┆ 2000    │
│ repay                                      ┆ 483292          ┆ 558028 ┆ 569947 ┆ 809526  ┆ 16001   │
│ take                                       ┆ 51387           ┆ 55130  ┆ 54594  ┆ 274548  ┆ 15998   │
```

2022-11-04 01:10 UTC, ith-harvey reviewed
Its a WIP let's keep chipping

2022-11-04 01:10 UTC, ith-harvey commented on src/erc20/ERC20Pool.sol
> +        if (auctionPrice >= bucketPrice) revert BadArbTakePrice();
Would rename revert to `revert AuctionPriceGTEQArbPrice()`

2022-11-04 01:10 UTC, ith-harvey commented on src/erc20/ERC20Pool.sol
> +        buckets[index_].collateral += collateralArbed;
nit: formatting assignment

2022-11-04 01:10 UTC, ith-harvey commented on src/libraries/Auctions.sol
> +        if (!isRewarded_) {
@mattcushman can you confirm... is there a possible case where the BPF is negative and the kicker is penalized?

Since the `auctionPrice` is always less then the `HPB` my understanding is that they kicker is never penalized and always rewarded.

2022-11-04 01:10 UTC, ith-harvey commented on src/libraries/Auctions.sol
> +        if (borrowerDebt >= bucketDeposit_) {
Should we perform a check `bucketDeposit_ != 0 && borrowerDebt != 0 && borrowerCollateral != 0` ? (remember an auction could be active have debt  but no collateral... as we have seen in tests : ))

Also I think this code could be simplified to:
```
uint256 depositToArb = Maths.min(bucketDeposit_, borrowerDebt);
collateralArbed_         = Maths.wdiv(depositToArb, Maths.wmul(auctionPrice_, factor))
```

2022-11-04 01:10 UTC, ith-harvey commented on src/libraries/Auctions.sol
> +        if (!isRewarded_) {
Actually now that I think of it yes this situation could happen. A lender could deposit after the loan has been kicked but before the debt has been taken... this situation would penalize the kicker.

2022-11-04 01:44 UTC, ith-harvey commented on src/_test/ERC20Pool/ERC20PoolLiquidations.t.sol
> +        // _arbTake(
I get an over/underflow when I uncomment the `arbTake` here -> https://github.com/ajna-finance/contracts/blob/21d2e82fe5d27370d69c99d22c52b26ea3bd229c/src/base/Pool.sol#L513

This is due to the arb take attempting to repay more debt then exists in the loan. I think this issue arrises here inside `auctions.arbTake` -> https://github.com/ajna-finance/contracts/blob/21d2e82fe5d27370d69c99d22c52b26ea3bd229c/src/libraries/Auctions.sol#L272

As that is where we determine the quoteTokenAmount to be repaid although I'm still not sure why that amount is greater then borrower debt...

2022-11-04 04:00 UTC, ith-harvey commented on src/libraries/Auctions.sol
> +        if (!isRewarded_) {
added that here but it overflows -> https://github.com/ajna-finance/contracts/pull/312/commits/20647e72eef345cfb282d71ed0d530d17a23798e

2022-11-04 05:30 UTC, grandizzy commented on src/libraries/Auctions.sol
> +        if (borrowerDebt >= bucketDeposit_) {
Check for collateral is done in ERC20Pool.arbTake

I wrote it this way to avoid stack too deep, I also think that's better readable, as Matt pointed out in some other reviews.

2022-11-04 05:33 UTC, grandizzy commented on src/libraries/Auctions.sol
> +        if (!isRewarded_) {
most probably due to the TODO here https://github.com/ajna-finance/contracts/pull/312/files#diff-f60f760fc956e7ea35a0c59d0aee29a65646591dc54271fff50ddc44c06ce7f3R184
`TODO should quoteTokenAmount be expressed in t0 debt or it is already?`

2022-11-04 06:50 UTC, grandizzy commented on src/libraries/Auctions.sol
> +        if (!isRewarded_) {
fixed with https://github.com/ajna-finance/contracts/pull/312/commits/24700909fb732c9a952e46738c00fa13c055282e

2022-11-04 07:08 UTC, grandizzy commented on src/erc20/ERC20Pool.sol
> +        if (auctionPrice >= bucketPrice) revert BadArbTakePrice();
changed in https://github.com/ajna-finance/contracts/pull/312/commits/5dcb833b7dc3e152e31a35b974897eed69453444

2022-11-04 07:08 UTC, grandizzy commented on src/erc20/ERC20Pool.sol
> +        buckets[index_].collateral += collateralArbed;
changed in https://github.com/ajna-finance/contracts/pull/312/commits/10a90e0b58ba54917c77200b2fa98308019ef4f8

2022-11-04 07:09 UTC, grandizzy commented on src/_test/ERC20Pool/ERC20PoolLiquidations.t.sol
> +        // _arbTake(
fixed with https://github.com/ajna-finance/contracts/commit/24700909fb732c9a952e46738c00fa13c055282e

2022-11-04 20:30 UTC, ith-harvey commented on src/libraries/Auctions.sol
> +        if (borrowerDebt >= bucketDeposit_) {
Sorry George, is that in response to this? -> 
```
Should we perform a check bucketDeposit_ != 0 && borrowerDebt != 0 && borrowerCollateral != 0 ? (remember an auction could be active have debt but no collateral... as we have seen in tests : ))
```

2022-11-05 11:14 UTC, grandizzy commented on src/libraries/Auctions.sol
> +        if (borrowerDebt >= bucketDeposit_) {
yeah, Check for collateral is done in `ERC20Pool.arbTake`

2022-11-05 14:43 UTC, mattcushman commented on src/libraries/Auctions.sol
> +            t0repayAmount_    = Maths.wdiv(quoteTokenAmount_, poolInflator_);
These should be:
t0repayAmount_ = Maths.wdiv(Maths.wmul(factor,quoteTokenAmount_), poolInflator_);

2022-11-05 14:43 UTC, mattcushman commented on src/libraries/Auctions.sol
> +            quoteTokenAmount_ = bucketDeposit_;
I think this should be Maths.wdiv(bucketDeposit_, factor);

2022-11-05 14:43 UTC, mattcushman commented on src/libraries/Auctions.sol
> +            quoteTokenAmount_ = Maths.wmul(t0repayAmount_, poolInflator_);
Should be 
quoteTokenAmount_ = Maths.wdiv(Maths.wmul(t0repayAmount_, poolInflator_), factor);;

2022-11-05 15:55 UTC, mattcushman requested changes

2022-11-05 15:55 UTC, mattcushman commented on src/erc20/ERC20Pool.sol
> +        deposits.remove(index_, quoteTokenAmount);
This should be quoteTokenAmount*factor.   Equivalently (and easier to implement and perhaps more intuitive) here would be to use:

if (isRewarded)
  deposits.remove(index_, quoteTokenAmount+bondChange);
else
  deposits.remove(index_, quoteTokenAmount);

2022-11-05 16:18 UTC, grandizzy commented on src/erc20/ERC20Pool.sol
> +        deposits.remove(index_, quoteTokenAmount);
added in https://github.com/ajna-finance/contracts/pull/312/commits/7ca0040cc2a23c2e0bffe63d9d367e5fb5e42957

2022-11-05 16:18 UTC, grandizzy commented on src/libraries/Auctions.sol
> +            quoteTokenAmount_ = Maths.wmul(t0repayAmount_, poolInflator_);
changed in https://github.com/ajna-finance/contracts/pull/312/commits/7ca0040cc2a23c2e0bffe63d9d367e5fb5e42957

2022-11-05 16:18 UTC, grandizzy commented on src/libraries/Auctions.sol
> +            quoteTokenAmount_ = bucketDeposit_;
changed in https://github.com/ajna-finance/contracts/pull/312/commits/7ca0040cc2a23c2e0bffe63d9d367e5fb5e42957

2022-11-05 16:18 UTC, grandizzy commented on src/libraries/Auctions.sol
> +            t0repayAmount_    = Maths.wdiv(quoteTokenAmount_, poolInflator_);
changed in https://github.com/ajna-finance/contracts/pull/312/commits/7ca0040cc2a23c2e0bffe63d9d367e5fb5e42957

2022-11-05 19:11 UTC, EdNoepel reviewed
Quite happy with the `_validateTake` and `addLPs` refactoring.
Agree about splitting up liquidation tests into several files/contracts in another PR.  Happy to help with that after this is merged.

2022-11-05 19:23 UTC, grandizzy commented
> Quite happy with the `_validateTake` and `addLPs` refactoring. Agree about splitting up liquidation tests into several files/contracts in another PR. Happy to help with that after this is merged.

Sounds great!
Re refactoring `addLPs` - I am still thinking if bucket accumulator should also be updated here (as it is PR) but rather rename `addLPs` to `addLenderLPs` and only update lenders balance... reason for this is that if we have to update balances for 2 lenders (as in arbTake case for kicker and taker) there will be 2 storage writes to update bucket lps... (whereas if updated outside of the function there will be only one, but probably increase contract size). What's your take on this?

2022-11-06 14:42 UTC, mattcushman commented on src/erc20/ERC20Pool.sol
> +    function arbTake(
What is there in this that is specific to erc20 tokens as opposed to NFTs?  In theory arbTake should be identical between the two, including allowing arbitrary fraction quantities of NFT to be taken.

2022-11-06 14:42 UTC, mattcushman commented on src/_test/ERC20Pool/ERC20PoolLiquidations.t.sol
> +        _arbTake(
I think it would be a good idea to add an assertion for the pool reserves before and after takes as well.  The reserves should remain invariant.

2022-11-06 15:12 UTC, grandizzy commented on src/erc20/ERC20Pool.sol
> +    function arbTake(
Unfortunately at this moment ERC721 pool contract size exceeds the limit if `arbTake` logic is moved in base class, will keep it for ERC20 pool only for now and check to make some more space for NFT in a follow up PR

2022-11-06 15:12 UTC, grandizzy commented on src/_test/ERC20Pool/ERC20PoolLiquidations.t.sol
> +        _arbTake(
assert it for both `take` and `arbTake` here https://github.com/ajna-finance/contracts/pull/312/commits/c29ded94ba9577f5bdefe5b5c637de980a61e374

2022-11-06 15:19 UTC, mattcushman reviewed
lgtm

2022-11-06 15:20 UTC, mattcushman approved these changes

2022-11-06 15:25 UTC, merged