Fix bug for apply penalty on remove liquidity
ajna-finance/ajna-core pull request #334
Opened 2022-11-11 19:14 UTC by grandizzy

- Fix apply penalty on remove quote token even if no collateral pledged to pool
- Add test to expose scenario where lender cannot withdraw all their quote tokens if there is still collateral pledged in bucket after repay

2022-11-11 19:38 UTC, MikeHathaway approved these changes
LGTM

2022-11-11 20:43 UTC, EdNoepel requested changes

2022-11-11 20:43 UTC, EdNoepel commented on src/libraries/PoolUtils.sol
> +                if (poolState_.collateral != 0) {
This logic still doesn't look right.  If it's called from `removeQuoteToken` (`toIndex_ == 0`), it should not apply the penalty if withdrawal is below the PTP.

2022-11-11 20:46 UTC, grandizzy commented on src/libraries/PoolUtils.sol
> +                if (poolState_.collateral != 0) {
I see. So what's the PTP value when there's no collateral pledged in pool, is it considered 0?

2022-11-11 21:11 UTC, EdNoepel commented on src/libraries/PoolUtils.sol
> +                if (poolState_.collateral != 0) {
Yes; from the spec:
```
Pool Threshold Price (PTP)
   Total Debt / Total Collateral Posted
   If no collateral has been deposited, the PTP is defined as 0.
```

2022-11-11 21:31 UTC, grandizzy commented on src/libraries/PoolUtils.sol
> +                if (poolState_.collateral != 0) {
👍

2022-11-12 09:52 UTC, grandizzy commented on src/libraries/PoolUtils.sol
> +                if (poolState_.collateral != 0) {
pls check with https://github.com/ajna-finance/contracts/pull/334/commits/052a104966464374018811ebccdf90ca34abaee3

2022-11-12 12:56 UTC, EdNoepel approved these changes
Perfecto.

2022-11-12 12:58 UTC, merged