Restructured Take tests
ajna-finance/ajna-core pull request #356
Opened 2022-11-21 17:42 UTC by ith-harvey

Tests that were added per @mattcushman request:
* `testTakeLoanColConstraintBpfPosNoResidual` - `C` contstraint
* `testTakeCallerColConstraintBpfPosNoResidual` - `Q/p` constraint
* `testTakeCallerColConstraintBpfPosResidual` - `Q/p` constraint
* `testTakeCallerColConstraintBpfNegResidual` - `Q/p` constraint
* `testTakeLoanDebtConstraintBpfPosResidual` - `Debt/p(1-BPF)` constraint

Other test related changes:
* altered `auctionInfo` to return `bondSize` (as bondSize check in tests was not addressing kicker kicking multiple loans)
* altered `_assertAuction` to take `neutralPrice` of auction.
* created `_assertPrices` method to mitigate stack too deep err in `_assertAuction`
* created `tests/forge/ERC20Pool/ERC20PoolLiquidationsMisc.t.sol` to store situational liquidation test cases

Tests were added based on this google sheet -> https://docs.google.com/spreadsheets/d/15wmijL-SZey6ZUe17FyXW1m7JFiEtxOMJUJKZqxlDS0/edit#gid=0

Old Coverage:
```
| File                                                | % Lines           | % Statements       | % Branches       | % Funcs          |
|-----------------------------------------------------|-------------------|--------------------|------------------|------------------|
| src/base/FlashloanablePool.sol                      | 90.91% (10/11)    | 86.67% (13/15)     | 75.00% (6/8)     | 100.00% (4/4)    |
| src/base/PermitERC20.sol                            | 0.00% (0/6)       | 0.00% (0/6)        | 0.00% (0/4)      | 0.00% (0/4)      |
| src/base/PermitERC721.sol                           | 92.86% (13/14)    | 94.12% (16/17)     | 33.33% (4/12)    | 100.00% (4/4)    |
| src/base/Pool.sol                                   | 99.64% (277/278)  | 98.90% (360/364)   | 92.22% (83/90)   | 100.00% (44/44)  |
| src/base/PoolInfoUtils.sol                          | 73.17% (60/82)    | 71.20% (89/125)    | 100.00% (6/6)    | 50.00% (8/16)    |
| src/base/PositionManager.sol                        | 92.00% (46/50)    | 88.57% (62/70)     | 56.25% (9/16)    | 80.00% (8/10)    |
| src/base/PositionNFT.sol                            | 0.00% (0/9)       | 0.00% (0/14)       | 100.00% (0/0)    | 0.00% (0/3)      |
| src/erc20/ERC20Pool.sol                             | 100.00% (49/49)   | 94.92% (56/59)     | 66.67% (8/12)    | 100.00% (11/11)  |
| src/erc20/ERC20PoolFactory.sol                      | 100.00% (8/8)     | 100.00% (12/12)    | 100.00% (0/0)    | 100.00% (1/1)    |
| src/erc721/ERC721Pool.sol                           | 100.00% (67/67)   | 97.53% (79/81)     | 71.43% (10/14)   | 100.00% (12/12)  |
| src/erc721/ERC721PoolFactory.sol                    | 100.00% (8/8)     | 100.00% (11/11)    | 100.00% (0/0)    | 100.00% (2/2)    |
| src/libraries/Auctions.sol                          | 90.64% (155/171)  | 89.73% (166/185)   | 90.38% (47/52)   | 100.00% (13/13)  |
| src/libraries/BucketMath.sol                        | 93.94% (31/33)    | 93.33% (42/45)     | 71.43% (10/14)   | 90.00% (9/10)    |
| src/libraries/Buckets.sol                           | 91.67% (44/48)    | 93.10% (54/58)     | 88.89% (16/18)   | 100.00% (12/12)  |
| src/libraries/Deposits.sol                          | 41.32% (50/121)   | 37.01% (57/154)    | 33.33% (16/48)   | 38.46% (5/13)    |
| src/libraries/Loans.sol                             | 0.00% (0/52)      | 0.00% (0/58)       | 0.00% (0/28)     | 0.00% (0/12)     |
| src/libraries/Maths.sol                             | 19.44% (7/36)     | 17.50% (7/40)      | 0.00% (0/4)      | 25.00% (7/28)    |
| src/libraries/PoolUtils.sol                         | 68.97% (20/29)    | 69.44% (25/36)     | 40.00% (4/10)    | 80.00% (12/15)   |
| Total                                               | 51.30% (966/1883) | 51.94% (1191/2293) | 59.76% (245/410) | 48.72% (190/390) |
```

Coverage with changes:
```
| File                                                | % Lines           | % Statements       | % Branches       | % Funcs          |
|-----------------------------------------------------|-------------------|--------------------|------------------|------------------|
| src/base/FlashloanablePool.sol                      | 90.91% (10/11)    | 86.67% (13/15)     | 75.00% (6/8)     | 100.00% (4/4)    |
| src/base/PermitERC20.sol                            | 0.00% (0/6)       | 0.00% (0/6)        | 0.00% (0/4)      | 0.00% (0/4)      |
| src/base/PermitERC721.sol                           | 92.86% (13/14)    | 94.12% (16/17)     | 33.33% (4/12)    | 100.00% (4/4)    |
| src/base/Pool.sol                                   | 99.64% (277/278)  | 98.90% (360/364)   | 92.22% (83/90)   | 100.00% (44/44)  |
| src/base/PoolInfoUtils.sol                          | 73.17% (60/82)    | 71.20% (89/125)    | 100.00% (6/6)    | 50.00% (8/16)    |
| src/base/PositionManager.sol                        | 92.00% (46/50)    | 88.57% (62/70)     | 56.25% (9/16)    | 80.00% (8/10)    |
| src/base/PositionNFT.sol                            | 0.00% (0/9)       | 0.00% (0/14)       | 100.00% (0/0)    | 0.00% (0/3)      |
| src/erc20/ERC20Pool.sol                             | 100.00% (49/49)   | 94.92% (56/59)     | 66.67% (8/12)    | 100.00% (11/11)  |
| src/erc20/ERC20PoolFactory.sol                      | 100.00% (8/8)     | 100.00% (12/12)    | 100.00% (0/0)    | 100.00% (1/1)    |
| src/erc721/ERC721Pool.sol                           | 100.00% (67/67)   | 97.53% (79/81)     | 71.43% (10/14)   | 100.00% (12/12)  |
| src/erc721/ERC721PoolFactory.sol                    | 100.00% (8/8)     | 100.00% (11/11)    | 100.00% (0/0)    | 100.00% (2/2)    |
| src/libraries/Auctions.sol                          | 90.64% (155/171)  | 89.73% (166/185)   | 90.38% (47/52)   | 100.00% (13/13)  |
| src/libraries/BucketMath.sol                        | 93.94% (31/33)    | 93.33% (42/45)     | 71.43% (10/14)   | 90.00% (9/10)    |
| src/libraries/Buckets.sol                           | 91.67% (44/48)    | 93.10% (54/58)     | 88.89% (16/18)   | 100.00% (12/12)  |
| src/libraries/Deposits.sol                          | 41.32% (50/121)   | 37.01% (57/154)    | 33.33% (16/48)   | 38.46% (5/13)    |
| src/libraries/Loans.sol                             | 0.00% (0/52)      | 0.00% (0/58)       | 0.00% (0/28)     | 0.00% (0/12)     |
| src/libraries/Maths.sol                             | 19.44% (7/36)     | 17.50% (7/40)      | 0.00% (0/4)      | 25.00% (7/28)    |
| src/libraries/PoolUtils.sol                         | 68.97% (20/29)    | 69.44% (25/36)     | 40.00% (4/10)    | 80.00% (12/15)   |

```

2022-11-25 13:54 UTC, grandizzy requested changes
great job, we should get a `make coverage` before and after, I expect to greatly improve it!  let's `tearDown` new tests too and see if that reveals something wrong with the pool (no need to fix them in this PR but just mark them with // FIXME so we're aware they're failing and to address later)

2022-11-25 13:54 UTC, grandizzy commented on tests/forge/ERC20Pool/ERC20PoolLiquidationsMisc.t.sol
> +    function testLenderForcedExit() external {
this test is different than in develop as it is missing `tearDown` (really important as this is the test that revealed dust amounts)

2022-11-25 13:54 UTC, grandizzy commented on tests/forge/ERC20Pool/ERC20PoolFactory.t.sol
> +        assertEq(address(pool),              poolAddress);
nit: remove extra space

2022-11-25 13:54 UTC, grandizzy commented on tests/forge/ERC20Pool/ERC20PoolLiquidationsArbTake.t.sol
> +        );
nit: remove extra space

2022-11-25 13:54 UTC, grandizzy commented on tests/forge/ERC20Pool/ERC20PoolLiquidationsTake.t.sol
> +    function testTakeCallerColConstraintBpfPosNoResidual() external {
missing `tearDown`

2022-11-25 13:54 UTC, grandizzy commented on tests/forge/ERC20Pool/ERC20PoolLiquidationsTake.t.sol
> +    function testTakeCallerColConstraintBpfPosResidual () external {
missing `tearDown`

2022-11-26 23:10 UTC, mattcushman commented on tests/forge/ERC20Pool/ERC20PoolLiquidationsArbTake.t.sol
> +               neutralPrice:      9.818751856078723036 * 1e18
Down below, it looks like the exchangeRate of the i1505.26 bucket slightly changes.  This is probably just rounding, but would be curious to dig into it a bit and undertand what happened there.  In general, I think it would be handy to have a way to assert the invariants that the bucket exchange rates don't change, and that the pool reserves don't change, upon any take, arbtake or deposit take.

2022-11-26 23:10 UTC, mattcushman commented on tests/forge/ERC20Pool/ERC20PoolLiquidationsDepositTake.t.sol
> +               neutralPrice:      10.054229685007659070 * 1e18
The exchange rate in line 503 for example below seems like more than a rounding change.  I think we should dig into why it changes by about .1%

2022-11-26 23:10 UTC, mattcushman commented on tests/forge/ERC20Pool/ERC20PoolLiquidationsDepositTake.t.sol
> +               neutralPrice:      10.054229685007659070 * 1e18
It would be helpful to know the price to more precision as well, I can only see 1505.26 (maybe it's here somewhere?)

2022-11-26 23:10 UTC, mattcushman commented on tests/forge/ERC20Pool/ERC20PoolLiquidationsDepositTake.t.sol
> +               neutralPrice:      10.054229685007659070 * 1e18
Below, this seems to suggest the amount of collateral is ever so slightly incorrect in the bucket.  According to the assert, there is 0.013139866518142482.

These are off by 2.5e-5, which is about the error in the exchange rate I observe.

awk '{printf("%.18f\n", 19.778456451861613480 / 1.005^1467)}'

0.013139529025907593

2022-11-27 10:37 UTC, grandizzy requested changes

2022-11-27 10:37 UTC, grandizzy commented on tests/forge/ERC20Pool/ERC20PoolLiquidationsTake.t.sol
> -    function testTakeAndSettle() external {
just noticed the `tearDown` sequence is also fixed by Fenwick dust commit and test is passing in develop, mind to change `testTakeAndSettle` to `function testTakeAndSettle() external tearDown {` and remove `//FIXME` in this PR?

2022-11-27 11:45 UTC, grandizzy commented on tests/forge/ERC20Pool/ERC20PoolLiquidationsArbTake.t.sol
> +               neutralPrice:      9.818751856078723036 * 1e18
maybe because when adding the 15 quote tokens in bucket to arb, pool debt is also accrued?
https://github.com/ajna-finance/contracts/blob/liq-take-test-refactor/tests/forge/ERC20Pool/ERC20PoolLiquidationsArbTake.t.sol#L533

2022-11-27 16:47 UTC, mattcushman commented on tests/forge/ERC20Pool/ERC20PoolLiquidationsArbTake.t.sol
> +               neutralPrice:      9.818751856078723036 * 1e18
yikes.  I'd recommend trying to strip these tests down to the bare minimum.  I don't think that this is the driver in this case, because the difference in exchange rates is so small.  What do we think of adding these invariant tests though, that check that, immediately before and after the take, the exchange rates and reserves don't change?

2022-11-29 22:52 UTC, ith-harvey commented on tests/forge/ERC20Pool/ERC20PoolLiquidationsMisc.t.sol
> +    function testLenderForcedExit() external {
resolved https://github.com/ajna-finance/contracts/pull/356/commits/04c38cae4ffa3cca600f2d85e5c2a3274ff2238c

2022-11-29 22:53 UTC, ith-harvey commented on tests/forge/ERC20Pool/ERC20PoolFactory.t.sol
> +        assertEq(address(pool),              poolAddress);
resolved

2022-11-29 22:54 UTC, ith-harvey commented on tests/forge/ERC20Pool/ERC20PoolLiquidationsArbTake.t.sol
> +        );
Resolved

2022-11-29 22:54 UTC, ith-harvey commented on tests/forge/ERC20Pool/ERC20PoolLiquidationsTake.t.sol
> +    function testTakeCallerColConstraintBpfPosNoResidual() external {
resolved

2022-11-29 22:54 UTC, ith-harvey commented on tests/forge/ERC20Pool/ERC20PoolLiquidationsTake.t.sol
> +    function testTakeCallerColConstraintBpfPosResidual () external {
resolved

2022-11-29 22:55 UTC, ith-harvey commented on tests/forge/ERC20Pool/ERC20PoolLiquidationsTake.t.sol
> -    function testTakeAndSettle() external {
resolved

2022-11-29 23:05 UTC, ith-harvey commented on tests/forge/ERC20Pool/ERC20PoolLiquidationsDepositTake.t.sol
> +               neutralPrice:      10.054229685007659070 * 1e18
Added an `_assertBucket` here -> https://github.com/ajna-finance/contracts/pull/356/commits/8be2503e0afd5b3f22048e21bd464d2fa31cc554

The price level for reference is `1_505.263728469068226832 * 1e18` -> https://github.com/ajna-finance/contracts/blob/2b83da1b6bef9ad58cf15bf4ffaab5082036c755/tests/forge/utils/DSTestPlus.sol#L49

2022-11-29 23:06 UTC, ith-harvey commented on tests/forge/ERC20Pool/ERC20PoolLiquidationsArbTake.t.sol
> +               neutralPrice:      9.818751856078723036 * 1e18
I could work with you to write a separate test if you would like @mattcushman in another PR :+1:

2022-11-29 23:07 UTC, ith-harvey commented on tests/forge/ERC20Pool/ERC20PoolLiquidationsDepositTake.t.sol
> +               neutralPrice:      10.054229685007659070 * 1e18
Since this isn't directly related to my tests as the tests I added were take related are we ok with getting this reviewed and added then tackling this issue in a separate test / fresh PR?

2022-11-30 18:59 UTC, EdNoepel commented on tests/forge/ERC20Pool/ERC20PoolLiquidationsMisc.t.sol
> +        _take(
The idea here is that the lender is willing to take early and forfeit some of their liquidation bond because they want to withdraw their deposit a few hours before the auction reaches a reasonable price?

2022-11-30 18:59 UTC, EdNoepel commented on src/base/interfaces/pool/IPoolState.sol
> +import '../../../libraries/Auctions.sol';
I'm in favor of returning the (nicely-packed) struct, but I'm concerned about having an interface include implementation source.  Should `struct Liquidation` move to the interface?

2022-11-30 19:02 UTC, EdNoepel commented
Would be helpful to exclude `tests/forge` from coverage results, since we care about covering contracts, not the tests themselves.

2022-11-30 22:22 UTC, ith-harvey commented on tests/forge/ERC20Pool/ERC20PoolLiquidationsMisc.t.sol
> +        _take(
correct, they are attempting to exit with their funds as quickly as possible. This example should be re-written (was used as more of a proof of concept scenario to prove how poor the lender's experience is if they wish to exit ASAP). This test already existed prior to my PR, I simply added it to the `Misc` file. I think @MikeHathaway should reformat this / reuse this test for the LP bond when that PR is ready.

2022-12-01 19:06 UTC, ith-harvey commented on src/base/interfaces/pool/IPoolState.sol
> +import '../../../libraries/Auctions.sol';
Revised the contract, this comment no longer applies : )

2022-12-01 19:06 UTC, ith-harvey commented
contract size is now below 100%

2022-12-01 19:13 UTC, grandizzy requested changes

2022-12-01 19:13 UTC, grandizzy commented on src/base/interfaces/pool/IPoolState.sol
> +import '../../../libraries/Auctions.sol';
this doesn't seem right, we should not import structs from libraries in interfaces

2022-12-01 19:13 UTC, grandizzy commented on src/base/Pool.sol
> +        return auctions.liquidations[borrower_];
I think we need a different way to handle this, it is also exceeding the contract deployment size and pretty sure is with this addition

2022-12-01 19:13 UTC, grandizzy commented on tests/forge/ERC721Pool/ERC721PoolLiquidationsTake.t.sol
> -    function testTakeCollateralAndSettleSubsetPool() external tearDown {
why removing tearDown?

2022-12-01 19:13 UTC, grandizzy commented on tests/forge/ERC721Pool/ERC721PoolLiquidationsTake.t.sol
> +    function testTakeCollateralSubsetPool() external {
why removing tearDown?

2022-12-01 19:13 UTC, grandizzy commented on tests/forge/utils/DSTestPlus.sol
> +// import 'src/libraries/Auctions.sol';
this can be removed

2022-12-01 19:15 UTC, EdNoepel commented on src/base/interfaces/pool/IPoolState.sol
> +    function auctionInfo(address borrower) external view returns (address, uint256, uint256, uint256, uint256, uint256);
Not sure why we want to break formatting with the other interface methods, which name the return variables.

2022-12-01 19:18 UTC, ith-harvey commented on src/base/Pool.sol
> +        return auctions.liquidations[borrower_];
resolved

2022-12-01 19:46 UTC, ith-harvey commented on src/base/interfaces/pool/IPoolState.sol
> +    function auctionInfo(address borrower) external view returns (address, uint256, uint256, uint256, uint256, uint256);
good call, updated -> https://github.com/ajna-finance/contracts/pull/356/commits/637f744d56fd2aff92200a680b7a1e162945f7ac

2022-12-01 19:49 UTC, ith-harvey commented on tests/forge/utils/DSTestPlus.sol
> +// import 'src/libraries/Auctions.sol';
good call, updated -> https://github.com/ajna-finance/contracts/commit/637f744d56fd2aff92200a680b7a1e162945f7ac

2022-12-01 19:49 UTC, ith-harvey commented on tests/forge/ERC721Pool/ERC721PoolLiquidationsTake.t.sol
> +    function testTakeCollateralSubsetPool() external {
good call, updated -> https://github.com/ajna-finance/contracts/commit/637f744d56fd2aff92200a680b7a1e162945f7ac

2022-12-01 19:49 UTC, ith-harvey commented on tests/forge/ERC721Pool/ERC721PoolLiquidationsTake.t.sol
> -    function testTakeCollateralAndSettleSubsetPool() external tearDown {
good call, updated -> https://github.com/ajna-finance/contracts/commit/637f744d56fd2aff92200a680b7a1e162945f7ac

2022-12-01 19:52 UTC, ith-harvey commented on src/base/interfaces/pool/IPoolState.sol
> +import '../../../libraries/Auctions.sol';
resolved -> https://github.com/ajna-finance/contracts/pull/356/commits/637f744d56fd2aff92200a680b7a1e162945f7ac

2022-12-01 20:14 UTC, EdNoepel approved these changes
LGTM

2022-12-01 20:19 UTC, grandizzy approved these changes

2022-12-01 20:21 UTC, merged