initial drawDebt implementations
ajna-finance/ajna-core pull request #372
Opened 2022-11-27 21:28 UTC by MikeHathaway

- Combine `borrow` and `pledgeCollateral` into a single `drawDebt` method. Due to pool type differences, this is implemented at the pool implementation level.
- Retrieve `PoolState` and `Loans.Borrower` structs once at the top of the `drawDebt` method. Updates the loan and pool state once at the end of the method.
- Replace separate `Borrow` and `PledgeCollateral` events with a combined `DrawDebt` event.
- Update tests. Most test changes involved updating the interface, however, calling `_updateInterestParams` at the end of the combined function resulted in higher interest numbers compared to consecutive `pledgeCollateral` and `borrow` calls. 
- Updates and increases pool interest accumulation as the prior implementation would have calculated pool interest rates based upon the debt at the time of pledgeCollateral not the immediately higher number after borrow (which would have held for at least 12 hours). This should result in generally higher interest across the board.

Using internal methods increases pool size by several hundred bytes vs develop, implementation level reduces contract size slightly.

```
============ branch with internal Sizes ============
  ERC721Pool               -  22,266B  (90.60%)
  ERC20Pool                -  20,931B  (85.16%)
```

```
============ branch Bytecode Sizes ============
  ERC721Pool               -  22,034B  (89.65%)
  ERC20Pool                -  20,694B  (84.20%)
```

```
============ develop Bytecode Sizes ============
  ERC721Pool               -  22,083B  (89.85%)
  ERC20Pool                -  20,733B  (84.36%)
```

Gas used is hard to compare, but generally, the `drawDebt` method is much cheaper than running separate `pledgeCollateral`, and `borrow` methods. The gas savings are especially pronounced for the ERC721Pool.

```	
| NEW INTERNAL ERC20Pool contract |                 |        |        |        |         |                                                                                                              
|--------------------------------------------|-----------------|--------|--------|--------|---------|                                                                                                              
 |                                                                                                              
| Function Name                              | min             | avg    | median | max    | # calls |                                                                                                                                                                                                                             
| drawDebt                                   | 26533           | 171838 | 185402 | 550318 | 245     |                                                                                                              

| NEW INTERNAL: ERC721Pool contract |                 |        |        |        |         |                                                                                                           
|-----------------------------------------------|-----------------|--------|--------|--------|---------|                                                                                                            |                                                                                                           
| Function Name                                 | min             | avg    | median | max    | # calls |                                                                                                                                                                                                                      
| drawDebt                                      | 27312           | 215647 | 207712 | 387116 | 94      |                                                                                                           

| NEW BRANCH: ERC20Pool contract |                 |        |        |        |         |                                                                                                              
|--------------------------------------------|-----------------|--------|--------|--------|---------|                                                                                                              
 |                                                                                                              
| Function Name                              | min             | avg    | median | max    | # calls |                                                                                                                                                                                                                             
| drawDebt                                   | 26283           | 171474 | 185093 | 549723 | 245     |                                                                                                              

| NEW BRANCH: ERC721Pool contract |                 |        |        |        |         |                                                                                                           
|-----------------------------------------------|-----------------|--------|--------|--------|---------|                                                                                                            |                                                                                                           
| Function Name                                 | min             | avg    | median | max    | # calls |                                                                                                                                                                                                                      
| drawDebt                                      | 27062           | 215361 | 207403 | 386645 | 94      |                                                                                                           

| DEVELOP: ERC20Pool contract |                 |        |        |        |         |                                                                                                              
|--------------------------------------------|-----------------|--------|--------|--------|---------|                                                                                                               |                                                                                                              
| Function Name                              | min             | avg    | median | max    | # calls |                                                                                                                     
| borrow                                     | 719             | 173788 | 167331 | 389209 | 161     |                                                                                                              
| pledgeCollateral                           | 25893           | 85395  | 51094  | 377823 | 145     |                                                                                                              

| DEVELOP: ERC721Pool contract |                 |        |        |        |         |                                                                                                           
|-----------------------------------------------|-----------------|--------|--------|--------|---------|                                                                                                            |                                                                                                           |                                                                                                           
| Function Name                                 | min             | avg    | median | max    | # calls |                                                                                  [...]

2022-11-29 20:45 UTC, grandizzy requested changes
Looks good, this is a great improvement!
Couple of things:
- needs to be merged with develop, there are several changes in there (_updatePool was also renamed)
- `Loans.Borrower memory borrower  = loans.getBorrowerInfo` can be done only once outside, at the beginning of `drawDebt`, similar with getting pool state
- loans.update and former _updatePool call should be made once, at the end of `drawDebt` function

2022-11-29 21:13 UTC, grandizzy commented
> Looks good, this is a great improvement! Couple of things:
> 
> * needs to be merged with develop, there are several changes in there (_updatePool was also renamed)
> * `Loans.Borrower memory borrower  = loans.getBorrowerInfo` can be done only once outside, at the beginning of `drawDebt`, similar with getting pool state
> * loans.update and former _updatePool call should be made once, at the end of `drawDebt` function

I think would also worth combining the 2 events in a `DrawDebt` one containing both `pledgedCollateral` and `borrowedAmount` and raised at the end of the call

2022-11-29 21:40 UTC, grandizzy commented on src/erc20/ERC20Pool.sol
> +        if (amountToBorrow_ != 0 || limitIndex_ != 0) {
do we want here to allow pledging for an address and borrowing of sender address? That is if the drawDebt function is called with a different address than msg.sender it means sender will pledge collateral for that address but will drawDebt for itself, I think this could be confusing... I recommend checking here `borrowerAddress == msg.sender` too for a borrow action

2022-11-29 23:16 UTC, MikeHathaway commented
> Looks good, this is a great improvement! Couple of things:
> 
>     * needs to be merged with develop, there are several changes in there (_updatePool was also renamed)
> 
>     * `Loans.Borrower memory borrower  = loans.getBorrowerInfo` can be done only once outside, at the beginning of `drawDebt`, similar with getting pool state
> 
>     * loans.update and former _updatePool call should be made once, at the end of `drawDebt` function

I looked into that, but `Loans.Borrower` can't easily be queried once, and passed into both since the borrower's state changes depending on whether or not `pledgeCollateral` is actually executed first. For example, we would be operating on a stale `borrower.collateral` amount when determining whether the newly drawn debt would push the loan into a state of under-collateralization. 

Likewise, having the `lup` be changeable based upon state changes in either of the two methods precludes using a single common `loans.update()`, and `_updateInterestParams()` call at the end of `drawDebt()`.

2022-11-29 23:33 UTC, MikeHathaway commented on src/erc20/ERC20Pool.sol
> +        if (amountToBorrow_ != 0 || limitIndex_ != 0) {
This matches the existing functionality. I agree that it's confusing though. I would be open to removing the ability to `pledgeCollateral` for a third-party since this functionality isn't replicated in any of the other external methods. 

Was the original intent to support tools like Defi Saver? If so, I would think we would need to expand it to other methods like `pullCollateral`

2022-11-29 23:48 UTC, MikeHathaway commented
> > Looks good, this is a great improvement! Couple of things:
> > 
> > * needs to be merged with develop, there are several changes in there (_updatePool was also renamed)
> > * `Loans.Borrower memory borrower  = loans.getBorrowerInfo` can be done only once outside, at the beginning of `drawDebt`, similar with getting pool state
> > * loans.update and former _updatePool call should be made once, at the end of `drawDebt` function
> 
> I think would also worth combining the 2 events in a `DrawDebt` one containing both `pledgedCollateral` and `borrowedAmount` and raised at the end of the call

I agree this would be a good change. I can combine those, but we would lose access to the new `lup` information in the newly emitted `DrawDebt` event. This might be important information on the client side (we could solve this by returning the new lup in the event emit).

2022-11-30 05:01 UTC, EdNoepel reviewed
Looks good.  I am concerned about that `borrower_` parameter.
Curious about gas and contract size differences.

2022-11-30 05:01 UTC, EdNoepel commented on src/erc20/ERC20Pool.sol
> +        if (amountToBorrow_ != 0 || limitIndex_ != 0) {
IIRC, we allow any actor to `pledge` and `repay` another borrower's loan to mitigate dusty or spammy loans which would be cheaper to recollateralize/close than to liquidate.

2022-11-30 05:01 UTC, EdNoepel commented on tests/forge/ERC20Pool/ERC20DSTestPlus.sol
> +    function _drawDebtNoCheckLup(
Thank you.  I'm often tempted to create `_poolActionWhichDoesntAssertThingsIrrelevantToTheTest` methods.

2022-11-30 07:12 UTC, grandizzy commented
> > Looks good, this is a great improvement! Couple of things:
> > ```
> > * needs to be merged with develop, there are several changes in there (_updatePool was also renamed)
> > 
> > * `Loans.Borrower memory borrower  = loans.getBorrowerInfo` can be done only once outside, at the beginning of `drawDebt`, similar with getting pool state
> > 
> > * loans.update and former _updatePool call should be made once, at the end of `drawDebt` function
> > ```
> 
> I looked into that, but `Loans.Borrower` can't easily be queried once, and passed into both since the borrower's state changes depending on whether or not `pledgeCollateral` is actually executed first. For example, we would be operating on a stale `borrower.collateral` amount when determining whether the newly drawn debt would push the loan into a state of under-collateralization.
> 
Was thinking this isn't the case if we load borrower outside, pass to pledge collateral, do the changes then pledge collateral returns the updated borrower struct which we pass to borrow that updates it and returns to main function for saving

> Likewise, having the `lup` be changeable based upon state changes in either of the two methods precludes using a single common `loans.update()`, and `_updateInterestParams()` call at the end of `drawDebt()`.

2022-11-30 07:33 UTC, grandizzy commented
> > > Looks good, this is a great improvement! Couple of things:
> > > ```
> > > * needs to be merged with develop, there are several changes in there (_updatePool was also renamed)
> > > 
> > > * `Loans.Borrower memory borrower  = loans.getBorrowerInfo` can be done only once outside, at the beginning of `drawDebt`, similar with getting pool state
> > > 
> > > * loans.update and former _updatePool call should be made once, at the end of `drawDebt` function
> > > ```
> > 
> > 
> > I looked into that, but `Loans.Borrower` can't easily be queried once, and passed into both since the borrower's state changes depending on whether or not `pledgeCollateral` is actually executed first. For example, we would be operating on a stale `borrower.collateral` amount when determining whether the newly drawn debt would push the loan into a state of under-collateralization.

Hm, this begs the question- isn't pool state stale when passing to borrow function too?
> 
> Was thinking this isn't the case if we load borrower outside, pass to pledge collateral, do the changes then pledge collateral returns the updated borrower struct which we pass to borrow that updates it and returns to main function for saving
> 
> > Likewise, having the `lup` be changeable based upon state changes in either of the two methods precludes using a single common `loans.update()`, and `_updateInterestParams()` call at the end of `drawDebt()`.

2022-12-01 00:25 UTC, MikeHathaway commented
> > > > Looks good, this is a great improvement! Couple of things:
> > > > ```
> > > > * needs to be merged with develop, there are several changes in there (_updatePool was also renamed)
> > > > 
> > > > * `Loans.Borrower memory borrower  = loans.getBorrowerInfo` can be done only once outside, at the beginning of `drawDebt`, similar with getting pool state
> > > > 
> > > > * loans.update and former _updatePool call should be made once, at the end of `drawDebt` function
> > > > ```
> > > 
> > > 
> > > I looked into that, but `Loans.Borrower` can't easily be queried once, and passed into both since the borrower's state changes depending on whether or not `pledgeCollateral` is actually executed first. For example, we would be operating on a stale `borrower.collateral` amount when determining whether the newly drawn debt would push the loan into a state of under-collateralization.
> 
> Hm, this begs the question- isn't pool state stale when passing to borrow function too?
> 
> > Was thinking this isn't the case if we load borrower outside, pass to pledge collateral, do the changes then pledge collateral returns the updated borrower struct which we pass to borrow that updates it and returns to main function for saving
> > > Likewise, having the `lup` be changeable based upon state changes in either of the two methods precludes using a single common `loans.update()`, and `_updateInterestParams()` call at the end of `drawDebt()`.

Yeah that's a good call out - there would have been a bug in the pool collateralization check. Updating them to return `PoolState`

2022-12-01 21:00 UTC, MikeHathaway commented on src/erc20/ERC20Pool.sol
> +            true,
I think we also need to revisit re-stamping the neutral price on pledge collateral. The state intention was to avoid punishing borrowers, but there are also cases (as seen in our current tests) where the user pledges additional collateral and sees their neutral price fall. This would also be a technically simpler implementation.

@mattcushman

2022-12-01 21:07 UTC, MikeHathaway commented on src/erc20/ERC20Pool.sol
> +        // if (poolState.accruedDebt != 0) {
Proposed fix to borrowers exploiting the pool by pledging collateral first without any debt, and setting the `debtEma` to an extremely low starting value.

2022-12-05 16:51 UTC, EdNoepel reviewed
Proposed reverting if drawing debt and `_borrower != msg.sender`.  We'll need to update documentation in the interfaces accordingly once we decide how to handle that.

2022-12-05 16:51 UTC, EdNoepel commented on src/erc20/ERC20Pool.sol
> +import '@std/console.sol';
remove before flight

2022-12-05 16:51 UTC, EdNoepel commented on src/erc20/ERC20Pool.sol
> +        if (amountToBorrow_ != 0 || limitIndex_ != 0) {
How about we revert if `borrower != msg.sender && amountToBorrow_ != 0`.

2022-12-05 16:51 UTC, EdNoepel commented on src/erc20/ERC20Pool.sol
> +
nit: extra blank line

2022-12-05 16:51 UTC, EdNoepel commented on src/erc20/ERC20Pool.sol
> +        // if (poolState.accruedDebt != 0) {
I have a strong preference for limiting interest rates as an alternative solution.

2022-12-05 16:51 UTC, EdNoepel commented on src/erc20/interfaces/pool/IERC20PoolBorrowerActions.sol
> +     *  @param  borrower_           The address of borrower to drawDebt for.
It's really the address of the `borrower_` to pledge collateral to.  Not sure the best way to document this.

2022-12-05 16:51 UTC, EdNoepel commented on src/erc20/interfaces/pool/IERC20PoolEvents.sol
> +     *  @param  borrower          `msg.sender`.
It doesn't have to be `msg.sender`.

2022-12-05 16:51 UTC, EdNoepel commented on tests/forge/utils/DSTestPlus.sol
> -
Prototypes remain the same.  Maybe leave abstract here and `override` them in subclasses?

2022-12-05 17:23 UTC, MikeHathaway commented on src/erc20/ERC20Pool.sol
> +        // if (poolState.accruedDebt != 0) {
I agree. I'll remove this comment.

2022-12-05 17:32 UTC, MikeHathaway commented on tests/forge/utils/DSTestPlus.sol
> -
Updated these methods to `virtual` and added `override`

2022-12-05 18:02 UTC, MikeHathaway commented on src/erc20/interfaces/pool/IERC20PoolBorrowerActions.sol
> +     *  @param  borrower_           The address of borrower to drawDebt for.
How about: "The borrower to whom collateral was pledged, and/or debt was drawn for.`

2022-12-05 18:28 UTC, MikeHathaway commented on src/erc20/ERC20Pool.sol
> +        if (amountToBorrow_ != 0 || limitIndex_ != 0) {
I added an `if (borrower_ != msg.sender) revert BorrowerNotSender();` revert check within the `borrow` clause. This way we can support the existing `pledgeCollateral` behaviour, while allowing users the option of deciding whether or not they also want to borrow or just add collateral to the pool. 

Another option would be to remove the revert entirely, and have the `if` check amount != 0, and borrower != msg.sender

2022-12-05 18:33 UTC, MikeHathaway commented on src/erc20/interfaces/pool/IERC20PoolEvents.sol
> +     *  @param  borrower          `msg.sender`.
How about: "The borrower to whom collateral was pledged, and/or debt was drawn for.`

2022-12-05 20:22 UTC, grandizzy reviewed
I think we should avoid copy pasting code in the 2 pools but rather add the method with common code in base contract or in an (external maybe?) library or in utils lib.
We can use virtual functions that are overriden in pool implementation, similar with settleAuction and isCollateralized (e.g. for transfer collateral)

2022-12-05 22:09 UTC, MikeHathaway commented
> I think we should avoid copy pasting code in the 2 pools but rather add the method with common code in base contract or in an (external maybe?) library or in utils lib. We can use virtual functions that are overriden in pool implementation, similar with settleAuction and isCollateralized (e.g. for transfer collateral)

I agree that it would be better not to copy/paste the code, and I had initially gone with that approach but it resulted in massive increases in gas cost and contract size compared to just copy pasting. Given the stage of development, I figured it would be better to take the maintenance/readability hit and just copy/paste.

2022-12-06 02:11 UTC, EdNoepel commented on tests/forge/utils/DSTestPlus.sol
> -
It doesn't help having implementation in the baseclass, because subclasses can't call `super` on an internal method.  Why not just leave abstract function prototypes here?

2022-12-06 18:56 UTC, MikeHathaway commented on tests/forge/utils/DSTestPlus.sol
> -
Updated - let me know if you were thinking of something different, may not be understanding properly.

2022-12-07 03:14 UTC, EdNoepel commented on tests/forge/utils/DSTestPlus.sol
> -
My bad, I thought that `ERC20DSTestPlus` and `ERC721DSTestPlus` were the only classes subclassing this.  Your earlier implementation seems better.

2022-12-07 03:27 UTC, MikeHathaway commented on tests/forge/utils/DSTestPlus.sol
> -
Previous implementation with just the reverts? Or to have them removed entirely?

2022-12-07 12:52 UTC, grandizzy requested changes
I *think* the drawDebt function is exposed to reentrancy attacks (wasn't able to prove it yet with code), see my comment below. Slither also complains about

2022-12-07 12:52 UTC, grandizzy commented on src/erc721/ERC721Pool.sol
> +        loans.update(
this should be done before `_transferQuoteToken` in `_borrow` function, otherwise we're vulnerable to reentrancy attacks. we can either move `_transferQuoteToken` out of `_borrow` or make `drawDebt` non reentrant

2022-12-07 12:56 UTC, prat-gpt approved these changes
LGTM!

2022-12-07 20:25 UTC, MikeHathaway commented on src/erc721/ERC721Pool.sol
> +        loans.update(
Good call out. Addecc a `nonReentrant` modifier, which seemed cleaner.

2022-12-07 20:42 UTC, grandizzy commented on src/erc721/ERC721Pool.sol
> +        loans.update(
:+1:

2022-12-07 20:43 UTC, grandizzy approved these changes
lgtm

2022-12-07 20:45 UTC, merged