Implemented mergeOrRemoveCollateral
ajna-finance/ajna-core pull request #392
Opened 2022-12-06 19:08 UTC by ith-harvey

Implemented `mergeOrRemove` Collateral:
- loops over `removalIndexes_`
- removes collateral up to `noOfNFTsToRemove_`
- If at any time `noOfNFTsToRemove_` fulfilled we stop looping and the collateral is sent to the caller
- If `noOfNFTsToRemove_` is never reached then the collateral removed from `removalIndexes_` is merged into `toIndex_` bucket.

Changes that need direct review from @mattcushman && @grandizzy :
- NFT `take` altered the rounding up / down for NFTs
- `priceToIndex` -> indexes returned by prices higher than or lower than the bounds return indexes that are the highest most and lowest most indexes now. Does this endanger the system in anyway?

Gas cost iterating over 100 buckets:
`| mergeOrRemoveCollateral                       | 1501111         | 1504108 | 1504108 | 1507105 | 2       | `

Contract size post update:
```
  ERC721Pool               -  23,397B  (95.20%)
  ERC20Pool                -  20,935B  (85.18%)
  PositionManager          -  17,916B  (72.90%)
  Auctions                 -  13,544B  (55.11%)
  PoolInfoUtils            -  11,574B  (47.09%)
  LenderActions            -   9,961B  (40.53%)
  PoolCommons              -   7,400B  (30.11%)
  ERC721                   -   4,421B  (17.99%)
  ERC721PoolFactory        -   2,876B  (11.70%)
  ERC20PoolFactory         -   2,194B  (8.93%)
  ERC20                    -   2,140B  (8.71%)
  ```

2022-12-11 02:05 UTC, ith-harvey commented on tests/forge/utils/BucketMath.sol
> +        if (price_ <= MIN_PRICE) price_ = MIN_PRICE + 1;
BIG CHANGE HERE: updated the `priceToIndex` method so it returns the highest or lowest index if the `price_` exceeds or falls below `MAX_PRICE` / `MIN_PRICE`

2022-12-11 02:23 UTC, ith-harvey commented on src/erc721/ERC721Pool.sol
> +        if (collateralTaken != collateralAmount && borrower.collateral >= collateralTaken + 1e18) { // collateral taken not a round number
This change is so nft take can now handle two scenarios:
- Rounds up when collateralTaken is not a round number (due to auction price) && borrower.collateral > collateralAmount
 - Rounds down when deposit take has lowered the amount of collateral the borrower has in auction. Was getting an underflow error here otherwise.

2022-12-11 07:15 UTC, grandizzy requested changes

2022-12-11 07:15 UTC, grandizzy commented on src/erc721/ERC721Pool.sol
> +        while (collateralToMerge < collateralAmount && i < removalIndexes_.length) {
Recommend moving this logic (while loop and the else at line 174) to external LenderAction library and use internal functions there to remove collateral. We should avoid calling external libraries in a loop and reduce calls to external libs as much as we can.

2022-12-11 07:15 UTC, grandizzy commented on src/erc721/ERC721Pool.sol
> +        if (collateralTaken != collateralAmount && borrower.collateral >= collateralTaken + 1e18) { // collateral taken not a round number
don't we add same 1e18 to col taken in the line below (245)?

2022-12-11 07:15 UTC, grandizzy commented on src/erc721/interfaces/pool/IERC721PoolLenderActions.sol
> +        uint256[] memory removeAmountAtIndex_,
Need memory or calldata is fine? Recommend using calldata as much as we can.

2022-12-11 07:15 UTC, grandizzy commented on src/erc721/ERC721Pool.sol
> +        uint256[] memory removalIndexes_,
Calldata should work if the functiin doesn't alter this

2022-12-11 07:16 UTC, grandizzy commented on tests/forge/utils/BucketMath.sol
> +        if (price_ <= MIN_PRICE) price_ = MIN_PRICE + 1;
I'm fine with it 👍

2022-12-11 07:49 UTC, grandizzy commented on src/erc721/ERC721Pool.sol
> +            // total collateral in buckets did not meet requested removal amount, noOfNFTsToRemove_
Is this comment accurate here? I'd expect to transfer out when requested amount is meet and not the other way around

2022-12-11 07:49 UTC, grandizzy commented on src/erc721/ERC721Pool.sol
> +        while (collateralToMerge < collateralAmount && i < removalIndexes_.length) {
Try reading length only once to save gas (as it is now it reads on each loop even the length doesn't change)

2022-12-11 08:13 UTC, grandizzy requested changes

2022-12-11 08:13 UTC, grandizzy commented on src/libraries/external/Auctions.sol
>                  if (depositToRemove >= debtToSettle && maxSettleableDebt >= debtToSettle) { // enough deposit in bucket and collateral avail to settle entire debt
As it looks none of the if else statements below would execute if depositToRemove is 0 but only line 208. Let's just leave this logic as it is and execute it only if `depositToRemove` != 0 and line 208 outside the if for both cases

2022-12-12 21:07 UTC, ith-harvey commented on src/erc721/ERC721Pool.sol
> +        if (collateralTaken != collateralAmount && borrower.collateral >= collateralTaken + 1e18) { // collateral taken not a round number
Yes we do! :) but we need to be sure that `borrower.collateral` exceeds `collateralTaken + 1e18`... if it doesn't then we would get an underflow error.

2022-12-12 22:01 UTC, ith-harvey commented on src/erc721/ERC721Pool.sol
> +        while (collateralToMerge < collateralAmount && i < removalIndexes_.length) {
updated -> https://github.com/ajna-finance/contracts/pull/392/commits/bede88277bfb490d34e0a85d293a7087e94cc455

2022-12-12 22:01 UTC, ith-harvey commented on src/erc721/ERC721Pool.sol
> +            // total collateral in buckets did not meet requested removal amount, noOfNFTsToRemove_
updated -> https://github.com/ajna-finance/contracts/pull/392/commits/bede88277bfb490d34e0a85d293a7087e94cc455

2022-12-12 22:01 UTC, ith-harvey commented on src/erc721/ERC721Pool.sol
> +        uint256[] memory removalIndexes_,
updated -> https://github.com/ajna-finance/contracts/pull/392/commits/bede88277bfb490d34e0a85d293a7087e94cc455

2022-12-12 22:02 UTC, ith-harvey commented on src/erc721/interfaces/pool/IERC721PoolLenderActions.sol
> +        uint256[] memory removeAmountAtIndex_,
updated -> https://github.com/ajna-finance/contracts/pull/392/commits/bede88277bfb490d34e0a85d293a7087e94cc455

2022-12-12 22:02 UTC, ith-harvey commented on src/erc721/ERC721Pool.sol
> +        while (collateralToMerge < collateralAmount && i < removalIndexes_.length) {
updated -> https://github.com/ajna-finance/contracts/pull/392/commits/bede88277bfb490d34e0a85d293a7087e94cc455

2022-12-12 22:03 UTC, ith-harvey commented on src/libraries/external/Auctions.sol
>                  if (depositToRemove >= debtToSettle && maxSettleableDebt >= debtToSettle) { // enough deposit in bucket and collateral avail to settle entire debt
See how I have it now... I do agree that this needs to get rewritten in a cleaner way as its confusing and feels to edgecasey

2022-12-13 06:16 UTC, grandizzy requested changes
This needs some changes so I made a PR with commits I added in comments + merged with develop https://github.com/ajna-finance/contracts/pull/418

The `testMergeOrRemoveCollateral` scenario where the entire NFT is recreated was wrong - settle should not reward LPs to settler (who can be an arbitrary address, not strictly the lender) but the collateral settled should be purchased from the bucket by depositing quote tokens.
I don't think we should have such big loops like here https://github.com/ajna-finance/contracts/pull/392/files#diff-aa300461f97bb15194ece10cf6afff91f45ab18a0628f8a49f682eb4b3068a16R714 in the regular tests because it is really slowing down the development process (not sure exactly though how can change, can you think to a better test case scenario?)
Mind that it's important to add `tearDown` to tests that is to make sure it always leave pool in an consistent state (rn this test fails, didn't dig to find out why I just marked it with FIXME)

2022-12-13 06:16 UTC, grandizzy commented on src/libraries/external/Auctions.sol
> +            if (depositToRemove != 0) {
not exactly the change I suggested, see https://github.com/ajna-finance/contracts/blob/nft-claim-multi-re/src/libraries/external/Auctions.sol#L189 (`Buckets.addCollateral` gives LPs to the user too which we don't want in case of settle, we just need to execute `buckets_[index].collateral += collateralUsed;` without all the other logic )

2022-12-13 06:16 UTC, grandizzy commented on src/libraries/external/LenderActions.sol
> +            (collateralRemoved, ) = LenderActions.removeMaxCollateral(
why calling internal function like this? `LenderActions.removeMaxCollateral` should be external, same `LenderActions.mergeOrRemoveCollateral` see https://github.com/ajna-finance/contracts/commit/a7ebfb084373fd9f44b64e94ab583abc0b5da0e4

You're also making `addCollateral` function internal to Pool contract which increase contract size and defeats the purpose of `LenderActions` being an external library, see https://github.com/ajna-finance/contracts/pull/418/commits/1ebf7f430913fbc1f56940b16dc02b9fcf348f98 for a fix. It is perfectly fine to have this inline as well instead calling yet another internal call, as that's really just a wrapper for `Buckets.addCollateral` library call, see https://github.com/ajna-finance/contracts/pull/418/commits/7a595e88fb27546cf1ec26d60b2a31e60ca600e6

2022-12-13 06:17 UTC, grandizzy commented on src/libraries/external/Auctions.sol
>                  if (depositToRemove >= debtToSettle && maxSettleableDebt >= debtToSettle) { // enough deposit in bucket and collateral avail to settle entire debt
see https://github.com/ajna-finance/contracts/pull/392#discussion_r1046685649

2022-12-13 06:18 UTC, grandizzy commented on src/erc721/interfaces/pool/IERC721PoolLenderActions.sol
> +        uint256[] memory removeAmountAtIndex_,
I updated in https://github.com/ajna-finance/contracts/commit/a7ebfb084373fd9f44b64e94ab583abc0b5da0e4

2022-12-13 17:33 UTC, ith-harvey commented on src/libraries/external/Auctions.sol
> +            if (depositToRemove != 0) {
As per Matts comment, we don't want the bucket to have 0LP and collateral as it messes with the exchange rate. See -> https://github.com/ajna-finance/contracts/pull/392/commits/f6c841827a3e38749bbc92b9572e00084247af81

2022-12-13 17:34 UTC, ith-harvey commented on src/libraries/external/LenderActions.sol
> +            (collateralRemoved, ) = LenderActions.removeMaxCollateral(
I see, makes sense.

2022-12-13 17:39 UTC, grandizzy requested changes
looks good, just couple of things and good to merge

2022-12-13 17:39 UTC, grandizzy commented on src/libraries/external/Auctions.sol
> +                // buckets_[index].collateral += params_.collateral; // no deposit in bucket, add entire collateral into bucket
let's remove commented line here

2022-12-13 17:39 UTC, grandizzy commented on src/libraries/external/Auctions.sol
> +            kicker.claimable   = 0;
nit: extra space

2022-12-13 17:39 UTC, grandizzy commented on src/libraries/external/LenderActions.sol
> +    error CannotMergeToHigherPrice();
can you add a negative test to catch this error?

2022-12-13 17:39 UTC, grandizzy commented on tests/forge/ERC721Pool/ERC721PoolCollateral.t.sol
> +    // function testMergeOrRemoveCollateral() external tearDown { FIXME: this fails with FAIL. Reason: Arithmetic over/underflow]
can you try figure out why test fails when `tearDown`?

2022-12-13 18:18 UTC, ith-harvey commented on src/libraries/external/Auctions.sol
> +            kicker.claimable   = 0;
No that's good right? cleans up formatting to match line `299` above? Will remove if you want

2022-12-13 18:24 UTC, grandizzy commented on src/libraries/external/Auctions.sol
> +            kicker.claimable   = 0;
No, it's good, my bad

2022-12-14 19:47 UTC, ith-harvey commented on tests/forge/utils/DSTestPlus.sol
>          bucketsUsed.add(index);
This is because the caller of deposit Take is not getting LPB in the bucket

2022-12-14 19:52 UTC, ith-harvey commented on tests/forge/ERC721Pool/ERC721PoolCollateral.t.sol
> +    // function testMergeOrRemoveCollateral() external tearDown { FIXME: this fails with FAIL. Reason: Arithmetic over/underflow]
There is a bug here : ( Going to create a card for it

2022-12-14 19:53 UTC, grandizzy commented on tests/forge/utils/DSTestPlus.sol
>          bucketsUsed.add(index);
👍

2022-12-14 19:55 UTC, grandizzy approved these changes

2022-12-14 21:27 UTC, ith-harvey commented on src/libraries/external/LenderActions.sol
> +    error CannotMergeToHigherPrice();
Yep, I did

2022-12-14 21:27 UTC, ith-harvey commented on src/libraries/external/Auctions.sol
> +                // buckets_[index].collateral += params_.collateral; // no deposit in bucket, add entire collateral into bucket
Agreed, done.

2022-12-14 22:21 UTC, MikeHathaway commented on src/erc721/interfaces/pool/IERC721PoolLenderActions.sol
> +     *  @param  noOfNFTsToRemove_    Intergral number of NFTs to remove if collateral amount is met noOfNFTsToRemove_, else merge at bucket index, toIndex_.
Can put `@return` args here

2022-12-14 22:28 UTC, MikeHathaway commented on tests/forge/ERC721Pool/ERC721PoolLiquidationsTake.t.sol
> -    function testTakeCollateralSubsetPool() external tearDown {
tearDown was removed

2022-12-14 23:17 UTC, ith-harvey commented on tests/forge/ERC721Pool/ERC721PoolLiquidationsTake.t.sol
> -    function testTakeCollateralSubsetPool() external tearDown {
fixed -> https://github.com/ajna-finance/contracts/pull/392/commits/8b30b9da93a49d28a5fe7f9821948cf795271b04

2022-12-14 23:26 UTC, ith-harvey commented on src/erc721/interfaces/pool/IERC721PoolLenderActions.sol
> +     *  @param  noOfNFTsToRemove_    Intergral number of NFTs to remove if collateral amount is met noOfNFTsToRemove_, else merge at bucket index, toIndex_.
Here -> https://github.com/ajna-finance/contracts/pull/392/commits/ccf680ef4ddd230b56fb7afc5a5da1e7ffa10fae

2022-12-14 23:50 UTC, MikeHathaway approved these changes
LGTM

2022-12-14 23:51 UTC, merged