Move/remove quote token changes.  Check reserves>0.  Fenwick mult cle…
ajna-finance/ajna-core pull request #403
Opened 2022-12-09 22:21 UTC by mattcushman

First set of changes focused on Fenwick tree clarification/bug fixes/optimization

Mostly on remove and move quote token

Some gas changes evident in removeQuoteToken (move only has 1 sample point so I think it's a anomaly).  Also size savings.

After:
`============ Deployment Bytecode Sizes ============
  ERC721Pool               -  24,399B  (99.28%)
  ERC20Pool                -  23,246B  (94.58%)

| src/erc20/ERC20Pool.sol:ERC20Pool contract |                 |        |        |        |         |
|--------------------------------------------|-----------------|--------|--------|--------|---------|
| Function Name                              | min             | avg    | median | max    | # calls |
|--------------------------------------------|-----------------|--------|--------|--------|---------|
| addQuoteToken                              | 104247          | 162652 | 144437 | 717981 | 52003   |
| borrow                                     | 143085          | 193447 | 163575 | 716810 | 120002  |
| borrowerInfo                               | 6889            | 6889   | 6889   | 6889   | 8001    |
| bucketTake                                 | 341567          | 406336 | 406352 | 471072 | 4       |
| inflatorInfo                               | 421             | 421    | 421    | 421    | 8001    |
| initialize                                 | 113565          | 113565 | 113565 | 113565 | 14      |
| interestRate                               | 2449            | 2449   | 2449   | 2449   | 8001    |
| kick                                       | 150879          | 175621 | 174332 | 994030 | 48000   |
| loansInfo                                  | 1839            | 2537   | 2537   | 8537   | 48017   |
| moveQuoteToken                             | 364973          | 364973 | 364973 | 364973 | 1       |
| pledgeCollateral                           | 61678           | 62027  | 61998  | 521090 | 112001  |
| removeQuoteToken                           | 141811          | 163771 | 164780 | 197451 | 4000    |
| repay                                      | 499424          | 531360 | 520659 | 679228 | 16001   |
| take                                       | 49939           | 50563  | 50352  | 333433 | 15998   |
`

Before:
`
============ Deployment Bytecode Sizes ============
  ERC721Pool               -  24,457B  (99.51%)
  ERC20Pool                -  23,293B  (94.78%)

| src/erc20/ERC20Pool.sol:ERC20Pool contract |                 |        |        |        |         |
|--------------------------------------------|-----------------|--------|--------|--------|---------|
| Function Name                              | min             | avg    | median | max    | # calls |
|--------------------------------------------|-----------------|--------|--------|--------|---------|
| addQuoteToken                              | 101758          | 162475 | 144339 | 657764 | 52003   |
| borrow                                     | 143085          | 193851 | 163575 | 722864 | 120002  |
| borrowerInfo                               | 6889            | 6889   | 6889   | 6889   | 8001    |
| bucketTake                                 | 346680          | 412088 | 412104 | 477463 | 4       |
| inflatorInfo                               | 421             | 421    | 421    | 421    | 8001    |
| initialize                                 | 113565          | 113565 | 113565 | 113565 | 14      |
| interestRate                               | 2449            | 2449   | 2449   | 2449   | 8001    |
| kick                                       | 150879          | 175622 | 174332 | 999538 | 48000   |
| loansInfo                                  | 1839            | 2537   | 2537   | 8537   | 48017   |
| moveQuoteToken                             | 294856          | 294856 | 294856 | 294856 | 1       |
| pledgeCollateral                           | 61678           | 62027  | 61998  | 527144 | 112001  |
| removeQuoteToken                           | 160000          | 179142 | 179044 | 213155 | 4000    |
| repay                                      | 505478          | 537414 | 526713 | 685282 | 16001   |
| take                                       | 49939           | 50564  | 50352  | 339207 | 15998   |
`

2022-12-10 21:15 UTC, ith-harvey reviewed
Provided some feedback / cleaning up related comments.

Really think this is great start in cleaning up the fenwick logic just a little unsure on its net gain if it comes at the cost of making our other outerfacing pool methods more complex logically : )

Great PR overall

2022-12-10 21:15 UTC, ith-harvey commented on src/base/Pool.sol
> +        {
Are these brackets here because you were getting a `stack too deep` err?

2022-12-10 21:15 UTC, ith-harvey commented on src/base/Pool.sol
> +            reserves = (assets > liabilities) ? (assets-liabilities) : 0;
This is to get around the reserves going negative right? May be worth having a one line comment saying `The reserve may be negative, in the case it is we set it to 0`

2022-12-10 21:15 UTC, ith-harvey commented on src/libraries/Buckets.sol
> +            // 10^18 * 1e36 / 10^27 = 10^54 / 10^27 = 10^27
lets move this comment to above line 143 to keep code consistency

2022-12-10 21:15 UTC, ith-harvey commented on src/libraries/Buckets.sol
> +
remove extra space here

2022-12-10 21:15 UTC, ith-harvey commented on src/libraries/Deposits.sol
> +            if((bit & index_)!=0) {
NIT: spacing

2022-12-10 21:15 UTC, ith-harvey commented on src/libraries/Deposits.sol
>          index_ += 1;
could change the above to:
```
unchecked {
  ++index_
}
```

2022-12-10 21:15 UTC, ith-harvey commented on src/libraries/Deposits.sol
> +                uint256 j=index_+bit;
NIT: spacing and can we make `j` a more understandable variable name by chance? : )

2022-12-10 21:15 UTC, ith-harvey commented on src/libraries/Deposits.sol
> +                value = (self.values[j] += sum);
why do we need `(` and `)` here? suggest we remove.

2022-12-10 21:15 UTC, ith-harvey commented on src/libraries/Deposits.sol
> +                if (scaling != 0) sum = Maths.wmul(value, scaling) - Maths.wmul(value-sum, scaling);
NIT: spacing

2022-12-10 21:15 UTC, ith-harvey commented on src/libraries/Deposits.sol
> +     *  @param  rawRemoveAmount_   Unscaled amount to decrease deposit by.
NIT: spacing needs to match above comment... `@param` descriptions should be aligned

2022-12-10 21:15 UTC, ith-harvey commented on src/libraries/Deposits.sol
>       *  @dev    Starts at leaf/target and moved up towards root
Could you also explain here that `rawRemove` is just adjusting the value and does not touch the scaling?

2022-12-10 21:15 UTC, ith-harvey commented on src/libraries/Deposits.sol
> +            if (scaling != 0) rawRemoveAmount_ = Maths.wmul(value+rawRemoveAmount_, scaling) - Maths.wmul(value,  scaling);
NIT: spacing

2022-12-10 21:15 UTC, ith-harvey commented on src/libraries/Deposits.sol
> +	index_+=1;  // TODO: is this right?
NIT: spacing ... handle comment?

2022-12-10 21:15 UTC, ith-harvey commented on src/libraries/Buckets.sol
> +
lines 223 - 237 are cumbersome to read. Is it possible to break these out into variables at the top of the file before you compare and perform computations in the hope of simplifying this code block?

2022-12-10 21:15 UTC, ith-harvey commented on src/libraries/external/LenderActions.sol
> +        vars.fromBucketRawDeposit  = Deposits.rawValueAt(deposits_, params_.fromIndex);
I'd like to get @grandizzy or @EdNoepel 's opinion on the net gain of these changes...

Pros:
- simplify fenwick tree logic
- gas savings

Cons:
- abstraction from fenwick is lost as scaling is brought into the outer methods -> `moveQuote`, `removeQuote`

Is that a net positive?

2022-12-10 21:18 UTC, EdNoepel requested changes

2022-12-10 21:18 UTC, EdNoepel commented on src/base/Pool.sol
> +        }
Assets are debt, and liabilities are deposit?

2022-12-10 21:18 UTC, EdNoepel commented on src/base/PoolInfoUtils.sol
> +        }
Should `PoolHelper._claimableReserves` also be updated to floor reserves at 0?

2022-12-10 21:18 UTC, EdNoepel commented on src/libraries/Buckets.sol
>      }
nit: missing newline

2022-12-10 21:18 UTC, EdNoepel commented on src/libraries/Buckets.sol
> +
nit: extra newline

2022-12-10 21:18 UTC, EdNoepel commented on src/libraries/Buckets.sol
> +	uint256 bucketScale_,
Strange to see a Fenwick artifact in `Buckets` library.  Seems it belongs in `Deposits` or `PoolHelper`.

2022-12-10 21:18 UTC, EdNoepel commented on src/libraries/Buckets.sol
> +            // 10^18 * 1e36 / 10^27 = 10^54 / 10^27 = 10^27
This stays under 10^77; no issue with truncation.

2022-12-10 21:18 UTC, EdNoepel commented on src/libraries/Buckets.sol
> +	// redeemedLPs_ = min ( maxAmount_/(rawExchangeRate*scale), rawDeposit/rawExchangeRate, lenderLPsBalance)
Please remove commented-out code or explain why it's needed.

2022-12-10 21:18 UTC, EdNoepel commented on src/libraries/Buckets.sol
> +				      uint256 depositScale_,
Because it mentions `scale`, seems this belongs in `Deposits` library.

2022-12-10 21:18 UTC, EdNoepel commented on src/libraries/external/LenderActions.sol
> +        if (rawDeposit == 0) revert InsufficientLiquidity(); // revert if there's no liquidity in bucket
nit: Could move this up a line, so caller does not spend gas calculating `depositScale` if it will revert.

2022-12-10 21:18 UTC, EdNoepel commented on tests/forge/ERC20Pool/ERC20PoolLiquidationsTake.t.sol
> +       );
Why all the whitespace changes here?  Seems a big block of code moved 1 character to the left.

2022-12-10 21:20 UTC, EdNoepel commented on src/libraries/Buckets.sol
> +            // 10^18 * 1e36 / 10^27 = 10^54 / 10^27 = 10^27
Disagree; the comment is specifically about the calculation on 143.  Current location seems appropriate.

2022-12-10 21:21 UTC, EdNoepel commented on src/libraries/external/LenderActions.sol
> +        vars.fromBucketRawDeposit  = Deposits.rawValueAt(deposits_, params_.fromIndex);
I think it's a net positive.

2022-12-11 16:12 UTC, mattcushman commented on src/base/Pool.sol
> +        {
yes.  Possibly can remove post merge, I actually didn't check

2022-12-11 16:12 UTC, mattcushman commented on src/base/Pool.sol
> +        {
works without them now... I'll remove

2022-12-11 16:12 UTC, mattcushman commented on src/base/Pool.sol
> +        }
yes, deposits (just as in analogy to a bank), deposits are a liability from the point of view of the contract -- it tracks QT owed to lenders.  Similarly, debt is an asset - it's owed to the contract from borrowers

2022-12-11 16:12 UTC, mattcushman commented on src/base/PoolInfoUtils.sol
> +        }
It does already (via differtence mechanism -- it subtracts the min of the assets with the liabilities when subtracting)

2022-12-11 16:12 UTC, mattcushman commented on src/libraries/Buckets.sol
> +	uint256 bucketScale_,
let's discuss the pros and cons of where to put it

2022-12-11 16:12 UTC, mattcushman commented on src/libraries/Buckets.sol
> +	// redeemedLPs_ = min ( maxAmount_/(rawExchangeRate*scale), rawDeposit/rawExchangeRate, lenderLPsBalance)
it was intended to be pseudocode explaining the logic -- added some more comment

2022-12-11 16:12 UTC, mattcushman commented on src/libraries/Buckets.sol
> +
I'm not sure exactly what you mean, but spreading out the code IMHO makes it harder not easier to track.  I think a large part of the reason it's hard to read is that we need to call library functions to do * and /, which was my goal in the comment above to clarify.  I expanded that a bit.

2022-12-11 16:12 UTC, mattcushman commented on src/libraries/Deposits.sol
> +                value = (self.values[j] += sum);
I wasn't sure if it would work without them -- note that there is a +=, not just a + in the parenthesis, so it has an assignment side effect.  This gives a little gas savings.  I personally find it easier to read with the parenthesis as it's not a very common construction and the order of operations might be unclear to readers.

2022-12-11 16:12 UTC, mattcushman commented on src/libraries/Deposits.sol
>       *  @dev    Starts at leaf/target and moved up towards root
it says "unscaled"

2022-12-11 16:12 UTC, mattcushman commented on src/libraries/external/LenderActions.sol
> +        if (rawDeposit == 0) revert InsufficientLiquidity(); // revert if there's no liquidity in bucket
done

2022-12-11 16:36 UTC, ith-harvey commented on src/libraries/Buckets.sol
> +            // 10^18 * 1e36 / 10^27 = 10^54 / 10^27 = 10^27
I think my point got lost in translation here is how I would like it to look:
```
return bucketLPs_ == 0 ? Maths.RAY :
             // 10^18 * 1e36 / 10^27 = 10^54 / 10^27 = 10^27
            (bucketRawDeposit_ + bucketPrice_ * bucketCollateral_ / bucketScale_ ) * 10**36 / bucketLPs_;
           
```

2022-12-11 19:31 UTC, EdNoepel reviewed
This is getting there.  Would like to have a group discussion to achieve consensus on whether entangling concerns are worth the benefits of these changes.  Also need to figure out where some new methods belong.

2022-12-12 21:17 UTC, ith-harvey commented on src/libraries/Buckets.sol
> +     *  @notice Returns the exchange rate for a given bucket.
This comment needs to be updated to reflect that this is the "unscaled" bucket exchange rate

2022-12-12 21:18 UTC, ith-harvey commented on src/libraries/Buckets.sol
> +    function getRawExchangeRate(
change to `getUnscaledExchangeRate`?

2022-12-12 21:19 UTC, ith-harvey commented on src/libraries/Buckets.sol
> +     *  @param  bucketRawDeposit_ The amount of unscaled Fenwick tree amount in bucket.
`bucketUnscaledDeposit_`

2022-12-12 21:19 UTC, ith-harvey commented on src/libraries/Buckets.sol
> +        uint256 bucketRawDeposit_,
`unscaled`?

2022-12-12 21:21 UTC, ith-harvey commented on src/libraries/Buckets.sol
> +     *  @param  rawDepositAvailable_   Raw (unscaled) deposit quantity in bucket
`unscaled` flag

2022-12-12 21:24 UTC, ith-harvey commented on src/libraries/Buckets.sol
> +     *  @return rawDepositAmount_      Amount of raw deposit satistfying constraint
`unscaled` flag

2022-12-12 21:34 UTC, ith-harvey commented on src/libraries/Buckets.sol
> +				      Bucket storage bucket_,
Should be `Bucket memory bucket_`

2022-12-12 21:37 UTC, ith-harvey commented on src/libraries/Buckets.sol
> +    ) internal view returns (uint256 rawDepositAmount_, uint256 lps_) {
Can this be `pure`? If so should it go into `poolCommons.sol`?

2022-12-12 21:51 UTC, ith-harvey commented on src/libraries/Deposits.sol
> +     *  @param  rawRemoveAmount_   Unscaled amount to decrease deposit by.
change raw to unscaled everywhere

2022-12-12 21:51 UTC, ith-harvey commented on src/libraries/external/LenderActions.sol
> +        uint256 fromBucketRawDeposit;
raw to unscaled flag

2022-12-12 21:51 UTC, ith-harvey commented on src/libraries/external/LenderActions.sol
> +        vars.fromBucketRawDeposit  = Deposits.rawValueAt(deposits_, params_.fromIndex);
:+1:

2022-12-12 21:52 UTC, ith-harvey commented on tests/forge/ERC20Pool/ERC20PoolLiquidationsMisc.t.sol
> +                lpRedeem: 1999891367962935869240000000000
add the decimals `<NUMBERHERE> * 1e27`

Goes for every set of numbers without decimals

2022-12-12 21:54 UTC, ith-harvey reviewed
in person review

2022-12-13 12:27 UTC, EdNoepel approved these changes
I'm good with this now.

2022-12-13 15:56 UTC, grandizzy requested changes
Please see inline

2022-12-13 15:56 UTC, grandizzy commented on src/base/Pool.sol
> +        uint256 reserves;
we can move this on line 262 like `uint256 reserves = (assets > liabilities) ? (assets-liabilities) : 0;`
Can we add an unit test for this, if we merge with develop at this stage the new code won't be taken into consideration as reserves is now put inline https://github.com/ajna-finance/contracts/blob/develop/src/base/Pool.sol#L263, but still all tests are passing which indicates new code not covered

2022-12-13 15:56 UTC, grandizzy commented on src/base/PoolInfoUtils.sol
> +        if( poolDebt + quoteTokenBalance >= poolSize + bondEscrowed + unclaimedReserve) {
`reserves_` is already declared as return param, so we can remove the else clause here as it defaults to 0

2022-12-13 15:56 UTC, grandizzy commented on src/libraries/Buckets.sol
> +
nit: indentation

2022-12-13 15:56 UTC, grandizzy commented on tests/forge/ERC20Pool/ERC20PoolLiquidationsMisc.t.sol
> +                lpBalance:    0,
nit: extra spaces

2022-12-13 15:56 UTC, grandizzy commented on tests/forge/ERC20Pool/ERC20PoolLiquidationsMisc.t.sol
> +		lpBalance:    0,
nit: indentation

2022-12-13 15:56 UTC, grandizzy commented on tests/forge/ERC20Pool/ERC20PoolLiquidationsTake.t.sol
> +
nit: extra space

2022-12-13 15:56 UTC, grandizzy commented on tests/forge/ERC20Pool/ERC20PoolLiquidationsTake.t.sol
> +             {
nit: extra space

2022-12-13 15:56 UTC, grandizzy commented on tests/forge/ERC20Pool/ERC20PoolLiquidationsMisc.t.sol
> +		newLup:   9.721295865031779605 * 1e18,
nit: indentation

2022-12-13 15:56 UTC, grandizzy commented on src/libraries/Deposits.sol
> +	++index_;
nit: indentation

2022-12-13 15:56 UTC, grandizzy commented on src/libraries/Deposits.sol
> +        if (scaling==0) scaling = Maths.WAD;
nit:code formatting, let's change to `if (scaling == 0)` and next line to `return Maths.wmul(scaling, self.values[SIZE]);`

2022-12-13 15:56 UTC, grandizzy commented on src/libraries/Deposits.sol
> +	depositValue_ = Maths.wmul(unscaledValueAt(self, index_), scale(self,index_));
nit: indentation

2022-12-13 15:56 UTC, grandizzy commented on src/libraries/Deposits.sol
>          index_ += 1;
in `scale` function we're `++index_;` should we do same on all occurrences (add, mult, prefixSum, unscaledRemove)?

2022-12-13 15:56 UTC, grandizzy commented on src/libraries/Deposits.sol
> +            uint256 value    = (self.values[index_] -= unscaledRemoveAmount_);
I personally find the syntax less readable, probably not an issue for auditors

2022-12-13 15:56 UTC, grandizzy commented on src/libraries/external/LenderActions.sol
> +            }
nit: space

2022-12-13 15:56 UTC, grandizzy commented on src/libraries/Deposits.sol
> +    function remove(
nit: indentation of the function

2022-12-13 15:56 UTC, grandizzy commented on src/libraries/Deposits.sol
> +	if (removeAmount_ == currentAmount_) {
I am not sure how this improves performance, so in Auction.settlePoolDebt we let's say need to obliterate the deposit, we're calling `Deposits.remove(deposits_, index, depositToRemove, deposit)` at line 216 where deposit was already loaded at line 188 as `uint256 deposit = Deposits.valueAt(deposits_, index);` . Then we load unscaled value at the same index and then call unscaledRemove with the unscaled value, it looks to me like duplicate iterations that can be somehow avoided?
can you please explain?

2022-12-13 16:21 UTC, grandizzy commented
updated comparison, nice savings in gas consumption on max (when pool interested accrued) and in regular bucketTake, removeQuoteToken and repayDebt, slightly increase of gas cost for the other functions (since the increase is of the same size I suspect something loaded multiple times from storage but cannot spot where), overall improvements are really great. Contract size increased a little bit (not a biggie, probably due to not properly merged too) 

```
============ Deployment Bytecode Sizes ============
  ERC721Pool               -  22,902B  (93.18%)
  ERC20Pool                -  20,839B  (84.79%)

| Function Name                              | min             | avg    | median | max    | # calls |
| addQuoteToken                              | 105093          | 161931 | 145303 | 653823 | 56003   |
| bucketTake                                 | 340255          | 404704 | 404721 | 469121 | 4       |
| drawDebt                                   | 202150          | 248402 | 222635 | 739056 | 128003  |
| kick                                       | 128451          | 157162 | 153333 | 934219 | 48000   |
| moveQuoteToken                             | 277358          | 277358 | 277358 | 277358 | 1       |
| removeQuoteToken                           | 141912          | 163892 | 168726 | 191582 | 4000    |
| repayDebt                                  | 521734          | 553778 | 543187 | 701757 | 16002   |
| take                                       | 41293           | 49538  | 51270  | 331494 | 15998   |

vs develop

============ Deployment Bytecode Sizes ============
  ERC721Pool               -  22,764B  (92.62%)
  ERC20Pool                -  20,701B  (84.23%)
  
  
| Function Name                              | min             | avg    | median | max    | # calls |
| addQuoteToken                              | 102190          | 161325 | 144805 | 659480 | 56003   |
| bucketTake                                 | 345101          | 410159 | 410175 | 475184 | 4       |
| drawDebt                                   | 200848          | 247484 | 221333 | 743895 | 128003  |
| kick                                       | 127583          | 156294 | 152465 | 938931 | 48000   |
| moveQuoteToken                             | 268198          | 268198 | 268198 | 268198 | 1       |
| removeQuoteToken                           | 157727          | 179068 | 178978 | 199545 | 4000    |
| repayDebt                                  | 527007          | 559052 | 548460 | 707030 | 16002   |
| take                                       | 40946           | 49192  | 50923  | 336681 | 15998   |
```

2022-12-13 16:29 UTC, grandizzy commented on src/base/Pool.sol
> +        uint256 reserves;
Should we use the same way of calculating reserves in `Auctions.startClaimableReserveAuction` function https://github.com/ajna-finance/contracts/blob/develop/src/libraries/external/Auctions.sol#L570 ?

2022-12-13 19:45 UTC, grandizzy approved these changes
Approving these, agreed with Matt to follow up on this with:
- PR that use same removal procedure for all functions. Having 2 methods to remove from deposits are bad for maintenance and audit (plus the legacy one is not efficient with the new changes)
- PR to use same function for calculating reserves

2022-12-13 20:12 UTC, merged