Fenwick bite settleremove mergedev
ajna-finance/ajna-core pull request #431
Opened 2022-12-19 22:12 UTC by mattcushman

Continuation of fenwick-bites-1.  Eliminated fenwick remove() in favor of unscaledRemove() everywhere, and reduced redundant iterations of the tree.  Unified take and bucketTake constraint logic.

Minor gas improvement for bucketTake and take

New:
|--------------------------------------------|-----------------|--------|--------|--------|---------|
| Function Name                              | min             | avg    | median | max    | # calls |
|--------------------------------------------|-----------------|--------|--------|--------|---------|
| addQuoteToken                              | 105426          | 163858 | 145637 | 654260 | 52003   |
| borrowerInfo                               | 6911            | 6911   | 6911   | 6911   | 8001    |
| bucketTake                                 | 342380          | 404972 | 404989 | 467532 | 4       |
| collateralScale                            | 452             | 452    | 452    | 452    | 1       |
| drawDebt                                   | 202481          | 250560 | 222966 | 739431 | 120003  |
| inflatorInfo                               | 443             | 443    | 443    | 443    | 8001    |
| initialize                                 | 91480           | 91480  | 91480  | 91480  | 14      |
| interestRateInfo                           | 2388            | 2388   | 2388   | 2388   | 8001    |
| kick                                       | 128605          | 157313 | 153480 | 934410 | 48000   |
| loansInfo                                  | 1817            | 2515   | 2515   | 8515   | 48017   |
| moveQuoteToken                             | 251933          | 251933 | 251933 | 251933 | 1       |
| quoteTokenScale                            | 410             | 410    | 410    | 410    | 8002    |
| removeQuoteToken                           | 142169          | 164183 | 165256 | 189460 | 4000    |
| repayDebt                                  | 521778          | 553824 | 543231 | 701801 | 16001   |
| take                                       | 40942           | 49187  | 50919  | 331138 | 15998   |

Old:
|--------------------------------------------|-----------------|--------|--------|--------|---------|
| Function Name                              | min             | avg    | median | max    | # calls |
|--------------------------------------------|-----------------|--------|--------|--------|---------|
| addQuoteToken                              | 105426          | 163858 | 145637 | 654260 | 52003   |
| borrowerInfo                               | 6911            | 6911   | 6911   | 6911   | 8001    |
| bucketTake                                 | 342068          | 406744 | 406761 | 471388 | 4       |
| collateralScale                            | 452             | 452    | 452    | 452    | 1       |
| drawDebt                                   | 202481          | 250560 | 222966 | 739431 | 120003  |
| inflatorInfo                               | 443             | 443    | 443    | 443    | 8001    |
| initialize                                 | 91480           | 91480  | 91480  | 91480  | 14      |
| interestRateInfo                           | 2388            | 2388   | 2388   | 2388   | 8001    |
| kick                                       | 128605          | 157313 | 153480 | 934410 | 48000   |
| loansInfo                                  | 1817            | 2515   | 2515   | 8515   | 48017   |
| moveQuoteToken                             | 278041          | 278041 | 278041 | 278041 | 1       |
| quoteTokenScale                            | 410             | 410    | 410    | 410    | 8002    |
| removeQuoteToken                           | 142169          | 164187 | 169053 | 191936 | 4000    |
| repayDebt                                  | 521778          | 553823 | 543231 | 701801 | 16001   |
| take                                       | 41368           | 49613  | 51344  | 331564 | 15998   |

2022-12-20 00:14 UTC, ith-harvey requested changes
Christmas came early because I absolutely <3 the `calculateTakeFlows` method... fantastic example of how a refactor can make the difference.

Provided some naming suggestions, apologies in advance. Have some crazy shoot from the hip possible suggestions if they don't seem possible feel free to shoot them down.
* Is it possible to calculate the BPF as t0?
* If this were to be refactored so QT is the input from the caller of `take` && `bucketTake` how much would it improve readability / simplify the code? Worth exploring?

2022-12-20 00:14 UTC, ith-harvey commented on src/base/Pool.sol
> +        if (remainingt0Debt == 0) remainingCollateral= _settleAuction(params.borrower, remainingCollateral);
NIT: fix spacing

2022-12-20 00:14 UTC, ith-harvey commented on src/libraries/external/Auctions.sol
> +        uint256 scaledQuoteTokenAmount;   // The quote token amount that taker should pay for collateral taken.
Does it bring more or less clarity to distinguish as `scaledQuoteTokenAmount` versus "scaled" just being our default. So renaming this to `quoteTokenAmount`?

2022-12-20 00:14 UTC, ith-harvey commented on src/libraries/external/Auctions.sol
> +        uint256 t0repayAmount;            // The amount of debt (quote tokens) that is recovered / repayed by take t0 terms.
NIT: `t0RepayAmount`

2022-12-20 00:14 UTC, ith-harvey commented on src/libraries/external/Auctions.sol
> +            uint256 depositScale    = Deposits.scale(deposits_, index);
is there a collateral scale? Does it make more sense for this to be named `scale`?

2022-12-20 00:14 UTC, ith-harvey commented on src/libraries/external/Auctions.sol
> +            uint256 index           = Deposits.findIndexOfSum(deposits_, 1);
Personal preference but I would prefer the comments in this chunk below are placed the line above the code versus along the right hand side. Would help my understanding : )

2022-12-20 00:14 UTC, ith-harvey commented on src/libraries/external/Auctions.sol
> +                uint256 depositScale = Deposits.scale(deposits_, index);
same comment as above, better to just call this `scale`?

2022-12-20 00:14 UTC, ith-harvey commented on src/libraries/external/Auctions.sol
> +    function calculateTakeFlows(uint256 totalCollateral,
`takeConstraints`?

2022-12-20 00:14 UTC, ith-harvey commented on src/libraries/external/Auctions.sol
> +        if (result.isRewarded) result.unscaledQuoteTokenAmount = Maths.wdiv(result.unscaledQuoteTokenAmount, Maths.WAD - uint256(bpf));
any reason why this code block isn't included in the if at LN 449?

2022-12-20 00:14 UTC, ith-harvey commented on src/libraries/external/Auctions.sol
> +        ) internal view returns (uint256 collateral,   // TODO: make pure again
Status on this lovely `TODO`?

2022-12-20 00:14 UTC, ith-harvey commented on src/libraries/external/Auctions.sol
> +            Maths.wmul(params_.t0debt, params_.inflator),
noticing that we calculate the non-t0 debt here and in `calculateTakeFlows`. Thoughts on passing it into `calculateTakeFlows`?

2022-12-20 00:14 UTC, ith-harvey commented on src/libraries/external/Auctions.sol
> +        result.unscaledDeposit = 2**256-1; // MAX_INT
I believe you can do `type(uint256).max`, but I would double check

2022-12-20 00:14 UTC, ith-harvey commented on src/libraries/external/Auctions.sol
> +        result.unscaledDeposit = 2**256-1; // MAX_INT
Also I think it would be worth leaving a comment as to why we set `result.unscaledDeposit` to this value....?

2022-12-20 00:14 UTC, ith-harvey commented on src/libraries/external/Auctions.sol
> +        if (unscaledQuoteToken != 2**256-1) {
see max comment I made above, also could you provide a comment explaining the reason for this if check? : )

2022-12-20 00:14 UTC, ith-harvey commented on src/libraries/external/Auctions.sol
> +        if (unscaledQuoteToken != 2**256-1) {
Could also rewrite this if:
```
scaledQuoteTokenPaid = (unscaledQuoteToken != 2**256-1) ? Maths.wmul(unscaledQuoteToken, quoteTokenScale) : 2**256 - 1
```

2022-12-20 00:14 UTC, ith-harvey commented on src/libraries/external/Auctions.sol
> +            uint256 takerRewardUnscaledQuoteToken = Maths.wdiv(Maths.wmul(result_.collateralAmount, result_.bucketPrice - result_.auctionPrice), result_.bucketScale);
Readability suggestion?
```
uint256 reward = Maths.wmul(result_.collateralAmount, result_.bucketPrice - result_.auctionPrice)
uint256 takerRewardUnscaledQuoteToken = Maths.wdiv(reward , result_.bucketScale);
```

2022-12-20 01:20 UTC, mattcushman commented on src/base/Pool.sol
> +        if (remainingt0Debt == 0) remainingCollateral= _settleAuction(params.borrower, remainingCollateral);
fixed

2022-12-20 01:22 UTC, mattcushman commented on src/libraries/external/Auctions.sol
> +        uint256 t0repayAmount;            // The amount of debt (quote tokens) that is recovered / repayed by take t0 terms.
done

2022-12-20 01:28 UTC, mattcushman commented on src/libraries/external/Auctions.sol
> +    function calculateTakeFlows(uint256 totalCollateral,
It's "flows" as it computes the flow of collateral and quote token around between the various parties.

I have a desire to make a utility function, called "maximizeSubjectToConstraints" or something like this, which takes several quantities (probably need it for 3, possiblity also 2 and 4) of the form c1 * x1, c2 * x2 etc and finds the optimal way to keep them all constrained to some limit... can be used for take, deposit take, remove quote token, move quote token, settle, etc etc.  But we're not there quite yet.

2022-12-20 01:29 UTC, mattcushman commented on src/libraries/external/Auctions.sol
> +        if (result.isRewarded) result.unscaledQuoteTokenAmount = Maths.wdiv(result.unscaledQuoteTokenAmount, Maths.WAD - uint256(bpf));
nope, it really should be, fixing now.

2022-12-20 01:30 UTC, mattcushman commented on src/libraries/external/Auctions.sol
> +        ) internal view returns (uint256 collateral,   // TODO: make pure again
done

2022-12-20 01:36 UTC, mattcushman commented on src/libraries/external/Auctions.sol
> +            Maths.wmul(params_.t0debt, params_.inflator),
good point, added it.  One messy thing is that, in trying to isolate various parts of the computation, they all need to depend on things like the current debt, so we end up with a proliferation of values getting passed around.

2022-12-20 01:42 UTC, mattcushman commented on src/libraries/external/Auctions.sol
> +            uint256 takerRewardUnscaledQuoteToken = Maths.wdiv(Maths.wmul(result_.collateralAmount, result_.bucketPrice - result_.auctionPrice), result_.bucketScale);
sure

2022-12-22 13:08 UTC, grandizzy commented
closed in favor of https://github.com/ajna-finance/contracts/pull/436

2022-12-22 13:08 UTC, closed without merging