Add Liquidation support, fix minor issue with sdk adding same borrowe…
ajna-finance/ajna-core pull request #44
Opened 2022-03-23 19:43 UTC by grandizzy

…r and lender twice

2022-03-23 20:20 UTC, MikeHathaway commented on sdk/ajna_sdk.py
>          self.borrowers = []
should `self.borrowers` and `self.lenders` be removed as well?

2022-03-23 20:21 UTC, MikeHathaway commented on src/ERC20Pool.sol
> +
is there a reason for the extra blank params?

2022-03-23 20:36 UTC, MikeHathaway commented on src/PriceBuckets.sol
> +            );
Does `_collateral` deviate enough from `debt / price` to need a second `Maths.min` check?

2022-03-23 20:42 UTC, MikeHathaway commented on src/PriceBuckets.sol
> +    }
seems to be missing return statement for `bucketRequiredCollateral`

2022-03-23 20:47 UTC, MikeHathaway reviewed
Generally looks good! Should a check for bucket debt updating be added as `_buckets.liquidate()` currently doesn't seem to return anything?

2022-03-23 20:50 UTC, grandizzy commented on src/PriceBuckets.sol
> +    }
It is returning accumulated `requiredCollateral` within return function signature as it's the only one needed for updating borrower and pool balances

2022-03-23 20:53 UTC, grandizzy commented on src/ERC20Pool.sol
> +
nope, was just reusing a function that returns all borrower info. Any suggestion to make this nicer?

2022-03-23 20:54 UTC, grandizzy commented on src/PriceBuckets.sol
> +            );
good question, I made it at par with sim code, maybe @EdNoepel can clarify this

2022-03-23 20:57 UTC, grandizzy commented on sdk/ajna_sdk.py
>          self.borrowers = []
yep, will remove them too

2022-03-23 20:59 UTC, MikeHathaway commented on src/ERC20Pool.sol
> +
Ah, yeah that makes sense. Can't think of a cleaner way

2022-03-23 21:01 UTC, MikeHathaway commented on src/PriceBuckets.sol
> +    }
Think i'm missing something then, isn't that return value used on lines 436, and 438 in ERC20Pool.sol? And would the value without an explicit return produce unexpected results?

2022-03-23 21:08 UTC, grandizzy commented on src/PriceBuckets.sol
> +    }
yeah, here return is not explicitly added but function will return the `uint256 requiredCollateral` variable declared in function signature (accumulated at line 296)

2022-03-23 21:33 UTC, EdNoepel commented on src/PriceBuckets.sol
> +            );
This function iterates through buckets, liquidating from the HPB downward.  ~I cannot directly map this to the logic in the sim.~

[Here](https://github.com/ajna-finance/ajna-sim/blob/master/ajna_sim/perpetualpool.py#L598) we see a minimum of three values expressed in collateral terms, in order:
- Remaining borrower debt priced at the bucket price
- Remaining borrower collateral
- Bucket debt

2022-03-23 21:40 UTC, grandizzy commented on src/PriceBuckets.sol
> +            );
I could get it wrong but isn't the iteration from hbp downwards similar with  https://github.com/ajna-finance/ajna-sim/blob/master/ajna_sim/perpetualpool.py#L590

Since Maths.min accepts only 2 args I broke it in 2 here https://github.com/ajna-finance/contracts/pull/44/files#diff-d75b7c1bf1c7bcbed9dea75aef974098ede266f07eaf78a9238f359c5f2f84f1R278, probably better to add a Maths.min with 3 args in solidity library

2022-03-23 21:40 UTC, EdNoepel commented on src/PriceBuckets.sol
> +            );
It looks like line 278 is doing this, in the same order as the sim.

2022-03-23 21:42 UTC, EdNoepel commented on src/PriceBuckets.sol
> +            );
So to answer @MikeHathaway 's question, `_collateral` represents the borrower's remaining collateral, and `debt / price` is the amount in the bucket which can be exchanged for collateral.

2022-03-24 02:58 UTC, EdNoepel commented on src/ERC20Pool.sol
> +        borrower.debt = 0;
Before we set `borrower.debt = 0` to forgive any remaining debt after collateral is exhausted, we need to subtract it from one (or, unlikely, more buckets).  Could you show where this happens?  It seems `_buckets.liquidate` is just handling the primary task of awarding borrower collateral to buckets.

2022-03-24 02:58 UTC, EdNoepel commented on src/_test/ERC20PoolLiquidate.t.sol
> +
In addition to checking the borrower and pool are in the correct state, I recommend checking that the bucket(s) have the awarded `collateral`.

2022-03-24 05:39 UTC, grandizzy commented on sdk/ajna_sdk.py
>          self.borrowers = []
actually they should stay as they are the arrays holding lenders and borrowers. appending lenders and borrowers happens in `lender = self.add_lender()` and `borrower = self.add_borrower()` so I removed dupes

2022-03-24 05:42 UTC, grandizzy commented on src/ERC20Pool.sol
> +        borrower.debt = 0;
yep, sure, that happens in `_buckets.liquidate` function https://github.com/ajna-finance/contracts/blob/liquidation/src/PriceBuckets.sol#L300 which also checks that debt fully liquidated here https://github.com/ajna-finance/contracts/blob/liquidation/src/PriceBuckets.sol#L311

2022-03-24 08:17 UTC, grandizzy commented on src/_test/ERC20PoolLiquidate.t.sol
> +
good point, added that with commit https://github.com/ajna-finance/contracts/pull/44/commits/6d90e9cded508d471483c202397d755c3e1af70b and used it in purchase bid / collateral claim tests too

2022-03-24 11:45 UTC, EdNoepel commented on src/ERC20Pool.sol
> +        borrower.debt = 0;
`bucketDebtToPurchase` is the product of collateral and bucket price.  My question is: What happens when the borrower has no remaining collateral, but still has debt?  It seems like it will simply revert on line 311 rather than forgiving the debt.

2022-03-24 11:56 UTC, EdNoepel commented on src/ERC20Pool.sol
> +        borrower.debt = 0;
Restated within the context of the code: There is a use case where `_collateral == 0` and `_debt > 0`.  When this happens, we need to `bucket.debt -= _debt`.  If we don't do this, total debt across all buckets will exceed pool and borrower debt.

2022-03-24 12:27 UTC, grandizzy commented on src/ERC20Pool.sol
> +        borrower.debt = 0;
:+1: got the idea now, will correct this

2022-03-24 13:54 UTC, grandizzy commented on src/ERC20Pool.sol
> +        borrower.debt = 0;
@EdNoepel please check with https://github.com/ajna-finance/contracts/pull/44/commits/505a472f29ddb63210071b3dbd0cc39b45c60118
Unclear why bucket 9_000 still have dust debt, should this be expected?

2022-03-24 15:55 UTC, EdNoepel commented on src/ERC20Pool.sol
> +        borrower.debt = 0;
No.  Two problems:
- `testLiquidateAndForgive` is not a scenario where debt would be forgiven.  To have insufficient collateral to cover the debt, the LUP would need to be close to (or equal to) the HPB.  This could be accomplished by writing a test where borrower is 100% collateralized, and interest accumulation pushes them under 100%.
- Regardless, `testLiquidateAndForgive` is not behaving as expected.  I created a [spreadsheet](https://docs.google.com/spreadsheets/d/1pI2XbR87Irvo2Kp6fic5h0aYc6W_63U2ZZHocJcOhhA/edit#gid=2135024352) to show expected state at key parts of the test.

2022-03-24 16:01 UTC, grandizzy commented on src/ERC20Pool.sol
> +        borrower.debt = 0;
> No. Two problems:
> 
>     * `testLiquidateAndForgive` is not a scenario where debt would be forgiven.  To have insufficient collateral to cover the debt, the LUP would need to be close to (or equal to) the HPB.  This could be accomplished by writing a test where borrower is 100% collateralized, and interest accumulation pushes them under 100%.
> 

in order to make sure it executed that test I did a revert here https://github.com/ajna-finance/contracts/pull/44/files#diff-d75b7c1bf1c7bcbed9dea75aef974098ede266f07eaf78a9238f359c5f2f84f1R305 and with the current scenario code was executed. I'll try to make a cleaner test

>     * Regardless, `testLiquidateAndForgive` is not behaving as expected.  I created a [spreadsheet](https://docs.google.com/spreadsheets/d/1pI2XbR87Irvo2Kp6fic5h0aYc6W_63U2ZZHocJcOhhA/edit#gid=2135024352) to show expected state at key parts of the test.

:eyes:

2022-03-25 10:07 UTC, grandizzy commented on src/ERC20Pool.sol
> +        borrower.debt = 0;
@EdNoepel that's fixed now and forge tests inline with spreadsheet numbers
with no time warp: https://github.com/ajna-finance/contracts/blob/liquidation/src/_test/ERC20PoolLiquidate.t.sol#L227
with time warp: https://github.com/ajna-finance/contracts/blob/liquidation/src/_test/ERC20PoolLiquidate.t.sol#L310
please recheck

Still have to find how to simulate the liquidate and forgive scenario, mind to work together on some numbers that would trigger such?

2022-03-25 11:15 UTC, ith-harvey commented on src/libraries/Buckets.sol
> +            if (_debt == 0 || bucket.down == 0) {
Since total borrower debt can never exceed total bucket debt do we need to check if it is the last bucket with `bucket.down == 0` ? If indeed it is the last bucket the `bucket.debt > _debt`. Does this exist for another case I'm not aware of?

2022-03-25 12:04 UTC, grandizzy commented on src/libraries/Buckets.sol
> +            if (_debt == 0 || bucket.down == 0) {
yep, you're right, this shouldn't ever happen. I can remove that or just revert in that case, just as a guard if somehow gets there, wdyt?

2022-03-25 12:15 UTC, ith-harvey commented on src/libraries/Buckets.sol
> +            if (_debt == 0 || bucket.down == 0) {
Don't want to blow this up and waste peoples time with a larger convo but I think you bring up a good point as to how we should approach writing protections... Since every character in solidity makes a difference I think we should all attempt to understand the software holistically and put in place protections where they are needed with logic backing those decisions. Although I do generally believe in "better safe than sorry" I think its best that we try to remove all unnecessary code and don't have "oh well just in case because of something we don't yet forsee" protections.

So I would suggest removing it  and not having a revert... then if this occurs in testing or in an audit we find a bug we insert a protection because there is logic backing that protection. Just an idea for how we approach situations like these. Curious to hear others opinions on this one : )

As this is MVP code and we are in a "rush" feel free to throw the protection in there or do whatever you want we just want momentum baby!

2022-03-25 12:26 UTC, grandizzy commented on src/libraries/Buckets.sol
> +            if (_debt == 0 || bucket.down == 0) {
I removed that check in last commit

2022-03-25 15:13 UTC, EdNoepel requested changes
Some concerns, commented within.  Happy to meet today to discuss realtime.

2022-03-25 15:13 UTC, EdNoepel commented on src/ERC20Pool.sol
> +                inflatorSnapshot - borrower.inflatorSnapshot
Why was this formula changed?

2022-03-25 15:13 UTC, EdNoepel commented on src/PriceBuckets.sol
>              uint256 bucketRequiredCollateral = Maths.min(
The old implementation considered three values when determining how much collateral to exchange for bucket debt:
1. Borrower debt priced at the bucket
2. Borrower collateral available
3. Bucket debt priced at the bucket

The new implementation seems to remove the first value.  As such, the new logic would unfairly award too much of the borrower's collateral if bucket debt exceeds the borrower's remaining debt.

2022-03-25 15:13 UTC, EdNoepel commented on src/_test/ERC20PoolLiquidate.t.sol
> +        assertEq(pool.totalQuoteToken(), 21_000 * 1e18);
`totalQuoteToken` doesn't seem right, but there may be an issue with how the simulator is handling `quote_token_accumulator`.  So let's defer that until I confirm it's working properly in the simulator.

2022-03-25 15:13 UTC, EdNoepel commented on src/_test/ERC20PoolLiquidate.t.sol
>          assertEq(deposit, 10_000 * 1e18);
There shouldn't be any deposit in buckets 10_000 or 9_000 post-liquidation.  The borrower already took the quote token.  The liquidate function has no way to mint quote token.

2022-03-25 15:13 UTC, EdNoepel commented on src/_test/ERC20PoolLiquidate.t.sol
> +        assertEq(bucketCollateral, 0);
These numbers look correct.

2022-03-25 15:13 UTC, EdNoepel commented on src/_test/ERC20PoolLiquidate.t.sol
> +        // check bucket 10_000, 9_000 and 8_000 debt and collateral after time passes and 2nd loan
Recommend updating comment to avoid confusion; no time has passed.

2022-03-25 15:13 UTC, EdNoepel commented on src/_test/ERC20PoolLiquidate.t.sol
> +        assertEq(debt, 10_000 * 1e18);
Interest only accumulated in the 8_000 bucket because someone touched it.  So this makes sense.

2022-03-25 15:13 UTC, EdNoepel commented on src/_test/ERC20PoolLiquidate.t.sol
> +        assertEq(bucketCollateral, 0);
These numbers look good.

2022-03-25 15:13 UTC, EdNoepel commented on src/PriceBuckets.sol
> +            accumulateBucketInterest(bucket, _inflator);
I missed this on the last review.  But yes, we need to accumulate interest on all buckets touched by liquidation.

2022-03-25 15:17 UTC, grandizzy commented on src/ERC20Pool.sol
> +                inflatorSnapshot - borrower.inflatorSnapshot
this is to make it inline with https://github.com/ajna-finance/contracts/blob/develop/src/ERC20Pool.sol#L559
It was the main issue with remaining 1000 debt in bucket 9000 as borrower debt wasn't properly accumulated

2022-03-25 15:25 UTC, grandizzy commented on src/PriceBuckets.sol
>              uint256 bucketRequiredCollateral = Maths.min(
:+1:  will add it back

2022-03-25 15:30 UTC, grandizzy commented on src/_test/ERC20PoolLiquidate.t.sol
>          assertEq(deposit, 10_000 * 1e18);
I see, so that's most probably because contract tracks `amount` as the number of quote tokens lended, will change liquidate method to update `bucket.amount` too and not only `bucket.debt`

2022-03-25 15:40 UTC, grandizzy commented on src/_test/ERC20PoolLiquidate.t.sol
>          assertEq(deposit, 10_000 * 1e18);
@EdNoepel this should be solved in commit https://github.com/ajna-finance/contracts/commit/50f8318c108e66645212efaf588fa01d0b9536ed

2022-03-25 15:43 UTC, grandizzy commented on src/_test/ERC20PoolLiquidate.t.sol
> +        // check bucket 10_000, 9_000 and 8_000 debt and collateral after time passes and 2nd loan
this one looks outdated, @EdNoepel pls check again

2022-03-25 15:49 UTC, grandizzy commented on src/PriceBuckets.sol
>              uint256 bucketRequiredCollateral = Maths.min(
@EdNoepel added back with https://github.com/ajna-finance/contracts/commit/c00ad6b73949c056e8b4cfcb0cc515d097d12d2b

2022-03-25 16:07 UTC, EdNoepel commented on src/ERC20Pool.sol
> +                inflatorSnapshot - borrower.inflatorSnapshot
~I'm good with this for now.  It's cheaper, so I'll update simulator and, assuming no issues, will confirm with Matt that this works.~

2022-03-25 16:14 UTC, EdNoepel commented on src/_test/ERC20PoolLiquidate.t.sol
>          assertEq(deposit, 10_000 * 1e18);
Fixed in 50f8318c108e66645212efaf588fa01d0b9536ed

2022-03-25 16:16 UTC, EdNoepel approved these changes
LGTM!

2022-03-25 17:23 UTC, EdNoepel commented on src/ERC20Pool.sol
> +                inflatorSnapshot - borrower.inflatorSnapshot
The new formula will not work, presumably because of continuous compounding.

2022-03-25 17:26 UTC, EdNoepel commented on src/ERC20Pool.sol
> +                inflatorSnapshot - borrower.inflatorSnapshot
This means the formula should be updated at borrower level.

2022-03-25 20:05 UTC, grandizzy commented on src/_test/ERC20PoolLiquidate.t.sol
> +        assertEq(pool.totalQuoteToken(), 21_000 * 1e18);
@EdNoepel this should be addressed with https://github.com/ajna-finance/contracts/pull/44/commits/5d91a4b1c36c6c925b77b0286242c7ef5851c457

2022-03-25 20:12 UTC, grandizzy commented on src/ERC20Pool.sol
> +                inflatorSnapshot - borrower.inflatorSnapshot
uh, the real problem wasn't formula but that I didn't use Maths.wdiv lib, will fix this

2022-03-25 20:50 UTC, EdNoepel commented
> I don't think that's the case with current contract implementation where pool accumulator tracks total tokens (on deposit + debt) instead on deposit? when they are lent out (that is `borrow` function called) the tokens are added to debt accumulator only and total quote token remains the same https://github.com/ajna-finance/contracts/blob/develop/src/ERC20Pool.sol#L306
> 
> there's a similar card here to change way tokens are tracked in buckets (that is `onDeposit` and `debt` instead `amount` and `debt`) https://www.notion.so/worlds-best-crypto-lending-platform/Test-recording-onDeposit-instead-total-amount-deposited-in-bucket-ac6583b66e8c4207952abeb8c789e5a3 can look into getting pool accumulator inline with that too

Yeah.  I'm happy leaving it wrong here and fixing it in another PR.  Maybe I should take that card myself.

2022-03-25 20:54 UTC, grandizzy commented
> > I don't think that's the case with current contract implementation where pool accumulator tracks total tokens (on deposit + debt) instead on deposit? when they are lent out (that is `borrow` function called) the tokens are added to debt accumulator only and total quote token remains the same https://github.com/ajna-finance/contracts/blob/develop/src/ERC20Pool.sol#L306
> > there's a similar card here to change way tokens are tracked in buckets (that is `onDeposit` and `debt` instead `amount` and `debt`) https://www.notion.so/worlds-best-crypto-lending-platform/Test-recording-onDeposit-instead-total-amount-deposited-in-bucket-ac6583b66e8c4207952abeb8c789e5a3 can look into getting pool accumulator inline with that too
> 
> Yeah. I'm happy leaving it wrong here and fixing it in another PR. Maybe I should take that card myself.

Sounds great. Please re review and if happy with the other changes I'll merge this one in develop

2022-03-25 20:55 UTC, EdNoepel approved these changes
Let's get this merged such that we can work on issues unrelated to liquidation.

2022-03-25 20:56 UTC, merged