7% debt penalty to Borrower on intial take
ajna-finance/ajna-core pull request #447
Opened 2022-12-22 21:26 UTC by ith-harvey

This PR implements the `_applyTakePenalty` method which increases the Borrowers debt by 7% on first take. This is added to the business logic to stop borrowers from waiting to get kicked then perform a `take` themselves above their loan's NP.

Gas and size pre change:
```
  ERC721Pool               -  23,559B  (95.86%)
  ERC20Pool                -  21,105B  (85.87%)
  PositionManager          -  17,737B  (72.17%)
  Auctions                 -  16,733B  (68.08%)
  PositionNFTSVG           -  15,261B  (62.09%)
  PoolInfoUtils            -  11,574B  (47.09%)
  LenderActions            -  10,040B  (40.85%)
  PoolCommons              -   7,393B  (30.08%)
  ERC721                   -   4,421B  (17.99%)
  ERC721PoolFactory        -   2,876B  (11.70%)
  ERC20PoolFactory         -   2,194B  (8.93%)
  ERC20                    -   2,140B  (8.71%)
  Address                  -      86B  (0.35%)
  Base64                   -      86B  (0.35%)
  Buckets                  -      86B  (0.35%)
  ClonesWithImmutableArgs  -      86B  (0.35%)
  Deposits                 -      86B  (0.35%)
  EnumerableSet            -      86B  (0.35%)
  Loans                    -      86B  (0.35%)
  Maths                    -      86B  (0.35%)
  PRBMath                  -      86B  (0.35%)
  PRBMathSD59x18           -      86B  (0.35%)
  PRBMathUD60x18           -      86B  (0.35%)
  SafeERC20                -      86B  (0.35%)
  SafeTokenNamer           -      86B  (0.35%)
  Strings                  -      86B  (0.35%)
  Clone                    -      63B  (0.26%)
```
```
| src/erc20/ERC20Pool.sol:ERC20Pool contract |                 |        |        |        |         |
|--------------------------------------------|-----------------|--------|--------|--------|---------|
| Deployment Cost                            | Deployment Size |        |        |        |         |
| 4247967                                    | 21142           |        |        |        |         |
| Function Name                              | min             | avg    | median | max    | # calls |
| addCollateral                              | 17101           | 172637 | 159923 | 394805 | 14      |
| addQuoteToken                              | 2626            | 232053 | 173747 | 674205 | 353     |
| approveLpOwnership                         | 20608           | 22576  | 22708  | 22708  | 48      |
| auctionInfo                                | 1640            | 3515   | 1640   | 11640  | 145     |
| borrowerInfo                               | 911             | 1533   | 911    | 6911   | 607     |
| bucketInfo                                 | 6011            | 10780  | 8822   | 42804  | 733     |
| bucketTake                                 | 3566            | 97876  | 45023  | 324537 | 29      |
| collateralAddress                          | 481             | 481    | 481    | 481    | 10      |
| collateralScale                            | 452             | 452    | 452    | 452    | 359     |
| debtInfo                                   | 5088            | 5724   | 5088   | 15588  | 876     |
| depositIndex                               | 1043            | 14620  | 12633  | 70425  | 651     |
| depositSize                                | 838             | 913    | 838    | 4838   | 266     |
| depositUtilization                         | 1223            | 37763  | 35764  | 75011  | 121     |
| drawDebt                                   | 27397           | 173434 | 165137 | 554269 | 565     |
| emasInfo                                   | 518             | 2726   | 4518   | 4518   | 125     |
| flashFee                                   | 659             | 750    | 776    | 817    | 3       |
| flashLoan                                  | 23280           | 42413  | 30143  | 73633  | 5       |
| inflatorInfo                               | 443             | 482    | 443    | 2443   | 916     |
| initialize                                 | 536             | 90796  | 91480  | 91480  | 133     |
| interestRateInfo                           | 388             | 444    | 388    | 2388   | 780     |
| kick                                       | 28832           | 497886 | 569913 | 658419 | 34      |
| kickWithDeposit                            | 66397           | 253133 | 243476 | 429145 | 13      |
| kickerInfo                                 | 730             | 1848   | 730    | 4730   | 143     |
| lenderInfo                                 | 963             | 2137   | 1230   | 7230   | 975     |
| loanInfo                                   | 1075            | 1824   | 1424   | 5773   | 30      |
| loansInfo                                  | 1839            | 2394   | 2537   | 5839   | 480     |
| maxFlashLoan                               | 823             | 4851   | 6168   | 6247   | 4       |
| moveQuoteToken                             | 4420            | 163742 | 138442 | 615625 | 15      |
| multicall                                  | 100598          | 396052 | 396052 | 691506 | 2       |
| pledgedCollateral                          | 385             | 409    | 385    | 2385   | 327     |
| poolType                                   | 380             | 380    | 380    | 380    | 5       |
| quoteTokenAddress                          | 436             | 436    | 436    | 436    | 223     |
| quoteTokenScale                            | 410             | 410    | 410    | 410    | 1028    |
| removeCollateral                           | 803             | 49368  | 55574  | 130544 | 44      |
| removeQuoteToken                           | 824             | 57843  | 52375  | 556239 | 315     |
| repayDebt                                  | 4884            | 67076  | 53141  | 423261 | 188     |
| reservesInfo                               | 607             | 2781   | 607    | 6607   | 149     |
| settle                                     | 6392            | 181433 | 166236 | 397456 | 14      |
| take                                       | 3112            | 151326 | 130769 | 507310 | 27      |
| transferLPTokens                           | 3058            | 38417  | 39340  | 115552 | 34      |
| withdrawBonds                              | 4375            | 4375   | 4375   | 4375   | 3       |
```

post change: 
```
============ Deployment Bytecode Sizes ============
  ERC721Pool               -  23,580B  (95.94%)
  ERC20Pool                -  21,126B  (85.96%)
  PositionManager          -  17,737B  (72.17%)
  Auctions                 -  16,896B  (68.75%)
  PositionNFTSVG           -  15,261B  (62.09%)
  PoolInfoUtils            -  11,574B  (47.09%)
  LenderActions            -  10,040B  (40.85%)
  PoolCommons              -   7,393B  (30.08%)
  ERC721                   -   4,421B  (17.99%)
  ERC721PoolFactory        -   2,876B  (11.70%)
  ERC20PoolFactory         -   2,194B  (8.93%)
  ERC20                    -   2,140B  (8.71%)
```
```
| src/erc20/ERC20Pool.sol:ERC20Pool contract |                 |        |        |        |         |
|--------------------------------------------|-----------------|--------|--------|--------|---------|
| Deployment Cost                            | Deployment Size |        |        |        |         |
| 4252176                                    | 21163           |        |        |        |         |
| Function Name                              | min             | avg    | median | max    | # calls |
| addCollateral                              | 17101           | 172502 | 159923 | 394805 | 14      |
| addQuoteToken                              | 2626            | 231673 | 173747 | 674205 | 353     |
| approveLpOwnership                         | 20608           | 22576  | 22708  | 22708  | 48      |
| auctionInfo                                | 1791            | 4315   | 1791   | 13791  | 145     |
| borrowerInfo                               | 911             | 1532   | 911    | 6911   | 608     |
| bucketInfo                                 | 6011            | 10733  [...]

2022-12-23 17:29 UTC, grandizzy requested changes
Have some comments to reduce number of storage saves to 1 for an auction and not for each time an auction is taken.

I suggest also to try with an uint256 and instead bool taken and write 1 on first take, then check if != 0. bool is 8 bit so will be filled until 256 to fit a storage slot, instead uint256 which is exactly one slot, hence probably better gas?

I agree it makes perfect sense to keep flag in current Liquidation struct but I also wonder how gas is impacted if we keep an external `mapping (address -> bool) takes` instead (though will have to do an extra deletion in `removeAuction` function) - we can play with this later, nothing that needs to be done for now.

2022-12-23 17:29 UTC, grandizzy commented on src/libraries/external/Auctions.sol
> +            liquidation.alreadyTaken
we shouldn't write this flag to storage on each and every *take, just on the first take (then will be automatically removed by removeAuction). consider doing it
```
bool taken = liquidation.alreadyTaken;
if (!taken) {
   borrowerDebt += Maths.wmul(borrowerDebt_, 0.07 * 1e18);
   liquidation.alreadyTaken = true;
}
```

also I think would be cleaner and less code to maintain if you move this check in `_takeParameters` that is where `borrowerDebt_` is calculated (and get rid of duplicated calls to `_applyTakePenalty`)

2022-12-23 18:12 UTC, mattcushman reviewed
looks good other than one minor suggestion -- agree with George's comments as well

2022-12-23 18:12 UTC, mattcushman commented on src/libraries/external/Auctions.sol
> +            borrowerDebt_ += Maths.wmul(borrowerDebt_, 0.07 * 1e18);
I would replace this with borrowerDebt_ = Maths.wmul(borrowerDebt_, 1.07 * 1e18);

2022-12-23 18:41 UTC, mattcushman reviewed
Actually, thinking about this more -- why don't we just multiply the borrower t0Debt itself by 1.07 at the first take call?  This would be more effective I think.  

I'm actually a little confused here where the borrowerdebt gets writtenback to storage.

2022-12-23 20:01 UTC, grandizzy commented
> Actually, thinking about this more -- why don't we just multiply the borrower t0Debt itself by 1.07 at the first take call? This would be more effective I think.
> 
> I'm actually a little confused here where the borrowerdebt gets writtenback to storage.

That's a good catch, it actually never happens. How it works is the repaid t0 amount is calculated and returned from Auctions.take functions and then borrower's t0 debt is updated in pool base class here https://github.com/ajna-finance/contracts/blob/develop/src/base/Pool.sol#L586
So the t0 repaid amount should be recalculated with the penalty (and can also probably be a negative number if take doesn't cover the entire penalty)
Probably it needs to be changed to return also the new t0debt borrower balance

2022-12-23 21:52 UTC, mattcushman commented
I’m not in front of a computer, but wouldn’t it be easier to just update
t0debt directly (perhaps in validate take?)

On Fri, Dec 23, 2022 at 3:01 PM grandizzy ***@***.***> wrote:

> Actually, thinking about this more -- why don't we just multiply the
> borrower t0Debt itself by 1.07 at the first take call? This would be more
> effective I think.
>
> I'm actually a little confused here where the borrowerdebt gets
> writtenback to storage.
>
> That's a good catch, it actually never happens. How it works is the repaid
> t0 amount is calculated and returned from Auctions.take functions and then
> borrower's t0 debt is updated in pool base class here
> https://github.com/ajna-finance/contracts/blob/develop/src/base/Pool.sol#L586
> So the t0 repaid amount should be recalculated with the penalty (and can
> also probably be a negative number is take doesn't cover the entire penalty)
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/ajna-finance/contracts/pull/447#issuecomment-1364287195>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AIV2GW2BTQVESW25BR6J4TDWOYAJ3ANCNFSM6AAAAAATHEH3PU>
> .
> You are receiving this because your review was requested.Message ID:
> ***@***.***>
>

2022-12-25 17:29 UTC, ith-harvey commented on src/libraries/external/Auctions.sol
> +    ) internal returns (
Gas change:
```
| src/erc20/ERC20Pool.sol:ERC20Pool contract |                 |        |        |        |         |
|--------------------------------------------|-----------------|--------|--------|--------|---------|
| Deployment Cost                            | Deployment Size |        |        |        |         |
| 4252176                                    | 21163           |        |        |        |         |
| Function Name                              | min             | avg    | median | max    | # calls |
| addCollateral                              | 17101           | 173936 | 159923 | 394805 | 14      |
| addQuoteToken                              | 2626            | 231834 | 173747 | 674205 | 353     |
| approveLpOwnership                         | 20608           | 22576  | 22708  | 22708  | 48      |
| auctionInfo                                | 1791            | 4315   | 1791   | 13791  | 145     |
| borrowerInfo                               | 911             | 1532   | 911    | 6911   | 608     |
| bucketInfo                                 | 6011            | 10742  | 8799   | 35387  | 733     |
| bucketTake                                 | 3566            | 103925 | 45023  | 324537 | 29      |
| collateralAddress                          | 481             | 481    | 481    | 481    | 10      |
| collateralScale                            | 452             | 452    | 452    | 452    | 358     |
| debtInfo                                   | 5088            | 5723   | 5088   | 15588  | 877     |
| depositIndex                               | 1043            | 14640  | 12633  | 70425  | 652     |
| depositSize                                | 838             | 913    | 838    | 4838   | 266     |
| depositUtilization                         | 1223            | 37758  | 35764  | 75011  | 121     |
| drawDebt                                   | 27397           | 173435 | 165137 | 554269 | 565     |
| emasInfo                                   | 518             | 2726   | 4518   | 4518   | 125     |
| flashFee                                   | 659             | 750    | 776    | 817    | 3       |
| flashLoan                                  | 23280           | 42413  | 30143  | 73633  | 5       |
| inflatorInfo                               | 443             | 482    | 443    | 2443   | 917     |
| initialize                                 | 536             | 90796  | 91480  | 91480  | 133     |
| interestRateInfo                           | 388             | 444    | 388    | 2388   | 781     |
| kick                                       | 28832           | 497880 | 569913 | 658419 | 34      |
| kickWithDeposit                            | 66397           | 253133 | 243476 | 429145 | 13      |
| kickerInfo                                 | 730             | 1848   | 730    | 4730   | 143     |
| lenderInfo                                 | 963             | 2137   | 1230   | 7230   | 975     |
| loanInfo                                   | 1075            | 1824   | 1424   | 5773   | 30      |
| loansInfo                                  | 1839            | 2394   | 2537   | 5839   | 480     |
| maxFlashLoan                               | 823             | 4851   | 6168   | 6247   | 4       |
| moveQuoteToken                             | 4420            | 163742 | 138442 | 615625 | 15      |
| multicall                                  | 100598          | 396052 | 396052 | 691506 | 2       |
| pledgedCollateral                          | 385             | 409    | 385    | 2385   | 327     |
| poolType                                   | 380             | 380    | 380    | 380    | 5       |
| quoteTokenAddress                          | 436             | 436    | 436    | 436    | 223     |
| quoteTokenScale                            | 410             | 410    | 410    | 410    | 1028    |
| removeCollateral                           | 803             | 49337  | 55574  | 130544 | 44      |
| removeQuoteToken                           | 824             | 57834  | 52375  | 556239 | 316     |
| repayDebt                                  | 4884            | 66998  | 53141  | 423261 | 188     |
| reservesInfo                               | 607             | 2781   | 607    | 6607   | 149     |
| settle                                     | 6392            | 181659 | 166517 | 397807 | 14      |
| take                                       | 3112            | 161291 | 130769 | 529016 | 27      |
| transferLPTokens                           | 3058            | 38417  | 39340  | 115552 | 34      |
| withdrawBonds                              | 4375            | 4375   | 4375   | 4375   | 3       |
```

2022-12-25 19:16 UTC, ith-harvey commented
> Have some comments to reduce number of storage saves to 1 for an auction and not for each time an auction is taken.

Done, see current imp. As you can see in PR can't write to `liquidation.alreadyTaken` in a view function.

> I suggest also to try with an uint256 and instead bool taken and write 1 on first take, then check if != 0. bool is 8 bit so will be filled until 256 to fit a storage slot, instead uint256 which is exactly one slot, hence probably better gas?

I'd be curious to know if this was true... that "filling" a slot (going from 8bit -> 256bit) costs more than the slot being "filled" on initialization (`uint256` on initialize). I made the change and didn't see a decrease in gas at all:
```
takeParameters is not view, alreadyTaken is uint256 -> no real reduction
 Deployment Cost                            | Deployment Size |        |        |        |         |

| bucketTake                                 | 3566            | 103869 | 45023  | 324537 | 29      |
| take                                       | 3112            | 161539 | 130769 | 537567 | 27      |
```

> I agree it makes perfect sense to keep flag in current Liquidation struct but I also wonder how gas is impacted if we keep an external `mapping (address -> bool) takes` instead (though will have to do an extra deletion in `removeAuction` function) - we can play with this later, nothing that needs to be done for now.

2022-12-25 19:20 UTC, grandizzy commented
> > Have some comments to reduce number of storage saves to 1 for an auction and not for each time an auction is taken.
> 
> Done, see current imp. As you can see in PR can't write to `liquidation.alreadyTaken` in a view function.

right, but you always write when you do `(liquidation.alreadyTaken, ) = function()` even if `function()` is a view function

> 
> > I suggest also to try with an uint256 and instead bool taken and write 1 on first take, then check if != 0. bool is 8 bit so will be filled until 256 to fit a storage slot, instead uint256 which is exactly one slot, hence probably better gas?
> 
> I'd be curious to know if this was true... that "filling" a slot (going from 8bit -> 256bit) costs more than the slot being "filled" on initialization (`uint256` on initialize). I made the change and didn't see a decrease in gas at all:
> 
> ```
> takeParameters is not view, alreadyTaken is uint256 -> no real reduction
>  Deployment Cost                            | Deployment Size |        |        |        |         |
> 
> | bucketTake                                 | 3566            | 103869 | 45023  | 324537 | 29      |
> | take                                       | 3112            | 161539 | 130769 | 537567 | 27      |
> ```
> 
> > I agree it makes perfect sense to keep flag in current Liquidation struct but I also wonder how gas is impacted if we keep an external `mapping (address -> bool) takes` instead (though will have to do an extra deletion in `removeAuction` function) - we can play with this later, nothing that needs to be done for now.

2022-12-25 19:25 UTC, grandizzy commented
> > Have some comments to reduce number of storage saves to 1 for an auction and not for each time an auction is taken.
> 
> Done, see current imp. As you can see in PR can't write to `liquidation.alreadyTaken` in a view function.
> 
> > I suggest also to try with an uint256 and instead bool taken and write 1 on first take, then check if != 0. bool is 8 bit so will be filled until 256 to fit a storage slot, instead uint256 which is exactly one slot, hence probably better gas?
> 
> I'd be curious to know if this was true... that "filling" a slot (going from 8bit -> 256bit) costs more than the slot being "filled" on initialization (`uint256` on initialize). I made the change and didn't see a decrease in gas at all:

Yeah, that's what they say here https://dev.to/javier123454321/solidity-gas-optimizations-pt-3-packing-structs-23f4, see

```
Also, if you will not be packing your structs this way, it actually can be more expensive to use a datatype which is smaller than the 32byte limit! So if you have something like

 

    uint8 a;
    uint256 b;
It will be cheaper to make both variables uint256! Counter intuitive, I know! 
```

> 
> ```
> takeParameters is not view, alreadyTaken is uint256 -> no real reduction
>  Deployment Cost                            | Deployment Size |        |        |        |         |
> 
> | bucketTake                                 | 3566            | 103869 | 45023  | 324537 | 29      |
> | take                                       | 3112            | 161539 | 130769 | 537567 | 27      |
> ```
> 
> > I agree it makes perfect sense to keep flag in current Liquidation struct but I also wonder how gas is impacted if we keep an external `mapping (address -> bool) takes` instead (though will have to do an extra deletion in `removeAuction` function) - we can play with this later, nothing that needs to be done for now.

2022-12-27 09:45 UTC, grandizzy commented on src/libraries/external/Auctions.sol
> +        result.t0Debt = _applyTakePenalty(liquidation, params_.t0Debt);
you should move this inside `_validateTake` and get rid of `_applyTakePenalty` otherwise `result.t0Debt` will be reseted on line 426 (where `params_.t0Debt` is passed). IMO it is also better as we won't have to repeat same code / logic in both takes

Also on line 442 and 518 I think `result.t0RepayAmount    = params_.t0Debt;` should be `result.t0RepayAmount    = result.t0Debt;`

2022-12-28 09:05 UTC, grandizzy commented on src/base/Pool.sol
> +        poolBalances.t0Debt            += t0DebtPenalty_;
this part doesn't make sense, line 636 is doing `poolBalances.t0Debt = poolBalances.t0Debt + t0DebtPenalty_` then line 637 `poolBalances.t0Debt  = poolBalances.t0Debt - t0RepaidDebt_ - t0DebtPenalty_`  which overall means `poolBalances.t0Debt  = poolBalances.t0Debt + t0DebtPenalty_ - t0RepaidDebt_ - t0DebtPenalty_ = poolBalances.t0Debt - t0RepaidDebt_` so only one liner (and only one write to storage) `poolBalances.t0Debt            -= t0RepaidDebt_;` should suffice

2022-12-28 09:05 UTC, grandizzy commented on src/base/Pool.sol
> +            poolState_.debt    += Maths.wmul(t0DebtPenalty_, poolState_.inflator);
line 596 and 597 can be written as one liner `poolState_.debt    -= repaidDebt;` (line 596 adds `Maths.wmul(t0DebtPenalty_, poolState_.inflator)` to `poolState_.debt` then line 597 subtracts `repaidDebt` and `Maths.wmul(t0DebtPenalty_, poolState_.inflator)` from `poolState_.debt`)

2022-12-29 18:24 UTC, grandizzy commented
closing in favor of https://github.com/ajna-finance/contracts/pull/462

2022-12-29 18:24 UTC, closed without merging