Adding custom errors
ajna-finance/ajna-core pull request #48
Opened 2022-03-26 22:08 UTC by ith-harvey

2022-03-30 00:01 UTC, ith-harvey commented on src/libraries/Buckets.sol
> +        if (bucket.collateral > 0 && _amount > bucket.collateral) {
Should this be -> `bucket.collateral > 0 || _amount > bucket.collateral`? I'm thinking we may actually need separate if statements and errors for these two error checks

2022-04-08 03:01 UTC, ith-harvey commented on src/ERC20Pool.sol
> +            loanCost
Would appreciate extra eyes on this logic : )

2022-04-08 04:05 UTC, EdNoepel reviewed
Didn't review the whole thing, just left some comments where questions were asked.

2022-04-08 04:05 UTC, EdNoepel commented on src/libraries/Buckets.sol
> +        if (bucket.collateral > 0 && _amount > bucket.collateral) {
The `require` test should be true to prevent the error.  The `revert` test should be true to raise the error.  I also don't believe the 0 check is needed.  I think this should be `if (_amount > bucket.collateral)`.

2022-04-08 04:05 UTC, EdNoepel commented on src/ERC20Pool.sol
> +            loanCost
For a verbatim translation, this would be:
```
        if (
            borrower.collateralDeposited <=
            Maths.wdiv(borrower.debt + _amount, lup) ||
            borrower.collateralDeposited - Maths.wdiv(borrower.debt, lup) <=
            loanCost
```
The first check ensures the borrower remains collateralized at their new total debt, priced at the new lup.  The second check basically does the same thing, but using the bucket-level accounting mechanism to calculate encumbered collateral.  We probably don't need both.

2022-04-08 04:05 UTC, EdNoepel commented on src/ERC20Pool.sol
> +        }
This ensures the borrower isn't already undercollateralized before drawing debt.  The check isn't needed, because the check after `_buckets.borrow` covers existing encumbered collateral.

2022-04-10 15:43 UTC, ith-harvey commented on src/ERC20Pool.sol
> +            loanCost
I kept the first check but removed the second 👍

2022-04-10 15:44 UTC, ith-harvey commented on src/ERC20Pool.sol
> +        }
Removed 👍

2022-04-10 15:47 UTC, ith-harvey commented on src/libraries/Buckets.sol
> +        if (bucket.collateral > 0 && _amount > bucket.collateral) {
changed 👍

2022-04-10 16:06 UTC, EdNoepel approved these changes
Admittedly, I skimmed over the tests and focused my review on the contracts themselves.  Looks great.  👍

2022-04-10 17:27 UTC, grandizzy requested changes

2022-04-10 17:27 UTC, grandizzy commented on src/ERC20Pool.sol
> +                collateralization: getPoolCollateralization()
let's do `uint256 col = getPoolCollateralization()` only once and use it in check and custom error

2022-04-10 17:27 UTC, grandizzy commented on src/ERC20Pool.sol
> +        // if collateralDeposited <= collateralSupportingDebt + newdebt
I think this line can go

2022-04-10 17:27 UTC, grandizzy commented on src/ERC20Pool.sol
> +        if (getPoolCollateralization() < Maths.ONE_WAD) {
same as above, let's calculate poolCollateralization only once

2022-04-10 17:27 UTC, grandizzy commented on src/ERC20Pool.sol
> +        if (getPoolCollateralization() < Maths.ONE_WAD) {
same as above

2022-04-11 00:59 UTC, ith-harvey commented on src/ERC20Pool.sol
> +                collateralization: getPoolCollateralization()
Thank you! updated 👍

2022-04-11 00:59 UTC, ith-harvey commented on src/ERC20Pool.sol
> +        if (getPoolCollateralization() < Maths.ONE_WAD) {
Thank you! updated 👍

2022-04-11 01:00 UTC, ith-harvey commented on src/ERC20Pool.sol
> +        // if collateralDeposited <= collateralSupportingDebt + newdebt
updated : )

2022-04-11 01:01 UTC, ith-harvey commented on src/ERC20Pool.sol
> +        if (getPoolCollateralization() < Maths.ONE_WAD) {
updated : )

2022-04-11 04:59 UTC, grandizzy requested changes

2022-04-11 04:59 UTC, grandizzy commented on src/libraries/Buckets.sol
> +        if (_amount > Maths.wmul(_lpBalance, exchangeRate)) {
let's calculate only once `Maths.wmul(_lpBalance, exchangeRate)` and reuse

2022-04-11 04:59 UTC, grandizzy commented on src/libraries/Buckets.sol
> +        if (_amount > bucket.onDeposit + bucket.debt) {
same as above, let's `bucket.onDeposit + bucket.debt` only once

2022-04-11 05:14 UTC, grandizzy approved these changes
LGTM

2022-04-11 13:27 UTC, merged