TODO cleanup PT 1
ajna-finance/ajna-core pull request #502
Opened 2023-01-06 00:46 UTC by ith-harvey

Removed three TODOs:
* One was irrelevant, didn't need to be there confirmed with @MikeHathaway 
* Checking the parent index sum after removal
* created utility approval wrapper for borrowers when running repay

2023-01-06 01:00 UTC, ith-harvey commented on tests/forge/interactions/ERC721TakeWithExternalLiquidity.sol
> +        _drawDebt({
Removed the second borrower -> `borrower2` from the test as the previous `TODO` had suggested.

2023-01-06 01:14 UTC, EdNoepel reviewed
Please update submodules.

2023-01-07 19:05 UTC, ith-harvey commented on tests/forge/ERC721Pool/ERC721PoolCollateral.t.sol
> -    // TODO: finish implementing
Spoke with Mike, not relevant anymore

2023-01-07 19:53 UTC, MikeHathaway commented on tests/forge/ERC721Pool/ERC721DSTestPlus.sol
> +    function _approveAndRepayDebtNoLupCheck(
Not a big deal, but can also use the new `_calculateLup` helper method to take the expected debt before - amountRepaid and get the resulting lup so we don't have to maintain separate `...NoLupCheck` methods.

2023-01-07 19:57 UTC, MikeHathaway commented on tests/forge/AjnaRewards.t.sol
> -            reward:            0.227347187766462422 * 1e18,
Why was this test changed? It seems to no longer be hitting the cap, and thus resulting in less code coverage

2023-01-07 20:04 UTC, MikeHathaway requested changes
Changes to `testClaimRewardsCap` should be reverted since they broke the purpose of the test, reducing code coverage from no longer hitting the cap.

Also need to run `git submodule sync && git submodule update` as clones-with-immutable-args was replaced with a different upstream.

2023-01-08 01:02 UTC, ith-harvey commented on tests/forge/AjnaRewards.t.sol
> -            reward:            0.227347187766462422 * 1e18,
I misunderstood what the test was doing, apologies : )

2023-01-08 02:30 UTC, MikeHathaway commented on tests/forge/AjnaRewards.t.sol
> -            reward:            0.227347187766462422 * 1e18,
No worries! thanks for the revert

2023-01-08 02:38 UTC, MikeHathaway approved these changes
LGTM

2023-01-08 04:58 UTC, merged