Test Coverage and Tests Style improvements
ajna-finance/ajna-core pull request #541
Opened 2023-01-12 06:39 UTC by grandizzy

- RewardsManager:  ajna balance less than rewards tests
- PoolCommons: no interest earned when htp > max price
- ERC721Pool: collateral tests for collection pool
- Pool: loan heap test
- Pool: test move dusty amounts

coverage improved from
```
Summary coverage rate:
  lines......: 99.3% (1524 of 1534 lines)
  functions..: 99.6% (226 of 227 functions)
  branches...: 94.6% (441 of 466 branches)
```
to
```
Summary coverage rate:
  lines......: 99.5% (1527 of 1534 lines)
  functions..: 99.6% (226 of 227 functions)
  branches...: 95.5% (445 of 466 branches)
```

2023-01-12 23:46 UTC, ith-harvey requested changes
As per Lucas's changes in his formatting PR I suggest moving forward we clean up all tests from this:
```
_assertLoans(
            {
                noOfLoans:         6,
                maxBorrower:       _borrower6,
                maxThresholdPrice: 12.016346153846153854 * 1e18
            }
        );
```
to this:
```
_assertLoans({
                noOfLoans:         6,
                maxBorrower:       _borrower6,
                maxThresholdPrice: 12.016346153846153854 * 1e18
            });
```
Happy to discuss on standup if you wish too to make sure the whole team is on board.

Additionally can we screenshot the coverage increases or are those automatically visible in the github actions?

2023-01-12 23:46 UTC, ith-harvey commented on tests/forge/ERC20Pool/ERC20PoolInterestRateAndEMAs.t.sol
> +        assertGt(MAX_PRICE, _htp());
I think it makes sense to do an `_assertPool` here

2023-01-12 23:46 UTC, ith-harvey commented on tests/forge/ERC20Pool/ERC20PoolLoanHeap.t.sol
> +        // Lender 1 adds Quote token accross 2 buckets
3 buckets

2023-01-12 23:46 UTC, ith-harvey commented on tests/forge/ERC20Pool/ERC20PoolLoanHeap.t.sol
> +
comment describing reassignment of head?

2023-01-12 23:46 UTC, ith-harvey commented on tests/forge/ERC20Pool/ERC20PoolLoanHeap.t.sol
> +
comment here describing reassignment of head

2023-01-12 23:46 UTC, ith-harvey commented on tests/forge/ERC20Pool/ERC20PoolLoanHeap.t.sol
> +        _repayDebt({
Same as above

2023-01-12 23:46 UTC, ith-harvey commented on tests/forge/ERC20Pool/ERC20PoolLoanHeap.t.sol
> +        _drawDebt(
same as above

2023-01-12 23:46 UTC, ith-harvey commented on tests/forge/RewardsManager.t.sol
> +        // claimed rewards amount is greater than available tokens in rewards manager contract
Is there any code/assertions supporting this claim?

2023-01-13 11:15 UTC, grandizzy commented on tests/forge/ERC20Pool/ERC20PoolInterestRateAndEMAs.t.sol
> +        assertGt(MAX_PRICE, _htp());
done in https://github.com/ajna-finance/contracts/pull/541/commits/c7c823fba82ba36416691802ef2b0fc86f0a36b2

2023-01-13 11:15 UTC, grandizzy commented on tests/forge/ERC20Pool/ERC20PoolLoanHeap.t.sol
> +        // Lender 1 adds Quote token accross 2 buckets
changed in https://github.com/ajna-finance/contracts/pull/541/commits/c7c823fba82ba36416691802ef2b0fc86f0a36b2

2023-01-13 11:15 UTC, grandizzy commented on tests/forge/ERC20Pool/ERC20PoolLoanHeap.t.sol
> +
added in https://github.com/ajna-finance/contracts/pull/541/commits/c7c823fba82ba36416691802ef2b0fc86f0a36b2

2023-01-13 11:15 UTC, grandizzy commented on tests/forge/ERC20Pool/ERC20PoolLoanHeap.t.sol
> +
added in https://github.com/ajna-finance/contracts/pull/541/commits/c7c823fba82ba36416691802ef2b0fc86f0a36b2

2023-01-13 11:15 UTC, grandizzy commented on tests/forge/ERC20Pool/ERC20PoolLoanHeap.t.sol
> +        _repayDebt({
added in https://github.com/ajna-finance/contracts/pull/541/commits/c7c823fba82ba36416691802ef2b0fc86f0a36b2

2023-01-13 11:16 UTC, grandizzy commented on tests/forge/ERC20Pool/ERC20PoolLoanHeap.t.sol
> +        _drawDebt(
added in https://github.com/ajna-finance/contracts/pull/541/commits/c7c823fba82ba36416691802ef2b0fc86f0a36b2

2023-01-13 11:16 UTC, grandizzy commented on tests/forge/RewardsManager.t.sol
> +        // claimed rewards amount is greater than available tokens in rewards manager contract
added in https://github.com/ajna-finance/contracts/pull/541/commits/c7c823fba82ba36416691802ef2b0fc86f0a36b2

2023-01-13 11:17 UTC, grandizzy commented
> As per Lucas's changes in his formatting PR I suggest moving forward we clean up all tests from this:
> 
> ```
> _assertLoans(
>             {
>                 noOfLoans:         6,
>                 maxBorrower:       _borrower6,
>                 maxThresholdPrice: 12.016346153846153854 * 1e18
>             }
>         );
> ```
> 
> to this:
> 
> ```
> _assertLoans({
>                 noOfLoans:         6,
>                 maxBorrower:       _borrower6,
>                 maxThresholdPrice: 12.016346153846153854 * 1e18
>             });
> ```
> 
I like the proposal, I applied same style across all unit tests with https://github.com/ajna-finance/contracts/pull/541/commits/3945a5b3556246a76c8f7c0e5898cca75926873f

> Happy to discuss on standup if you wish too to make sure the whole team is on board.
> 
> Additionally can we screenshot the coverage increases or are those automatically visible in the github actions?

I added coverage comparison in PR description

2023-01-16 16:07 UTC, ith-harvey approved these changes
LGTM

2023-01-16 17:33 UTC, MikeHathaway approved these changes
LGTM - much cleaner now

2023-01-16 17:56 UTC, merged