Borrower only pay their debt | bucket deposit check removed on borrow
ajna-finance/ajna-core pull request #55
Opened 2022-03-31 15:23 UTC by ith-harvey

* Fixed bug where borrower could repay other borrower's debt if they passed an amount greater than their own debt
* Fixed bug by removing the arbitrary requirement for `bucket.deposit > bucket.debt`

2022-03-31 17:51 UTC, EdNoepel reviewed
~Brownie tests in this branch just hang for some reason.  Recommend investigation.~  This was an environment issue in my WC.

No issues with contract changes.  I did not thoroughly review the tests, but appreciate the added coverage.

2022-03-31 19:33 UTC, grandizzy approved these changes
Only a minor comment, something that I already changed in a subsequent PR anyway so up to you if you want to address it here as well. LGTM, nice catch!

2022-03-31 19:33 UTC, grandizzy commented on src/ERC20Pool.sol
> -        (uint256 lentTokens, uint256 requiredCollateral) = _buckets.liquidate(
`lentTokens` can be entirely removed from Bucket return function as it's not used anymore

2022-03-31 19:52 UTC, MikeHathaway approved these changes
LGTM

2022-03-31 21:50 UTC, ith-harvey commented
Repay fails in brownie 😨 ... investigating.

2022-04-01 16:12 UTC, EdNoepel requested changes

2022-04-01 16:12 UTC, EdNoepel commented on src/ERC20Pool.sol
>          (lup, debtToPay) = _buckets.repay(_maxAmount, lup, inflatorSnapshot);
This isn't right; `_maxAmount` needs to be dropped to `borrower.debt` before running `_buckets.repay`.

2022-04-01 16:14 UTC, EdNoepel commented on src/ERC20Pool.sol
>          (lup, debtToPay) = _buckets.repay(_maxAmount, lup, inflatorSnapshot);
To clarify, `_buckets.repay` is actually paying off bucket debt up to `_maxAmount`.  If we don't first limit it by the borrower debt, bucket accounting will show `_maxAmount` has been paid off, but borrower and pool accounting will decrement by the expected amount.

2022-04-01 17:16 UTC, ith-harvey commented on src/ERC20Pool.sol
>          (lup, debtToPay) = _buckets.repay(_maxAmount, lup, inflatorSnapshot);
I believe this has been resolved, still not sure on the brownie error. Just asked @MikeHathaway to attempt on his machine

2022-04-01 19:38 UTC, EdNoepel approved these changes
Looks good now.

2022-04-01 21:01 UTC, merged