Sherlock 39: expiration timestamp and slippage control
ajna-finance/ajna-core pull request #600
Opened 2023-02-09 14:22 UTC by EdNoepel

# The deposit / withdraw / trade transaction lack of expiration timestamp check and slippage control

## Summary

The deposit / withdraw / trade transaction lack of expiration timestamp and slippage control

## Vulnerability Detail

The transaction can be pending in mempool  for a long and the trading activity is very time senstive. Without deadline check, the trade transaction can be executed in a long time after the user submit the transaction, at that time, the trade can be done in a sub-optimal price, which harms user's position.

The deadline check ensure that the transaction can be executed on time and the expired transaction revert.

## Impact

Because the deadline check is missing, 

After a lender submit a transaction and want to add the token into Highest price busket to make sure the quote token can be borrowed out and generate yield.

However, the transaction is pending in the mempool for a very long time.

Borrower create more debt and other lender's add and withdraw quote token before the lender's transaction is executed.

After a long time later, the lender's transaction is executed.

The lender find out that the highest priced bucket moved and the lender cannot withdraw his token because doing would move the LUP down eligible for liquidiation.

## Recommendation

We recommend the protocol add deadline check and add slippage control.

## Out of scope

Liquidations were not mentioned in the report and require further discussion.

2023-02-09 16:45 UTC, EdNoepel commented on tests/forge/ERC20Pool/ERC20PoolQuoteToken.t.sol
> -
moved to line 205

2023-02-09 18:32 UTC, EdNoepel commented
Have been resolving conflicts as they come.

2023-02-10 09:25 UTC, grandizzy requested changes
Looks good, have a suggestion to make checks consistent in draw debt as well

2023-02-10 09:25 UTC, grandizzy commented on src/libraries/external/BorrowerActions.sol
> +            if (result_.newLup < _priceAt(limitIndex_)) revert LimitIndexReached();
makes sense and at par with `if (vars.lupId > limitIndex_) revert LimitIndexReached();` check in `borrow`. would it make sense to change that one too for clarity / consistency from

```solidity
            // determine new lup index and revert if borrow happens at a price higher than the specified limit (lower index than lup index)
            vars.lupId = _lupIndex(deposits_, result_.poolDebt);
            if (vars.lupId > limitIndex_) revert LimitIndexReached();

            // calculate new lup and check borrow action won't push borrower into a state of under-collateralization
            // this check also covers the scenario when loan is already auctioned
            result_.newLup = _priceAt(vars.lupId);
```
to
```solidity
            // revert if LUP dropped below the limit
            result_.newLup = _lup(deposits_, result_.poolDebt);

            if (result_.newLup < _priceAt(limitIndex_)) revert LimitIndexReached();
```

We can also consider to have a revert helper function and use it for both places?

2023-02-10 19:45 UTC, EdNoepel commented on src/libraries/external/BorrowerActions.sol
> +            if (result_.newLup < _priceAt(limitIndex_)) revert LimitIndexReached();
I did this in a separate PR, #604 , because it touched a lot of things.

2023-02-10 19:51 UTC, grandizzy commented on src/libraries/external/BorrowerActions.sol
> +            if (result_.newLup < _priceAt(limitIndex_)) revert LimitIndexReached();
sounds good, we can follow up on that one

2023-02-10 19:51 UTC, grandizzy approved these changes

2023-02-10 20:34 UTC, MikeHathaway approved these changes
LGTM. Should the checks also be added to `removeCollateral`?

2023-02-10 21:15 UTC, EdNoepel commented
> LGTM. Should the checks also be added to `removeCollateral`?

I don't see a need to impose an expiry on removal of quote or collateral.  Lender is never at risk for redeeming their LP, regardless of when the TX is finalized.

2023-02-11 21:50 UTC, grandizzy commented on src/libraries/external/BorrowerActions.sol
> +            // if (vars.lupId > limitIndex_) revert LimitIndexReached();
We can remove the commented code here

2023-02-11 22:48 UTC, EdNoepel commented on src/libraries/external/BorrowerActions.sol
> +            // if (vars.lupId > limitIndex_) revert LimitIndexReached();
Done in c15d036f8f6a44b19b4e4e59cc413a12b85999bc.

2023-02-12 03:01 UTC, dmitriia approved these changes
Looks ok.

Comment can be updated though as the argument is a price index:

```diff
    /**
     * @notice  Check if LUP is at or above index limit provided by borrower.
     * @notice  Prevents stale transactions and certain MEV manipulations.
     * @param newLup_     New LUP as a result of the borrower action.
-    * @param limitIndex_ Price limit provided by user creating the TX.
+    * @param limitIndex_ Limit price index provided by user creating the TX.
     */
    function _revertIfLupDroppedBelowLimit(
        uint256 newLup_,
        uint256 limitIndex_
    ) pure {
        if (newLup_ < _priceAt(limitIndex_)) revert LimitIndexReached();
    }
```

And maybe rename the error, as now call reverts when index not just reached, but when it is exceeded?

```solidity
+   error LimitIndexExceeded();
```

Comments here can be updated, it's a little bit confusing now (describing loan price, checking lup; saying about lup calculation after it was done):

```solidity
    // determine new lup index and revert if borrow happens at a price higher than the specified limit (lower index than lup index)
    vars.lupId = _lupIndex(deposits_, result_.poolDebt);
    result_.newLup = _priceAt(vars.lupId);

    _revertIfLupDroppedBelowLimit(result_.newLup, limitIndex_);

    // calculate new lup and check borrow action won't push borrower into a state of under-collateralization
    // this check also covers the scenario when loan is already auctioned

    if (!_isCollateralized(vars.borrowerDebt, borrower.collateral, result_.newLup, poolState_.poolType)) {
        revert BorrowerUnderCollateralized();
    }
```

2023-02-12 09:23 UTC, grandizzy commented
> ```solidity
> LimitIndexExceeded
> ```

@EdNoepel if OK to accommodate these changes - I made a PR on top of yours, pls have a look https://github.com/ajna-finance/contracts/pull/607

2023-02-12 10:51 UTC, grandizzy commented
realized that by using `_revertIfLupDroppedBelowLimit` gas costs will be a little bit higher than before, because in the former implementation we were comparing indexes (hence not requiring an additional `_priceAt` call for provided limit index) whereas in this implementation we're always calculating the price for limit index. I think how PR handles this it's OK for consistency and probably not a big increase in gas either, just wanted to flag this

2023-02-12 14:27 UTC, dmitriia approved these changes

2023-02-12 16:15 UTC, merged