Sherlock 100: Debt weighted tu
ajna-finance/ajna-core pull request #605
Opened 2023-02-10 20:28 UTC by ith-harvey

# Description of change
## High level
* Currently interest rates are set by looking at the current utilization versus a target utilization (TU).  TU is computed by taking a moving average of the inverse of the pool collateralization ratio over time.
`TUcurrent= EMA PoolDebtLUPPoolPledgedCollateral`
* This may be vulnerable to gaming by someone pledging a large amount of collateral in the pool and taking no debt.  This would result in TU moving down over time, with rates then moving upward, rendering the pool uneconomical to borrow from, at least temporarily.
* To mitigate this risk, this PR down weights loans with excessively high collateralization ratios (essentially infinite in the case where there is no debt at all).  This emphasizes loans that are more actively managed with “market” collateralization ratios.

Implementation
* Added a global accumulator `t0PoolUtilizationDebtWeight` that tracks the sum of t0-debt squared divided by the collateral posted over all borrowers.
* The `t0PoolUtilizationDebtWeight` accumulator is the sum of `t0d**2/ collateral` across all borrowers with `collateral >0`
* When a Borrower’s debt is increased, `t0PoolUtilizationDebtWeight` is increased. 
* When Borrower’s debt is decreased `t0PoolUtilizationDebtWeight` is decreased.
* When Borrower’s collateral is increased (borrower must have debt) `t0PoolUtilizationDebtWeight` is decreased.
* When Borrower’s collateral is decreased (borrower must have debt) `t0PoolUtilizationDebtWeight` is increased.
* Adding or removing collateral to a loan with no debt has no effect on the accumulator.
* If collateral is reduced to zero by an action, borrower’s position is closed and `t0PoolUtilizationDebtWeight` is decreased.
* Updated current term in the EMAs used to compute the `TU` with `EMA(poolInflator * poolT0DebtSquaredToCollateral / lup) / EMA(poolT0DebtAccumulator)`

# Description of bug or vulnerability and solution
Summary

Interest rates algorithm is based on MAU to TAU dynamics, where TAU is 3.5 day EMA of total debt to LUP * total collateral. The latter value can be manipulated by a big collateral holder by becoming a borrower with insignificant debt and lots of collateral, so 3.5d EMA of Debt / (LUP * Collateral) will become depressed and rates will go up irrespective to the real debt supply/demand situation.

Vulnerability Detail

Let's suppose Bob is a big WBTC holder and current market rate for its lending is insignificant, say base WBTC deposit APY on major platforms is below 5 basis points. Say Bob is a big lender of USDC-WBTC (quote-collateral) pool or Bob has interests in disturbing that pool operations for any reasons, for example Bob is a beneficiary of a rival lending protocol.

Bob can borrow a minimal loan, say 1000 USDC with big, magnitudes excessive, WBTC collateral, say 1000 WBTC. As the pool is permissionless it is safe, Bob can withdraw any time, market risk is close to zero as the loan is too small, interest rates risk is small too as Bob left near zero market interest rate for the strict zero income while the WBTC is used as collateral in the pool. I.e. it's low risk, low cost strategy for Bob to do so.

Pool, on the other hand, will experience gradual rise of the interest rate as while MAU will stay relatively constant, TAU will become low due to total collateral amount being big (and stable, so EMA will move to the corresponding value), while other parts of Debt / (LUP * Collateral) be relatively constant.

Observing the rise of interest rates above market the borrowers will gradually leave. But not all, and Bob has achieved above market interest income from dormant part of the borrowers, who are slow to react to this dynamics. But, given borrowers being mostly rational and informed, this to be relatively short-term situation. More importantly, as the rate went up and borrowers has left, lenders will observe significantly decreased utilization and will leave pool as well, not receiving enough interest income for their deposits.

This way Bob essentially disturbed the USDC-WBTC pool, so he can leave some small part of WBTC collateral there so that the rate will stay elevated and pool remain to be unusable due to significantly elevated interest rate, as no borrower will enter there on such conditions.

# Contract size
## Pre Change
```
============ Deployment Bytecode Sizes ============
  ERC721Pool               -  22,692B  (92.33%)
  ERC20Pool                -  22,124B  (90.02%)
  Auctions                 -  19,710B  (80.20%)
  PositionManager          -  18,036B  (73.39%)
  PositionNFTSVG           -  15,261B  (62.09%)
  PoolInfoUtils            -  11,958B  (48.66%)
  BorrowerActions          -  11,322B  (46.07%)
  LenderActions            -  10,623B  (43.22%)
  RewardsManager           -   8,212B  (33.41%)
  PoolCommons              -   7,585B  (30.86%)
  ERC721                   -   4,421B  (17.99%)
  ERC721PoolFactory        -   3,340B  (13.59%)
  ERC20PoolFactory         -   2,473B  (10.06%)
```
## Post Change
```
============ Deployment Bytecode Sizes ============
  ERC721Pool               -  22,936B  (93.32%)
  ERC20Pool                -  22,374B  (91.04%)
  Auctions                 -  20,288B  (82.55%)
  PositionManager          -  18,036B  (73.39%)
  PositionNFTSVG           -  15,261B  (62.09%)
  PoolInfoUtils            -  11,958B  (48.66%)
  BorrowerActions          -  11,682B  (47.53%)
  LenderActions            -  10,623B  (43.22%)
  RewardsManager           -   8,212B  (33.41%)
  PoolCommons              -   7,622B  (31.01%)
  ERC721                   -   4,421B  (17.99%)
  ERC721PoolFactory        -   3,340B  (13.59%)
  ERC20PoolFactory         -   2,473B  (10.06%)
```

# Gas usage
## Pre Change
```
| src/ERC20Pool.sol:ERC20Pool contract            |                 |        |        |        |         |
|-------------------------------------------------|-----------------|--------|--------|--------|---------|
| Deployment Cost                                 | Deployment Size |        |        |        |         |
| 4452044                                         | 22162           |        |        |        |         |
| Function Name                                   | min             | avg    | median | max    | # calls |
| addCollateral(uint256,uint256,uint256)          | 180765          | 181758 | 181758 | 182751 | 2       |
| addCollateral(uint256,uint256,uint256)(uint256) | 715             | 155912 | 143976 | 396280 | 26      |
| addQuoteToken(uint256,uint256,uint256)          | 345133          | 417307 | 450368 | 475433 | 5       |
| addQuoteToken(uint256,uint256,uint256)(uint256) | 714             | 225536 | 172698 | 693533 | 620     |
| approveLpOwnership                              | 27361           | 73684  | 73085  | 233120 | 61      |
| approveLpTransferors                            | 2823            | 16898  | 25428  | 25428  | 54      |
| approvedTransferors                             | 787             | 1453   | 787    | 2787   | 3       |
| auctionInfo                                     | 1776            | 4296   | 1776   | 13776  | 196     |
| borrowerInfo                                    | 933             | 1437   | 933    | 6933   | 975     |
| bucketCollateralDust                            | 790             | 1629   | 790    | 2902   | 15      |
| bucketExchangeRate                              | 14187           | 16136  | 15735  | 18501  | 390     |
| bucketInfo                                      | 3739            | 7562   | 5458   | 45688  | 1768    |
| bucketTake                                      | 8084            | 127084 | 132801 | 364230 | 36      |
| burnInfo                                        | 864             | 898    | 864    | 4864   | 1489    |
| collateralAddress                               | 459             | 459    | 459    | 459    | 234     |
| collateralScale                                 | 408             | 408    | 408    | 408    | 561     |
| currentBurnEpoch            [...]

2023-02-10 20:30 UTC, ith-harvey commented on tests/forge/ERC20Pool/ERC20PoolInterestRateAndEMAs.t.sol
> -            debtEma:   4_340.881358710158802477 * 1e18,
flagging this... this most likely has to do with the EMA now being based on `t0Debt`. @mattcushman hoping to get your eyes on this

2023-02-10 20:31 UTC, ith-harvey commented on tests/forge/ERC20Pool/ERC20PoolInterestRateAndEMAs.t.sol
> +                targetUtilization:    1 * 1e18,
Flagging this as well, just seems like a very large increase CC: @mattcushman

2023-02-11 13:36 UTC, mattcushman reviewed
I was reviewing this along the way, and I think that we need to do this in a slightly different manner.  We should implement a function that takes in a t0debt quantity and a collateral quantity, and returns Maths.wdiv(Maths.wmul(t0Debt,t0Debt), collateral).  

Then, in these functions where those quantities change, we snapshot what they are in the beginning and the end, and add/subtract that change to the global accumulator.

Why is this?  Because we need to maintain the invariant that these literally sum up properly across all loans/borrowers in the book.  If we try to do these piecemeal updates along the way, using things like maths.wmul etc, we will be rounding off.  Some of this is my fault for just thinking of the math as being integer precision while it's really not (for example, I think it's dangerous to use 1/x-1/y = (y-x)/xy which I did in the write up).

2023-02-11 13:36 UTC, mattcushman commented on src/libraries/external/BorrowerActions.sol
> +                uint256 collateralChange = borrower.collateral - (borrower.collateral - collateralToPledge_);
why do you need this?  collateralChange is just collateralToPledge_

2023-02-11 13:36 UTC, mattcushman commented on src/libraries/external/BorrowerActions.sol
> +            if (vars.borrowerDebt != 0) {
Why not put this in the if(vars.pledge) ... block up above?  This only affects collateral if someone is pledging right?

2023-02-11 13:36 UTC, mattcushman commented on src/libraries/external/BorrowerActions.sol
> +                result_.t0PoolUtilizationDebtWeight -= Maths.wmul(borrower.t0Debt ** 2, collateralPortion);
When squaring a WAD, we can't just **2 like this, because of the scale.  I'd recommend using wmul just to remain consistent:
result_.t0PoolUtilizationDebtWeight -= Maths.wmul(Maths.wmul(borrower.t0Debt,borrower.t0Debt), collateralPortion);

2023-02-11 13:36 UTC, mattcushman commented on src/libraries/external/BorrowerActions.sol
> +            result_.t0PoolUtilizationDebtWeight += Maths.wdiv(((borrower.t0Debt + vars.t0DebtChange) ** 2) - (borrower.t0Debt ** 2), borrower.collateral);
same comment as above -- can't just **2 because of the WAD scaling

2023-02-17 12:11 UTC, mattcushman commented on src/libraries/external/Auctions.sol
> +    function adjustUtilizationWeight(
Rather than have this function in Auctions, why don't we put it somewhere available to borrower actions and auctions, and call it from there?  it's basically the same functions used in both places, which does the same thing.

2023-02-17 12:13 UTC, mattcushman commented on src/libraries/external/BorrowerActions.sol
> +            uint256 oldDebt = Maths.wdiv(Maths.wmul(borrower.t0Debt, borrower.t0Debt),
it's not really debt, so perhaps there would be a better variable name than oldDebt/newDebt?  even something like debtSquaredToCollateral? (debt-squared-to-collateral)

2023-02-21 02:05 UTC, ith-harvey commented on src/libraries/external/BorrowerActions.sol
> +            if (vars.borrowerDebt != 0) {
it is inside of `vars.pledge`

2023-02-21 02:05 UTC, ith-harvey commented on src/libraries/external/PoolCommons.sol
>              uint256 maxLupColEma = Maths.wmul(poolState_.debt, Maths.wad(10));
is using non-t0 debt alright here?

2023-02-21 02:05 UTC, ith-harvey commented on tests/forge/ERC20Pool/ERC20PoolCollateral.t.sol
> +                targetUtilization:    7.081111825921092812 * 1e18,
Seeing value increases like this, make me think something is incorrectly implemented. CC: @mattcushman

2023-02-22 19:30 UTC, ith-harvey commented on tests/forge/ERC20Pool/ERC20PoolCollateral.t.sol
> +                targetUtilization:    7.081111825921092812 * 1e18,
Here are some logs, seems to be behaving as intended.
  After borrow after adjustment t0PoolUtilizationDebtWeight: `4_418_484.846523668643127938`
  start of repay before adjustment t0PoolUtilizationDebtWeight: `4_418_484.846523668643127938`
  end of repay after adjustment t0PoolUtilizationDebtWeight: `8_836_969.693047337286255876`
  
  collateral is removed so utilization Debt Weight increases.

2023-02-22 19:33 UTC, ith-harvey commented on tests/forge/ERC721Pool/ERC721PoolBorrow.t.sol
> +                interestRateUpdate:   _startTime // todo: why this change?
This doesn't make sense to me, repayDebt above should be the action that updates the pool and apparently it's not?

2023-02-22 20:20 UTC, ith-harvey commented on tests/forge/ERC721Pool/ERC721PoolBorrow.t.sol
> +                interestRateUpdate:   _startTime // todo: why this change?
So after looking into this the `updateInterestRate()` method is fired however the `newInterestRate` variable is not updated. This is due to the if else checks here:

https://github.com/ajna-finance/contracts/blob/e3c9724de79aa051409d7d1d878a8d934a75e7b5/src/libraries/external/PoolCommons.sol#L108

 in this example
 tu -> `0.083613626841426309`
 new mau 102 -> `0.051232021515115742`
 
 Which based on the if statement logic above does not result in an increase or a decrease of the rate. Does this seem correct @mattcushman ?

2023-02-23 10:51 UTC, ith-harvey commented
> I was reviewing this along the way, and I think that we need to do this in a slightly different manner. We should implement a function that takes in a t0debt quantity and a collateral quantity, and returns Maths.wdiv(Maths.wmul(t0Debt,t0Debt), collateral).
> 
> Then, in these functions where those quantities change, we snapshot what they are in the beginning and the end, and add/subtract that change to the global accumulator.
> 
> Why is this? Because we need to maintain the invariant that these literally sum up properly across all loans/borrowers in the book. If we try to do these piecemeal updates along the way, using things like maths.wmul etc, we will be rounding off. Some of this is my fault for just thinking of the math as being integer precision while it's really not (for example, I think it's dangerous to use 1/x-1/y = (y-x)/xy which I did in the write up).

Has been resolved.

2023-02-23 13:33 UTC, mattcushman commented on src/libraries/external/PoolCommons.sol
> +        int256 tu = (curDebtEma != 0 && curLupColEma != 0) ? int256(Maths.wdiv(curLupColEma, curDebtEma)) : int(Maths.WAD);
as i review the spec right now, I think we don't need to divide by ema of current debt here. so, we can just eliminate the curDebtEma altogether.

2023-02-23 13:37 UTC, mattcushman commented on src/libraries/external/PoolCommons.sol
>                  Maths.wmul(Maths.min(lupCol, maxLupColEma), EMA_7D_RATE_FACTOR) +
It looks like this EMA is not computed properly.  We need to maintain the ema state, which would be formed by:
 new value =LAMBDA_EMA_7D * (old value) + (1e18-LAMBDA_EMA_7D) * lupCol

I don't see much value in the constant EMA_7D_RATE_FACTOR which is just 1e18- LAMBDA_EMA_7D

2023-02-23 20:53 UTC, ith-harvey commented on src/libraries/external/PoolCommons.sol
>                  Maths.wmul(Maths.min(lupCol, maxLupColEma), EMA_7D_RATE_FACTOR) +
@EdNoepel is there a reason for the `maxLupColEma` variable and `Maths.min(lupCol, maxLupColEma)` comparison here? I can't seem to find how that is represented in the spec, wondering if you could lend a hand?

2023-02-23 23:33 UTC, EdNoepel requested changes
`PoolInfoUtils._targetUtilization` is unchanged, which doesn't seem right.  The parameters and computation have changed.  Recommend updating that method first, writing tests against a spreadsheet of known values, and then decide whether the new implementation could be shared between _PoolInfoUtils_ and `PoolCommons.updateInterestRate`.

2023-02-23 23:33 UTC, EdNoepel commented on src/libraries/external/PoolCommons.sol
> +                Maths.wmul(poolState_.t0Debt, EMA_7D_RATE_FACTOR) +
Why did this EMA change to use t0debt?

2023-02-23 23:33 UTC, EdNoepel commented on src/libraries/external/PoolCommons.sol
>              uint256 maxLupColEma = Maths.wmul(poolState_.debt, Maths.wad(10));
EMAs should be calculated from current debt, not t0 debt.

2023-02-23 23:33 UTC, EdNoepel commented on src/interfaces/pool/commons/IPoolState.sol
>      uint256 lupColEma;          // [WAD] sample of LUP price * collateral EMA. capped at 10 times current pool debt
Seems these two EMAs would be combined into a single EMA of the DWAC's numerator.  I assume we are removing the cap, which I do not see in requirements.

2023-02-24 20:22 UTC, ith-harvey commented on src/libraries/external/PoolCommons.sol
> +        int256 tu = (curDebtEma != 0 && curLupColEma != 0) ? int256(Maths.wdiv(curLupColEma, curDebtEma)) : int(Maths.WAD);
I believe this suggested change contradicts  white paper? See the following:

> Precisely, TU is the ratio of the 3.5 day exponentially weighted moving average (EMA) of the numerator of DWAC to the denominator of DWAC in this equation sampled every twelve hours.  

By getting rid of `curDebtEMA` we would be removing "to the denominator of DWAC" in the instruction above. Is that the intention?

As well as the TU spec paper:
> Given this accumulator, we replace the current term in the EMAs used to compute the TU with EMA(poolInflator * poolT0DebtSquaredToCollateral / lup) / EMA(poolT0DebtAccumulator)

2023-02-24 20:22 UTC, ith-harvey commented on src/libraries/external/PoolCommons.sol
> +                Maths.wmul(poolState_.t0Debt, EMA_7D_RATE_FACTOR) +
Per the TU design doc:
> Given this accumulator, we replace the current term in the EMAs used to compute the TU with EMA(poolInflator * poolT0DebtSquaredToCollateral / lup) / EMA(poolT0DebtAccumulator)

Per the white paper:
> Precisely, TU is the ratio of the 3.5 day exponentially weighted moving average (EMA) of the numerator of DWAC to the denominator of DWAC in this equation sampled every twelve hours. 

Upon inspection the denominator of the DWAC appears to be `poolState_.t0Debt` and the white paper is asking that an EMA is taken of it, thus the code change.

I don't know the why... and I agree with you, this seems counterintuitive, if we multiply the numerator by the inflator but not the denominator we are dividing by an incomplete debt amount. @mattcushman you mind expanding why the denominator isn't multiplied by the inflator?

2023-02-24 21:53 UTC, ith-harvey commented on src/libraries/external/PoolCommons.sol
>                  Maths.wmul(Maths.min(lupCol, maxLupColEma), EMA_7D_RATE_FACTOR) +
@mattcushman I updated the EMA to reflect the white paper as I understand it. Please let me know if you still deem it incorrectly calculated : ).

2023-02-24 21:56 UTC, ith-harvey commented on src/interfaces/pool/commons/IPoolState.sol
>      uint256 lupColEma;          // [WAD] sample of LUP price * collateral EMA. capped at 10 times current pool debt
The docs say that they should both be calculated separately, not sure what the impacts are of each implementation. will investigate as it could save us gas.

2023-02-27 12:45 UTC, grandizzy requested changes

2023-02-27 12:45 UTC, grandizzy commented on src/libraries/external/Auctions.sol
> +            borrower.t0Debt,
`borrower` is struct loaded from storage so subsequent access of `borrower.t0Debt` and `borrower.collateral` will spend gas to read. I suggest either change `Borrower storage borrower` to `Borrower memory borrower` and call the `Loans.update` function after (which will remove the need of calling `Loans.adjustUtilizationWeight`) or record initial values in local vars and reuse.

2023-02-27 12:45 UTC, grandizzy commented on src/libraries/external/Auctions.sol
> +        Loans.adjustUtilizationWeight(
maybe would be nicer to call `Loans.update` and not explicitly `Loans.adjustUtilizationWeight`?
Have to check other implications there though.
Another (nicer) way would be to have this as a free function / helper imported and used each time we touch a borrower / loan.

2023-02-27 12:45 UTC, grandizzy commented on src/libraries/external/Auctions.sol
> +            t0DebtSettled_ + borrower.t0Debt,
I think this should be recorded when function enter as `t0DebtPreaction = borrower.t0Debt` and use it here. Same for `collateralPreaction = borrower.collateral` instead recalculating it as `collateralSettled_ + collateralRemaining_`

2023-02-27 12:45 UTC, grandizzy commented on src/libraries/external/Auctions.sol
> +                  t0BorrowerDebt + t0RepayAmount,
this should be recorded when function enters as `t0DebtPreAction = borrower.toDebt` and used here. Same for next line `borrower.collateral - result_.collateralAmount`

2023-02-27 12:45 UTC, grandizzy commented on src/libraries/external/Auctions.sol
> +        result_ = _takeLoan(
check if `result_` values set prior calling `_takeLoan` are still there after calling the function (I suspect they won't as we rewrite `result_` with what's returned from `_takeLoan`)

2023-02-27 12:45 UTC, grandizzy commented on src/libraries/external/Auctions.sol
> +        result_ = _takeLoan(
same comments as for `bucketTake` function

2023-02-27 12:45 UTC, grandizzy commented on src/libraries/external/BorrowerActions.sol
> +        // result_.t0PoolUtilizationDebtWeight = Loans.adjustUtilizationWeight(
this can be removed

2023-02-27 12:45 UTC, grandizzy commented on src/libraries/external/BorrowerActions.sol
> +            borrower.t0Debt - vars.t0DebtChange,
same as above, if I am not wrong we need to record these values when function enters / borrower balances unaltered and then use them here

2023-02-27 12:45 UTC, grandizzy commented on src/libraries/external/BorrowerActions.sol
> +            borrower.t0Debt + vars.t0RepaidDebt,
same as above, if I am not wrong we need to record these values when function enters / borrower balances unaltered and then use them here

2023-02-27 12:45 UTC, grandizzy commented on src/libraries/internal/Loans.sol
> +        // bool activeBorrower = (borrower_.t0Debt != 0 && borrower_.collateral != 0);
why removing these and then use same `borrower_.t0Debt != 0 && borrower_.collateral != 0` instead `activeBorrower`?

2023-02-27 12:45 UTC, grandizzy commented on src/libraries/internal/Loans.sol
> +        adjustUtilizationWeight(loans_,
can be renamed to `_adjustUtilizationWeight` to reflect is an internal function, params need to be aligned

2023-02-27 12:45 UTC, grandizzy commented on src/libraries/internal/Loans.sol
> +        ) internal {
nit alignment

2023-02-27 12:45 UTC, grandizzy commented on src/libraries/internal/Loans.sol
> +        uint256 utilWeight = loans_.t0PoolUtilizationDebtWeight;
I think the `t0PoolUtilizationDebtWeight` naming should be changed to reflect the fact is loan driven, not sure though what would be a better naming

2023-02-27 12:45 UTC, grandizzy commented on src/libraries/internal/Loans.sol
> +            debtColAccumPreAction = colPreAction != 0 ? Maths.wdiv(Maths.wmul(debtPreAction, debtPreAction), colPreAction): 0;
this line is repeating at 277, I suggest to rewrite code below as

```
        // position is closed, bad debt is created, purely interest update deduct from accumulator
        debtColAccumPreAction = colPreAction != 0 ? Maths.wdiv(Maths.wmul(debtPreAction, debtPreAction), colPreAction): 0;

        if (colPostAction == 0) {
            loans_.t0PoolUtilizationDebtWeight -= debtColAccumPreAction;
        } else {
            // partial take, depositTake, arbTake, settle
            debtColAccumPostAction = Maths.wdiv(Maths.wmul(debtPostAction, debtPostAction), colPostAction);
            
            utilWeight += debtColAccumPostAction;
            utilWeight -= debtColAccumPreAction;

            loans_.t0PoolUtilizationDebtWeight = utilWeight; 
        }
```

2023-02-27 12:45 UTC, grandizzy commented on src/libraries/internal/Loans.sol
> +        if (colPreAction == 0 && debtPreAction != 0) return;
do we need this check here or can we do it early than when this function is executed?

2023-02-27 12:45 UTC, grandizzy commented on src/libraries/internal/Loans.sol
> +        debtColAccumPostAction = Maths.wdiv(Maths.wmul(debtPostAction, debtPostAction), colPostAction);
can you explain what's the rationale of `Maths.wmul(debtPostAction, debtPostAction)` instead `pow 2` `debtPostAction ** 2 / colPostAction`? Same for `debtPreAction` computation

2023-02-27 18:51 UTC, mattcushman commented on src/libraries/external/PoolCommons.sol
> +        int256 tu = (curDebtEma != 0 && curLupColEma != 0) ? int256(Maths.wdiv(curLupColEma, curDebtEma)) : int(Maths.WAD);
Scratch this -- what I had originally is correct.

2023-02-27 19:01 UTC, mattcushman commented on src/libraries/external/PoolCommons.sol
> +                Maths.wmul(poolState_.t0Debt, EMA_7D_RATE_FACTOR) +
The reason we use t0Debt accumulator here is that we can then use the borrower inflator afterwards to track this properly.  It's much easier to act on the t0Debt in the accumulator as that doesn't change with interest rates.  We end up with 2 inflators in the numerator in fact (because we're weighting debt with debt) and one in the denominator (for total debt).  After cancelling one in the numerator with one is denonomintor, we're just left with 1  in the numerator, which we then multiply.

2023-02-27 21:35 UTC, ith-harvey commented on src/libraries/external/PoolCommons.sol
> +                Maths.wmul(poolState_.t0Debt, EMA_7D_RATE_FACTOR) +
Essentially because we multiply the numerator by the inflator we can leave the denominator as t0

2023-02-27 22:58 UTC, ith-harvey commented on src/libraries/internal/Loans.sol
> +        debtColAccumPostAction = Maths.wdiv(Maths.wmul(debtPostAction, debtPostAction), colPostAction);
Was instructed by @mattcushman that `wmul` and `** 2` are not the same opperation. We need to use `wmul` to maintain percision

2023-02-28 06:01 UTC, grandizzy commented on src/libraries/internal/Loans.sol
> +        debtColAccumPostAction = Maths.wdiv(Maths.wmul(debtPostAction, debtPostAction), colPostAction);
hm, not sure how we could loose precision if we do `debtPostAction ** 2 / colPostAction` or `debtPostAction * debtPostAction / colPostAction`, I'd say this has better precision  than a `Maths.wdviv(Maths.wmul)` can you pls elaborate?

2023-02-28 08:54 UTC, ith-harvey commented on src/libraries/internal/Loans.sol
> +        debtColAccumPostAction = Maths.wdiv(Maths.wmul(debtPostAction, debtPostAction), colPostAction);
sure, take the following code for example:
```
console.log("sq prec", 1.234567891011121314 * 1e18 ** 2 / 1.234567891011121314 * 1e18);
console.log("sq prec wmul", Maths.wdiv(Maths.wmul(1.234567891011121314 * 1e18, 1.234567891011121314 * 1e18), 1.234567891011121314 * 1e18 ));
```
and their respective output:
```
  sq prec 1000000000000000000000000000000000000000000000000000000
  sq prec wmul 1234567891011121314
```

As you know the `wmul` isn't actually just multiplying, nor is the `wdiv` just doing division. in the `wmul` case we are actually doing `(x * y + 1e18 / 2) / 1e18` which doesn't blow up the number as we perform a division by `1e18` to maintain precision during the opperation. You're already aware of all of this though so you must mean something differently. Let me know if I missed your question : )

2023-02-28 09:01 UTC, grandizzy commented on src/libraries/internal/Loans.sol
> +        debtColAccumPostAction = Maths.wdiv(Maths.wmul(debtPostAction, debtPostAction), colPostAction);
yeah, sorry, what you compare is not the same :) try
`uint256 x = 1.234567891011121314 * 1e18`
Then compare with `x ** 2 / x`. Also compare with `x * x / x`

2023-02-28 09:42 UTC, ith-harvey commented on src/libraries/internal/Loans.sol
> +        debtColAccumPostAction = Maths.wdiv(Maths.wmul(debtPostAction, debtPostAction), colPostAction);
You are correct, my values we're wrong.
input:
```
uint256 x = 1.234567891011121314 * 1e18;
console.log("sq prec", x ** 2 / x);
console.log("sq prec wmul", Maths.wdiv(Maths.wmul(x, x), x));
```

output:
```
  sq prec 1234567891011121314
  sq prec wmul 1234567891011121314
```

Which would you prefer, I take it back to -> `x ** 2 / y`. @mattcushman feel free to chime in as you had originally requested the change, I'll go with @grandizzy 's method for now.

2023-02-28 09:44 UTC, grandizzy commented on src/libraries/internal/Loans.sol
> +        debtColAccumPostAction = Maths.wdiv(Maths.wmul(debtPostAction, debtPostAction), colPostAction);
IMO rounding nearest as Maths does isn't really relevant for this accumulator, hence saving some gas is preferred

2023-02-28 12:36 UTC, mattcushman commented on src/libraries/internal/Loans.sol
> +        debtColAccumPostAction = Maths.wdiv(Maths.wmul(debtPostAction, debtPostAction), colPostAction);
I'm good with doing it as @grandizzy suggests -- the original code I commented on I think didn't have the division in the denominator, and just did the **2 in the numerator, which would interfere with the WAD scaling.

One point that we need to ensure however: however we increment the global accumulator, we need to ensure that we decrement it exactly the same way.  Otherwise we will start to stray from the invariant that the accumulator is equal to the sum of t0debt^2/collateral across all loans with collateral>0.

2023-02-28 12:46 UTC, ith-harvey commented on src/libraries/external/Auctions.sol
> +        result_ = _takeLoan(
Checked and values are the same before as after... This is because of the `result_` value that is taken in as an arg on line 519, added to then returned.

2023-02-28 19:53 UTC, ith-harvey commented on src/libraries/internal/Loans.sol
> +        uint256 utilWeight = loans_.t0PoolUtilizationDebtWeight;
... yeah it's loan driven (really borrower driven more accurately) but yet the accumulator or weight is used at the pool level in our interest calc.

How about `t0BorrowerUtilizationWeight`?

2023-02-28 19:55 UTC, grandizzy commented on src/libraries/internal/Loans.sol
> +        uint256 utilWeight = loans_.t0PoolUtilizationDebtWeight;
does it matter that is t0 or borrower's / pools? How about `utilizationWeight`?

2023-02-28 20:03 UTC, ith-harvey commented on src/libraries/external/Auctions.sol
> +        result_ = _takeLoan(
see `bucketTake` response

2023-02-28 20:04 UTC, ith-harvey commented on src/libraries/external/BorrowerActions.sol
> +        // result_.t0PoolUtilizationDebtWeight = Loans.adjustUtilizationWeight(
done

2023-02-28 20:06 UTC, ith-harvey commented on src/libraries/internal/Loans.sol
> +        uint256 utilWeight = loans_.t0PoolUtilizationDebtWeight;
I think `t0` was suggested by Matt since the value will be in `t0` terms... I'm fine with `t0UtilizationWeight`

2023-02-28 20:14 UTC, grandizzy commented on src/libraries/internal/Loans.sol
> +        uint256 utilWeight = loans_.t0PoolUtilizationDebtWeight;
👍

2023-03-01 18:30 UTC, ith-harvey commented on tests/forge/ERC20Pool/ERC20PoolBorrow.t.sol
> +                targetUtilization:    5.236283713605985205 * 1e18,
Have a large bump here... from `13% -> 523%`

2023-03-01 18:32 UTC, ith-harvey commented on tests/forge/ERC721Pool/ERC721PoolBorrow.t.sol
> +                targetUtilization:    11.959773039106476725 * 1e18,
go from `16% -> 119%`

2023-03-01 18:33 UTC, ith-harvey commented on tests/forge/ERC20Pool/ERC20PoolInterestRateAndEMAs.t.sol
> +                targetUtilization:    8_170_210.475701867592667419 * 1e18,
Got to be incorrect `9% -> 817,021,047%`

2023-03-01 21:26 UTC, ith-harvey commented on tests/forge/utils/DSTestPlus.sol
> +        (uint256 curLupColEma, uint256 curDebtEma) = _pool.emasInfo();
switched to match order that the `tu` calculation uses -> `curLupColEma / curDebtEma`

2023-03-02 16:13 UTC, ith-harvey commented on src/libraries/internal/Loans.sol
> +        adjustUtilizationWeight(loans_,
done

2023-03-02 16:14 UTC, ith-harvey commented on src/libraries/internal/Loans.sol
> +        // bool activeBorrower = (borrower_.t0Debt != 0 && borrower_.collateral != 0);
a dirty way to get around stack to deep... seeing if I can come up with somthing more elegant as I think this variable does help code readability.

2023-03-02 18:54 UTC, ith-harvey commented on src/libraries/external/Auctions.sol
> +                  t0BorrowerDebt + t0RepayAmount,
Gives me stack too deep, do you want me to play with creating a new struct in this method called `vars` to see if that will allow these variables to exist in this functions scope?

2023-03-03 00:46 UTC, ith-harvey commented on src/libraries/internal/Loans.sol
> +            debtColAccumPreAction = colPreAction != 0 ? Maths.wdiv(Maths.wmul(debtPreAction, debtPreAction), colPreAction): 0;
agree, updated

2023-03-03 00:47 UTC, ith-harvey commented on src/libraries/internal/Loans.sol
> +        uint256 utilWeight = loans_.t0PoolUtilizationDebtWeight;
agree, updated

2023-03-03 01:01 UTC, ith-harvey commented on src/libraries/external/Auctions.sol
> +            t0DebtSettled_ + borrower.t0Debt,
happy to do this, note that I will be introducing a vars struct locally in this method just for this purpose as I keep fighting with `stack too deep`.

Open to any other suggestion that makes this possible too

2023-03-03 01:04 UTC, ith-harvey commented on src/libraries/external/Auctions.sol
> +        Loans._adjustUtilizationWeight(
was thinking about making this a `loans.update` call...

Truth is we only need to update `borrower.t0Debt` here. Due to the little amount of updating needed I think a `loans.update` may be overkill. Although if you feel like we should make the change for readability @grandizzy happy to make it.

2023-03-03 01:44 UTC, ith-harvey commented on src/libraries/external/Auctions.sol
> +            borrower.t0Debt,
fixed with a kick vars struct

2023-03-03 01:44 UTC, ith-harvey commented on src/libraries/external/Auctions.sol
> +        Loans.adjustUtilizationWeight(
fixed this by performing a `loans.update` instead.

2023-03-03 01:45 UTC, ith-harvey commented on src/libraries/internal/Loans.sol
> +        ) internal {
resolved

2023-03-03 19:59 UTC, grandizzy commented
will be tracked with https://github.com/ajna-finance/contracts/pull/644

2023-03-03 19:59 UTC, grandizzy commented
will be tracked in https://github.com/ajna-finance/contracts/pull/644

2023-03-03 19:59 UTC, closed without merging