LPS and Exchange Rate as WADs - Sherlock 133 & 83
ajna-finance/ajna-core pull request #606
Opened 2023-02-10 21:48 UTC by grandizzy

# Description of change
## High level
* Keep LPs and calculate exchange rate as WADs rather than RAYs
  * In order to avoid rounding issues and have code consistency this PR change the precision for LPs and exchange rate from RAYs to WADs. Several issues revealed by invariant tests are solved by changing this precision.

# Description of bug or vulnerability and solution
* Invariants for exchange rate failing due to rounding issues
* Theoretically an attacker could manipulate a bucket exchange rate by depositing large amounts of quote tokens
- changed LPs and exchange rate to WAD. Used `Maths.wmul` and `Maths.wdiv` consistently in LP calculations. Used `Buckets.collateralToLPs` and `Buckets.getExchangeRate` and LPs calculated always for scaled deposits.
- (if remaining collateral in bucket is not 0 but LPs and deposit of bucket are 0) on remove collateral transfer remaining dust collateral (not backed by any LP) to redeemer
- add BucketBankruptcy check in plain removeCollateral and in moveQuoteToken (Sherlock 133  https://github.com/sherlock-audit/2023-01-ajna-judging/issues/133 and Sherlock 83 https://github.com/sherlock-audit/2023-01-ajna-judging/issues/83)
- minor gas improvement: do not update lender lps when bucket goes bankrupt (as they will be reset to 0 anyways)
- remove RAY related maths and update descriptions
- updated tests, taking into account that lender LPs are 0 when bucket goes bankrupt. Removed infamous 1 wei rounding issue.
- code coverage improved (lines should have been 100% without the extra safety check to revert on NFT not rounded take. branches still below mostly because rewards manager)
```
Lines: 		1520 	1521 	99.9 %
Functions: 	219 	219 	100.0 %
Branches: 	428 	446 	96.0 %
```

NOTE: there are 4 tests failing in `tearDown` sequence due to dust deposit after auctions are settled.

# Contract size
## Pre Change
<PASTE_OUTPUT_HERE>
## Post Change
<PASTE_OUTPUT_HERE>

# Gas usage
## Pre Change
<PASTE_OUTPUT_HERE>
## Post Change
<PASTE_OUTPUT_HERE>

2023-02-10 22:56 UTC, EdNoepel commented on src/libraries/external/LenderActions.sol
> +        (removedAmount_, redeemedLPs_, scaledRemaining) = _removeMaxDeposit(
Why no longer working with unscaled quantity?

2023-02-10 22:56 UTC, EdNoepel commented on src/libraries/internal/Maths.sol
>      function rayToWad(uint256 x) internal pure returns (uint256) {
Assume `rayToWad` is no longer needed.

2023-02-10 22:56 UTC, EdNoepel commented on tests/forge/ERC20Pool/ERC20DSTestPlus.sol
> -            assertEq(lenderLpBalance, 0);
Why skip this validation?  Would make more sense to remove blank line 91, such that this validates the `removeCollateral` call above.

2023-02-10 23:00 UTC, grandizzy commented on tests/forge/ERC20Pool/ERC20DSTestPlus.sol
> -            assertEq(lenderLpBalance, 0);
the validation doesn't work properly as there are cases where bucket goes bankrupt and lender lp balance is zeroed out. The line after this one checks lender balance properly, that is accounting if bucket is bankrupt

2023-02-10 23:01 UTC, grandizzy commented on src/libraries/internal/Maths.sol
>      function rayToWad(uint256 x) internal pure returns (uint256) {
it is still used by `_reserveAuctionPrice` helper function

2023-02-10 23:06 UTC, grandizzy commented on src/libraries/external/LenderActions.sol
> +        (removedAmount_, redeemedLPs_, scaledRemaining) = _removeMaxDeposit(
if not consistent in the way we calculate LPs then rounding issues are introduced, hence it is desired to use same approach. While changing this I noticed in tests that for example when LPs here are calculated for scaled amount but LPs in auctions were still awarded for unscaled, tests were failing with leaving dust amounts in buckets.
All parts of the code are now calculating LPs using scaled amounts

2023-02-11 20:03 UTC, mattcushman approved these changes
Overall I think it's a great simplificatpoin to use WADs everywhere and get rid of RAYs.  Also great that it somewhat mysteriously helps stabilize the exchange rate in some cases.


My only real concern is that we should make sure that we are being careful in translating between scaled and unscaled values.  In particular, I highlighted a place in lenderActions where we make a special case for withdrawing all deposit in a bucket, but when we actually remove from the bucket I fear that it's possible to either over or under withdraw, due to rounding.

The more I consider this, the more I like the idea of just keeping the system robust to these issues, rather than trying to avoid them altogether.  E.G. allow a bucket to recover when it has LPs==0, by allowing lenders to add to it with exchange rate 1.0, which I believe we do now.

The remaining concern would be if, in those cases, one could end up with a spurious underflow revert when trying to withdraw all.

2023-02-11 20:03 UTC, mattcushman commented on src/libraries/external/LenderActions.sol
> +        uint256 unscaledRemovedAmount = Maths.wdiv(removedAmount_, depositScale);
This sort of thing makes me very nervous.  We are computing unscaledRemovedAmount as removeAmount/scale.  If we are redeeming the entire bucket, this is removedAmount = (unscaledDepositAvailable*scale)/scale.  

But I fear that this latter quantity might not be unscaledDepositAvailable if scale !=1 due to rounding issues.   If it's too large get get an underflow, if it's too small we leave dust even though were trying to redeem all LPs

2023-02-11 20:03 UTC, mattcushman commented on tests/forge/ERC20Pool/ERC20PoolLiquidationsSettle.t.sol
> +            index:        _i9_72,
im a little confused about this one

2023-02-11 20:03 UTC, mattcushman commented on tests/forge/ERC721Pool/ERC721DSTestPlus.sol
> +                        depositRequired = Maths.wmul(1e18 - fractionOfNftRemaining, price);
interesting...

2023-02-11 20:08 UTC, grandizzy commented on tests/forge/ERC20Pool/ERC20PoolLiquidationsSettle.t.sol
> +            index:        _i9_72,
that's the unit test for move quote token that exercise the bucket bankruptcy logic

2023-02-11 20:32 UTC, ith-harvey commented on src/libraries/external/LenderActions.sol
>          // abandon dust amounts upon last withdrawal
I would change this to: `give dust amounts to the reserve`. abandoning would be leaving in the bucket, the reality is we are zeroing out the bucket but leaving the QT in the contract.

2023-02-11 20:33 UTC, ith-harvey commented on src/libraries/external/LenderActions.sol
>          // abandon dust amounts upon last withdrawal
I like this... I was initially worried that by leaving a little bit of QT in the bucket (which we are not doing) we would give malicious actors the chance to perform bucket takes with the dust... which wouldn't be good : (

2023-02-11 20:59 UTC, grandizzy commented on src/libraries/external/LenderActions.sol
> +        uint256 unscaledRemovedAmount = Maths.wdiv(removedAmount_, depositScale);
here's guard against underflow https://github.com/ajna-finance/contracts/pull/606/commits/a8b867d922ee51fe4475835cbf5cc2829f885fd6

2023-02-11 21:04 UTC, ith-harvey commented on src/libraries/external/LenderActions.sol
> +        if (bucketLPs == 0 && bucketDeposit == 0) {
This If statement here defends against a scenario where there is only one lender in the bucket... What if there were two lenders?

2023-02-11 21:06 UTC, ith-harvey commented on src/libraries/external/LenderActions.sol
> +            collateralAmount_ = Maths.wmul(Maths.wdiv(lenderLpBalance, requiredLPs), bucketCollateral);
This is the line that I would like confirmation on... In the case where there is only one NFT in the pool and an "attacker" has deposited just enough QT to get 1 LPB in the bucket... can precision loss occur here where that one NFT cannot be merged because it will never fully constitute a whole number as a little bit of collateral will be left in the bucket?

2023-02-11 21:06 UTC, grandizzy commented on src/libraries/external/LenderActions.sol
> +        if (bucketLPs == 0 && bucketDeposit == 0) {
> This If statement here defends against a scenario where there is only one lender in the bucket... What if there were two lenders?

`bucketLPs` is the accumulator for bucket, so for all lenders

2023-02-11 21:29 UTC, mattcushman commented on src/libraries/external/LenderActions.sol
> +            collateralAmount_ = Maths.wmul(Maths.wdiv(lenderLpBalance, requiredLPs), bucketCollateral);
i see... excellent question.  i think it would be ok though as someone would always be depositing some QT to get LPB.  the place to check would be in mergeandremove

2023-02-11 22:54 UTC, EdNoepel commented on tests/forge/ERC721Pool/ERC721DSTestPlus.sol
> +                        depositRequired = Maths.wmul(1e18 - fractionOfNftRemaining, price);
My initial suspicion was that, with RAYs, the `fractionOfNftRemaining` provided a more precise number, requiring the workaround.  However, that didn't make sense, as the collateral amount was always stored as a WAD.

2023-02-11 23:59 UTC, dmitriia requested changes
It has become `collateralAmount_ = Maths.wmul(Maths.wdiv(lenderLpBalance, requiredLPs), bucketCollateral)` from `collateralAmount_ = Maths.wmul(Maths.rrdivw(lenderLpBalance,lpsForAllCollateral), bucketCollateral)`, it looks like it needs to be amended as:

https://github.com/ajna-finance/contracts/blob/a5d4fb13b4f2d1248a7f03de91a48cf6ec268452/src/libraries/external/LenderActions.sol#L656-L663

```solidity
        // limit withdrawal by the lender's LPB
        if (requiredLPs <= lenderLpBalance) {
            // withdraw collateralAmount_ as is
            lpAmount_ = requiredLPs;
        } else {
            lpAmount_         = lenderLpBalance;
-           collateralAmount_ = Maths.wmul(Maths.wdiv(lenderLpBalance, requiredLPs), bucketCollateral);
+           collateralAmount_ = Maths.wmul(Maths.wdiv(lenderLpBalance, requiredLPs), collateralAmount_);
        }
```

As `requiredLPs` is needed for `collateralAmount_`, `lenderLpBalance` is needed for `collateralAmount_ * (lenderLpBalance / requiredLPs)` as required LPs formula is linear in terms of the collateral asked.


Also, this part looks redundant as if `redeemedLPs_ == params_.bucketLPs` then `scaledRemaining_` is already zero and `removedAmount_ == scaledDepositAvailable`:

https://github.com/ajna-finance/contracts/blob/a5d4fb13b4f2d1248a7f03de91a48cf6ec268452/src/libraries/external/LenderActions.sol#L741-L752

```solidity
        // If clearing out the bucket deposit, ensure it's zeroed out
        if (redeemedLPs_ == params_.bucketLPs) {
            removedAmount_ = scaledDepositAvailable;
        }

        scaledRemaining_ = scaledDepositAvailable - removedAmount_;

-       // abandon dust amounts upon last withdrawal
-       if (scaledRemaining_ < params_.dustLimit && redeemedLPs_ == params_.bucketLPs) {
-           removedAmount_   = scaledDepositAvailable;
-           scaledRemaining_ = 0;
-       }
```
That is, of course, optional.

All the rest looks ok to me.

2023-02-12 00:06 UTC, dmitriia commented on src/libraries/external/LenderActions.sol
> +            collateralAmount_ = Maths.wmul(Maths.wdiv(lenderLpBalance, requiredLPs), bucketCollateral);
Didn't saw the comment, stumbled upon the same line. Doesn't it look like just a substitution mistake?

It is now assumed that `requiredLPs` is for whole `bucketCollateral`, which is not the case, `requiredLPs` is for `collateralAmount_ `.

2023-02-12 00:47 UTC, EdNoepel commented on src/libraries/external/LenderActions.sol
> +        (removedAmount_, redeemedLPs_, scaledRemaining) = _removeMaxDeposit(
Would appreciate @mattcushman 's thoughts on this.
Would it be better to instead use unscaled amounts for LPs in auctions?

2023-02-12 02:58 UTC, MikeHathaway reviewed
Other than the few comments made by others, this LGTM. The additional simplicity of having everything in terms of `WAD`s is a big improvement

2023-02-12 05:31 UTC, grandizzy commented on src/libraries/external/LenderActions.sol
> +            collateralAmount_ = Maths.wmul(Maths.wdiv(lenderLpBalance, requiredLPs), bucketCollateral);
Yes, that makes sense, it is changed with https://github.com/ajna-finance/contracts/pull/606/commits/de7f9406d166bf03c1dc64adcdb6eba3637cc5e9. Unclear though why no unit tests changed but it looks right to me, @mattcushman would appreciate your validation

2023-02-12 05:31 UTC, grandizzy commented
> It has become `collateralAmount_ = Maths.wmul(Maths.wdiv(lenderLpBalance, requiredLPs), bucketCollateral)` from `collateralAmount_ = Maths.wmul(Maths.rrdivw(lenderLpBalance,lpsForAllCollateral), bucketCollateral)`, it looks like it needs to be amended as:
> 
> https://github.com/ajna-finance/contracts/blob/a5d4fb13b4f2d1248a7f03de91a48cf6ec268452/src/libraries/external/LenderActions.sol#L656-L663
> 
> ```solidity
>         // limit withdrawal by the lender's LPB
>         if (requiredLPs <= lenderLpBalance) {
>             // withdraw collateralAmount_ as is
>             lpAmount_ = requiredLPs;
>         } else {
>             lpAmount_         = lenderLpBalance;
> -           collateralAmount_ = Maths.wmul(Maths.wdiv(lenderLpBalance, requiredLPs), bucketCollateral);
> +           collateralAmount_ = Maths.wmul(Maths.wdiv(lenderLpBalance, requiredLPs), collateralAmount_);
>         }
> ```
> 
> As `requiredLPs` is needed for `collateralAmount_`, `lenderLpBalance` is needed for `collateralAmount_ * (lenderLpBalance / requiredLPs)` as required LPs formula is linear in terms of the collateral asked.
> 
> Also, this part looks redundant as if `redeemedLPs_ == params_.bucketLPs` then `scaledRemaining_` is already zero and `removedAmount_ == scaledDepositAvailable`:
> 
> https://github.com/ajna-finance/contracts/blob/a5d4fb13b4f2d1248a7f03de91a48cf6ec268452/src/libraries/external/LenderActions.sol#L741-L752
> 
> ```solidity
>         // If clearing out the bucket deposit, ensure it's zeroed out
>         if (redeemedLPs_ == params_.bucketLPs) {
>             removedAmount_ = scaledDepositAvailable;
>         }
> 
>         scaledRemaining_ = scaledDepositAvailable - removedAmount_;
> 
> -       // abandon dust amounts upon last withdrawal
> -       if (scaledRemaining_ < params_.dustLimit && redeemedLPs_ == params_.bucketLPs) {
> -           removedAmount_   = scaledDepositAvailable;
> -           scaledRemaining_ = 0;
> -       }
> ```
> 
> That is, of course, optional.
> 
> All the rest looks ok to me.

changes made with https://github.com/ajna-finance/contracts/pull/606/commits/de7f9406d166bf03c1dc64adcdb6eba3637cc5e9

2023-02-12 07:38 UTC, mattcushman approved these changes
lgtm

2023-02-12 08:07 UTC, mattcushman approved these changes

2023-02-12 08:07 UTC, mattcushman commented on src/libraries/external/LenderActions.sol
> +        (removedAmount_, redeemedLPs_, scaledRemaining) = _removeMaxDeposit(
i think its ok.  this seems to work well and we've made everything more robust to dust anyway

2023-02-12 09:05 UTC, merged

2023-02-12 14:01 UTC, dmitriia reviewed
Looks ok