check for bucket bankruptcy in rewards manager
ajna-finance/ajna-core pull request #630
Opened 2023-02-22 21:44 UTC by MikeHathaway

# Description of change
## High level
* Handle bankrupt buckets in RewardManager.sol
  * Check that a staker isn't attempting to claim rewards for an NFT that was staked in a bucket that was bankrupt. If the bucket was bankrupt that staker must memorialize additional LP that earns interest to earn rewards.
  * Check that a bucket's exchange rate didn't decrease due to bad debt. If the exchange rate decreases then there is an underflow error in the existing logic.

# Gas usage
## Pre Change
```
| src/RewardsManager.sol:RewardsManager contract |                 |        |        |         |         |
|------------------------------------------------|-----------------|--------|--------|---------|---------|
| Deployment Cost                                | Deployment Size |        |        |         |         |
| 1666799                                        | 8573            |        |        |         |         |
| Function Name                                  | min             | avg    | median | max     | # calls |
| calculateRewards                               | 4229            | 37191  | 20359  | 179097  | 41      |
| claimRewards                                   | 523             | 89269  | 86536  | 406091  | 40      |
| getBucketStateStakeInfo                        | 728             | 4725   | 4728   | 4728    | 44334   |
| getStakeInfo                                   | 683             | 683    | 683    | 683     | 30      |
| onERC721Received                               | 914             | 914    | 914    | 914     | 22      |
| stake                                          | 2409            | 524536 | 567315 | 1066207 | 23      |
| unstake                                        | 544             | 171236 | 128566 | 394546  | 10      |
| updateBucketExchangeRatesAndClaim              | 15821           | 266303 | 181046 | 529654  | 35      |
```

## Post Change with inline bucket bankruptcy check
```
| src/RewardsManager.sol:RewardsManager contract |                 |        |        |         |         |
|------------------------------------------------|-----------------|--------|--------|---------|---------|
| Deployment Cost                                | Deployment Size |        |        |         |         |
| 1658807                                        | 8540            |        |        |         |         |
| Function Name                                  | min             | avg    | median | max     | # calls |
| calculateRewards                               | 4140            | 99357  | 42950  | 536072  | 45      |
| claimRewards                                   | 611             | 138425 | 118675 | 763159  | 44      |
| getBucketStateStakeInfo                        | 750             | 4748   | 4750   | 4750    | 59112   |
| getStakeInfo                                   | 683             | 683    | 683    | 683     | 34      |
| stake                                          | 2386            | 518692 | 594090 | 1160275 | 27      |
| unstake                                        | 522             | 190066 | 148060 | 452366  | 12      |
| updateBucketExchangeRatesAndClaim              | 15883           | 277967 | 204484 | 543984  | 31      |
```
## Post Change with `getPositionIndexesFiltered`
```
| src/RewardsManager.sol:RewardsManager contract |                 |        |        |         |         |
|------------------------------------------------|-----------------|--------|--------|---------|---------|
| Deployment Cost                                | Deployment Size |        |        |         |         |
| 1629557                                        | 8387            |        |        |         |         |
| Function Name                                  | min             | avg    | median | max     | # calls |
| calculateRewards                               | 38552           | 89642  | 56275  | 244508  | 25      |
| claimRewards                                   | 611             | 110885 | 97346  | 471585  | 24      |
| getBucketStateStakeInfo                        | 750             | 4748   | 4750   | 4750    | 59112   |
| getStakeInfo                                   | 683             | 683    | 683    | 683     | 14      |
| stake                                          | 2386            | 512410 | 594112 | 1119518 | 26      |
| unstake                                        | 522             | 178296 | 145950 | 421024  | 12      |
| updateBucketExchangeRatesAndClaim              | 15883           | 311968 | 315432 | 529206  | 22      |
```

2023-02-23 09:53 UTC, grandizzy commented on src/RewardsManager.sol
> +            if (positionManager.isPositionBucketBankrupt(tokenId_, bucketIndex)) {
cannot we just use the existing `PositionManager.getLPs` which checks the bucket bankruptcy time?

2023-02-23 17:35 UTC, MikeHathaway commented on src/RewardsManager.sol
> +            if (positionManager.isPositionBucketBankrupt(tokenId_, bucketIndex)) {
We could but that would be slightly more computation (same calculations + an additional mload + check if == 0), and i was thinking it would be useful to have the `isPositionBucketBankrupt` method so someone can determine if it's bankrupt as opposed to just not present in a bucket (outside of the rewards context)

2023-02-27 10:55 UTC, grandizzy commented on src/RewardsManager.sol
> +            if (positionManager.isPositionBucketBankrupt(tokenId_, bucketIndex)) {
kk. I think here would be more preferable to go only with the happy path instead increment and continue, as in
```

            // calculate rewards only for healthy / solvent buckets
            if (!positionManager.isPositionBucketBankrupt(tokenId_, bucketIndex))
            execute rewards logic
```
execute rewards logic

2023-02-28 18:31 UTC, MikeHathaway commented on src/RewardsManager.sol
> +            if (positionManager.isPositionBucketBankrupt(tokenId_, bucketIndex)) {
Updated accordingly

2023-02-28 18:44 UTC, MikeHathaway commented on tests/forge/RewardsManager.t.sol
> +        //     lpBalance:    10_000.000000000000000000 * 1e18,
lpBalance assertion here is continuously failing for some reason... if 10k it expects 5k, and at 5k it expects 10k. Unclear why this is happening

2023-02-28 18:57 UTC, grandizzy requested changes
looking some more at the way is implemented - there's a big improvement we can do here by removing `PositionManager.isPositionBucketBankrupt` function and external calling it while looping through buckets:
- `_calculateNextEpochRewards` function is called from `_calculateAndClaimRewards` and `calculateRewards` functions with the indexes obtain from `PositionManager.getPositionIndexes(tokenId_)`
- instead using existing `PositionManager.getPositionIndexes(tokenId_)` call a different function within `Positionmanager` (or the same passing a bool flag to filter out insolvent buckets) that filters out bankrupt buckets. This way `RewardsManager` obtain only indexes of healthy buckets from `PositionManager`. `PositionManager.isPositionBucketBankrupt` function is no longer needed
- keep the same logic when calculating the rewards and remove external calls to `PositionManager` for checking if bucket is healthy

2023-02-28 19:06 UTC, MikeHathaway commented
> looking some more at the way is implemented - there's a big improvement we can do here by removing `PositionManager.isPositionBucketBankrupt` function and external calling it while looping through buckets:
> 
>     * `_calculateNextEpochRewards` function is called from `_calculateAndClaimRewards` and `calculateRewards` functions with the indexes obtain from `PositionManager.getPositionIndexes(tokenId_)`
> 
>     * instead using existing `PositionManager.getPositionIndexes(tokenId_)` call a different function within `Positionmanager` (or the same passing a bool flag to filter out insolvent buckets) that filters out bankrupt buckets. This way `RewardsManager` obtain only indexes of healthy buckets from `PositionManager`. `PositionManager.isPositionBucketBankrupt` function is no longer needed
> 
>     * keep the same logic when calculating the rewards and remove external calls to `PositionManager` for checking if bucket is healthy

Good call, that makes sense to me. I will update accordingly. Is there any use case you can think of for having `getPositionIndexes` not return filtered indexes for bankrupt buckets?

2023-02-28 19:08 UTC, grandizzy commented
> > looking some more at the way is implemented - there's a big improvement we can do here by removing `PositionManager.isPositionBucketBankrupt` function and external calling it while looping through buckets:
> > ```
> > * `_calculateNextEpochRewards` function is called from `_calculateAndClaimRewards` and `calculateRewards` functions with the indexes obtain from `PositionManager.getPositionIndexes(tokenId_)`
> > 
> > * instead using existing `PositionManager.getPositionIndexes(tokenId_)` call a different function within `Positionmanager` (or the same passing a bool flag to filter out insolvent buckets) that filters out bankrupt buckets. This way `RewardsManager` obtain only indexes of healthy buckets from `PositionManager`. `PositionManager.isPositionBucketBankrupt` function is no longer needed
> > 
> > * keep the same logic when calculating the rewards and remove external calls to `PositionManager` for checking if bucket is healthy
> > ```
> 
> Good call, that makes sense to me. I will update accordingly. Is there any use case you can think of for having `getPositionIndexes` not return filtered indexes for bankrupt buckets?

No, I don't see any scenario to do that, so yeah, probably better to just filter out bankrupt buckets

2023-02-28 20:01 UTC, MikeHathaway commented
> > > looking some more at the way is implemented - there's a big improvement we can do here by removing `PositionManager.isPositionBucketBankrupt` function and external calling it while looping through buckets:
> > > ```
> > > * `_calculateNextEpochRewards` function is called from `_calculateAndClaimRewards` and `calculateRewards` functions with the indexes obtain from `PositionManager.getPositionIndexes(tokenId_)`
> > > 
> > > * instead using existing `PositionManager.getPositionIndexes(tokenId_)` call a different function within `Positionmanager` (or the same passing a bool flag to filter out insolvent buckets) that filters out bankrupt buckets. This way `RewardsManager` obtain only indexes of healthy buckets from `PositionManager`. `PositionManager.isPositionBucketBankrupt` function is no longer needed
> > > 
> > > * keep the same logic when calculating the rewards and remove external calls to `PositionManager` for checking if bucket is healthy
> > > ```
> > 
> > 
> > Good call, that makes sense to me. I will update accordingly. Is there any use case you can think of for having `getPositionIndexes` not return filtered indexes for bankrupt buckets?
> 
> No, I don't see any scenario to do that, so yeah, probably better to just filter out bankrupt buckets

Needed the unfiltered method for deleting positions in `unstake`. Also, for updating exchange rates I figured we may want to update all bucket exchange rates even if that bucket went bankrupt (if we don't want to do this we might be able to remove another getPositionIndexes<>() call from `_claimRewards` and pass the filtered index to `_calculateAndClaimRewards`).

2023-02-28 20:13 UTC, grandizzy reviewed
Looks better! Wonder how gas is affected by this change comparing with prev approach.  Have comment / suggestion of just using array push instead the current way of populating filtered indexes array

2023-02-28 20:13 UTC, grandizzy commented on tests/forge/RewardsManager.t.sol
> +        //     lpBalance:    10_000.000000000000000000 * 1e18,
Does this still happen?

2023-02-28 20:13 UTC, grandizzy commented on src/PositionManager.sol
> +        filteredIndexes_ = new uint256[](indexesLength);
Wouldn't be easier / cleaner just to push the index in filtered array instead creating with size and then resize using assembly?

2023-02-28 20:16 UTC, MikeHathaway commented on src/PositionManager.sol
> +        filteredIndexes_ = new uint256[](indexesLength);
It would but unfortunately you can't push to an array in memory, only storage. Since the size changes I couldn't simply predefine array size and update the indexes. This approach saves us from a double loop of 1) counting filtered array size, 2) populate filtered array

2023-02-28 20:23 UTC, grandizzy commented on src/PositionManager.sol
> +        filteredIndexes_ = new uint256[](indexesLength);
ah, I see, missed that. 👍

2023-02-28 20:26 UTC, MikeHathaway commented on tests/forge/RewardsManager.t.sol
> +        //     lpBalance:    10_000.000000000000000000 * 1e18,
Yup, fails every time even when I change the value to expected. No idea what's going on there since it should be deterministic

2023-02-28 20:37 UTC, MikeHathaway commented
> Looks better! Wonder how gas is affected by this change comparing with prev approach. Have comment / suggestion of just using array push instead the current way of populating filtered indexes array

There's definitely significant gas savings from the approach you recommended doing the filtering in `PositionManager` vs inline. Added an additional gas report to the intro comment for comparison. The gas savings should be especially pronounced if someone is claiming rewards for many buckets, with some of those being bankrupt

2023-02-28 20:48 UTC, grandizzy reviewed
LGTM, would like to understand why the failing test before approving, I will try debugging it

2023-03-01 04:43 UTC, grandizzy commented on tests/forge/RewardsManager.t.sol
> +        //     lpBalance:    10_000.000000000000000000 * 1e18,
that's because `_assertBucket` calls `_validateBucketLp` to make sure LPs of users is the same as LPs in bucket, however it does not account the LPs of `PositionManager` (that is LPs transferred when memorializing positions)

2023-03-01 05:13 UTC, grandizzy commented on tests/forge/RewardsManager.t.sol
> +        //     lpBalance:    10_000.000000000000000000 * 1e18,
that's fixed now with https://github.com/ajna-finance/contracts/pull/630/commits/e89a32bab8fe0b79e856a231c4ec120590a6ce55

2023-03-01 05:15 UTC, grandizzy approved these changes
LGTM

2023-03-02 18:56 UTC, EdNoepel reviewed
This adds a bit of work to `claimRewards`.  Is there an issue here where an attacker makes a tiny deposit in all buckets (collateral above HPB, quote token below), memorializes and transfers the position to someone else's NFT?  If possible, they could force `claimRewards` to iterate through all 7388 buckets.  Could that be done without exceeding the block limit?

2023-03-03 03:44 UTC, MikeHathaway commented
> This adds a bit of work to `claimRewards`. Is there an issue here where an attacker makes a tiny deposit in all buckets (collateral above HPB, quote token below), memorializes and transfers the position to someone else's NFT? If possible, they could force `claimRewards` to iterate through all 7388 buckets. Could that be done without exceeding the block limit?

I think the main defense to this attack is the massive gas cost it would impose upon the attacker. That being said, I'm not sure how we could prevent this and it seems like an attack vector on the existing implementation. It seems like the main fix would involve requiring the new owner to *accept* the transferred LP tokens somehow.

2023-03-03 04:54 UTC, grandizzy commented
> > This adds a bit of work to `claimRewards`. Is there an issue here where an attacker makes a tiny deposit in all buckets (collateral above HPB, quote token below), memorializes and transfers the position to someone else's NFT? If possible, they could force `claimRewards` to iterate through all 7388 buckets. Could that be done without exceeding the block limit?
> 
> I think the main defense to this attack is the massive gas cost it would impose upon the attacker. That being said, I'm not sure how we could prevent this and it seems like an attack vector on the existing implementation. It seems like the main fix would involve requiring the new owner to _accept_ the transferred LP tokens somehow.

Positions can be transferred by transferring the position NFT (hence is up to the new owner if they want to redeem / stake) or by calling the transferLP function. Besides the gas that attacker should pay for transfer we also have the notion of approved transferor now so one should explicitly approve the attacker address as transferor for this to happen.

2023-03-04 21:07 UTC, EdNoepel approved these changes
LGTM

2023-03-04 21:27 UTC, merged

2023-03-06 17:11 UTC, dmitriia reviewed
Looks ok