Move quote token
ajna-finance/ajna-core pull request #65
Opened 2022-04-05 11:38 UTC by grandizzy

- create target bucket if not initialized
- move tokens with up reallocation from lower to upper bucket
- update lup if lup in (from, to) bucket interval

2022-04-06 04:58 UTC, MikeHathaway commented on src/libraries/Buckets.sol
>      function reallocateUp(
Does `reallocateDown` need to be modified as well with explicit passing of the `fromBucket` and `toBucket`?

2022-04-06 05:05 UTC, MikeHathaway approved these changes
Question about the reallocate interface, but generally LGTM

2022-04-06 06:50 UTC, grandizzy commented on src/libraries/Buckets.sol
>      function reallocateUp(
I don't think so, only `reallocateUp` is bounded by a fom and to bucket, `reallocateDown` starts from a bucket and reallocate as long as there is debt to reallocate

2022-04-07 20:57 UTC, EdNoepel requested changes
The reallocation logic doesn't seem right.  When moving the price down, we must allocate that debt to the HUP downward.

Here are some truth tables to foster discussion:
| moving down		| from bucket utilized	   | from bucket unutilized |
| :--------------------| :-----------------------| :----------------------|
| to bucket utilized	| reallocateUp(to,from)   | not possible           |
| to bucket unutilized	| reallocateDown(from,lup)| no reallocation        |

| moving up		| from bucket utilized	| from bucket unutilized |
| :--------------------| :--------------------| :----------------------|
| to bucket utilized	| reallocateUp(from,to)| reallocateUp(lup,to)   |
| to bucket unutilized	| not possible		| no reallocation        |

I recommend we implement this in the simulator, such that we can examine the state of the book while interacting with it, to ensure we've gotten the reallocation logic right.

2022-04-07 20:57 UTC, EdNoepel commented on src/libraries/Buckets.sol
> +        if (_fromPrice > _toPrice) {
This is going to cause interest accumulation regardless of whether the bucket is utilized.  We shouldn't need to reallocate anything if neither bucket is utilized.

2022-04-26 11:44 UTC, grandizzy commented
will be addressed in PR #90

2022-04-26 11:44 UTC, closed without merging