Update lender deposit time only when non-zero lps are added
ajna-finance/ajna-core pull request #674
Opened 2023-03-09 08:07 UTC by prat-gpt

# Description of change
## High level
* In cases when bucket take happens for an auction with auction price zero, the bond change is calculated as zero and LPs awarded to kicker are 0. We want to avoid executing the logic within `Bucket.addLenderLPs` as it only updates kicker's deposit time resulting in additional gas costs.
*  Added a check to update Lender/kicker `depositTime` only when non-zero lps are added

2023-03-09 08:09 UTC, grandizzy approved these changes
test will be added when invariant branch merged

2023-03-09 11:25 UTC, mattcushman approved these changes
This looks fine to me... although I can't see how this would affect anything.  If this is fixing a test someplace, I'm concerned that there is a deeper bug elsewhere.  If someone makes a 0 deposit and updates their timestamp (and at the same time, wiping out their old LPB which is what it looks like this code does), I don't *think* it should affect anything else downstream, as LPB with a pre-bankruptcy timestamp should be rendered worthless (effectively zero).

2023-03-09 11:30 UTC, grandizzy commented
> This looks fine to me... although I can't see how this would affect anything. If this is fixing a test someplace, I'm concerned that there is a deeper bug elsewhere. If someone makes a 0 deposit and updates their timestamp (and at the same time, wiping out their old LPB which is what it looks like this code does), I don't _think_ it should affect anything else downstream, as LPB with a pre-bankruptcy timestamp should be rendered worthless (effectively zero).

there's caused by bucket take a collateral calculated 0 amount, hence reward / lps awarded is 0. Will have a fix for that scenario, we could put this one on hold and see if reproducible after

2023-03-09 13:25 UTC, grandizzy commented
> > This looks fine to me... although I can't see how this would affect anything. If this is fixing a test someplace, I'm concerned that there is a deeper bug elsewhere. If someone makes a 0 deposit and updates their timestamp (and at the same time, wiping out their old LPB which is what it looks like this code does), I don't _think_ it should affect anything else downstream, as LPB with a pre-bankruptcy timestamp should be rendered worthless (effectively zero).
> 
> there's caused by bucket take a collateral calculated 0 amount, hence reward / lps awarded is 0. Will have a fix for that scenario, we could put this one on hold and see if reproducible after

This actually happens when bucketTake is called on an auction with auction price 0, so `borrowerPrice` is calculated 0 here https://github.com/ajna-finance/contracts/blob/develop/src/libraries/external/Auctions.sol#L1169 hence `collateralValue` is 0 as well https://github.com/ajna-finance/contracts/blob/develop/src/libraries/external/Auctions.sol#L1174 and it ends up in `quoteTokenAmount` / `bondChange` / `kickerReward` being 0 https://github.com/ajna-finance/contracts/blob/develop/src/libraries/external/Auctions.sol#L1198

2023-03-09 18:34 UTC, MikeHathaway approved these changes
LGTM

2023-03-09 19:06 UTC, EdNoepel requested changes
PR description template has not been completed.

2023-03-09 19:06 UTC, EdNoepel commented on tests/forge/ERC20Pool/ERC20PoolLiquidationsDepositTake.t.sol
> +        ERC20Pool(address(_pool)).drawDebt(actor2, 895835179323.954988585146991431 * 1e18, 7388, 333688779.021420071719646593 * 1e18);
Same concerns as #676:
- Style nit regarding thousands separators.
- Lack of comments in test.
- Unclear why not using (`ERC20DSTestPlus._drawDebtNoLupCheck`).

2023-03-09 19:06 UTC, EdNoepel commented on src/libraries/internal/Buckets.sol
>          address lender_,
Irrelevant to change, but could you also remove comment on line 68?  This doesn't touch bucket accumulators; it only mutates lender accounting.

2023-03-09 19:22 UTC, grandizzy commented on tests/forge/ERC20Pool/ERC20PoolLiquidationsDepositTake.t.sol
> +        ERC20Pool(address(_pool)).drawDebt(actor2, 895835179323.954988585146991431 * 1e18, 7388, 333688779.021420071719646593 * 1e18);
we're going to cosmetize test in a follow up task, for the moment we're just trying to fix invariants and have invariants PR merged in develop

2023-03-09 19:25 UTC, grandizzy commented on src/libraries/internal/Buckets.sol
>          address lender_,
updated in https://github.com/ajna-finance/contracts/pull/674/commits/5592dade7147ef9225541d9a0e752313c337fae4

2023-03-10 05:31 UTC, grandizzy commented
> PR description template has not been completed.

updated

2023-03-10 05:45 UTC, grandizzy commented on tests/forge/ERC20Pool/ERC20PoolLiquidationsDepositTake.t.sol
> +        ERC20Pool(address(_pool)).drawDebt(actor2, 895835179323.954988585146991431 * 1e18, 7388, 333688779.021420071719646593 * 1e18);
formatted test in https://github.com/ajna-finance/contracts/pull/674/commits/7f7eebb9d8c00b9f01f5348721c8d6c28a34eb18

2023-03-10 05:51 UTC, merged