Bucket take with tiny deposit
ajna-finance/ajna-core pull request #676
Opened 2023-03-09 13:48 UTC by grandizzy

# Description of change
## High level
* if deposit in bucket cannot cover at least 1 unit of collateral (that is calculated amount to take is zero) then taker reward is zero and bucket is left with no collateral, no deposit and unbacked LPs
*  fix by reverting if bucket take on a bucket with not enough deposit to cover at least one unit of collateral
*  unit test

2023-03-09 17:50 UTC, mattcushman approved these changes
lgtm

2023-03-09 18:31 UTC, MikeHathaway approved these changes
LGTM

2023-03-09 18:36 UTC, EdNoepel approved these changes
Test is missing comments summarizing what is going on.  No concerns about this change though.

2023-03-09 18:36 UTC, EdNoepel commented on tests/forge/ERC20Pool/ERC20PoolLiquidationsDepositTake.t.sol
> +        _pool.kick(actor0, 7388);
Could use `MAX_INDEX` constant here and line 730, but seems there's many places where that isn't used.

2023-03-09 18:36 UTC, EdNoepel commented on tests/forge/ERC20Pool/ERC20PoolLiquidationsDepositTake.t.sol
> +        ERC20Pool(address(_pool)).drawDebt(actor0, 963917415300.377728022097440900 * 1e18, 7388, 359048665.215178534787974447 * 1e18);
Why not `ERC20DSTestPlus._drawDebtNoLupCheck`?

2023-03-09 18:36 UTC, EdNoepel commented on src/libraries/external/Auctions.sol
> +        if (vars_.collateralAmount == 0) revert InsufficientLiquidity();
This is really the change.  Reverting if `_calculateTakeFlowsAndBondChange` determines no collateral can be purchased.

2023-03-09 18:36 UTC, EdNoepel commented on src/libraries/external/Auctions.sol
> +        if (vars_.collateralAmount == 0) revert InsufficientLiquidity();
`_take` does not need to do likewise, because user specifies collateral amount in `take` call, and reverts with `InvalidAmount` if 0.

2023-03-09 18:36 UTC, EdNoepel commented on tests/forge/ERC20Pool/ERC20PoolLiquidationsDepositTake.t.sol
> +        _pool.addQuoteToken(1927834830600.755456044194881800 * 1e18, 2572, block.timestamp + 100);
Why no thousands separators?

2023-03-09 18:40 UTC, EdNoepel requested changes
Why are we now ignoring the PR description template?

2023-03-09 19:20 UTC, grandizzy commented on tests/forge/ERC20Pool/ERC20PoolLiquidationsDepositTake.t.sol
> +        _pool.addQuoteToken(1927834830600.755456044194881800 * 1e18, 2572, block.timestamp + 100);
> Why no thousands separators?

We have a follow up task to cosmetize these tests, rn we're trying to fix all invariants and merge invariants PR in develop as double maintenance is a really problem (test is caught in invariants branch, then we have to manually replicate in a PR against develop - because invariant code to reproduce is not there, then merge back in invariant test)

2023-03-09 19:21 UTC, grandizzy commented
> Why are we now ignoring the PR description template?

will try to do it going forward

2023-03-10 06:13 UTC, grandizzy commented on tests/forge/ERC20Pool/ERC20PoolLiquidationsDepositTake.t.sol
> +        ERC20Pool(address(_pool)).drawDebt(actor0, 963917415300.377728022097440900 * 1e18, 7388, 359048665.215178534787974447 * 1e18);
changed in https://github.com/ajna-finance/contracts/pull/676/commits/e2a37e81c6f4c6c8c9b1af6de1e81e0f3582ff34

2023-03-10 06:13 UTC, grandizzy commented on tests/forge/ERC20Pool/ERC20PoolLiquidationsDepositTake.t.sol
> +        _pool.addQuoteToken(1927834830600.755456044194881800 * 1e18, 2572, block.timestamp + 100);
changed in https://github.com/ajna-finance/contracts/pull/676/commits/e2a37e81c6f4c6c8c9b1af6de1e81e0f3582ff34

2023-03-10 06:17 UTC, merged