Inflator precision update
ajna-finance/ajna-core pull request #75
Opened 2022-04-14 20:06 UTC by MikeHathaway

2022-04-15 00:51 UTC, MikeHathaway commented
Marking this ready to review so people can take a look at the precision updates. The tests are still a WIP, most of the required test fixes involve slight changes to the expected amounts in tests due to deviations in inflator / pool interest from the higher precision.

2022-04-15 01:04 UTC, MikeHathaway commented on src/ERC20Pool.sol
> +                    secondsSinceLastUpdate
This deviates in that `secondsSinceLastUpdate` is no longer scaled. Otherwise WAD -> RAY

2022-04-15 02:25 UTC, EdNoepel reviewed
So far so good.  Also appreciate commenting the types.

2022-04-15 02:25 UTC, EdNoepel commented on src/ERC20Pool.sol
> +    /// @param _amount RAD The amount of quote token to purchase
The idea was to keep public interfaces for deposit/withdrawal/borrow/repay at WAD precision, using a higher precision internally.  That way any rounding stays around the RAY boundary, and disappears upon conversion back to WAD.

Also makes it cleaner to integrate with other WAD-based protocols.

2022-04-15 03:49 UTC, MikeHathaway commented
Most test's have similar outputs after the precision changes, except for Liquidations and collateral claims.

2022-04-15 03:56 UTC, MikeHathaway commented on src/ERC20Pool.sol
> +    /// @param _amount RAD The amount of quote token to purchase
Gotcha, this comment was poorly placed - no change was made to input RAD's instead of WADs.

2022-04-18 12:02 UTC, EdNoepel approved these changes
Looking forward to this.

2022-04-18 13:28 UTC, grandizzy requested changes
In the light of exchangeRate bug fix, I wonder if we still need all wad to rad / rad to ray conversions or if we can accommodate only the inflator precision

2022-04-18 13:28 UTC, grandizzy commented on src/ERC20Pool.sol
> +        if (_amount > totalQuoteToken) {
This was removed from PR that was merged in develop as per Friday discussion,

2022-04-19 15:31 UTC, MikeHathaway commented on src/ERC20Pool.sol
> +        if (_amount > totalQuoteToken) {
This matches the logic that was merged on Friday: https://github.com/ajna-finance/contracts/pull/78/files#diff-0603d54ebc5f996b7feb0bc3660e3fa4b32699beeca732622d91afe7a1094fd7R227-R232

2022-04-19 15:37 UTC, grandizzy commented on src/ERC20Pool.sol
> +        if (_amount > totalQuoteToken) {
Yeah, I mean the behaviour was changed in develop branch but I didn't update the PR https://github.com/ajna-finance/contracts/blob/develop/src/ERC20Pool.sol#L214

2022-04-19 15:40 UTC, MikeHathaway commented on src/ERC20Pool.sol
> +        if (_amount > totalQuoteToken) {
Ah I see, ok I will remove that change from the PR

2022-04-19 16:29 UTC, MikeHathaway commented
> In the light of exchangeRate bug fix, I wonder if we still need all wad to rad / rad to ray conversions or if we can accommodate only the inflator precision

Only updating the inflator precision would seem to defeat the purpose to some extent - a new RAY inflator is used in several other functions who would then, in rounding down, remove any additional precision gains. Also, putting all of the math operations into like-terms allows us to use the DS-Math functions which have built-in overflow protection for each precision level (other than RAD).

2022-04-19 17:09 UTC, merged