Fix overflow underflow
ajna-finance/ajna-core pull request #754
Opened 2023-04-20 08:46 UTC by prat-gpt

# Description of change
## High level
- Avoid an underflow revert when `redeemedLP` > `lenderLps`. Updated to redeemLP to `vars.redeemedLP = Maths.min(lender.lps, vars.redeemedLP)` in `kickWithDeposit`.
- Add bankruptcy check in `kickWithDeposit`.
- Avoid an overflow revert in `_calculateInterestRate` by updating `((tu + mau102 - 1e18) ** 2) / 1e18`  to `(((tu + mau102 - 1e18) / 1e9) ** 2)`.

# Contract Size
No size change for pool contract as changes are only in external libraries.

2023-04-20 08:48 UTC, grandizzy commented on src/libraries/external/KickerActions.sol
> +        lender.lps -= Maths.min(lender.lps, vars.redeemedLPs);
need @mattcushman  opinion on https://github.com/ajna-finance/contracts/pull/747#discussion_r1170820632

2023-04-20 08:48 UTC, grandizzy reviewed
LGTM, waiting for Matt's comment on `Maths.min` and `BucketBankruptcy`

2023-04-20 15:26 UTC, mattcushman commented on src/libraries/external/KickerActions.sol
> +        lender.lps -= Maths.min(lender.lps, vars.redeemedLPs);
Won't this cause an issue with the line below, where the bucket LPs and the lender LPs are decremented by different quantities?  This will mess up the invariant that requires them to match.

I'd rather find a good way to constrain redeemedLPs to be <= lender.lps.

2023-04-20 16:02 UTC, grandizzy commented on src/libraries/external/KickerActions.sol
> +        lender.lps -= Maths.min(lender.lps, vars.redeemedLPs);
consider doing `vars.redeemedLPs = Maths.min(lender.lps, vars.redeemedLPs);` and check for `BucketBankruptcy`

2023-04-21 10:57 UTC, prat-gpt commented on src/libraries/external/KickerActions.sol
> +        lender.lps -= Maths.min(lender.lps, vars.redeemedLPs);
Updated here [38a1b83](https://github.com/ajna-finance/contracts/pull/754/commits/38a1b83f81f54ab499f6ad0d79f0843e165b3f89)

2023-04-21 13:14 UTC, grandizzy requested changes

2023-04-21 13:14 UTC, grandizzy commented on src/libraries/external/KickerActions.sol
> +        vars.bucketUnscaledDeposit = Deposits.unscaledValueAt(deposits_, index_);
instead reloading this by walking Fenwick again, let's use original `vars.bucketUnscaledDeposit` and decrement as we go

2023-04-21 13:16 UTC, grandizzy commented on src/libraries/external/KickerActions.sol
> +        uint256 bucketRemainingLP = bucket.lps - vars.redeemedLP;
same here, we already have` vars.bucketLP` loaded, no need to load it again

2023-04-21 14:24 UTC, prat-gpt commented on src/libraries/external/KickerActions.sol
> +        vars.bucketUnscaledDeposit = Deposits.unscaledValueAt(deposits_, index_);
Updated in [44c62b7](https://github.com/ajna-finance/contracts/pull/754/commits/44c62b75879eec33cd7aeb6c3df02408e66e46b0)

2023-04-21 14:24 UTC, prat-gpt commented on src/libraries/external/KickerActions.sol
> +        uint256 bucketRemainingLP = bucket.lps - vars.redeemedLP;
Updated in [44c62b7](https://github.com/ajna-finance/contracts/pull/754/commits/44c62b75879eec33cd7aeb6c3df02408e66e46b0)

2023-04-21 14:33 UTC, mattcushman approved these changes
lgtm

2023-04-21 14:36 UTC, grandizzy approved these changes
looks good!

2023-04-21 15:17 UTC, merged