Codearena-494, 179: moveLiquidity to bucket deposit time and LP fix
ajna-finance/ajna-core pull request #815
Opened 2023-05-15 17:34 UTC by grandizzy

# Description of change
## High level
* See https://github.com/code-423n4/2023-05-ajna-findings/issues/494
  * update position deposit time with the renewed to bucket deposit time: when moving liquidity set deposit time in to bucket to the one retrieved from pool instead setting the from deposit time. this prevents losing LP funds when moving healthy positions memorialized in a block before target bucket went bankrupt (e.g. moving from bucket with depositTime 1000 to a bucket bankrupt at time 2000)
  * added unit test ensuring position is healthy after such move

* See https://github.com/code-423n4/2023-05-ajna-findings/issues/179
  * reset LP balance if moving to a bucket that went bankrupt since memorialization
  * check if to bucket went bankrupt since memorialization
  * if to bucket bankrupt since memorialization then reset LP balance in to bucket when moving liquidity
  * added unit test ensuring position is healthy after such move

## Gas pre change
```
 Function Name                                    | min             | avg    | median | max     | # calls |
| moveLiquidity                                    | 232150          | 288910 | 252802 | 475110  | 10      |
```
## Gas post change
```
 Function Name                                    | min             | avg    | median | max     | # calls |
| moveLiquidity                                    | 238986          | 295847 | 259898 | 483137  | 10      |
```

Additional reports:

- https://github.com/code-423n4/2023-05-ajna-findings/issues/128
- https://github.com/code-423n4/2023-05-ajna-findings/issues/111
- https://github.com/code-423n4/2023-05-ajna-findings/issues/97
- https://github.com/code-423n4/2023-05-ajna-findings/issues/88

2023-05-16 11:06 UTC, prat-gpt submitted a review, later dismissed
LGTM. This also fixes a failing regression test for PM1 in position manager invariants PR #793.

2023-05-16 17:06 UTC, grandizzy commented
> LGTM. This also fixes a failing regression test for PM1 in position manager invariants PR #793.

I think this needs an additional change to fix https://github.com/code-423n4/2023-05-ajna-findings/issues/179 by checking if from / to went bankrupt since depositTime

2023-05-16 19:05 UTC, ith-harvey commented on src/PositionManager.sol
> +        // reset LP in to bucket if bucket went bankrupt after memorialization
Exactly the check we needed, nice : )

2023-05-16 19:38 UTC, ith-harvey requested changes

2023-05-16 19:38 UTC, ith-harvey commented on src/PositionManager.sol
> +        toPosition.depositTime = vars.toDepositTime;
Think we also need a check here:
```
if (fromPosition.lps == 0) fromPosition.depositTime = 0 
```

2023-05-16 19:50 UTC, grandizzy commented on src/PositionManager.sol
> +        toPosition.depositTime = vars.toDepositTime;
see https://github.com/code-423n4/2023-05-ajna-findings/issues/503

2023-05-16 22:28 UTC, ith-harvey commented on src/PositionManager.sol
> +        toPosition.depositTime = vars.toDepositTime;
I don't see how your comment about another issue unrelated to `fromPosition.depositTime` is directly related to my comment here aside from there being more work to do... Are you suggesting that the deposit time suggestion I'm making here is done in a separate PR? I'm OK with that if that is the plan :+1: .

2023-05-16 22:30 UTC, ith-harvey approved these changes
This PR sufficiently addresses issues 494 and 179 code arena issues.

2023-05-17 02:39 UTC, MikeHathaway commented on tests/forge/unit/PositionManager.t.sol
> +        _assertBucketAssets({
Might be good to also assert the number of LPs owned by each position when moving to the formerly bankrupt bucket

2023-05-17 02:49 UTC, MikeHathaway commented on src/PositionManager.sol
> +        if (bankruptcyTime != 0) return depositTime_ <= bankruptcyTime;
What's the purpose of the extra `if (bankruptcyTime != 0)` check? It seems to returns false either way?

2023-05-17 03:02 UTC, MikeHathaway reviewed
Looks great - just had a few small comments. Test suggestion can be ignored since the LPs are checked in the other unit test.

2023-05-17 03:54 UTC, grandizzy commented on src/PositionManager.sol
> +        if (bankruptcyTime != 0) return depositTime_ <= bankruptcyTime;
without the check function returns true (position bankrupt) in a bucket that is not bankrupt and there's no deposit

2023-05-17 05:09 UTC, MikeHathaway approved these changes
LGTM

2023-05-17 06:02 UTC, grandizzy commented on src/PositionManager.sol
> +        toPosition.depositTime = vars.toDepositTime;
yes, correct, will follow up on fixing from position

2023-05-17 07:32 UTC, merged