Code Arena: Nft svg encoding
ajna-finance/ajna-core pull request #816
Opened 2023-05-15 17:51 UTC by MikeHathaway

# Description of change
## High level
* Add explicit base64 encoding of svg image string to simplify json parsing of token metadata.
* Tested the change manually due to issues with setting up json parsing in forge

# Description of bug or vulnerability and solution
* https://github.com/code-423n4/2023-05-ajna-findings/issues/161

2023-05-15 17:56 UTC, grandizzy requested changes
I think testTokenURI should also be updated? Tried to figure out what's the difference but wasn't able, so good to go from my pov after test update

2023-05-16 03:28 UTC, MikeHathaway commented
> I think testTokenURI should also be updated? Tried to figure out what's the difference but wasn't able, so good to go from my pov after test update

Current plan is to test via the front end

2023-05-18 05:07 UTC, grandizzy approved these changes

2023-05-24 14:08 UTC, EdNoepel reviewed
Keep in mind, this cannot be tested through SDK/dapp until after an RC5 release.

2023-05-24 14:08 UTC, EdNoepel commented on tests/forge/unit/PositionManager.t.sol
> +        // emit log(decodedURI.image);
Why the commented-out code?

2023-05-26 02:28 UTC, MikeHathaway commented on tests/forge/unit/PositionManager.t.sol
> +        // emit log(decodedURI.image);
Removed the unused code

2023-05-30 20:01 UTC, ith-harvey approved these changes
This cannot be tested until after RC5 release which can't be created until after this code gets in :shrug: 

Don't see any threats to contracts by approving this as it's used to render the NFT image / details about the NFT.

2023-05-30 20:02 UTC, merged