Codearena-317: Old bucket snapshot info not deleted
ajna-finance/ajna-core pull request #826
Opened 2023-05-16 11:03 UTC by grandizzy

# Description of change
## High level
* See https://github.com/code-423n4/2023-05-ajna-findings/issues/317
  * if Position manager change positions after NFT staked for rewards then old bucket snapshots are not deleted when NFT unstaked
  * add `StakeInfo.indexesAtStakeTime` array to save in storage the position indexes at time of stake
  * in unstake use recorded positions to remove snapshots
  * return number of staked positions in `RewardsManager.getStakeInfo`  and ensure in test that they are zero after each unstake action

# Gas usage
Quite big impact on stake, expected as positions array are now saved in storage
## Pre Change
```
| Function Name                                  | min             | avg    | median | max    | # calls |
| calculateRewards                               | 33685           | 43068  | 36004  | 163896 | 281     |
| claimRewards                                   | 567             | 109705 | 104321 | 393013 | 283     |
| getBucketStateStakeInfo                        | 638             | 2636   | 2638   | 2638   | 88668   |
| getStakeInfo                                   | 694             | 694    | 694    | 694    | 329     |
| stake                                          | 118723          | 306603 | 167844 | 891644 | 50      |
| unstake                                        | 78443           | 172427 | 141011 | 398450 | 14      |
| updateBucketExchangeRatesAndClaim              | 4108            | 232698 | 181887 | 543267 | 45      |
```
## Post Change
```
| Function Name                                  | min             | avg    | median | max     | # calls |
| calculateRewards                               | 35685           | 74469  | 52579  | 163896  | 22      |
| claimRewards                                   | 567             | 87651  | 104321 | 393013  | 24      |
| getBucketStateStakeInfo                        | 638             | 2636   | 2638   | 2638    | 96057   |
| getStakeInfo                                   | 818             | 818    | 818    | 818     | 50      |
| stake                                          | 154353          | 517425 | 559140 | 1135712 | 28      |
| unstake                                        | 34371           | 162407 | 140117 | 397557  | 15      |
| updateBucketExchangeRatesAndClaim              | 4108            | 247176 | 217046 | 543267  | 32      |
```

2023-05-16 11:20 UTC, grandizzy commented
converting to draft, realized it can be circumvented by ReardsManager.moveLiquidity

2023-05-17 05:58 UTC, grandizzy commented
> converting to draft, realized it can be circumvented by ReardsManager.moveLiquidity

no longer the case, move not possible through rewards manager anymore

2023-05-18 02:33 UTC, MikeHathaway requested changes
Do we still need this PR? Now that moveStakedLiquidity is gone, the indexes stay the same the entirety of a staked lifecycle. It seems like we can just use the existing check in that case

2023-05-18 02:33 UTC, grandizzy commented
> Do we still need this PR? Now that `moveStakedLiquidity` is gone, the indexes stay the same the entirety of a staked lifecycle. It seems like we can just use the existing check in that case

yeah, we need it because we rely on position manager memorialized indexes when unstake

2023-05-18 02:34 UTC, grandizzy commented
> > Do we still need this PR? Now that `moveStakedLiquidity` is gone, the indexes stay the same the entirety of a staked lifecycle. It seems like we can just use the existing check in that case
> 
> yeah, we need it because we rely on position manager memorialized indexes when unstake

hm, actually we probably don't,  will redo the test

2023-05-18 04:47 UTC, grandizzy commented
> Do we still need this PR? Now that moveStakedLiquidity is gone, the indexes stay the same the entirety of a staked lifecycle. It seems like we can just use the existing check in that case

you are right, more, this report is invalid, I was tricked by the provided POC which redeems on behalf of rewards manager (`changePrank(address(_rewardsManager));` at https://github.com/ajna-finance/contracts/pull/826/files#diff-4af083e04d07dc98fdd3d5fa63adc05f67fc78fa87889e3a8eb8645da34a1760R2114) closing

2023-05-18 04:47 UTC, closed without merging