CodeArena-361,326,237,135,124,116: Loss of rewards due to underfunded contract
ajna-finance/ajna-core pull request #833
Opened 2023-05-18 06:11 UTC by prat-gpt

# Description of change
## High level
* Revert with `InsufficientLiquidity` in `_transferAjnaRewards` if calculated rewards or contract balance is below specified min amount to receive limit.
* No revert in `stake`, and `updateBucketExchangeRate`, if rewards are more than the contract token balance.
* Add `minAmount_` param in `claimRewards` to enable the user to claim the available Ajna balance as rewards.

* `Stake` (possible regardless pool balance):
  * enough balance - staker should receive rewards for bucket update
  * insufficient balance - staker should receive portion of reward for bucket update (available balance)
  * no balance - staker should not receive any token but should be able to stake
* `Bucket Exchange rate update` (possible regardless pool balance):
  * enough balance - staker should receive rewards for bucket update
  * insufficient balance - staker should receive portion of reward for bucket update (available balance)
  * no balance - staker should not receive any token but should be able to update rate
* `Claim Rewards` (constrained by pool balance and user provided limit):
  * balance > rewards and rewards > limit - staker should receive rewards
  * balance > rewards and rewards < limit - tx should revert
  * balance < rewards and balance > limit - staker should receive balance
  * balance < rewards and balance < limit - tx should revert
  * balance = 0 and limit != 0 - tx should revert
  * balance = 0 and limit = 0 - staker should receive no token
* `Unstake` (constrained by pool balance):
  * unstake with balance > rewards - staker should receive rewards
  * unstake with balance < rewards - tx should revert

# Description of bug or vulnerability and solution
* See
https://github.com/code-423n4/2023-05-ajna-findings/issues/361
https://github.com/code-423n4/2023-05-ajna-findings/issues/326
https://github.com/code-423n4/2023-05-ajna-findings/issues/237
https://github.com/code-423n4/2023-05-ajna-findings/issues/135
https://github.com/code-423n4/2023-05-ajna-findings/issues/124
https://github.com/code-423n4/2023-05-ajna-findings/issues/116
* User can lose some rewards when Ajna token balance in the contract is less than rewards earned.
* Fixed with adding revert in `unstake` if contract balance is less than rewards earned and adding 'minAmountToClaim_' in `claimRewards` to enable the user to claim expected rewards or if contract balance is less than `minAmountToClaim_` should revert.

# Contract size
## Pre Change
RewardsManager           -   8,216B  (33.43%)
## Post Change
RewardsManager           -   8,346B  (33.96%)

2023-05-18 06:45 UTC, grandizzy reviewed
Looks good! have couple of style suggestions

2023-05-18 06:45 UTC, grandizzy commented on src/RewardsManager.sol
> +        _claimRewards({ tokenId_: tokenId_, epochToClaim_: epochToClaim_, claimMaxAvailable_: false });
for better readability I suggest formatting as
```Solidity
        _claimRewards({
            tokenId_:           tokenId_,
            epochToClaim_:      epochToClaim_,
            claimMaxAvailable_: false
        });
```

2023-05-18 06:45 UTC, grandizzy commented on src/RewardsManager.sol
> +        _claimRewards({ tokenId_: tokenId_, epochToClaim_: epochToClaim_, claimMaxAvailable_: true });
same as above
```Solidity
        _claimRewards({
            tokenId_:           tokenId_,
            epochToClaim_:      epochToClaim_,
            claimMaxAvailable_: true
        });
```

2023-05-18 06:45 UTC, grandizzy commented on src/RewardsManager.sol
> +        _transferAjnaRewards({ rewardsEarned_: updateReward, transferMaxAvailable_: true });
```Solidity
        _transferAjnaRewards({
            rewardsEarned_:        updateReward,
            transferMaxAvailable_: true
        });
```

2023-05-18 06:45 UTC, grandizzy commented on src/RewardsManager.sol
> +        _transferAjnaRewards({ rewardsEarned_: rewardsEarned, transferMaxAvailable_: claimMaxAvailable_ });
same formatting

2023-05-18 06:45 UTC, grandizzy commented on src/RewardsManager.sol
> +        _transferAjnaRewards({ rewardsEarned_: updateReward, transferMaxAvailable_: true });
same formatting

2023-05-18 06:45 UTC, grandizzy commented on src/RewardsManager.sol
> +        _transferAjnaRewards({rewardsEarned_: rewardsEarned, transferMaxAvailable_: false});
same formatting

2023-05-18 06:45 UTC, grandizzy commented on src/RewardsManager.sol
> +        // if remaining balance is greater and transferMaxAvailable_ is true, set to remaining balance else revert
I suggest a little bit of reorganizing this as
```Solidity
        uint256 ajnaBalance = IERC20(ajnaToken).balanceOf(address(this));

        // if contract balance cannot cover rewards earned
        if (rewardsEarned_ > ajnaBalance) {
            // revert if not opt in to give up part of rewards (claim rewards and unstake actions)
            if (!transferMaxAvailable_) revert InsufficientFunds();

            // cap rewards earned to available balance (update bucket exchange and claim max rewards actions)
            rewardsEarned_ = ajnaBalance;
        }

        if (rewardsEarned_ != 0) {
            // transfer rewards to sender
            IERC20(ajnaToken).safeTransfer(msg.sender, rewardsEarned_);
        }
```

2023-05-18 07:02 UTC, grandizzy commented on src/RewardsManager.sol
> +        uint256 rewardsEarned = _calculateAndClaimAllRewards(stakeInfo, tokenId_, epochToClaim_, true, stakeInfo.ajnaPool);
maybe split this too as
```Solidity
        uint256 rewardsEarned = _calculateAndClaimAllRewards(
            stakeInfo,
            tokenId_,
            epochToClaim_,
            true,
            stakeInfo.ajnaPool
        );
```

2023-05-18 08:19 UTC, grandizzy approved these changes
LGTM!

2023-05-19 21:04 UTC, MikeHathaway commented on src/RewardsManager.sol
> +    function _calculateAndClaimAllRewards(
We should probably rename some of these methods as they are no longer performing claims - maybe `_calculateAllRewards`

2023-05-19 21:06 UTC, MikeHathaway commented on src/RewardsManager.sol
> +            transferMaxAvailable_: false
For `unstake` it seems like this should be `true`. We shouldn't be making people revert on an unstake action due to the contract balance. That would be a worse UX than current.

2023-05-19 21:07 UTC, MikeHathaway requested changes
We should avoid reverting for contract balance on `unstake`

2023-05-19 21:10 UTC, grandizzy commented on src/RewardsManager.sol
> +            transferMaxAvailable_: false
I think false is desired to prevent losing rewards without being aware of such (also it is unlikely that contract doesn't have enough funds and this scenario to happen). In such case staker could call claim max rewards and then unstake

2023-05-22 04:43 UTC, prat-gpt commented on src/RewardsManager.sol
> +            transferMaxAvailable_: false
yes, I did a revert for the reason mentioned by George.

2023-05-22 09:42 UTC, prat-gpt commented on src/RewardsManager.sol
> +    function _calculateAndClaimAllRewards(
we already have [this](https://github.com/ajna-finance/contracts/blob/de89d16a63883e38bd81b2fbd282c1b683d0bdb6/src/RewardsManager.sol#L266) method named `calculateRewards` which calculates both type of rewards the only difference is that this method doesn't update the `isEpochClaimed` mapping. As this method is updating the state as well, I have named this as `_calculateAndClaimAllRewards`.

2023-05-24 03:54 UTC, MikeHathaway submitted a review, later dismissed
LGTM

2023-05-24 03:58 UTC, grandizzy commented
before merging, since it's a redesign of claim rewards @ith-harvey @mattcushman @EdNoepel could have one more look?

2023-05-24 10:36 UTC, EdNoepel reviewed
I do not understand the motivation to complicate the interface with two separate methods.  The contract will be funded a single time.  As such, if the user earned more rewards than the contract balance can deliver, there would be no reason to desire a revert, because they cannot come back later when the contract balance has increased.

2023-05-24 12:14 UTC, mattcushman submitted a review, later dismissed
lgtm and this semantics makes sense to me.  sounds like there are some questions however so let's discuss before merging.

2023-05-25 18:11 UTC, grandizzy submitted a review, later dismissed
I think the discussion was to have a new param max amount to be passed to `claimRewards` so user could either pass max uint256 to claim all rewards (constrained by the pool balance) or user could check rewards balance prior of claiming. though this could lead to front running and still losing unclaimed rewards...

2023-05-26 19:47 UTC, mattcushman requested changes
added some comments, concerned about unstake and the argument naming is a little worrisome to me

2023-05-26 19:47 UTC, mattcushman commented on src/RewardsManager.sol
> +    function _transferAjnaRewards(uint256 rewardsEarned_, bool transferMaxAvailable_, uint256 minRewardToClaim_) internal {
I think the way we are using this works... however, I find this a little unclear in naming. if the `rewardsEarned_ <=` the pool balance, yet less than `minRewardToClaim_`, then this will transfer rewardsEarned, even though this is less than `minRewardToClaim`.  Can we simplify this by getting rid of the boolean `transferMaxAvailable_` altogether, just have a `minRewardToClaim_` argument, and just revert if the amount that would be transferred is less than `minRewardToClaim_`?

2023-05-26 19:47 UTC, mattcushman commented on src/RewardsManager.sol
> +            rewardsEarned_: rewardsEarned,
If someone wants to `unstake` and yet they've earned rewards that are greater than the pool balance, will this allow them to do so?  seems like not if i follow the logic, as they will end up reverting in `_transferAjnaRewards`

2023-05-27 20:14 UTC, grandizzy commented on src/RewardsManager.sol
> +    function _transferAjnaRewards(uint256 rewardsEarned_, bool transferMaxAvailable_, uint256 minRewardToClaim_) internal {
please rereview

2023-05-27 20:16 UTC, grandizzy commented on src/RewardsManager.sol
> +            rewardsEarned_: rewardsEarned,
that's correct, but they have options as claimRewards with a minAmount or (if needed) do an emergency unstake. see unit tests with all possible scenarios here https://github.com/ajna-finance/contracts/pull/833/commits/95f40326a765484fa75aed5c81f5a8051ca5f9e3

2023-05-28 10:53 UTC, mattcushman approved these changes
lgtm.  I like this way of doing it more...

2023-05-29 19:32 UTC, ith-harvey commented on src/RewardsManager.sol
> +        if (transferAmount_ < minAmount_) revert InsufficientLiquidity();
Although not directly fixing, this indirectly solves the pain point of https://github.com/code-423n4/2023-05-ajna-findings/issues/361

By allowing the user to specify a `minAmount_` we give them the ability to not execute their claim unless it fufills their minimum expectation. Users are therefore less likely to be surprised that they have received less rewards then expected and their claim to future rewards are also gone.

2023-05-29 19:34 UTC, ith-harvey approved these changes
As I mentioned in my comment this PR solves for the pain point of  https://github.com/code-423n4/2023-05-ajna-findings/issues/361

without directly solving the issue. I am fine with this but suggest we mark the issue as acknowledged

2023-05-30 04:50 UTC, merged