Lock initialize method in ERC20Pool clones.
ajna-finance/ajna-core pull request #85
Opened 2022-04-20 23:21 UTC by MikeHathaway

Prior to this modifier, external callers would have been able to call `initialize` and reset pool state.

2022-04-20 23:22 UTC, MikeHathaway commented on src/_test/utils/DSTestPlus.sol
> +contract DSTestPlus is DSTest, Test {
I thought I needed one of the new Forge cheatcodes, so I updated forge-std.

2022-04-21 03:47 UTC, grandizzy requested changes

2022-04-21 03:47 UTC, grandizzy commented on src/ERC20Pool.sol
> +        require(poolInitializations == 0, "ajna/already-initialized");
Let's use custom errors as for all other cases

2022-04-21 22:10 UTC, MikeHathaway commented on src/ERC20Pool.sol
> +        require(poolInitializations == 0, "ajna/already-initialized");
Updated accordingly

2022-04-22 13:09 UTC, EdNoepel approved these changes

2022-04-22 13:26 UTC, grandizzy approved these changes

2022-04-22 15:56 UTC, merged