PROTOTECH-42 (continuation): Update rounding in pool calculations to favour pool
ajna-finance/ajna-core pull request #851
Opened 2023-05-24 14:57 UTC by prat-gpt

# Description of change
## High level
* Update rounding in favor of pool accounting
* Introduced `floorWdiv`, `floorWmul`, `ceilWdiv`, and `ceilWmul` in `Maths` to round up or down when div and mul
  * round up (`ceilWmul`) when current pool / borrower debt is calculated (t0debt * inflator) 
  * round up (`ceilWdiv`) when increasing amount borrowed
  * round down (`floorWdiv`) when decreasing borrower debt
  * round up (`ceilWmul`) when calculating quote tokens to repay by borrower
  * round up (`ceilWdiv`) when removing deposit used to kick with deposit
  * round down (`floorWmul`) reserves assets to use for settle bad debt
  * round up (`ceilWdiv`) borrower collateral used to settle bad debt
  * round up (`ceilWmul`) the amount of ajna token required to take reserves
* Set optimizer runs to 0

# Gas usage
## Pre Change
```
| Function Name                        | min             | avg    | median | max     | # calls |
| addQuoteToken                        | 120670          | 177879 | 162529 | 712332  | 60004   |
| bucketTake                           | 308310          | 326951 | 326951 | 345592  | 4       |
| drawDebt                             | 250666          | 295554 | 269490 | 809196  | 136003  |
| kick                                 | 148581          | 222602 | 221103 | 1033456 | 48000   |
| kickWithDeposit                      | 198038          | 275685 | 271831 | 998200  | 8000    |
| moveQuoteToken                       | 259878          | 259878 | 259878 | 259878  | 1       |
| removeQuoteToken                     | 145090          | 168983 | 173408 | 193133  | 4000    |
| repayDebt                            | 575207          | 607363 | 597255 | 755625  | 16002   |
| settle                               | 349355          | 349355 | 349355 | 349355  | 1       |
| take                                 | 81311           | 82713  | 82404  | 314148  | 15998   |
```
## Post Change
```
| Function Name                        | min             | avg    | median | max     | # calls |
| addQuoteToken                        | 122519          | 179833 | 164382 | 715582  | 60004   |
| bucketTake                           | 310035          | 328676 | 328676 | 347317  | 4       |
| drawDebt                             | 253325          | 298341 | 272221 | 812976  | 136003  |
| kick                                 | 149519          | 223592 | 222084 | 1035153 | 48000   |
| kickWithDeposit                      | 200288          | 277971 | 274117 | 1001101 | 8000    |
| moveQuoteToken                       | 250002          | 250002 | 250002 | 250002  | 1       |
| removeQuoteToken                     | 148134          | 172220 | 176922 | 196623  | 4000    |
| repayDebt                            | 577752          | 609908 | 599800 | 758170  | 16002   |
| settle                               | 351196          | 351196 | 351196 | 351196  | 1       |
| take                                 | 82491           | 83841  | 83513  | 316305  | 15998   |
```

# Contract size
## Pre Change
```
============ Deployment Bytecode Sizes ============
  ERC721Pool               -  24,499B  (99.68%)
  ERC20Pool                -  23,847B  (97.03%)
```
## Post Change
```
============ Deployment Bytecode Sizes ============
  ERC721Pool         -  24,476B  (99.59%)
  ERC20Pool          -  23,710B  (96.47%)
```

2023-05-26 06:15 UTC, grandizzy commented
@prateek105 wonder if there are places in invariant logic that we need to make inline with these changes?

2023-05-26 19:25 UTC, mattcushman submitted a review, later dismissed
lgtm

2023-05-29 19:58 UTC, EdNoepel submitted a review, later dismissed
LGTM

2023-05-30 21:21 UTC, grandizzy commented
> LGTM

rerequesting review as PR changed

2023-05-30 21:21 UTC, grandizzy commented
> lgtm

rerequesting review as PR changed

2023-05-30 22:45 UTC, EdNoepel approved these changes
Reviewed two new commits since my last review.  Did not review the merge from `develop`.

2023-05-30 22:45 UTC, EdNoepel commented on foundry.toml
> +optimizer_runs      = 0
I must have missed this discussion.  Are we disabling because we hit the size limit?

2023-05-30 22:45 UTC, EdNoepel commented on src/libraries/internal/Buckets.sol
> +        );
The original purpose of `getExchangeRate` was for use in LP-to-token conversion functions.  Do we even need it anymore?

2023-05-30 22:47 UTC, grandizzy commented on foundry.toml
> +optimizer_runs      = 0
yes, that's correct, with these changes contract size limit gets over deployment size

2023-05-30 22:50 UTC, grandizzy commented on src/libraries/internal/Buckets.sol
> +        );
it is also used by rewards manager to retrieve the rate at stake time and when updating exchange rate

2023-05-30 23:09 UTC, mattcushman requested changes
left one comment on a comment, other than that looks good (I've reviewed before so just glanced at the parts that changed)

2023-05-30 23:09 UTC, mattcushman commented on tests/forge/invariants/base/BasicInvariants.t.sol
> +                        1e8,  // otherwise require exchange rates to be within 1e-5
comment should now say `1e-10`

2023-05-30 23:15 UTC, grandizzy commented on tests/forge/invariants/base/BasicInvariants.t.sol
> +                        1e8,  // otherwise require exchange rates to be within 1e-5
changed in https://github.com/ajna-finance/contracts/pull/851/commits/acba5909bf4bbbe12da5615b6b8cfddc09aebb37

2023-05-30 23:17 UTC, merged