Position invariants
ajna-finance/ajna-core pull request #854
Opened 2023-05-29 11:06 UTC by ith-harvey

# Description of change
## High level
* Added PositionManager invariant scaffolding
* Added asserts for PostionManger in handlers
* Added `PM1` - `PM8` invariant check
* Added forge test commands for `Rewards` and `Position` invariants
* cleaned up invariant logging
* turned `getEpochInfo()` into "free" method

2023-05-29 11:18 UTC, ith-harvey commented on tests/forge/invariants/PositionsAndRewards/handlers/PositionHandlerAbstract.sol
> +        if (bucketCollateral != 0) return;
As I mentioned in chat, working on removing collateral from a bucket and resetting the exchange rate in a separate branch as it was causing some difficulty. I would like to get the positionManager invariants I have here in so we can start getting runs

2023-05-29 15:27 UTC, EdNoepel approved these changes
There were several TODOs; assuming the goal here is to get the current implementation merged into `develop` so work may continue in a fresh branch.  Pointed out some cosmetic issues, but my biggest concern is that we're only testing ERC20 pools.

2023-05-29 15:27 UTC, EdNoepel commented on tests/forge/invariants/PositionsAndRewards/PositionsInvariants.t.sol
> +        console.log("UBPositionHandler.mint              ",  IBaseHandler(_handler).numberOfCalls("UBPositionHandler.mint"));
What do the `UB` and `B` prefixes mean?

2023-05-29 15:27 UTC, EdNoepel commented on tests/forge/invariants/PositionsAndRewards/RewardsInvariants.t.sol
> +
nit: extra whitespace

2023-05-29 15:27 UTC, EdNoepel commented on tests/forge/invariants/PositionsAndRewards/RewardsInvariants.t.sol
> +
Where are invariants RW3-RW9 tested?  TBD or out of scope for this PR?
Also nit, extra whitespace.

2023-05-29 15:27 UTC, EdNoepel commented on tests/forge/invariants/PositionsAndRewards/handlers/PositionHandlerAbstract.sol
> +    /*******************************/
nit: right side of ascii art misaligned on lines 23,25

2023-05-29 15:27 UTC, EdNoepel commented on tests/forge/invariants/PositionsAndRewards/handlers/PositionHandlerAbstract.sol
> +        //TODO: stake w/ multiple buckets instead of just one
Assuming these TODOs will be addressed in a future PR.  Space between `//` and `TODO` might be useful for IDEs to parse.

2023-05-29 15:27 UTC, EdNoepel commented on tests/forge/invariants/PositionsAndRewards/handlers/PositionHandlerAbstract.sol
> +
nit: extra whitespace

2023-05-29 15:27 UTC, EdNoepel commented on tests/forge/invariants/PositionsAndRewards/handlers/RewardsHandler.sol
> +
nit: whitespace

2023-05-29 15:27 UTC, EdNoepel commented on tests/forge/invariants/PositionsAndRewards/handlers/unbounded/BasePositionsHandler.sol
> +import { BaseERC20PoolHandler }         from '../../../ERC20Pool/handlers/unbounded/BaseERC20PoolHandler.sol';
Concerned that the _Base_ position handler is only dealing with ERC20 pools.  NFT pools are arguably a better use case for LP NFTs and staking/rewards, and this continues a trend of implicitly under-representing them in testing.

2023-05-29 15:27 UTC, EdNoepel commented on tests/forge/invariants/base/handlers/unbounded/BaseHandler.sol
> +    uint256 public totalUpdaterRewPerEpoch;  // amount of reserve increase
nit: comment alignment on preceding three lines

2023-05-29 15:27 UTC, EdNoepel commented on tests/forge/invariants/base/handlers/unbounded/BaseHandler.sol
> +    //EnumerableSet.UintSet internal collateralBuckets;
Can this be removed?

2023-05-29 15:27 UTC, EdNoepel commented on tests/forge/invariants/base/handlers/unbounded/UnboundedLiquidationPoolHandler.sol
> +        numberOfCalls['UBLiqHandler.kickAuction']++;
`UBLiquidationHandler` was renamed in a few places, but not all.  Recommend making it consistent throughout the file.

2023-05-29 15:27 UTC, EdNoepel commented on tests/forge/invariants/trace.log
Is this file meant to be committed?

2023-05-29 15:27 UTC, EdNoepel commented on tests/forge/regression/PositionAndRewards/RegressionRewardsManager.t.sol
> +    // }
Why is the above test commented out?  Perhaps needs a TODO somewhere above it?

2023-05-29 15:43 UTC, grandizzy requested changes

2023-05-29 15:43 UTC, grandizzy commented on tests/forge/invariants/PositionsAndRewards/RewardsInvariants.t.sol
> +    function invariant_rewards_RW1() public useCurrentTimestamp {
please compact all invariants in one to make tests effective, see https://github.com/ajna-finance/contracts/pull/853/files#diff-2adb36d3f6294e82320a2c4bb81389d0bd06f89f2f4871acfd4ca2b9228fe1adR35

2023-05-29 15:43 UTC, grandizzy commented on tests/forge/invariants/PositionsAndRewards/handlers/PositionHandlerAbstract.sol
> +abstract contract PositionHandlerAbstract is UnboundedPositionsHandler {
not a fan of `Abstract` in contract name

2023-05-29 15:43 UTC, grandizzy commented on tests/forge/invariants/PositionsAndRewards/handlers/RewardsHandler.sol
> +        skip(365 days);
this doesn't seem right and will probably make tests to revert with overflow as huge interest will accumulate

2023-05-29 15:43 UTC, grandizzy commented on tests/forge/invariants/PositionsAndRewards/handlers/RewardsHandler.sol
> +        //TODO: Perform multiple randomized reserve auctions to ensure staked position has rewards over multiple epochs
TODO here to address

2023-05-29 15:43 UTC, grandizzy commented on tests/forge/invariants/PositionsAndRewards/handlers/RewardsHandler.sol
> +        //TODO: Update exchange rates to ensure staked position has rewards
TODO here to address

2023-05-29 15:43 UTC, grandizzy commented on tests/forge/invariants/PositionsAndRewards/handlers/unbounded/UnboundedPositionsHandler.sol
> +            // TODO: store memorialized position's tokenIds in mapping, for reuse in unstake and redeem calls
TODO here to address

2023-05-29 15:43 UTC, grandizzy commented on tests/forge/invariants/base/handlers/unbounded/BaseHandler.sol
> +    mapping(uint256 => uint256) public totalRewardPerEpoch;    // total rewards per epoch
why keeping Rewards manager related stuff in Base (pool) hanlder?

2023-05-29 15:43 UTC, grandizzy commented on tests/forge/invariants/trace.log
> +sender=0x0000000000000000000000000e06f1f47e2f9b06 addr=[tests/forge/invariants/PositionsAndRewards/handlers/RewardsHandler.sol:RewardsHandler]0xf535008760a9349da0650d92756d9a730c51c9ad calldata=takeR
this should not be committed, I thought was already in .gitignore, if it's not please add

2023-05-29 15:43 UTC, grandizzy commented on tests/forge/regression/PositionAndRewards/RegressionPositionManager.t.sol
> +    function test_regression_position_evm_revert_1() external {
please provide short description of issue in test and how was solved

2023-05-29 15:43 UTC, grandizzy commented on tests/forge/regression/PositionAndRewards/RegressionPositionManager.t.sol
> +    function test_regression_position_evm_revert_2() external {
same as above

2023-05-29 15:43 UTC, grandizzy commented on tests/forge/regression/PositionAndRewards/RegressionPositionManager.t.sol
> +    function test_regression_position_moveLiquidity_assertions() external {
same as above, and for all the other tests

2023-05-29 21:20 UTC, ith-harvey commented on tests/forge/invariants/PositionsAndRewards/PositionsInvariants.t.sol
> +        console.log("UBPositionHandler.mint              ",  IBaseHandler(_handler).numberOfCalls("UBPositionHandler.mint"));
"bound" versus "unbound"

2023-05-30 12:18 UTC, prat-gpt commented on tests/forge/invariants/PositionsAndRewards/handlers/PositionHandlerAbstract.sol
> +abstract contract PositionHandlerAbstract is UnboundedPositionsHandler {
I had to add Abstract as there is already a contract named `PositionHandler` which just adds a constructor to this abstract contract. Had to name that contract as `PositionHandler` for consistency. So added abstract here. I am unable to think of a better name.

2023-06-02 20:01 UTC, ith-harvey commented on tests/forge/invariants/PositionsAndRewards/RewardsInvariants.t.sol
> +    function invariant_rewards_RW1() public useCurrentTimestamp {
After touching base with @dizzy , was suggested we leave this for a separate PR

2023-06-02 20:01 UTC, ith-harvey commented on tests/forge/invariants/PositionsAndRewards/RewardsInvariants.t.sol
> +
correct, out of scope

2023-06-02 20:46 UTC, ith-harvey commented on tests/forge/regression/PositionAndRewards/RegressionPositionManager.t.sol
> +    function test_regression_position_evm_revert_1() external {
I don't remember anymore, some of these @prateek105 commited.

2023-06-02 20:46 UTC, ith-harvey commented on tests/forge/regression/PositionAndRewards/RegressionPositionManager.t.sol
> +    function test_regression_position_evm_revert_2() external {
same as above

2023-06-02 20:47 UTC, ith-harvey commented on tests/forge/regression/PositionAndRewards/RegressionPositionManager.t.sol
> +    function test_regression_position_moveLiquidity_assertions() external {
same as above, happy to remove the regressions if you don't want them to exist without comment.

2023-06-03 23:23 UTC, ith-harvey commented on tests/forge/invariants/base/handlers/unbounded/BaseHandler.sol
> +    mapping(uint256 => uint256) public totalRewardPerEpoch;    // total rewards per epoch
fixed -> https://github.com/ajna-finance/contracts/pull/854/commits/f978e2a28da2dbab4cc39f85acc18a9548cb9e49

2023-06-03 23:23 UTC, ith-harvey commented on tests/forge/invariants/PositionsAndRewards/handlers/RewardsHandler.sol
> +        skip(365 days);
fixed -> https://github.com/ajna-finance/contracts/pull/854/commits/f978e2a28da2dbab4cc39f85acc18a9548cb9e49

2023-06-03 23:23 UTC, ith-harvey commented on tests/forge/regression/PositionAndRewards/RegressionRewardsManager.t.sol
> +    // }
fixed -> https://github.com/ajna-finance/contracts/pull/854/commits/f978e2a28da2dbab4cc39f85acc18a9548cb9e49

2023-06-03 23:24 UTC, ith-harvey commented on tests/forge/invariants/base/handlers/unbounded/UnboundedLiquidationPoolHandler.sol
> +        numberOfCalls['UBLiqHandler.kickAuction']++;
fixed -> https://github.com/ajna-finance/contracts/pull/854/commits/f978e2a28da2dbab4cc39f85acc18a9548cb9e49

2023-06-03 23:24 UTC, ith-harvey commented on tests/forge/invariants/base/handlers/unbounded/BaseHandler.sol
> +    //EnumerableSet.UintSet internal collateralBuckets;
fixed -> https://github.com/ajna-finance/contracts/pull/854/commits/f978e2a28da2dbab4cc39f85acc18a9548cb9e49

2023-06-03 23:24 UTC, ith-harvey commented on tests/forge/invariants/base/handlers/unbounded/BaseHandler.sol
> +    uint256 public totalUpdaterRewPerEpoch;  // amount of reserve increase
fixed -> https://github.com/ajna-finance/contracts/pull/854/commits/f978e2a28da2dbab4cc39f85acc18a9548cb9e49

2023-06-03 23:25 UTC, ith-harvey commented on tests/forge/invariants/PositionsAndRewards/handlers/PositionHandlerAbstract.sol
> +    /*******************************/
fixed -> https://github.com/ajna-finance/contracts/pull/854/commits/f978e2a28da2dbab4cc39f85acc18a9548cb9e49

2023-06-03 23:26 UTC, ith-harvey commented on tests/forge/invariants/PositionsAndRewards/RewardsInvariants.t.sol
> +
fixed -> https://github.com/ajna-finance/contracts/pull/854/commits/f978e2a28da2dbab4cc39f85acc18a9548cb9e49

2023-06-03 23:26 UTC, ith-harvey commented on tests/forge/invariants/PositionsAndRewards/handlers/PositionHandlerAbstract.sol
> +
fixed -> https://github.com/ajna-finance/contracts/pull/854/commits/f978e2a28da2dbab4cc39f85acc18a9548cb9e49

2023-06-03 23:26 UTC, ith-harvey commented on tests/forge/invariants/PositionsAndRewards/handlers/RewardsHandler.sol
> +
fixed -> https://github.com/ajna-finance/contracts/pull/854/commits/f978e2a28da2dbab4cc39f85acc18a9548cb9e49

2023-06-03 23:27 UTC, ith-harvey commented on tests/forge/invariants/PositionsAndRewards/handlers/unbounded/BasePositionsHandler.sol
> +import { BaseERC20PoolHandler }         from '../../../ERC20Pool/handlers/unbounded/BaseERC20PoolHandler.sol';
agree plan was a separate PR

2023-06-03 23:29 UTC, ith-harvey commented on tests/forge/invariants/trace.log
no it was not, develop had the fix

2023-06-04 21:13 UTC, ith-harvey commented on tests/forge/invariants/PositionsAndRewards/handlers/RewardsHandler.sol
> +        //TODO: Perform multiple randomized reserve auctions to ensure staked position has rewards over multiple epochs
removed todo, putting off for later PR to reduce the complexity of this one.

2023-06-04 21:13 UTC, ith-harvey commented on tests/forge/invariants/PositionsAndRewards/handlers/RewardsHandler.sol
> +        //TODO: Update exchange rates to ensure staked position has rewards
done -> https://github.com/ajna-finance/contracts/commit/f978e2a28da2dbab4cc39f85acc18a9548cb9e49

2023-06-04 21:14 UTC, ith-harvey commented on tests/forge/invariants/PositionsAndRewards/handlers/unbounded/UnboundedPositionsHandler.sol
> +            // TODO: store memorialized position's tokenIds in mapping, for reuse in unstake and redeem calls
done -> https://github.com/ajna-finance/contracts/pull/854/commits/8ada8225bf96442f2b2f56d7ffd0319d6e510958

2023-06-05 13:15 UTC, prat-gpt commented on tests/forge/regression/PositionAndRewards/RegressionPositionManager.t.sol
> +    function test_regression_position_evm_revert_1() external {
I have added comments for some of the regression tests that I added that I remember here [93e0f71](https://github.com/ajna-finance/contracts/pull/854/commits/93e0f71c6b197ea54359a528dc0a6c9342c17bb3)

2023-06-05 16:54 UTC, MikeHathaway commented on tests/forge/invariants/trace.log
> +sender=0x00000000000000000000000000000000000006da addr=[tests/forge/invariants/PositionsAndRewards/handlers/RewardsHandler.sol:RewardsHandler]0xf535008760a9349da0650d92756d9a730c51c9ad calldata=claim
Can remove this file with `git rm` if not needed

2023-06-05 17:05 UTC, MikeHathaway commented on .gitignore
> +tests/forge/invariants/trace.log
nit: can update with a more general restriction `*.log` since we shouldn't be committing any log files in this repo

2023-06-05 17:07 UTC, MikeHathaway commented on src/RewardsManager.sol
> +    /**********************/
I like the idea of sectioning, but would be helpful to be more specific - Rewards Calculations or similar. Also, this is probably best handled in a separate PR.

2023-06-05 17:09 UTC, MikeHathaway reviewed
Generally looks great! Just a few small comments. Also a general nit: many of the new files are missing a new line at the end of the file

2023-06-05 17:30 UTC, ith-harvey commented on tests/forge/invariants/trace.log
> +sender=0x00000000000000000000000000000000000006da addr=[tests/forge/invariants/PositionsAndRewards/handlers/RewardsHandler.sol:RewardsHandler]0xf535008760a9349da0650d92756d9a730c51c9ad calldata=claim
good call -> https://github.com/ajna-finance/contracts/pull/854/commits/9dec6dfe81bcdeb50f6affff73b128f092e396d2

2023-06-05 17:30 UTC, ith-harvey commented on .gitignore
> +tests/forge/invariants/trace.log
nice, fixed -> https://github.com/ajna-finance/contracts/pull/854/commits/9dec6dfe81bcdeb50f6affff73b128f092e396d2

2023-06-05 17:30 UTC, ith-harvey commented on src/RewardsManager.sol
> +    /**********************/
agreed, separate PR

2023-06-05 17:36 UTC, ith-harvey commented
> Generally looks great! Just a few small comments. Also a general nit: many of the new files are missing a new line at the end of the file

fixed -> https://github.com/ajna-finance/contracts/pull/854/commits/2d93b7dc113a9e1fae08398bbd061b2fb3b9c8d3

2023-06-05 18:55 UTC, MikeHathaway approved these changes
LGTM

2023-06-06 06:55 UTC, grandizzy requested changes

2023-06-06 06:55 UTC, grandizzy commented on tests/forge/invariants/PositionsAndRewards/PositionsInvariants.t.sol
> +        _position         = new PositionManager(_erc20poolFactory, _erc721poolFactory);
nit: spacing

2023-06-06 06:55 UTC, grandizzy commented on tests/forge/invariants/PositionsAndRewards/RewardsInvariants.t.sol
> +    function invariant_rewards_RW1() public useCurrentTimestamp {
that's fine, though easy to group them now in an `invariant_rewards_RW1_RW2` as they almost use same values to compare, e.g.

```Solidity
    function invariant_rewards_RW1_RW2() public useCurrentTimestamp {

        // get current epoch (is incremented every kickReserve() call) 
        uint256 curEpoch = _pool.currentBurnEpoch();

        // get rewards that have been claimed
        uint256 claimedRewards  = IBaseHandler(_handler).totalRewardPerEpoch(curEpoch);

        // total ajna burned by the pool over the epoch
        (, uint256 totalBurnedInPeriod,) = _getEpochInfo(address(_pool), curEpoch);

        // stake rewards cap is 80% of total burned
        uint256 stakeRewardsCap = Maths.wmul(totalBurnedInPeriod, 0.8 * 1e18);
        // check claimed rewards < rewards cap
        if (stakeRewardsCap != 0) require(claimedRewards < stakeRewardsCap, "Rewards invariant RW1");

        // update rewards cap is 10% of total burned
        uint256 updateRewardsCap = Maths.wmul(totalBurnedInPeriod, 0.1 * 1e18);
        // check claimed rewards < rewards cap
        if (updateRewardsCap != 0) require(claimedRewards < updateRewardsCap, "Rewards invariant RW2");
    }
```

2023-06-06 06:55 UTC, grandizzy commented on tests/forge/invariants/PositionsAndRewards/handlers/PositionHandlerAbstract.sol
> +import { BaseERC20PoolHandler }     from '../../ERC20Pool/handlers/unbounded/BaseERC20PoolHandler.sol';
nit: spacing

2023-06-06 06:55 UTC, grandizzy commented on tests/forge/invariants/PositionsAndRewards/handlers/PositionHandlerAbstract.sol
> +abstract contract PositionHandlerAbstract is UnboundedPositionsHandler {
what about `Base` as we already use in `BaseHandler` so `BasePositionHandler`?

2023-06-06 06:55 UTC, grandizzy commented on tests/forge/invariants/PositionsAndRewards/handlers/PositionHandlerAbstract.sol
> +        boundedFromIndex_      = constrictToRange(fromIndex_, LENDER_MIN_BUCKET_INDEX, LENDER_MAX_BUCKET_INDEX);
nit: extra spaces

2023-06-06 06:55 UTC, grandizzy commented on tests/forge/invariants/PositionsAndRewards/handlers/unbounded/BasePositionsHandler.sol
> +abstract contract BasePositionsHandler is BaseERC20PoolHandler {
why not merging this one with `UnboundedPositionsHandler`?

2023-06-06 06:55 UTC, grandizzy commented on tests/forge/invariants/PositionsAndRewards/handlers/unbounded/UnboundedPositionsHandler.sol
> +            assert (preActionFromIndexQuote + preActionToIndexQuote >= postActionFromIndexQuote + postActionToIndexQuote);
please use `require` and explicit revert message

2023-06-06 06:55 UTC, grandizzy commented on tests/forge/invariants/PositionsAndRewards/handlers/RewardsHandler.sol
> +        assertEq(_position.ownerOf(tokenId), _actor);
please use `require` with explicit revert message

2023-06-06 06:55 UTC, grandizzy commented on tests/forge/invariants/PositionsAndRewards/handlers/unbounded/UnboundedPositionsHandler.sol
> +            require(posIndexes.length == 0);
revert message needed in require

2023-06-06 06:55 UTC, grandizzy commented on tests/forge/invariants/PositionsAndRewards/handlers/unbounded/UnboundedPositionsHandler.sol
> +            require(posPreActionLps == 0);
revert message needed in require

2023-06-06 06:55 UTC, grandizzy commented on tests/forge/invariants/PositionsAndRewards/handlers/unbounded/UnboundedPositionsHandler.sol
> +                require(poolLps == bucketIndexToActorPoolLps[bucketIndex] + bucketIndexToPositionManPoolLps[bucketIndex]);
revert message needed in require

2023-06-06 06:55 UTC, grandizzy commented on tests/forge/invariants/PositionsAndRewards/handlers/unbounded/UnboundedPositionsHandler.sol
> +                require(poolDepositTime == bucketIndexToDepositTime[bucketIndex]);
revert message needed in require

2023-06-06 06:55 UTC, grandizzy commented on tests/forge/invariants/PositionsAndRewards/handlers/unbounded/UnboundedPositionsHandler.sol
> +                require(posLps == bucketIndexToActorPoolLps[bucketIndex]);
revert message needed in require

2023-06-06 06:55 UTC, grandizzy commented on tests/forge/invariants/PositionsAndRewards/handlers/unbounded/UnboundedPositionsHandler.sol
> +            require(_position.ownerOf(tokenId) == _actor);
revert message needed in require

2023-06-06 06:55 UTC, grandizzy commented on tests/forge/invariants/PositionsAndRewards/handlers/unbounded/UnboundedPositionsHandler.sol
> +            require(poolAddress == address(_pool));
revert message needed in require

2023-06-06 06:55 UTC, grandizzy commented on tests/forge/invariants/PositionsAndRewards/handlers/unbounded/UnboundedPositionsHandler.sol
> +            require(posIndexes.length == 0);
revert message needed in require

2023-06-06 06:55 UTC, grandizzy commented on tests/forge/invariants/PositionsAndRewards/handlers/unbounded/UnboundedPositionsHandler.sol
> +            require(posPreActionLps > 0);
revert message needed in require

2023-06-06 06:55 UTC, grandizzy commented on tests/forge/invariants/PositionsAndRewards/handlers/unbounded/UnboundedPositionsHandler.sol
> +                require(poolPosLps == positionManPoolLps - (poolActorLps - actorPoolLps));
revert message needed in require

2023-06-06 06:55 UTC, grandizzy commented on tests/forge/invariants/PositionsAndRewards/handlers/unbounded/UnboundedPositionsHandler.sol
> +                require(poolActorLps == actorPoolLps + (positionManPoolLps - poolPosLps));
revert message needed in require

2023-06-06 06:55 UTC, grandizzy commented on tests/forge/invariants/PositionsAndRewards/handlers/unbounded/UnboundedPositionsHandler.sol
> +                require(posLps == 0);
revert message needed in require

2023-06-06 06:55 UTC, grandizzy commented on tests/forge/invariants/PositionsAndRewards/handlers/unbounded/UnboundedPositionsHandler.sol
> +                require(posDepositTime == 0);
revert message needed in require

2023-06-06 06:55 UTC, grandizzy commented on tests/forge/invariants/PositionsAndRewards/handlers/unbounded/UnboundedPositionsHandler.sol
> +            require(fromLps == 0); // difficult to estimate LPS, assert that it is less than
revert message needed in require

2023-06-06 06:55 UTC, grandizzy commented on tests/forge/invariants/PositionsAndRewards/handlers/unbounded/UnboundedPositionsHandler.sol
> +            require(fromDepositTime == 0);
revert message needed in require

2023-06-06 06:55 UTC, grandizzy commented on tests/forge/invariants/PositionsAndRewards/handlers/unbounded/UnboundedPositionsHandler.sol
> +            require(toLps >= preActionToLps); // difficult to estimate LPS, assert that it is greater than
revert message needed in require

2023-06-06 06:55 UTC, grandizzy commented on tests/forge/invariants/PositionsAndRewards/handlers/unbounded/UnboundedPositionsHandler.sol
> +            require(toDepositTime == postActionDepositTime);
revert message needed in require

2023-06-06 06:55 UTC, grandizzy commented on tests/forge/invariants/PositionsAndRewards/handlers/unbounded/UnboundedPositionsHandler.sol
> +            require(poolAddress == address(0));
revert message needed in require

2023-06-06 06:55 UTC, grandizzy commented on tests/forge/invariants/interfaces/IBaseHandler.sol
> +    function totalRewardPerEpoch(uint256) external view returns(uint256);
suggest a different interface for pos / rewards handler

2023-06-06 18:34 UTC, ith-harvey commented on tests/forge/invariants/PositionsAndRewards/handlers/unbounded/BasePositionsHandler.sol
> +abstract contract BasePositionsHandler is BaseERC20PoolHandler {
I think this could be merged but @prateek105 did this to match the pattern that exists in the ERC20Pool and ERC721Pool invariant folders. He may be able to explain his thought process better. I beleive it keeps the variables separate from the methods, for improved readability.

2023-06-07 06:32 UTC, grandizzy commented on tests/forge/invariants/PositionsAndRewards/handlers/unbounded/BasePositionsHandler.sol
> +    PositionManager internal _position;
please name this `_positionManager` and `_rewardsManager` for readability

2023-06-07 13:50 UTC, ith-harvey commented on tests/forge/invariants/PositionsAndRewards/handlers/unbounded/BasePositionsHandler.sol
> +    PositionManager internal _position;
Yep, fixed -> https://github.com/ajna-finance/contracts/pull/854/commits/301a11c646a7e151cacad2badbff3a01e75778c4

2023-06-07 13:51 UTC, ith-harvey commented on tests/forge/invariants/interfaces/IBaseHandler.sol
> +    function totalRewardPerEpoch(uint256) external view returns(uint256);
fixed -> https://github.com/ajna-finance/contracts/pull/854/commits/c7c84e2087b263a12a521ef88739132696ec747a

2023-06-07 13:51 UTC, ith-harvey commented on tests/forge/invariants/PositionsAndRewards/handlers/PositionHandlerAbstract.sol
> +import { BaseERC20PoolHandler }     from '../../ERC20Pool/handlers/unbounded/BaseERC20PoolHandler.sol';
fixed

2023-06-07 13:54 UTC, ith-harvey commented on tests/forge/invariants/PositionsAndRewards/RewardsInvariants.t.sol
> +    function invariant_rewards_RW1() public useCurrentTimestamp {
added -> https://github.com/ajna-finance/contracts/pull/854/commits/c7c84e2087b263a12a521ef88739132696ec747a

2023-06-07 13:55 UTC, ith-harvey commented on tests/forge/invariants/PositionsAndRewards/handlers/unbounded/UnboundedPositionsHandler.sol
> +            require(fromDepositTime == 0);
fixed -> https://github.com/ajna-finance/contracts/pull/854/commits/c7c84e2087b263a12a521ef88739132696ec747a

2023-06-07 13:55 UTC, ith-harvey commented on tests/forge/invariants/PositionsAndRewards/handlers/unbounded/UnboundedPositionsHandler.sol
> +            require(toLps >= preActionToLps); // difficult to estimate LPS, assert that it is greater than
fixed -> https://github.com/ajna-finance/contracts/pull/854/commits/c7c84e2087b263a12a521ef88739132696ec747a

2023-06-07 13:55 UTC, ith-harvey commented on tests/forge/invariants/PositionsAndRewards/handlers/unbounded/UnboundedPositionsHandler.sol
> +            require(toDepositTime == postActionDepositTime);
fixed -> https://github.com/ajna-finance/contracts/pull/854/commits/c7c84e2087b263a12a521ef88739132696ec747a

2023-06-07 13:55 UTC, ith-harvey commented on tests/forge/invariants/PositionsAndRewards/handlers/unbounded/UnboundedPositionsHandler.sol
> +            require(poolAddress == address(0));
fixed -> https://github.com/ajna-finance/contracts/pull/854/commits/c7c84e2087b263a12a521ef88739132696ec747a

2023-06-07 13:56 UTC, ith-harvey commented on tests/forge/invariants/PositionsAndRewards/handlers/unbounded/UnboundedPositionsHandler.sol
> +            assert (preActionFromIndexQuote + preActionToIndexQuote >= postActionFromIndexQuote + postActionToIndexQuote);
fixed -> https://github.com/ajna-finance/contracts/pull/854/commits/c7c84e2087b263a12a521ef88739132696ec747a

2023-06-07 13:56 UTC, ith-harvey commented on tests/forge/invariants/PositionsAndRewards/handlers/RewardsHandler.sol
> +        assertEq(_position.ownerOf(tokenId), _actor);
fixed -> https://github.com/ajna-finance/contracts/pull/854/commits/c7c84e2087b263a12a521ef88739132696ec747a

2023-06-07 13:56 UTC, ith-harvey commented on tests/forge/invariants/PositionsAndRewards/handlers/unbounded/UnboundedPositionsHandler.sol
> +            require(posIndexes.length == 0);
fixed -> https://github.com/ajna-finance/contracts/pull/854/commits/c7c84e2087b263a12a521ef88739132696ec747a

2023-06-07 13:56 UTC, ith-harvey commented on tests/forge/invariants/PositionsAndRewards/handlers/unbounded/UnboundedPositionsHandler.sol
> +            require(posPreActionLps == 0);
fixed -> https://github.com/ajna-finance/contracts/pull/854/commits/c7c84e2087b263a12a521ef88739132696ec747a

2023-06-07 13:56 UTC, ith-harvey commented on tests/forge/invariants/PositionsAndRewards/handlers/unbounded/UnboundedPositionsHandler.sol
> +                require(poolLps == bucketIndexToActorPoolLps[bucketIndex] + bucketIndexToPositionManPoolLps[bucketIndex]);
fixed -> https://github.com/ajna-finance/contracts/pull/854/commits/c7c84e2087b263a12a521ef88739132696ec747a

2023-06-07 13:56 UTC, ith-harvey commented on tests/forge/invariants/PositionsAndRewards/handlers/unbounded/UnboundedPositionsHandler.sol
> +                require(poolDepositTime == bucketIndexToDepositTime[bucketIndex]);
fixed -> https://github.com/ajna-finance/contracts/pull/854/commits/c7c84e2087b263a12a521ef88739132696ec747a

2023-06-07 13:56 UTC, ith-harvey commented on tests/forge/invariants/PositionsAndRewards/handlers/unbounded/UnboundedPositionsHandler.sol
> +                require(posLps == bucketIndexToActorPoolLps[bucketIndex]);
fixed -> https://github.com/ajna-finance/contracts/pull/854/commits/c7c84e2087b263a12a521ef88739132696ec747a

2023-06-07 13:57 UTC, ith-harvey commented on tests/forge/invariants/PositionsAndRewards/handlers/unbounded/UnboundedPositionsHandler.sol
> +            require(_position.ownerOf(tokenId) == _actor);
fixed -> https://github.com/ajna-finance/contracts/pull/854/commits/c7c84e2087b263a12a521ef88739132696ec747a

2023-06-07 13:58 UTC, ith-harvey commented on tests/forge/invariants/PositionsAndRewards/handlers/unbounded/UnboundedPositionsHandler.sol
> +            require(poolAddress == address(_pool));
fixed -> https://github.com/ajna-finance/contracts/pull/854/commits/c7c84e2087b263a12a521ef88739132696ec747a

2023-06-07 13:58 UTC, ith-harvey commented on tests/forge/invariants/PositionsAndRewards/handlers/unbounded/UnboundedPositionsHandler.sol
> +            require(posIndexes.length == 0);
fixed -> https://github.com/ajna-finance/contracts/pull/854/commits/c7c84e2087b263a12a521ef88739132696ec747a

2023-06-07 13:58 UTC, ith-harvey commented on tests/forge/invariants/PositionsAndRewards/handlers/unbounded/UnboundedPositionsHandler.sol
> +            require(posPreActionLps > 0);
fixed -> https://github.com/ajna-finance/contracts/pull/854/commits/c7c84e2087b263a12a521ef88739132696ec747a

2023-06-07 13:59 UTC, ith-harvey commented on tests/forge/invariants/PositionsAndRewards/handlers/unbounded/UnboundedPositionsHandler.sol
> +                require(poolPosLps == positionManPoolLps - (poolActorLps - actorPoolLps));
fixed -> https://github.com/ajna-finance/contracts/pull/854/commits/c7c84e2087b263a12a521ef88739132696ec747a

2023-06-07 13:59 UTC, ith-harvey commented on tests/forge/invariants/PositionsAndRewards/handlers/unbounded/UnboundedPositionsHandler.sol
> +                require(poolActorLps == actorPoolLps + (positionManPoolLps - poolPosLps));
fixed -> https://github.com/ajna-finance/contracts/pull/854/commits/c7c84e2087b263a12a521ef88739132696ec747a

2023-06-07 13:59 UTC, ith-harvey commented on tests/forge/invariants/PositionsAndRewards/handlers/unbounded/UnboundedPositionsHandler.sol
> +                require(posLps == 0);
fixed -> https://github.com/ajna-finance/contracts/pull/854/commits/c7c84e2087b263a12a521ef88739132696ec747a

2023-06-07 13:59 UTC, ith-harvey commented on tests/forge/invariants/PositionsAndRewards/handlers/unbounded/UnboundedPositionsHandler.sol
> +                require(posDepositTime == 0);
fixed -> https://github.com/ajna-finance/contracts/pull/854/commits/c7c84e2087b263a12a521ef88739132696ec747a

2023-06-07 13:59 UTC, ith-harvey commented on tests/forge/invariants/PositionsAndRewards/handlers/unbounded/UnboundedPositionsHandler.sol
> +            require(fromLps == 0); // difficult to estimate LPS, assert that it is less than
fixed -: https://github.com/ajna-finance/contracts/pull/854/commits/c7c84e2087b263a12a521ef88739132696ec747a

2023-06-07 18:21 UTC, ith-harvey commented on tests/forge/invariants/PositionsAndRewards/PositionsInvariants.t.sol
> +        _position         = new PositionManager(_erc20poolFactory, _erc721poolFactory);
fixed

2023-06-07 18:38 UTC, grandizzy approved these changes
LGTM

2023-06-07 18:40 UTC, merged