Invariants improvement: add remaining rewards invariants
ajna-finance/ajna-core pull request #880
Opened 2023-06-07 19:31 UTC by ith-harvey

# Description of change
## High level
* Implemented the remaining rewards invariants
* on `claimRewards()` and `unstake()` the caller can receive both exchange update rewards and staking rewards. This causes the invariant tests to perform workarounds in order to track what a user is earning.
* `RW7` enforces check that an actor's ajna balance never exceed the rewards claimed. This is important as it works with `RW1` and `RW2` ensuring that a actor never receives ajna rewards in excess of their respective caps

2023-06-14 21:22 UTC, ith-harvey commented on tests/forge/invariants/PositionsAndRewards/handlers/unbounded/UnboundedPositionsHandler.sol
> +            _isPoolError(err_),
added this since I was getting pool errors when running invariants tests for positionManager and rewardsManager.

2023-06-14 21:22 UTC, ith-harvey commented on tests/forge/invariants/base/handlers/unbounded/UnboundedReservePoolHandler.sol
> +        // ensure actor always has the amount to take reserves
When we gave the user `type(uint256).max);` I was getting overflows. Followed what we had in regular auctions.

2023-06-15 01:47 UTC, MikeHathaway approved these changes
LGTM

2023-06-16 17:04 UTC, grandizzy requested changes

2023-06-16 17:04 UTC, grandizzy commented on tests/forge/invariants/PositionsAndRewards/handlers/RewardsHandler.sol
> +        uint256 tokenId = _preUnstake(_lenderBucketIndex, amountToAdd_);
I  think that's fine for now, but ideally this should receive `tokenId` as a fuzzed param , bounded to the array of staked tokens (to be cached when stake is called), and call unstake with that token id. Only if there's no staked token the current logic should be executed (stake / emergency unstake). Otherwise we always force the same logic / execution path and that's something we want to avoid.
Same should be done on `unstake` and `claimRewards`

2023-06-16 17:04 UTC, grandizzy commented on tests/forge/invariants/PositionsAndRewards/handlers/unbounded/UnboundedRewardsHandler.sol
> +            require(totalRewardsEarnedPreAction == totalRewardsEarnedPostAction,
this shouldn't be the case. on emergency unstake claimer gives up on rewards / rewards are not calculated /accumulated (`claimRewards_` is false here https://github.com/ajna-finance/contracts/blob/develop/src/RewardsManager.sol#L742)

2023-06-16 17:21 UTC, grandizzy approved these changes
approving this version, will work on refining them in subsequent PR

2023-06-16 17:47 UTC, merged