`updateRewardsClaimed()` and `rewardsClaimed()` become inaccurate once rewardsManager is out of ajna
ajna-finance/ajna-core pull request #888
Opened 2023-06-11 21:41 UTC by ith-harvey

# Description of change
## High level
* removed ajna balance restriction from `_transferAjnaRewards()`
* applied the ajna balance restriction on the rewarded amount in a new `enforceRewards()` method at a lower level in the logic flow. By applying the restriction at this depth `updateRewardsClaimed()` and `rewardsClaimed()` are altered properly across all calls against the contract.
* re-applied a ajna balance check inside `_calculateAndClaimAllRewards()` in the event `unstake()` is called and the caller should receive rewards for updating exchange rates and staking rewards
* added a `maxAmount_` argument to `_calculateAndClaimStakingRewards()` in order to ensure the amounts reduced from the `rewardsClaimed()` accumulator were accurate.
* SIDE EFFECT OF CHANGE: `calculateRewards()` now provides an accurate rewards calculation restricted by the ajna balance of the contract at the time the call is made.

# Description of bug or vulnerability and solution
There is a discrepancy in the `rewardsManger.sol` contract's reward accumulators and events when we apply the ajna balance restriction to the amount of rewards transferred to the updaters and staking claimers.
* `rewardsClaimed()` - was greater than the amount claimed by caller
* `updateRewardsClaimed()` - was greater than the amount claimed by caller
* `ClaimedRewards` event - was emitting a greater value then was actually claimed

# Contract size
## Pre Change
<PASTE_OUTPUT_HERE>
## Post Change
<PASTE_OUTPUT_HERE>

# Gas usage
## Pre Change
<PASTE_OUTPUT_HERE>
## Post Change
<PASTE_OUTPUT_HERE>

2023-06-12 02:29 UTC, EdNoepel reviewed
Some questions/concerns inline.  Also, PR description template needs gas/size numbers filled out.

2023-06-12 02:29 UTC, EdNoepel commented on src/RewardsManager.sol
> +            if (rewards_ + nextEpochRewards > maxReward_) nextEpochRewards = maxReward_ - rewards_;
This makes sense.

2023-06-12 02:29 UTC, EdNoepel commented on src/RewardsManager.sol
> -        if (transferAmount_ > ajnaBalance) transferAmount_ = ajnaBalance;
This check moved into `_calculateAndClaimAllRewards`.  `stake` and `updateBucketExchangeRatesAndClaim` call `_transferAjnaRewards` without calling `_calculateAndClaimAllRewards`.  Are there use cases where these methods can be called when contract balance is insufficiently low to transfer earned rewards?   If so, is an _insufficient balance_ revert desirable here?

2023-06-12 02:29 UTC, EdNoepel commented on src/RewardsManager.sol
> +        if (cappedRewards_ > ajnaBalance) cappedRewards_ = ajnaBalance;
nit: Stylistically, we usually write this in the form `cappedRewards = Maths.min(cappedRewards, ajnaBalance)`.

2023-06-12 03:53 UTC, grandizzy commented
> 

I am not sure I fully understand the problem, when it says `greater than the amount claimed by caller` in
```
rewardsClaimed() - was greater than the amount claimed by caller
updateRewardsClaimed() - was greater than the amount claimed by caller
ClaimedRewards event - was emitting a greater value then was actually claimed
```

you mean `greater than the amount received by claimer`?

2023-06-12 06:58 UTC, grandizzy requested changes
let's talk about this, how I see it is that accumulators should not reflect amount of tokens transferred to claimers but rather the total calculated rewards unconstrained by rewards manager token liquidity

2023-06-12 06:58 UTC, grandizzy commented on tests/forge/unit/Rewards/ClaimRewards.t.sol
> -            reward:  4.089939384822468148 * 1e18
this test is for `testClaimOnUpdateRateWithInsufficientFunds` and expose a difference between how much one should be rewarded in normal conditions (`reward:  4.089939384822468148 * 1e18`) vs how much they received because of the balance constraint (`assertEq(updaterBalance, 1 * 1e18);`). I don't see any issue with this, IMO would be wrong to emit transferred amount rather than the entitled rewards in `UpdateExchangeRates`  event. `Transfer` event will reflect 1 token transferred (constrained by contract balance)

2023-06-12 06:58 UTC, grandizzy commented on tests/forge/unit/Rewards/ClaimRewards.t.sol
> +            reward:  0
same as above, there will be a single event: `UpdateExchangeRates` with reward of `4.089939384822468148 * 1e18` and no `Transfer` event

2023-06-12 06:58 UTC, grandizzy commented on tests/forge/unit/Rewards/RewardsManager.t.sol
> +        // check reward generated is equal to the manager token balance
the rewards can be greater (if not enough token balance) or equal, but never less than contract balance

2023-06-13 10:19 UTC, ith-harvey commented
This functionality is to be expected, closing PR

2023-06-13 10:19 UTC, closed without merging