Invariants improvements: Position Manager invariants for ERC721Pool and multiple token precisions
ajna-finance/ajna-core pull request #889
Opened 2023-06-12 13:13 UTC by prat-gpt

# Description of change
## High level
* Add Position Manager invariants for ERC721Pool
* Add scripts to run Position manager invariants for ERC20/ERC721 Pool with multiple token precisions.

2023-06-13 07:18 UTC, grandizzy approved these changes
LGTM

2023-06-13 17:58 UTC, ith-harvey approved these changes
LGTM, thank you sir

2023-06-14 22:54 UTC, MikeHathaway commented on tests/forge/invariants/PositionsAndRewards/handlers/unbounded/UnboundedERC721PoolPositionsHandler.sol
> +            'PM8: previous owner is no longer owner on redemption');
There seem to be multiple different descriptions here all referencing the same `PM8`. We should update these to match the actual

2023-06-14 22:55 UTC, MikeHathaway commented on tests/forge/invariants/PositionsAndRewards/handlers/unbounded/UnboundedERC721PoolPositionsHandler.sol
> +            require(posIndexes.length == 0, "PM4: positions are associated with tokenId");
Same here: multiple different descriptions pointing to the same invariant number

2023-06-14 22:56 UTC, MikeHathaway requested changes
It's unclear which invariants are which in `UnboundedERC721PoolPositionsHandler`. We should make sure the invariant ID matches the appropriate description string

2023-06-15 13:59 UTC, prat-gpt commented on tests/forge/invariants/PositionsAndRewards/handlers/unbounded/UnboundedERC721PoolPositionsHandler.sol
> +            require(posIndexes.length == 0, "PM4: positions are associated with tokenId");
there are multiple description as all these things are checked in PM4 invariant. The error string with more precise descriptions I think is better than having same description for all of these require checks. The other way to resolve this would be to break this PM4 invariant and other similar big invariants into smaller specific invariants. I can break these into smaller ones if u agree in a following PR.

2023-06-15 19:06 UTC, MikeHathaway commented on tests/forge/invariants/PositionsAndRewards/handlers/unbounded/UnboundedERC721PoolPositionsHandler.sol
> +            require(posIndexes.length == 0, "PM4: positions are associated with tokenId");
I understand now. It's ok like this, a little confusing at first but makes sense.

2023-06-15 19:08 UTC, MikeHathaway approved these changes
LGTM

2023-06-16 05:08 UTC, merged