Rewards Invariants: Significant improvements
ajna-finance/ajna-core pull request #897
Opened 2023-06-18 23:24 UTC by ith-harvey

# Description of change
## High level
Continued iteration on RewardsManger.sol invaraints
  * calls to rewards handlers now prioritize existing NFT positions instead of always creating new ones
  * `updateExchangeRate()` now updates buckets with positions
  * positionManager and rewardsManager bucket index tracking cleanup
  * added missing pool errors in `_ensurePositionManagerError` method
  * adjusted how much quote token is added when position if first memorialized to get around `tokenID does not have lps associated on redemption` error
  * cleaned up unused `UnboundedBasePositionHandler` tracking
  * bound `updateExchangeRates()` now creates a position if none exist
  * Added rewards manager handler for erc721pool
  * added env var `MAX_EPOCHS_ADVANCE` which sets the maximum number of epochs you can advance the tests by for unstaking and claiming
  * refactored positionManager and rewardsManager handlers so they reuse the same baseclass
  
  ### Tests
  * Cleaned up some unit tests that were failing because they were ignored off of CL / CI check because of Makefile changes here: https://github.com/ajna-finance/contracts/commit/1692046f755a71d34df505e3eb3420a53e6e8aa8#diff-76ed074a9305c04054cdebb9e9aad2d818052b07091de1f20cad0bbac34ffb52L5

2023-06-20 05:22 UTC, grandizzy submitted a review, later dismissed
lgtm

2023-06-22 02:26 UTC, grandizzy commented on tests/forge/invariants/regression_generator.py
> -handler_prefix = '_' + ''.join(full_handler[:1].lower())
why the change?

2023-06-23 15:43 UTC, ith-harvey commented on tests/forge/invariants/regression_generator.py
> -handler_prefix = '_' + ''.join(full_handler[:1].lower())
Accident, fixed -> https://github.com/ajna-finance/contracts/pull/897/commits/51a1049cd1185a782c87116d32d1be8ab2a60822

2023-06-27 19:18 UTC, MikeHathaway commented on tests/README.md
> +| MAX_EPOCH_ADVANCE | ERC20 ERC721 | 2 | The maximum number of epochs that will be created before an unstake or claimRewards call |
This default feels a little too low - what about 5?

2023-06-27 19:44 UTC, MikeHathaway commented on tests/forge/invariants/PositionsAndRewards/handlers/ERC20PoolRewardsHandler.sol
> +            _updateExchangeRate(indexes_);
Are we making the tests overly structured by automatically updating exchange rates as part of creating reserves? Worried that we're missing out on testing how the system reacts to partial exchange rate updates which contains a lot of logical complexity

2023-06-27 19:45 UTC, MikeHathaway commented on tests/forge/invariants/PositionsAndRewards/handlers/ERC20PoolRewardsHandler.sol
> +            uint256 boundedTakeAmount = constrictToRange(amountToAdd_, claimableReserves / 2, claimableReserves);
Is there any benefit to configurable take amounts?

2023-06-27 19:48 UTC, MikeHathaway commented on tests/forge/invariants/PositionsAndRewards/handlers/ERC721PoolRewardsHandler.sol
> +    function _preStake(
Can we put these methods into a single file and inheriting from it? The `Prepare Test Functions` seem to be duplicated between ERC20 and ERC721 Pools which will make maintenance much more difficult

2023-06-27 19:51 UTC, MikeHathaway commented on tests/forge/invariants/PositionsAndRewards/handlers/unbounded/UnboundedERC20PoolPositionsHandler.sol
> +            uint256 positionManMangerLps;
Naming on this one is a bit awkward - duplicate Man

2023-06-27 19:55 UTC, MikeHathaway commented on tests/forge/invariants/PositionsAndRewards/handlers/unbounded/UnboundedERC20PoolPositionsHandler.sol
> +            // assert PositionsMan LP in pool matches the amount redeemed by actor
These checks are great - would there be any value in also checking the individual indexes lp amount as well as the net amount?

2023-06-27 20:07 UTC, MikeHathaway reviewed
Overall looks great - just a few comments about potential improvements but would be ok with addressing those as part of a future PR.

2023-06-27 20:14 UTC, MikeHathaway commented
Also, looking at the Position invariants more generally - is there ever a situation in which a NFT has more than three indexes associated with it? Currently seems like that's the cap unless i'm missing something

2023-06-29 12:58 UTC, ith-harvey commented on tests/forge/invariants/PositionsAndRewards/handlers/unbounded/UnboundedERC20PoolPositionsHandler.sol
> +            // assert PositionsMan LP in pool matches the amount redeemed by actor
I used to have this but it caused the tests to have a mapping that was difficult to clean up and ultimately looked sloppy. Tried pushing to an array as well but same thing, didn't come out as clean.

The total variables can be built up and torn down cleanly in the scope of the function, which I prefer.

2023-06-29 13:01 UTC, ith-harvey commented on tests/forge/invariants/PositionsAndRewards/handlers/unbounded/UnboundedERC20PoolPositionsHandler.sol
> +            uint256 positionManMangerLps;
Fixed -> https://github.com/ajna-finance/contracts/pull/897/commits/45ccb2a8b987be40241d0db3fe7580ef6af46d52

2023-06-29 13:01 UTC, ith-harvey commented on tests/README.md
> +| MAX_EPOCH_ADVANCE | ERC20 ERC721 | 2 | The maximum number of epochs that will be created before an unstake or claimRewards call |
fixed -> https://github.com/ajna-finance/contracts/pull/897/commits/45ccb2a8b987be40241d0db3fe7580ef6af46d52

2023-06-29 18:12 UTC, ith-harvey commented on tests/forge/invariants/PositionsAndRewards/handlers/ERC20PoolRewardsHandler.sol
> +            _updateExchangeRate(indexes_);
fixed -> https://github.com/ajna-finance/contracts/pull/897/commits/a5ca30bfaf3f0dec38af40156f3a9bb4ba3aa2cd

2023-06-29 18:53 UTC, ith-harvey commented on tests/forge/invariants/PositionsAndRewards/handlers/ERC20PoolRewardsHandler.sol
> +            uint256 boundedTakeAmount = constrictToRange(amountToAdd_, claimableReserves / 2, claimableReserves);
Since the remainders of takes are carried over from one auction to another I don't think it offers much utility to rewards testing but may be something worth adding to better test reserve auctions generally.

I can put on my todos for another PR

2023-06-29 19:02 UTC, ith-harvey commented
> Also, looking at the Position invariants more generally - is there ever a situation in which a NFT has more than three indexes associated with it? Currently seems like that's the cap unless i'm missing something

Unfortunatley worse than that -> https://github.com/ajna-finance/contracts/blob/a5ca30bfaf3f0dec38af40156f3a9bb4ba3aa2cd/tests/forge/invariants/PositionsAndRewards/handlers/BaseERC20PoolPositionHandler.sol#L129

Only one bucket in the current set of tests. Wanted to get everything else working then come back in with varying indexes as it's own PR since it is a significant complexity add. I'll start working on that next as I think that is a big priority.

2023-06-29 19:36 UTC, ith-harvey commented on tests/forge/invariants/PositionsAndRewards/handlers/ERC721PoolRewardsHandler.sol
> +    function _preStake(
I agree, suggest a future PR for this guy

2023-06-29 20:04 UTC, MikeHathaway commented on tests/forge/invariants/PositionsAndRewards/handlers/unbounded/UnboundedERC20PoolPositionsHandler.sol
> +            // assert PositionsMan LP in pool matches the amount redeemed by actor
I think the priority should be on robustness of test over code elegance. It should still be possible to delete a global mapping for tear down, and it would be expected for many of these checks to rely on global state. Furthermore, we might actually prefer global state tracking as it massively improves our introspection into the system.

2023-06-30 03:14 UTC, EdNoepel requested changes
Issues:
- ERC*PoolRewardsHandler should have a collateral-neutral baseclass rather than copypastaed methods.  Would rather we not add technical debt by doing it in a separate PR.
- Compilation warnings should be resolved.
- First run of `make test-invariants-all` with 18 decimal pool, default depth, produced `[FAIL. Reason: tokenID does not have lps associated on redemption] ` error in `ERC20PoolRewardsInvariants`.

2023-06-30 03:14 UTC, EdNoepel commented on tests/forge/invariants/PositionsAndRewards/handlers/unbounded/UnboundedERC20PoolPositionsHandler.sol
> +
nit: whitespace

2023-06-30 03:14 UTC, EdNoepel commented on tests/forge/invariants/PositionsAndRewards/handlers/unbounded/UnboundedERC721PoolRewardsHandler.sol
> +            totalRewardsEarnedPreAction  += _rewardsManager.rewardsClaimed(epoch) + _rewardsManager.updateRewardsClaimed(epoch);
nit: whitespace

2023-06-30 03:14 UTC, EdNoepel commented on tests/forge/regression/PositionAndRewards/RegressionTestERC721PoolPositionManager.t copy.sol
Why does this filename end in `.t copy.sol`?  Seems unintentional.

2023-06-30 03:14 UTC, EdNoepel commented on tests/forge/invariants/PositionsAndRewards/handlers/ERC20PoolRewardsHandler.sol
> +    ) internal returns (uint256[] memory boundBuckets_) {
This should be a `view`.

2023-06-30 03:14 UTC, EdNoepel commented on tests/forge/invariants/PositionsAndRewards/handlers/ERC721PoolRewardsHandler.sol
> +    ) internal returns (uint256[] memory boundBuckets_) {
This should be a `view`.  Really, this method, along with others, should be refactored into a common base instead of copypastaed across ERC20/ERC721.

2023-07-03 04:44 UTC, ith-harvey commented on tests/forge/regression/PositionAndRewards/RegressionTestERC721PoolPositionManager.t copy.sol
fixed -> https://github.com/ajna-finance/contracts/pull/897/commits/5f112b3a3d09e5ca74b15fdcd50eaa0c72351a11

2023-07-03 04:44 UTC, ith-harvey commented on tests/forge/invariants/PositionsAndRewards/handlers/unbounded/UnboundedERC20PoolPositionsHandler.sol
> +
removed in refactor -> https://github.com/ajna-finance/contracts/pull/897/commits/03448b0189b9055b7ef2bb84c4decadc188354f9

2023-07-03 04:45 UTC, ith-harvey commented on tests/forge/invariants/PositionsAndRewards/handlers/unbounded/UnboundedERC721PoolRewardsHandler.sol
> +            totalRewardsEarnedPreAction  += _rewardsManager.rewardsClaimed(epoch) + _rewardsManager.updateRewardsClaimed(epoch);
cleaned up in refactor -> https://github.com/ajna-finance/contracts/pull/897/commits/6c9950a291995fe51350c8d10d58f6ff9f0d840c

2023-07-03 04:49 UTC, ith-harvey commented on tests/forge/invariants/PositionsAndRewards/handlers/unbounded/UnboundedERC20PoolPositionsHandler.sol
> +            // assert PositionsMan LP in pool matches the amount redeemed by actor
changed back to mapping -> https://github.com/ajna-finance/contracts/pull/897/commits/6c9950a291995fe51350c8d10d58f6ff9f0d840c

Trade off between totals and mapping is by checking each index we rule out the tests passing if the LP didn't move correctly across indexes but still totals correctly.

2023-07-03 04:49 UTC, ith-harvey commented on tests/forge/invariants/PositionsAndRewards/handlers/ERC20PoolRewardsHandler.sol
> +    ) internal returns (uint256[] memory boundBuckets_) {
fixed -> https://github.com/ajna-finance/contracts/pull/897/commits/03448b0189b9055b7ef2bb84c4decadc188354f9

2023-07-03 04:49 UTC, ith-harvey commented on tests/forge/invariants/PositionsAndRewards/handlers/ERC721PoolRewardsHandler.sol
> +    ) internal returns (uint256[] memory boundBuckets_) {
fixed -> https://github.com/ajna-finance/contracts/pull/897/commits/03448b0189b9055b7ef2bb84c4decadc188354f9

2023-07-03 09:51 UTC, prat-gpt commented on tests/forge/regression/PositionAndRewards/RegressionTestRewardsManager.t.sol
the filename can be `RegressionTestERC20PoolRewardsManager`.

2023-07-03 09:51 UTC, prat-gpt commented on tests/forge/regression/PositionAndRewards/RegressionTestPositionManager.t.sol
The filename can be same as contract `RegressionTestERC20PoolPositionManager `.

2023-07-03 15:44 UTC, MikeHathaway commented on tests/forge/invariants/PositionsAndRewards/ERC20PoolPositionsInvariants.t.sol
> +            bytes32(keccak256("ERC20_NON_SUBSET_HASH")),
Since this value is constant, we don't really need to pass it as a param. The ERC20PoolPositionHandler should always use that hash

2023-07-03 16:47 UTC, EdNoepel reviewed
Looking much better.  Agree with other reviewers' comments.

2023-07-03 16:47 UTC, EdNoepel commented on tests/forge/invariants/PositionsAndRewards/ERC721PoolPositionsInvariants.t.sol
> +            bytes32(keccak256("ERC721_NON_SUBSET_HASH")),
Agree with Mike: https://github.com/ajna-finance/contracts/pull/897/files#r1251053928

2023-07-03 16:47 UTC, EdNoepel commented on tests/forge/invariants/PositionsAndRewards/handlers/unbounded/UnboundedBasePositionHandler.sol
> +    uint256 MAX_AJNA_AMOUNT = vm.envOr("MAX_AJNA_AMOUNT_ERC20", uint256(100_000_000 * 1e18));
I know this PR does not introduce it, but I don't see this variable documented in the README.

2023-07-03 16:47 UTC, EdNoepel commented on tests/forge/invariants/PositionsAndRewards/handlers/ERC20PoolRewardsHandler.sol
> +    ) internal returns (uint256[] memory boundBuckets_) {
Is `pure` now; even better.

2023-07-03 18:28 UTC, ith-harvey commented on tests/forge/invariants/PositionsAndRewards/handlers/unbounded/UnboundedBasePositionHandler.sol
> +    uint256 MAX_AJNA_AMOUNT = vm.envOr("MAX_AJNA_AMOUNT_ERC20", uint256(100_000_000 * 1e18));
fixed -> https://github.com/ajna-finance/contracts/pull/897/commits/1baa56a67be0d5b8c4918e6ceaf0d544c8eb559a

2023-07-03 18:29 UTC, ith-harvey commented on tests/forge/invariants/PositionsAndRewards/ERC721PoolPositionsInvariants.t.sol
> +            bytes32(keccak256("ERC721_NON_SUBSET_HASH")),
fixed -> https://github.com/ajna-finance/contracts/pull/897/commits/1baa56a67be0d5b8c4918e6ceaf0d544c8eb559a

2023-07-03 18:29 UTC, ith-harvey commented on tests/forge/invariants/PositionsAndRewards/ERC20PoolPositionsInvariants.t.sol
> +            bytes32(keccak256("ERC20_NON_SUBSET_HASH")),
fixed -> https://github.com/ajna-finance/contracts/pull/897/commits/1baa56a67be0d5b8c4918e6ceaf0d544c8eb559a

2023-07-03 18:29 UTC, ith-harvey commented on tests/forge/regression/PositionAndRewards/RegressionTestPositionManager.t.sol
fixed -> https://github.com/ajna-finance/contracts/pull/897/commits/1baa56a67be0d5b8c4918e6ceaf0d544c8eb559a

2023-07-03 18:29 UTC, ith-harvey commented on tests/forge/regression/PositionAndRewards/RegressionTestRewardsManager.t.sol
fixed -> https://github.com/ajna-finance/contracts/pull/897/commits/1baa56a67be0d5b8c4918e6ceaf0d544c8eb559a

2023-07-03 18:51 UTC, MikeHathaway commented on tests/forge/invariants/PositionsAndRewards/handlers/unbounded/UnboundedERC20PoolPositionsHandler.sol
> +            // assert PositionsMan LP in pool matches the amount redeemed by actor
Not sure i'm following - can you explain why the tests wont pass / how LP wouldn't move correctly? Shouldn't we still be able to track this state? The ordering may be different but that can be corrected

2023-07-03 18:55 UTC, MikeHathaway commented on tests/forge/invariants/PositionsAndRewards/handlers/unbounded/UnboundedPositionPoolHandler.sol
> +            // cleanup buckets so they don't interfere with future calls
Might be missing something but we should be able to remove these deletions from the catch block since the transaction would have already failed to update state

2023-07-03 18:56 UTC, MikeHathaway commented on tests/forge/invariants/PositionsAndRewards/handlers/unbounded/UnboundedPositionPoolHandler.sol
> +            for ( uint256 i = 0; i < indexes_.length; i++) {
same here - not sure we should be updating state on failed transactions

2023-07-03 18:58 UTC, ith-harvey commented on tests/forge/invariants/PositionsAndRewards/handlers/unbounded/UnboundedPositionPoolHandler.sol
> +            // cleanup buckets so they don't interfere with future calls
Yeah, I don't like it either... suggest we go back to totals personally or I can try the array route again. Reason is here: https://github.com/ajna-finance/contracts/pull/897/files/1baa56a67be0d5b8c4918e6ceaf0d544c8eb559a#diff-4b4e73069bf8962689af5e2c8a6d47d02b09c0c7fa5363e2a90dbb2d9fa7fb5bR46

We set the values before the try and if the tx fails then they don't get cleaned up and the data effects subsequent calls.

2023-07-03 18:59 UTC, ith-harvey commented on tests/forge/invariants/PositionsAndRewards/handlers/unbounded/UnboundedPositionPoolHandler.sol
> +            for ( uint256 i = 0; i < indexes_.length; i++) {
see -> https://github.com/ajna-finance/contracts/pull/897#discussion_r1251200838

2023-07-03 19:12 UTC, MikeHathaway commented on tests/forge/invariants/PositionsAndRewards/handlers/unbounded/UnboundedPositionPoolHandler.sol
> +            // cleanup buckets so they don't interfere with future calls
That approach feels dangerous. It would be a lot simpler to just keep the values in local memory variables, and then update global state in the `try` block upon a succesful call. If that call fails, then the memory values are discarded automatically without us having to write the additional loop and check that every value is properly deleted (as opposed to doing it in a single spot)

2023-07-03 19:15 UTC, ith-harvey commented on tests/forge/invariants/PositionsAndRewards/handlers/unbounded/UnboundedPositionPoolHandler.sol
> +            // cleanup buckets so they don't interfere with future calls
Agree with the approach, my understanding is you can't initialize a mapping in memory... needs to be storage.

I'll re-try array the array again and see if I can make it cleaner.

2023-07-03 19:23 UTC, MikeHathaway commented on tests/forge/invariants/PositionsAndRewards/handlers/unbounded/UnboundedPositionPoolHandler.sol
> +            // cleanup buckets so they don't interfere with future calls
Gotcha, yeah i think the mapping needs to be in storage, but you could also create a separate mapping for the local, and then only update the globally available mapping in the try block (similar to how we pass storage mappings to libraries, we can manipulate the scope)

2023-07-03 20:23 UTC, EdNoepel approved these changes
I'm good with this now.

2023-07-03 20:34 UTC, ith-harvey commented on tests/forge/invariants/PositionsAndRewards/handlers/unbounded/UnboundedERC20PoolPositionsHandler.sol
> +            // assert PositionsMan LP in pool matches the amount redeemed by actor
Spoke with @MikeHathaway we decieded the LP tracking / invariants could use a more significant revamp.  Conclusion was to tackle this in a separate PR

2023-07-03 20:47 UTC, MikeHathaway commented on tests/forge/invariants/PositionsAndRewards/RewardsInvariants.t.sol
> +        console.log("--Rewards--------");
Out of scope for this PR, but we should also expand logging to gain introspection into the state of the invariants. Can help us increase certainty and answer questions like which buckets have lps at the end of the scenario, and how much lp is in those buckets. Which actors claimed the most rewards, were some buckets more likely to be updated than others, etc

2023-07-03 20:48 UTC, MikeHathaway approved these changes
LGTM. Still improvements to be made, but happy to merge this as is given it's a major step forward and it's becoming increasingly difficult to track changes via this PR.

2023-07-04 04:07 UTC, prat-gpt approved these changes
lgtm.

2023-07-04 05:16 UTC, MikeHathaway commented on tests/forge/invariants/PositionsAndRewards/handlers/unbounded/UnboundedPositionPoolHandler.sol
> +            // info for tear down
See references to `tear down` frequently, but doesn't really seem to be what's occurring here?

2023-07-04 09:15 UTC, merged