Bug fix: use better precision when calculating quote tokens in `_calculateTakeFlowsAndBondChange`
ajna-finance/ajna-core pull request #898
Opened 2023-06-19 07:22 UTC by grandizzy

# Description of change
## High level
* Big exchange rate deviation on a bucket take in a pool with high quote token precision (18) / low collateral token precision (4)
```
  ======================================
  Bucket Index           --> 2572
  Previous exchange Rate --> 1000000000301411858
  Current exchange Rate  --> 892630847785426572
  Current bucket lps     --> 1813515122673179981
  ======================================
```
  * due to the way `t0RepayAmount` and `unscaledQuoteTokenAmount` were calculated in `_calculateTakeFlowsAndBondChange` function, for a pool with collateral precision < quote token, the resulting exchange rate deviated with more than 1e16 than previous exchange rate
  * fixed by using OZ's `Math.mulDiv` to calculate quote amounts
  * lowered invariant deviation to `1e8` (could be lowered more, in the regression test now previous and current exchange rate are equal)
 ```
  ======================================
  Bucket Index           --> 2572
  Previous exchange Rate --> 1000000000301411858
  Current exchange Rate  --> 1000000000301411858
  Current bucket lps     --> 1813515122673179981
  ======================================
```

# Contract size
## Pre Change
```
TakerActions             -  15,104B  (61.46%)
```
## Post Change
```
TakerActions             -  15,148B  (61.63%)
```

# Gas usage
## Pre Change
```
| bucketTake                           | 309224          | 327865 | 327866 | 346507  | 4       |
| take                                 | 81754           | 83331  | 83067  | 315373  | 15998   |
```
## Post Change
```
| Function Name                        | min             | avg    | median | max     | # calls |
| bucketTake                           | 309332          | 348904 | 328264 | 429755  | 4       |
| take                                 | 81754           | 83331  | 83067  | 315373  | 15998   |
```

2023-06-19 15:30 UTC, mattcushman requested changes
i think we're using the wrong price at one place in `calculateTakeFlows`.  This should not affect bucket exchange rates, but will impact the residual debt (basically with the current bug, in bucketTake in one case the lenders are paying the bond).

2023-06-19 15:30 UTC, mattcushman commented on tests/forge/invariants/base/BasicInvariants.t.sol
> +                        1e8,  // otherwise require exchange rates to be within 1e-10,
nice

2023-06-19 15:30 UTC, mattcushman commented on tests/forge/unit/ERC20Pool/ERC20PoolLiquidationsArbTake.t.sol
> +            deposit:      10,
slightly ungainly that this remains now, but I think that it makes sense now that we recompute the deposit remaining based on the collateral actually taken

2023-06-19 15:30 UTC, mattcushman commented on src/libraries/external/TakerActions.sol
> +            vars.t0RepayAmount            = Math.mulDiv(vars.collateralAmount, vars.auctionPrice, inflator_);
I think that this should actually be `vars.borrowerPrice`.  My mistake.

2023-06-19 16:04 UTC, EdNoepel approved these changes
LGTM.

2023-06-19 16:04 UTC, EdNoepel commented on src/libraries/external/TakerActions.sol
> +            vars.t0RepayAmount            = Math.mulDiv(vars.collateralAmount, vars.auctionPrice, inflator_);
Before, `vars.t0RepayAmount` was calculated prior to `vars.quoteTokenAmount` being mutated.  Is now fine to calculate after, because `vars.quoteTokenAmount` is no longer in the calculation.

2023-06-19 16:04 UTC, EdNoepel commented on tests/forge/unit/ERC20Pool/ERC20PoolLiquidationsArbTake.t.sol
> +            deposit:      10,
Was it intentional to leave this infinitesimal amount in the bucket?

2023-06-19 16:04 UTC, EdNoepel commented on tests/forge/unit/ERC721Pool/ERC721PoolLiquidationsSettleAuction.t.sol
> +            borrowerDebt:              7_437.077367881532976520 * 1e18,
Significant impact on debt.

2023-06-19 18:05 UTC, grandizzy commented on src/libraries/external/TakerActions.sol
> +            vars.t0RepayAmount            = Math.mulDiv(vars.collateralAmount, vars.auctionPrice, inflator_);
fixed with https://github.com/ajna-finance/contracts/pull/898/commits/a752f45748c2bff115c5ff6e027c15d266aa7d9e

2023-06-19 18:31 UTC, grandizzy commented on tests/forge/unit/ERC721Pool/ERC721PoolLiquidationsSettleAuction.t.sol
> +            borrowerDebt:              7_437.077367881532976520 * 1e18,
that was actually a bug solved with https://github.com/ajna-finance/contracts/pull/898/commits/a752f45748c2bff115c5ff6e027c15d266aa7d9e

2023-06-19 18:34 UTC, grandizzy commented on tests/forge/unit/ERC20Pool/ERC20PoolLiquidationsArbTake.t.sol
> +            deposit:      10,
see Matt comment https://github.com/ajna-finance/contracts/pull/898#discussion_r1234198292

2023-06-19 18:39 UTC, mattcushman approved these changes
lgtm

2023-06-19 18:39 UTC, mattcushman commented on tests/forge/unit/ERC721Pool/ERC721PoolCollateral.t.sol
> +                poolDebt:             439.681348088864224563 * 1e18,
this looks much better now

2023-06-20 20:39 UTC, ith-harvey approved these changes

2023-06-21 04:00 UTC, MikeHathaway commented on src/libraries/external/TakerActions.sol
> -            vars.unscaledQuoteTokenAmount = Maths.wdiv(borrowerCollateralValue, vars.bucketScale);
Do we still need the `borrowerCollateralValue` if its now used just once?

2023-06-21 04:02 UTC, MikeHathaway approved these changes
LGTM - just one comment about potentially removing another variable

2023-06-21 04:38 UTC, prat-gpt approved these changes
LGTM!

2023-06-21 05:03 UTC, grandizzy commented on src/libraries/external/TakerActions.sol
> -            vars.unscaledQuoteTokenAmount = Maths.wdiv(borrowerCollateralValue, vars.bucketScale);
yeah, it's actually used twice in determining the branch to calculate take amount

2023-06-21 05:04 UTC, merged

2023-07-03 23:59 UTC, dmitriia commented on src/libraries/external/TakerActions.sol
>          }
Looks ok for handling numerical corner cases. It can be somewhat generalized, for example:

https://github.com/ajna-finance/contracts/blob/94be5c24dc448a9a0e914036450ac57b00c5ad11/src/libraries/external/TakerActions.sol#L749-L778

```diff
        vars.quoteTokenAmount = (vars.unscaledDeposit != type(uint256).max) ? Maths.wmul(vars.unscaledDeposit, vars.bucketScale) : type(uint256).max;

        uint256 borrowerCollateralValue = Maths.wmul(totalCollateral_, borrowerPrice);
        
        if (vars.quoteTokenAmount <= vars.borrowerDebt && vars.quoteTokenAmount <= borrowerCollateralValue) {
            // quote token used to purchase is constraining factor
            vars.collateralAmount         = _roundToScale(Maths.wdiv(vars.quoteTokenAmount, borrowerPrice), collateralScale_);
-           vars.quoteTokenAmount         = Maths.wmul(vars.collateralAmount, vars.auctionPrice);
            vars.t0RepayAmount            = Math.mulDiv(vars.collateralAmount, borrowerPrice, inflator_);
            vars.unscaledQuoteTokenAmount = Maths.min(
                vars.unscaledDeposit,
                Math.mulDiv(vars.collateralAmount, borrowerPrice, vars.bucketScale)
            );

        } else if (vars.borrowerDebt <= borrowerCollateralValue) {
            // borrower debt is constraining factor
            vars.collateralAmount         = _roundToScale(Maths.wdiv(vars.borrowerDebt, borrowerPrice), collateralScale_);
-           vars.t0RepayAmount            = vars.t0BorrowerDebt;
-           vars.unscaledQuoteTokenAmount = Maths.wdiv(vars.borrowerDebt, vars.bucketScale);
+           vars.t0RepayAmount            = Maths.min(
+               vars.t0BorrowerDebt,
+               Math.mulDiv(vars.collateralAmount, borrowerPrice, inflator_)
+           );
+           vars.unscaledQuoteTokenAmount = Math.mulDiv(vars.collateralAmount, borrowerPrice, vars.bucketScale);

-           vars.quoteTokenAmount         = (vars.isRewarded) ? Maths.wdiv(vars.borrowerDebt, borrowerPayoffFactor) : vars.borrowerDebt;

        } else {
            // collateral available is constraint
            vars.collateralAmount         = totalCollateral_;
            vars.t0RepayAmount            = Math.mulDiv(totalCollateral_, borrowerPrice, inflator_);
            vars.unscaledQuoteTokenAmount = Math.mulDiv(totalCollateral_, borrowerPrice, vars.bucketScale);

-           vars.quoteTokenAmount         = Maths.wmul(vars.collateralAmount, vars.auctionPrice);
        }
+       vars.quoteTokenAmount         = Maths.wmul(vars.collateralAmount, vars.auctionPrice);
```

2023-07-04 12:13 UTC, mattcushman commented on src/libraries/external/TakerActions.sol
>          }
This would result in slightly different computation of quoteTokenAmount in the middle (debt constrained) case it seems.  Consider the easier case of the bond getting penalized; one is `vars.borrrowerDebt` and the new proposal would be `Maths.wmul(_roundToScale(Maths.wdiv(vars.borrowerDebt, vars.auctionPrice), collateralScale_), vars.auctionPrice);` if I read this correctly?

2023-07-04 13:00 UTC, dmitriia commented on src/libraries/external/TakerActions.sol
>          }
Borrower debt is a constraint in this case, but then collateral amount is calculated off it with rounding. One approach is to say it will be full constraint utilized (in this approach it should be just `vars.unscaledQuoteTokenAmount = vars.unscaledDeposit` in the previous case, as an example), another, which is de facto proposed with this PR, is to recalculate everything from the real collateral amount, which is rounded and do not strictly corresponding to the constraint used. I believe you written the formula correctly, it is collateral amount from `borrowerDebt` first, then `quoteTokenAmount` off actually used collateral.