Sherlock-35 Final: Nonce is not incremented, leading to signature replay
ajna-finance/ajna-core pull request #906
Opened 2023-06-23 14:07 UTC by prat-gpt

# Description of change
## High level
* Nonce is not incremented in `permit` which allows the user to replay the same signature even after the owner manually revokes his approval after `permit`.
* Fixed with Increment nonces in approve to avoid signature replay.

# Description of bug or vulnerability and solution
* See - https://github.com/sherlock-audit/2023-04-ajna-judging/issues/35
* Fixed with incrementing nonces in approve

2023-06-23 18:02 UTC, MikeHathaway approved these changes
LGTM

2023-06-26 10:02 UTC, grandizzy approved these changes

2023-06-26 21:28 UTC, ith-harvey requested changes
The links that summarize the issue are dead, please copy and paste the issue into the description

2023-06-26 21:52 UTC, ith-harvey approved these changes
LGTM

2023-06-28 17:00 UTC, EdNoepel approved these changes
Surprised that OpenZeppelin does not offer a subclass with EIP-4494 permit support.  Looks good.

2023-06-28 17:23 UTC, merged

2023-06-28 18:01 UTC, MikeHathaway commented on tests/forge/unit/Positions/PositionManager.t.sol
> +        assertEq(_positionManager.nonces(tokenId), 2);
Looking at this more - why is this 2? Shouldn't this still be 1?

2023-06-29 02:29 UTC, MikeHathaway commented on tests/forge/unit/Positions/PositionManager.t.sol
> +        assertEq(_positionManager.nonces(tokenId), 2);
I suppose due to the duplicate nonce incrementing in this implementation