Sherlock-31 Final: EIP 4494 compliance
ajna-finance/ajna-core pull request #907
Opened 2023-06-23 14:10 UTC by prat-gpt

# Description of change
## High level
* The `PermitERC721` and `PositionManager` contracts do not satisfy the requirements of the `EIP-4494` standard. Specifically, they lack the implementation of the IERC165 interface and do not indicate support for the 0x5604e225 interface. These discrepancies, mark the contracts as non-compliant with the EIP-4494 standard, which could lead to potential interoperability issues. https://github.com/sherlock-audit/2023-04-ajna-judging/issues/31
* Add `supportsInterface` for EIP-4494 compliance

2023-06-23 18:01 UTC, MikeHathaway commented on src/base/PermitERC721.sol
> +            interfaceId == type(IPermit).interfaceId || // 0x5604e225
can just use the constant bytes4 in the equality check and have the derivation in the comment to save gas.

2023-06-26 18:00 UTC, MikeHathaway requested changes
---We already have an external `nonces` method implemented--- This is just for the interface

2023-06-26 18:02 UTC, MikeHathaway approved these changes
LGTM

2023-06-26 18:05 UTC, grandizzy commented
> We already have an external `nonces` method implemented

I think the new function is only in interface that is overriden by existing one

2023-06-26 21:29 UTC, ith-harvey submitted a review, later dismissed
The links that summarize the issue may die... please copy and paste the issue into the description directly

2023-06-27 04:30 UTC, grandizzy approved these changes
LGTM

2023-06-28 17:05 UTC, EdNoepel commented on src/base/PermitERC721.sol
> +            interfaceId == type(IPermit).interfaceId || // 0x5604e225
Since this is less likely to be called from a contract in a transaction, I'm happy with it as-is for readability tradeoff.

2023-06-28 17:07 UTC, EdNoepel approved these changes
As mentioned in the other PR, I'm surprised OZ does not offer a fully-baked EIP-4494-compliant ERC-721 token.

2023-06-28 18:40 UTC, grandizzy commented
> The links that summarize the issue may die... please copy and paste the issue into the description directly

done

2023-06-28 18:49 UTC, ith-harvey approved these changes
LGTM

2023-06-28 18:54 UTC, merged