Sherlock-110: revert add settleable
ajna-finance/ajna-core pull request #909
Opened 2023-06-23 18:42 UTC by mattcushman

# Description of change
## High level
* see https://github.com/sherlock-audit/2023-04-ajna-judging/issues/110
  * do not allow adding quote tokens into the pool if there's auction to settle
  * `Pool.addQuoteToken` revert with `AuctionNotCleared` custom error

# Contract size
## Pre Change
```
============ Deployment Bytecode Sizes ============
  ERC721Pool               -  24,477B  (99.59%)
  ERC20Pool                -  23,719B  (96.51%)
```
## Post Change
```
============ Deployment Bytecode Sizes ============
  ERC721Pool               -  24,490B  (99.65%)
  ERC20Pool                -  23,732B  (96.56%)
```

# Gas usage
## Pre Change
```
| addQuoteToken                        | 122500          | 179774 | 164363 | 715163  | 60004   |
```
## Post Change
```
| addQuoteToken                        | 122895          | 180303 | 164758 | 719558  | 60004   |
```

2023-06-25 05:19 UTC, grandizzy commented on tests/forge/unit/ERC721Pool/ERC721PoolLiquidationsSettleAuction.t.sol
> +            settledDebt: 323.391444837465801745 * 1e18 //confused why this is not the same as line 213
that's because this line is borrower's `t0Debt` while line 213 is calculated in `PoolInfoUtils` as `Maths.ceilWmul(t0Debt, pendingInflator)`

2023-06-26 15:45 UTC, mattcushman reviewed
lgtm

2023-06-26 21:29 UTC, ith-harvey requested changes
The links that summarize the issue are dead, please copy and paste the issue into the description

2023-06-26 23:59 UTC, grandizzy commented
> The links that summarize the issue are dead, please copy and paste the issue into the description

Will update to new judge repo which is permanent

2023-06-28 00:22 UTC, ith-harvey approved these changes
I consider this change a mitigation to the issue rather than the fix, which is fine. I'm 51% no change 49% fine with this change. As was detailed in the issue why would a lender perform a dusting to protect a position that they can't withdraw? The incentives don't seem significant enough to warrant a lender performing this dusting...

As a lender who is performing the dusting I see two very simple workarounds:
- dust with `addCollateral()`, performs the same protections
- call `addQuoteToken()` on the 71st hour of the auction (before settle is callable) , this mitigation doesn't protect against.

Approving PR because it suffices as a soft mitigation and code looks correct. Again happy to leave code as is and not merge this PR because I don't see sufficient incentives for lender to perform dusting, nor do I see this mitigation as entirely solving the issue.

2023-06-28 17:30 UTC, grandizzy approved these changes
LGTM

2023-06-28 17:31 UTC, ith-harvey commented
> I consider this change a mitigation to the issue rather than the fix, which is fine. I'm 51% no change 49% fine with this change. As was detailed in the issue why would a lender perform a dusting to protect a position that they can't withdraw? The incentives don't seem significant enough to warrant a lender performing this dusting...
> 
> As a lender who is performing the dusting I see two very simple workarounds:
> 
>     * dust with `addCollateral()`, performs the same protections
> 
>     * call `addQuoteToken()` on the 71st hour of the auction (before settle is callable) , this mitigation doesn't protect against.
> 
> 
> Approving PR because it suffices as a soft mitigation and code looks correct. Again happy to leave code as is and not merge this PR because I don't see sufficient incentives for lender to perform dusting, nor do I see this mitigation as entirely solving the issue.

I stand corrected, `addCollateral()` doesn't effect the HPB so that would be ineffective to reproduce the attack.

2023-06-28 17:42 UTC, MikeHathaway approved these changes
LGTM

2023-06-28 19:23 UTC, EdNoepel approved these changes
Unrelated to this change, I was surprised to learn we don't allow lenders to remove collateral when an auction is settleable.  LGTM.

2023-06-28 21:23 UTC, merged

2023-07-01 13:28 UTC, dmitriia reviewed
Looks ok