Invariants Improvements: Add Multiple position in single handler in Position
ajna-finance/ajna-core pull request #928
Opened 2023-07-20 05:38 UTC by prat-gpt

# Description of change
## High level
* Add ability for position manager invariant handler to memorialize and redeem multiple positions in a single handler call.
* Update redeem position handler to redeem partial positions.
* Add random time skip (15 days to 30 days) between epochs in rewards manager invariant setup.

2023-07-26 04:06 UTC, MikeHathaway commented on tests/forge/invariants/PositionsAndRewards/handlers/PositionPoolHandler.sol
> +        (tokenId_, indexes) = _getNFTPosition(1, amountToMove_);
Is this supposed to be hardcoded to 1?

2023-07-26 04:15 UTC, MikeHathaway commented
LGTM - would suggest also ensuring a variable number of indexes are used in the other PM and RM methods.

2023-07-26 12:09 UTC, ith-harvey commented on tests/forge/invariants/PositionsAndRewards/handlers/PositionPoolHandler.sol
> +    function _preMemorializePositionsMultipleBuckets(
I think its fine to keep this method name as `preMemorializePositions`... the new "default" action is using multiple buckets which was always the plan : )

2023-07-26 12:09 UTC, ith-harvey commented on tests/forge/invariants/PositionsAndRewards/handlers/PositionPoolHandler.sol
> +        randomBuckets_ = new uint256[](noOfBuckets_);
NIT: new line here

2023-07-26 12:58 UTC, prat-gpt commented on tests/forge/invariants/PositionsAndRewards/handlers/PositionPoolHandler.sol
> +        (tokenId_, indexes) = _getNFTPosition(1, amountToMove_);
yes, it is hardcoded to `1`, just to ensure we add position in only one bucket for `moveLiquidity` as we are going to move this to another bucket.

2023-07-26 13:34 UTC, EdNoepel commented on tests/forge/regression/PositionAndRewards/RegressionTestERC20PoolPositionManager.t.sol
> -        _erc20positionHandler.moveLiquidity(0, 115792089237316195423570985008687907853269984665640564039457584007913129639933, 0, 3, 2);
Confused that `moveLiquidity` is now being called with one less parameter, yet I see no changes to `function moveLiquidity` prototype in this PR.

2023-07-26 13:57 UTC, prat-gpt commented on tests/forge/regression/PositionAndRewards/RegressionTestERC20PoolPositionManager.t.sol
> -        _erc20positionHandler.moveLiquidity(0, 115792089237316195423570985008687907853269984665640564039457584007913129639933, 0, 3, 2);
`fromIndex_`  parameter is removed [here](https://github.com/ajna-finance/contracts/pull/928/files#diff-100f3ce688ac7947f62cf8e31bdc1f5ba91bf8206a6938e1ded2447b38c522c8L75)

2023-07-27 10:09 UTC, prat-gpt commented on tests/forge/invariants/PositionsAndRewards/handlers/PositionPoolHandler.sol
> +        randomBuckets_ = new uint256[](noOfBuckets_);
Fixed in [bafcbb3](https://github.com/ajna-finance/contracts/pull/928/commits/bafcbb31344be97981a260e5e6cf1bba801e5513)

2023-07-27 10:09 UTC, prat-gpt commented on tests/forge/invariants/PositionsAndRewards/handlers/PositionPoolHandler.sol
> +    function _preMemorializePositionsMultipleBuckets(
Updated in [bafcbb3](https://github.com/ajna-finance/contracts/pull/928/commits/bafcbb31344be97981a260e5e6cf1bba801e5513)

2023-07-27 14:50 UTC, ith-harvey approved these changes
LGTM

2023-07-28 00:16 UTC, MikeHathaway commented on tests/forge/invariants/PositionsAndRewards/handlers/PositionPoolHandler.sol
> +        (tokenId_, indexes) = _getNFTPosition(1, amountToMove_);
`moveLiquidity` should be possible with multiple indexes though - it would be good to have this test variable numbers in the moves

2023-07-28 00:17 UTC, MikeHathaway requested changes
I think we should remove hardcoding to 1 bucket at a time, and add support for variable numbers of buckets in `moveLiquidity`

2023-07-28 01:13 UTC, MikeHathaway commented on tests/forge/invariants/PositionsAndRewards/handlers/PositionPoolHandler.sol
> +        (tokenId_, indexes) = _getNFTPosition(1, amountToMove_);
Alternatively, could we specify an amount to move that takes amounts from an arbitrary number of buckets?

2023-07-28 14:22 UTC, prat-gpt commented
> I think we should remove hardcoding to 1 bucket at a time, and add support for variable numbers of buckets in `moveLiquidity`

while working on this i realised that the contract does not support moving of multiple positions in a single call, so i don't think that this would be useful in this scenario.

2023-07-28 14:44 UTC, EdNoepel approved these changes
LGTM

2023-07-28 17:01 UTC, MikeHathaway commented
> > I think we should remove hardcoding to 1 bucket at a time, and add support for variable numbers of buckets in `moveLiquidity`
> 
> while working on this i realised that the contract does not support moving of multiple positions in a single call, so i don't think that this would be useful in this scenario.

Good point - ok with merging as is then

2023-07-28 17:02 UTC, MikeHathaway approved these changes
LGTM

2023-07-31 13:30 UTC, merged