First borrower
ajna-finance/ajna-core pull request #968
Opened 2023-11-08 16:42 UTC by EdNoepel

## Description

Fixed [Sherlock 006-M](https://github.com/sherlock-audit/2023-09-ajna-judging/issues/24) - Bug causing the first borrower in a pool to accrue interest from the first lender interaction on the pool rather than from loan origination.  Implemented new unit test to demonstrate the issue and confirm the fix.

## Purpose

When the first loan is drawn, the inflator is set to 1 and the timestamp is from the first lender interaction (likely when liquidity was added).  In `_updateInterestState`, `isNewInterestAccrued` is false because it's a new loan, but debt is now nonzero, so the timestamp is left stale.  To resolve the bug, handle this usecase by updating the timestamp where necessary.

## Impact

Conceivably:  Small gas increase in most pool operations are expected due to the additional branch and comparisons.  Early pool actors previously had a gas advantage, not needing to write `inflatorUpdate` to storage.  This change eliminates that advantage, bringing gas cost in line with actions after the first loan has been originated.
Empirically: No noticeable change in gas consumption was observed.

## Tasks

- [x] Changes to protocol contracts are covered by unit tests executed by CI.
- [ ] Protocol contract size limits have not been exceeded.
- [x] Gas consumption for impacted transactions have been compared with the target branch, and nontrivial changes cited in the _Impact_ section above.
- [x] Scope labels have been assigned as appropriate.
- [x] Invariant tests have been manually executed as appropriate for the nature of the change.

2023-11-08 20:43 UTC, mattcushman requested changes
as noted in the comment i don't think this covers the case where the pool has borrowing for a time, but then all loans are repaid and has zero debt for a time.

2023-11-08 20:43 UTC, mattcushman commented on src/base/Pool.sol
> +            inflatorState.inflatorUpdate = uint48(block.timestamp);
I don't think this is sufficient... what happens down the road, when there is pool activity so that `inflator != 0` but all the debt gets paid back for some period of time.  Won't the next loan taken out still have the same issue?  It might be a slight gas hit in some circumstances, but i feel like it would be safer to just always update the timestamp.  Or at least remove the first part of the if check.

2023-11-08 20:49 UTC, EdNoepel commented on src/base/Pool.sol
> +            inflatorState.inflatorUpdate = uint48(block.timestamp);
Once debt hits 0, inflator gets reset to 1 (line 692), and line 696 should execute the next loan.

2023-11-08 20:59 UTC, mattcushman approved these changes
lgtm

2023-11-08 20:59 UTC, mattcushman commented on src/base/Pool.sol
> +            inflatorState.inflatorUpdate = uint48(block.timestamp);
oh jeez, got it.  that's actually good, it resets the inflator.  i had forgotten that we do that.  OK, then it looks good to me.

2023-11-09 11:33 UTC, prat-gpt approved these changes
LGTM

2023-11-14 19:44 UTC, MikeHathaway approved these changes
LGTM

2023-11-15 16:09 UTC, EdNoepel commented
Merging with `develop` has caused the ERC721 to exceed the size limit.

2023-11-15 22:53 UTC, ith-harvey approved these changes
LGTM

2023-11-16 00:06 UTC, ith-harvey commented
need to fix failing unit test then we can merge

2023-11-16 14:17 UTC, EdNoepel commented
> need to fix failing unit test then we can merge

CI is failing due to `develop` contract size exceeding the limit.  Merging PR #979 should resolve this.

2023-11-16 15:37 UTC, merged

2023-12-04 11:11 UTC, grandizzy commented
minor improvement proposed https://github.com/ajna-finance/contracts/pull/1005/commits/8896342d1439d706d36790fef94cc5ff2b629b78

2023-12-08 01:08 UTC, dmitriia reviewed
Looks ok