Borrower with threshold price less than `MIN_PRICE` cannot be kicked.
ajna-finance/ajna-core pull request #973
Opened 2023-11-09 14:18 UTC by prat-gpt

## Description
* Borrower with TP less than `MIN_PRICE` cannot be kicked.
* Updated `_isCollateralized` to return `false` if `TP < MIN_PRICE` and `LUP = MIN_PRICE`. 
* Add unit test to check borrower with threshold price less than `MIN_PRICE` cannot be kicked. 

## Purpose
* Borrower with TP less than `MIN_PRICE` cannot be kicked, borrower can misuse this in pool with very less collateral price like (SHIB - BTC)
* Solves the issue discovered in kiril audit M-02 (https://github.com/k1rill-fedoseev/audits/blob/master/solo/Ajna.md)
```
## [M-02] Positions with threshold price below `MIN_PRICE` cannot be kicked

In order for the borrower’s position to be kicked, it should be under-collateralized with respect to the current LUP.
However, as per the pool constraints, LUP cannot go lower than `MIN_PRICE`. Thus, positions with threshold price
below `MIN_PRICE` can’t ever be kicked, irrespective of kicker or lender actions. Even when `lenderKick` is being used,
the total debt is increased by the deposit amount and starts to exceed the overall deposit in the pool, `LUP` will still
be bounded by the `MIN_PRICE`.

### Recommendation

Allow to kick any position, irrespective of its collateralization, if the `LUP` index ever reaches `MAX_FENWICK_INDEX`.
```
* Solves what we internally have called Dmitrii - 9, an issue discovered by @dmitriia (although not eligible for the Sherlock report) -> 
```
**Summary of the Vulnerability:**
The code outlines a scenario where a borrower can exploit the auction mechanism post-default to incur minimal penalties and unfairly benefit at the expense of the lender (kicker). This is achieved by the borrower exiting the auction early at an artificially high price, avoiding significant taker penalties, and causing collateral damage to the lender. The penalty paid by the borrower is negligible compared to the advantage gained, rendering the penalty almost irrelevant.

** Link an example of the issue: **
https://github.com/ajna-finance/contracts/pull/981/files#diff-e59157bfa5bad910c2f5c2a00cfba7d222f0ad6f1969eb5ab4b2fbd22903b951R212

**Sudo Code Representation of the Attack:**

1. Lender adds liquidity to the pool.

2. Borrower draws a large debt from the pool.

3. Time skip of 100 days.

4. Lender initiates a kick due to default.

5. Borrower exploits the situation by depositing into a high price bucket.

6. Borrower takes from the bucket, reducing their penalty significantly.

7. Borrower removes a large portion of the collateral at an inflated price.

8. Post-removal, the lender's position is significantly weakened, with minimal gains.

9. Borrower ends up with a minor loss in USDC and almost no loss in WETH.

10. Lender gains are marginal compared to the potential loss incurred.

**Analysis:**
- The borrower controls the collateral price, impacting the distribution between borrower and taker. However, when the borrower and taker are the same, the price becomes irrelevant.
- The taker penalty, which should be a deterrent, is reduced to an insignificant amount due to the borrower's control over the collateral price.
- The kicker (lender) faces a substantial loss of bond, while the borrower benefits by virtually eliminating the penalty at a negligible cost.
- The potential for this exploit increases if issue #16 mentioned is fixed, allowing borrowers to execute this strategy more easily and atomically.

This vulnerability creates an imbalance in the protocol, favoring borrowers who default and strategically manipulate the auction process, while significantly disadvantaging lenders who face the brunt of the collateral damage. The protocol needs to address this imbalance to ensure fair and secure interactions between all parties involved.
```

## Impact

## Tasks

- [x] Changes to protocol contracts are covered by unit tests executed by CI.
- [x] Protocol contract size limits have not been exceeded.
- [x] Gas consumption for impacted transactions have been compared with the target branch, and nontrivial changes cited in the _Impact_ section above.
- [x] Scope labels have been assigned as appropriate.
- [x] Invariant tests have been manually executed as appropriate for the nature of the change.

2023-11-15 15:28 UTC, EdNoepel reviewed
Here's the report from Kirill M-02:

> In order for the borrower’s position to be kicked, it should be under-collateralized with respect to the current LUP. However, as per the pool constraints, LUP cannot go lower than `MIN_PRICE`. Thus, positions with threshold price below `MIN_PRICE` can’t ever be kicked, irrespective of kicker or lender actions. Even when `lenderKick` is being used, the total debt is increased by the deposit amount and starts to exceed the overall deposit in the pool, `LUP` will still be bounded by the `MIN_PRICE`.


The point of the change is to ensure loans with a TP below `MIN_PRICE` _can_ be kicked if they go below the LUP when LUP == `MIN_PRICE`.  Is there an existing unit test which exercises that use case?

2023-11-15 15:28 UTC, EdNoepel commented on src/libraries/helpers/PoolHelper.sol
> +        if (type_ == uint8(PoolType.ERC721)) {
```suggestion
        // use collateral floor for NFT pools
        if (type_ == uint8(PoolType.ERC721)) {
```

2023-11-15 15:28 UTC, EdNoepel commented on src/libraries/helpers/PoolHelper.sol
> +        if (type_ == uint8(PoolType.ERC721)) {
Recommend adding the above comment.

2023-11-15 16:59 UTC, mattcushman requested changes

2023-11-15 16:59 UTC, mattcushman commented on src/libraries/helpers/PoolHelper.sol
> +            return debt_ >= Maths.wmul(collateral_, MIN_PRICE);
This doesn't look right -- it just swaps the order.

I guess the issue here is that when debt > deposit, we calc the lup as `MIN_PRICE`, when really it should be `0`.  This means that fixing this bug would require going through lots of code to try to figure it out.  I'd suggest the easy way out as just always returning `FALSE` in case `price==MIN_PRICE`

2023-11-16 12:13 UTC, prat-gpt commented
> The point of the change is to ensure loans with a TP below `MIN_PRICE` _can_ be kicked if they go below the LUP when LUP == `MIN_PRICE`. Is there an existing unit test which exercises that use case?

I have added a unit test here https://github.com/ajna-finance/contracts/pull/973/commits/1d0120f8bfa4149cc7fa9a6cf8e7a393f8f20c1b @EdNoepel

2023-11-16 12:46 UTC, prat-gpt commented on src/libraries/helpers/PoolHelper.sol
> +            return debt_ >= Maths.wmul(collateral_, MIN_PRICE);
updated [172cb3a](https://github.com/ajna-finance/contracts/pull/973/commits/172cb3a6aaaff2c3900de3ebd52304b1aaaf332f)

2023-11-16 13:57 UTC, ith-harvey commented on tests/forge/unit/ERC20Pool/ERC20BorrowerTpLessThanMinPrice.t.sol
> +    function testTpLessThanMinPriceNoKickable() external tearDown {
I concur that this issue exists off of develop. Waiting to see src changes that make this test case invalid before approval.

2023-11-16 14:25 UTC, prat-gpt commented on tests/forge/unit/ERC20Pool/ERC20BorrowerTpLessThanMinPrice.t.sol
> +    function testTpLessThanMinPriceNoKickable() external tearDown {
done here [f9563e0](https://github.com/ajna-finance/contracts/pull/973/commits/f9563e0e006b8d5ecf0447cd75d820bd2147b888)

2023-11-16 18:29 UTC, mattcushman approved these changes
lgtm

2023-11-17 14:04 UTC, ith-harvey commented on src/libraries/helpers/PoolHelper.sol
> +        if (price_ == MIN_PRICE) return false;
So if the LUP is at the min price this would make every loan in the book undercollateralized?

Shouldn't it be every loan is kickable with a TP < minprice && the LUP is at the min price?

2023-11-17 14:05 UTC, EdNoepel approved these changes
LGTM

2023-11-17 14:08 UTC, EdNoepel commented on src/libraries/helpers/PoolHelper.sol
> +        if (price_ == MIN_PRICE) return false;
If you think about it, when the pool is fully utilized, every loan is already kickable, because LUP is at min price, below everyone's TP.  At that point, we're only relying on the neutral price to dissuade undesirable kicks.

2023-11-17 14:27 UTC, ith-harvey commented on tests/forge/unit/ERC20Pool/ERC20BorrowerTpLessThanMinPrice.t.sol
> +    function testTpLessThanMinPriceBorrowerKickable() external tearDown {
Can we add a second borrower whose TP is below the min price while the lup is at min price and fire an expected revert as that borrower should not be kickable?

2023-11-17 14:44 UTC, ith-harvey commented on tests/forge/unit/ERC20Pool/ERC20BorrowerTpLessThanMinPrice.t.sol
> +    function testTpLessThanMinPriceBorrowerKickable() external tearDown {
Spoke with team, this is in fact the reason for the change is that a borrower like this should be kickable.

2023-11-17 15:07 UTC, ith-harvey approved these changes
LGTM

2023-11-17 15:26 UTC, merged