added dust tests and lenderActions changes
ajna-finance/ajna-core pull request #978
Opened 2023-11-13 23:20 UTC by ith-harvey

## Description
* Created `testRemoveQuoteDust` and `testMoveQuoteDust` tests
* added dust limit checks in the following functions (ensuring that the bucket) is not left with deposit after the action):
  * `removeMaxDeposit()`
  * `addQuoteToken()`
  * `moveQuoteToken()`
 
## Purpose
* Resolves `Kirill L-01` as detailed here:
```
## [L-01] Dust checks for quote tokens are inconsistent

`LenderActions::RemoveDepositParams::dustLimit` is defined but is left unused in `moveQuoteToken`
and `removeQuoteToken`.

Also, `LenderActions::moveQuoteToken` constrains `maxAmountToMove` from below with `quoteTokenScale` as a dust limit.
However, `LenderActions::removeQuoteToken` is missing such a constraint.

### Recommendation

1. Remove `LenderActions::RemoveDepositParams::dustLimit`.
2. Add dust limit check to the `LenderActions::removeQuoteToken`.

if (params_.maxAmount < poolState_.quoteTokenScale)
    revert DustAmountNotExceeded();

3. Simplify constraint in `LenderActions::moveQuoteToken`.

if (params_.maxAmountToMove == 0)
    revert InvalidAmount();
-if (params_.maxAmountToMove != 0 && params_.maxAmountToMove < poolState_.quoteTokenScale)
+if (params_.maxAmountToMove < poolState_.quoteTokenScale)
    revert DustAmountNotExceeded();
```
## Impact

old
```
addQuoteToken                        | 1950            | 252735 | 169787 | 723088 | 944     |
moveQuoteToken                       | 1918            | 149390 | 107324 | 634633 | 41      |
```

new
```
addQuoteToken                        | 1950            | 253720 | 170124 | 723195 | 949     |
moveQuoteToken                       | 1918            | 146633 | 107386 | 634829 | 44      |
```

### size
old
```
  ERC721Pool               -  24,069B  (97.93%)
  ERC20Pool                -  23,360B  (95.05%)
  PositionManager          -  17,801B  (72.43%)
  TakerActions             -  15,866B  (64.56%)
  PositionNFTSVG           -  15,271B  (62.14%)
  PoolInfoUtils            -  14,399B  (58.59%)
  LenderActions            -  10,715B  (43.60%)
  BorrowerActions          -   9,358B  (38.08%)
  SettlerActions           -   9,349B  (38.04%)
  KickerActions            -   9,153B  (37.24%)
  PoolCommons              -   9,089B  (36.98%)
  RewardsManager           -   8,693B  (35.37%)
  PoolInfoUtilsMulticall   -   8,539B  (34.74%)
  ERC721                   -   4,276B  (17.40%)
  ERC721PoolFactory        -   3,742B  (15.23%)
  LPActions                -   2,952B  (12.01%)
  ERC20PoolFactory         -   2,564B  (10.43%)
```

new
```
  ERC721Pool               -  24,069B  (97.93%)
  ERC20Pool                -  23,360B  (95.05%)
  PositionManager          -  17,801B  (72.43%)
  TakerActions             -  15,866B  (64.56%)
  PositionNFTSVG           -  15,271B  (62.14%)
  PoolInfoUtils            -  14,399B  (58.59%)
  LenderActions            -  10,823B  (44.04%)
  BorrowerActions          -   9,358B  (38.08%)
  SettlerActions           -   9,349B  (38.04%)
  KickerActions            -   9,153B  (37.24%)
  PoolCommons              -   9,089B  (36.98%)
  RewardsManager           -   8,693B  (35.37%)
  PoolInfoUtilsMulticall   -   8,539B  (34.74%)
  ERC721                   -   4,276B  (17.40%)
  ERC721PoolFactory        -   3,742B  (15.23%)
  LPActions                -   2,952B  (12.01%)
  ERC20PoolFactory         -   2,564B  (10.43%)
  ERC20                    -   2,114B  (8.60%)
```
## Tasks

- [x] Changes to protocol contracts are covered by unit tests executed by CI.
- [x] Protocol contract size limits have not been exceeded.
- [x] Gas consumption for impacted transactions have been compared with the target branch, and nontrivial changes cited in the _Impact_ section above.
- [x] Scope labels have been assigned as appropriate.
- [x] Invariant tests have been manually executed as appropriate for the nature of the change.

2023-11-15 16:42 UTC, mattcushman approved these changes
lgtm

2023-11-15 23:32 UTC, EdNoepel requested changes
_LenderActions_ lines 173 and 315 seem redundant, and unit tests pass with them commented-out.  If they are needed, we should create a unit test to demonstrate why.

2023-11-15 23:32 UTC, EdNoepel commented on src/libraries/external/LenderActions.sol
> +        if (bucketDeposit + addedAmount < poolState_.quoteTokenScale) revert DustAmountNotExceeded();
I don't see the purpose of this line.  https://github.com/ajna-finance/contracts/blob/develop/src/base/Pool.sol#L164 already ensures the bucket cannot have between 0 and the token scale in an `addQuoteToken` call.

2023-11-15 23:32 UTC, EdNoepel commented on tests/forge/unit/ERC721Pool/ERC721PoolInputValidation.t.sol
> +        // revert on innsufficientLiquidity amount if none in bucket
nit: spelling _insufficient_

2023-11-15 23:32 UTC, EdNoepel commented on src/libraries/external/LenderActions.sol
> +        if (vars.toBucketDeposit + movedAmount_ < poolState_.quoteTokenScale) revert DustAmountNotExceeded();
This seems superfluous.  Line 252 prevents moving less than than token precision/dust amount.

2023-11-15 23:32 UTC, EdNoepel commented on tests/forge/interactions/ERC20DustCheck.t.sol
> +contract ERC20TakeWithExternalLiquidityTest is Test {
Why is contract named as such?  There is no _take_ operation.  Should likely relate to filename.

2023-11-16 01:11 UTC, EdNoepel commented on tests/forge/interactions/ERC20DustCheck.t.sol
> +contract ERC20TakeWithExternalLiquidityTest is Test {
There are also some unnecessary imports and constants.

2023-11-16 02:08 UTC, EdNoepel commented on tests/forge/interactions/ERC20DustCheck.t.sol
> +contract ERC20TakeWithExternalLiquidityTest is Test {
Also probably doesn't belong in the `interactions` folder, as we're not testing interactions with external liquidity.

2023-11-16 11:22 UTC, ith-harvey commented on src/libraries/external/LenderActions.sol
> +        if (vars.toBucketDeposit + movedAmount_ < poolState_.quoteTokenScale) revert DustAmountNotExceeded();
Agree, fixed -> https://github.com/ajna-finance/contracts/pull/978/commits/bb64f2d5c74f654275a0d2b365d465f73b0d3197

2023-11-16 11:22 UTC, ith-harvey commented on tests/forge/unit/ERC721Pool/ERC721PoolInputValidation.t.sol
> +        // revert on innsufficientLiquidity amount if none in bucket
Agree, wrong comment entirely -> https://github.com/ajna-finance/contracts/pull/978/commits/bb64f2d5c74f654275a0d2b365d465f73b0d3197

2023-11-16 11:23 UTC, ith-harvey commented on src/libraries/external/LenderActions.sol
> +        if (bucketDeposit + addedAmount < poolState_.quoteTokenScale) revert DustAmountNotExceeded();
Agree, redundant -> https://github.com/ajna-finance/contracts/commit/bb64f2d5c74f654275a0d2b365d465f73b0d3197

2023-11-16 17:23 UTC, EdNoepel commented
Also, merge target should be `develop` branch, not `master`.

2023-11-16 19:48 UTC, ith-harvey commented
> Also, merge target should be `develop` branch, not `master`.

I mentioned this briefly in our standup the other day. First step was the team agreeing that this was an issue by creating a unit test off of `master`. <- Seem to have consensus there.

Now will move it to off of develop so we can get it merged there : )

2023-11-16 19:48 UTC, ith-harvey commented on tests/forge/interactions/ERC20DustCheck.t.sol
> +contract ERC20TakeWithExternalLiquidityTest is Test {
Agree, thank you for your help. Resolved -> https://github.com/ajna-finance/contracts/pull/978/commits/d3c304710b62a5303ce54e78c48f3c80998f5e28

2023-11-16 20:46 UTC, ith-harvey commented
Changes we're moved onto this branch to simply git commits -> https://github.com/ajna-finance/contracts/pull/980

2023-11-16 20:46 UTC, closed without merging