formatting: Update code to standardize styling, remove linter
ajna-finance/ajna-core pull request #99
Opened 2022-05-02 12:50 UTC by grandizzy

- remove `ERC20` import from `ERC20PoolFactory.sol`
- used alignment where possible to improve readability (in both contracts and tests)
- standardize underscore syntax
`_internalVariable`
`publicVariable`
`memoryVariable`
`parameterVariable_`
`CONSTANT`
- improve tests readability
- organize imports

2022-05-02 19:34 UTC, lucas-manuel requested changes

2022-05-02 19:34 UTC, lucas-manuel commented on src/_test/tokens/Ajna.t.sol
> +import { AjnaToken }    from "../../tokens/Ajna.sol";
```solidity
import { AjnaToken } from "../../tokens/Ajna.sol";

import { DSTestPlus } from "../utils/DSTestPlus.sol";
```

2022-05-02 19:34 UTC, lucas-manuel commented on src/_test/tokens/Ajna.t.sol
> +        assertEq(_token.name(), "Ajna");
```solidity
assertEq(_token.name(),     "Ajna");
assertEq(_token.symbol(),   "AJNA");
assertEq(_token.decimals(), 18);
```

2022-05-02 19:34 UTC, lucas-manuel commented on src/_test/utils/DSTestPlus.sol
> +import { DSTest }   from "@ds-test/test.sol";
```solidity
import { DSTest } from "@ds-test/test.sol";
import { ERC20 }  from "@solmate/tokens/ERC20.sol";
import { Test }   from "@std/Test.sol";
import { Vm }     from "@std/Vm.sol";
```

2022-05-02 19:34 UTC, lucas-manuel commented on src/_test/utils/DSTestPlus.sol
> +    uint256 internal _p50159        = 50_159.593888626183666006 * 1e18;
```solidity
    uint256 internal _p50159    = 50_159.593888626183666006 * 1e18;
    uint256 internal _p49910    = 49_910.043670274810022205 * 1e18;
    uint256 internal _p10016    = 10_016.501589292607751220 * 1e18;
    uint256 internal _p9020     = 9_020.461710444470171420 * 1e18;
    uint256 internal _p8002     = 8_002.824356287850613262 * 1e18;
    uint256 internal _p5007     = 5_007.644384905151472283 * 1e18;
    uint256 internal _p4000     = 4_000.927678580567537368 * 1e18;
    uint256 internal _p3514     = 3_514.334495390401848927 * 1e18;
    uint256 internal _p3010     = 3_010.892022197881557845 * 1e18;
    uint256 internal _p2850     = 2_850.155149230026939621 * 1e18;
    uint256 internal _p2835     = 2_835.975272865698470386 * 1e18;
    uint256 internal _p2821     = 2_821.865943149948749647 * 1e18;
    uint256 internal _p2807     = 2_807.826809104426639178 * 1e18;
    uint256 internal _p2793     = 2_793.857521496941952028 * 1e18;
    uint256 internal _p2779     = 2_779.957732832778084277 * 1e18;
    uint256 internal _p2503     = 2_503.519024294695168295 * 1e18;
    uint256 internal _p2000     = 2_000.221618840727700609 * 1e18;
    uint256 internal _p1004     = 1_004.989662429170775094 * 1e18;
    uint256 internal _p502      = 502.433988063349232760 * 1e18;
    uint256 internal _p146      = 146.575625611106531706 * 1e18;
    uint256 internal _p145      = 145.846393642892072537 * 1e18;
    uint256 internal _p100      = 100.332368143282009890 * 1e18;
    uint256 internal _p13_57    = 13.578453165083418466 * 1e18;
    uint256 internal _p5_26     = 5.263790124045347667 * 1e18;
    uint256 internal _p1_64     = 1.646668492116543299 * 1e18;
    uint256 internal _p1_31     = 1.315628874808846999 * 1e18;
    uint256 internal _p1_05     = 1.051140132040790557 * 1e18;
    uint256 internal _p0_951347 = 0.951347940696068854 * 1e18;
    uint256 internal _p0_607286 = 0.607286776171110946 * 1e18;
    uint256 internal _p0_189977 = 0.189977179263271283 * 1e18;
    uint256 internal _p0_006856 = 0.006856528811048429 * 1e18;
    uint256 internal _p0_006822 = 0.006822416727411372 * 1e18;
    uint256 internal _p0_000046 = 0.000046545370002462 * 1e18;
    uint256 internal _p1        = 1 * 1e18;
```

2022-05-02 19:34 UTC, lucas-manuel commented on src/_test/utils/Tokens.sol
> +import { ERC20 }    from "@openzeppelin/contracts/token/ERC20/ERC20.sol";
`import { ERC20 } from "@openzeppelin/contracts/token/ERC20/ERC20.sol";`

2022-05-02 19:34 UTC, lucas-manuel commented on src/_test/utils/Users.sol
> +import { ERC20Pool }    from "../../ERC20Pool.sol";
```solidity
import { ERC20Pool } from "../../ERC20Pool.sol";

import { IERC20 } from "@openzeppelin/contracts/token/ERC20/ERC20.sol";
```

2022-05-02 19:34 UTC, lucas-manuel commented on src/_test/BucketMathTest.t.sol
> +import { DSTestPlus }   from "./utils/DSTestPlus.sol";
Rm extra spaces

2022-05-02 19:34 UTC, lucas-manuel commented on src/_test/BucketMathTest.t.sol
> +        assertEq(BucketMath.indexToPrice(2169),         _p49910);
Follow this format for all below assertions

```solidity
        assertEq(BucketMath.indexToPrice(2169),    _p49910);
        assertEq(BucketMath.priceToIndex(_p49910), 2169);
```

2022-05-02 19:34 UTC, lucas-manuel commented on src/_test/ERC20Pool.t.sol
> +import { CollateralToken, QuoteToken }              from "./utils/Tokens.sol";
Rm extra spaces

2022-05-02 19:34 UTC, lucas-manuel commented on src/_test/ERC20Pool.t.sol
> +        assertEq(address(_collateral), address(_pool.collateral()));
```solidity
        assertEq(address(_collateral), address(_pool.collateral()));
        assertEq(address(_quote),      address(_pool.quoteToken()));
```

2022-05-02 19:34 UTC, lucas-manuel commented on src/_test/ERC20Pool.t.sol
> +        assertEq(_pool.inflatorSnapshot(),              initialInflator);
Rm extra spaces

2022-05-02 19:34 UTC, lucas-manuel commented on src/_test/ERC20Pool.t.sol
> +        assertGt(_pool.inflatorSnapshot(),              initialInflator);
Rm extra spaces

2022-05-02 19:34 UTC, lucas-manuel commented on src/_test/ERC20Pool.t.sol
> +        assertGt(_pool.inflatorSnapshot(),              initialInflator);
Rm extra spaces

2022-05-02 19:34 UTC, lucas-manuel commented on src/_test/ERC20PoolBid.t.sol
> +import { CollateralToken, QuoteToken }              from "./utils/Tokens.sol";
Rm extra spaces

2022-05-02 19:34 UTC, lucas-manuel commented on src/_test/ERC20PoolBid.t.sol
> +import { Buckets }      from "../libraries/Buckets.sol";
Rm extra spaces

2022-05-02 19:34 UTC, lucas-manuel commented on src/_test/ERC20PoolBid.t.sol
> +        assertEq(_collateral.balanceOf(address(_bidder)),   100 * 1e18);
Rm extra spaces

2022-05-02 19:34 UTC, lucas-manuel commented on src/_test/ERC20PoolBid.t.sol
> +        assertEq(deposit,           0);
Rm extra spaces

2022-05-02 19:34 UTC, lucas-manuel commented on src/_test/ERC20PoolBid.t.sol
> +        assertEq(deposit,           0);
Rm extra spaces

2022-05-02 19:34 UTC, lucas-manuel commented on src/_test/ERC20PoolBid.t.sol
> +        assertEq(bucketCollateral,  0);
Rm extra spaces

2022-05-02 19:34 UTC, lucas-manuel commented on src/_test/ERC20PoolBid.t.sol
> +        assertEq(bucketCollateral,  0);
Rm extra spaces

2022-05-02 19:34 UTC, lucas-manuel commented on src/_test/ERC20PoolBid.t.sol
> +        assertEq(_collateral.balanceOf(address(_bidder)),   99.500115932935445694 * 1e18);
Rm extra spaces

2022-05-02 19:34 UTC, lucas-manuel commented on src/_test/ERC20PoolBid.t.sol
> +        assertEq(_collateral.balanceOf(address(_bidder)),   100 * 1e18);
Rm extra spaces

2022-05-02 19:34 UTC, lucas-manuel commented on src/_test/ERC20PoolBid.t.sol
> +        assertEq(deposit,           0);
Rm extra spaces

2022-05-03 05:45 UTC, grandizzy commented
@lucas-manuel I addressed rm extra spaces with https://github.com/ajna-finance/contracts/pull/99/commits/4fa9531694f8f41da4973734555ff8fc72aa66e1 pls recheck

2022-05-03 12:52 UTC, EdNoepel approved these changes
I prefer we merge this sooner, rather than amassing merge conflicts.  Significant improvement in readability.

2022-05-03 12:52 UTC, EdNoepel commented on src/ERC20Pool.sol
> +import { Clone } from "@clones/Clone.sol";
I'd expect whitespace padding to line up the `from` statements.

2022-05-03 12:52 UTC, EdNoepel commented on src/libraries/Buckets.sol
> +                    amount_         = 0;
Whitespace on lines 191 and 196 was altered, but the operators still don't line up.

2022-05-03 13:04 UTC, grandizzy commented on src/libraries/Buckets.sol
> +                    amount_         = 0;
Fixed with https://github.com/ajna-finance/contracts/pull/99/commits/fc50f3d58fa836cfae024a4155b23fc8978b9e96

2022-05-03 13:07 UTC, grandizzy commented on src/ERC20Pool.sol
> +import { Clone } from "@clones/Clone.sol";
yeah, the padding applies only in scope of the same group, I split here in two groups as they are different functionality @lucas-manuel you think that's OK or they should still be same group?

2022-05-03 17:07 UTC, MikeHathaway approved these changes
LGTM!

2022-05-03 17:26 UTC, merged